integr8ly/integreatly-operator

- deploy/operator.template.yaml
That particular template file will only be used on OCP 3.11 and we don't expect OLM to ever be present there.
> Remove CLUSTER_HAS_OLM parameter from template

- pkg/apis/integreatly/v1alpha1/installation_types.go
- pkg/controller/installation/products/codeready/reconciler.go
Remove the `CreateNamespaces` boolean from the Installation CR, since any existing namespaces will be used by default anyway
> Remove create namespaces option from installation

- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/products/Reconciler_moq.go
- pkg/controller/installation/products/amqstreams/reconciler.go
- pkg/controller/installation/products/codeready/reconciler.go
- pkg/controller/installation/products/codeready/reconciler_test.go
- pkg/controller/installation/products/reconciler.go
- pkg/controller/installation/products/rhsso/reconciler.go
the `r.client` has issues with a stale cache, so I've removed it, and pass it in from the installation_controller, with a fresh client created on each reconcile.
> fix issue with stale serverclient

- README.md
Add the following to the readme:
- There is a known [issue](https://github.com/matryer/moq/issues/98) in moq that results in the following error below when used:
```
Couldn't load source package: No packages found
```
> add prerequisites and moq installation to readme

- README.md
Tiny fix for rhsso namespace name in README.
was: openshift-rhsso
is: integreatly-rhsso
Currently,`integreatly-` is used as a prefix by default, see https://github.com/integr8ly/integreatly-operator/blob/master/deploy/crds/examples/installation.cr.yaml#L7
> Fixed rhsso namespace name in local setup section

- deploy/crds/examples/installation.cr.yaml
Probably committed by mistake. Example values should be used instead of hard-coded ones in example-installation Installation CR.
> Added back Installation CR example values

- Makefile
- README.md
- scripts/dedicated-cleanup.sh
- scripts/dedicated-setup.sh
Against an OS 4 cluster create a namespace ```mynamespace``` with an admin user
then run
```
cd scripts
./dedicated-setup.sh
```
once the dedicated operator is up and running
logout of your cluster and login back in using the ```test Identity Provider```
login with the customer-admin user
The password for this user is outputted from the script
You should only be able to see the mynamespace project
> add support for dedicated like setup

- .githooks/pre-commit
- Makefile
Adds a precommit git hook to check if any staged .go files, ignoring `vendor/` files, are not formatted correctly. This should prevent build failures caused by unformatted files. 
https://golang.org/misc/git/pre-commit
> add precommit git hook to check for unformatted files

- .gitignore
- scripts/setup-htpass-idp.sh
OpenShift 4 RHPDS clusters already have htpasswd provider.
This changes will ensure that `make setup/dedicated` will be compatible with RHPDS clusters.
Verification steps:
Get OS4 RHPDS cluster
Login to your cluster via oc and run `make setup/dedicated`
In the web console you should be able to login as opentlc-mgr and customer-admin
> Fix dedicated/setup compatibility with RHPDS

- .travis.yml
- Makefile
- scripts/ci/OWNERS
- scripts/ci/unit_test.sh
* Add script to run unit tests which also supports coverage reporting to coveralls for CI.
* Removes PR testing with travis since it's no longer required, images should still be pushed to quay on master updates though.
/cc @pmccarthy
> Enable coveralls in prow job

- pkg/apis/integreatly/v1alpha1/installation_types.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/products/rhsso/reconciler.go
- pkg/controller/installation/products/rhsso/reconciler_test.go
- pkg/controller/installation/products/rhssouser/reconciler.go
- pkg/controller/installation/products/rhssouser/reconciler_test.go
- pkg/controller/installation/products/solutionexplorer/reconciler.go
- pkg/controller/installation/products/threescale/objects_test.go
- pkg/controller/installation/products/threescale/reconciler.go
- pkg/resources/finalizers.go
- pkg/resources/reconciler.go
fixing a bug where the finalizers are never removed if the installation object is deleted while the operator is not running.
- Install stack using this operator
- stop the operator
- delete the installation CR
- start the operator
- see the uninstall function normally.
> fix finalizer bug

- .travis.yml
- scripts/ci/unit_test.sh
Update travis to execute unit tests and report coveralls coverage report.
Stop goveralls failing builds if there is a coveralls backend issue.
There is some weirdness with the coveralls reporting from prow, so reverting back to travis for the moment.
/cc @philbrookes
> Update unit test script to support travis and prow

- pkg/controller/installation/products/fuse/reconciler.go
- pkg/controller/installation/products/threescale/reconciler.go
- pkg/resources/pullSecret.go
- pkg/resources/pullSecret_test.go
- pkg/resources/reconciler.go
- pkg/resources/reconciler_test.go
Refactors `ReconcilePullSecret`. Logic for copying the secret is moved to `pullSecret.go` under the same package. Also adds support for specifying the name of the pull secret copied into the component namespace.
1. Run the operator locally
2. Ensure that a pull secret is created in 3Scale and Fuse
3. Ensure that the pull secret in Fuse is named `syndesis-pull-secret`
/cc @philbrookes
> INTLY-3511: refactor reconcile pull secret

- deploy/olm-catalog/integreatly-operator/integreatly-operator-1.9.8/integreatly-operator.v1.9.8.clusterserviceversion.yaml
- deploy/role.yaml
Correct permissions for integreatly-operator
- syntax error in role.yaml
- cluster perms missing for mdc, mss, push (and monitoring in csv due to previous syntax error)
> Cluster perms fix

- pkg/apis/integreatly/v1alpha1/installation_types.go
JIRA: https://issues.jboss.org/browse/INTLY-3961
Related PR: https://github.com/integr8ly/manifests/pull/84
Currently the latest GA fuse version is on 1.4.0 but the manifest repo is referring to 7.4.0, to fix this the manifest repo needs to be renamed to 1.4.0, the CSV file updated to use the correct version and update the version in the integreatly operator
> Fuse operator version 1.4.0

- Makefile
- pkg/apis/integreatly/v1alpha1/installation_types.go
- pkg/controller/installation/types.go
- test/e2e/integreatly_test.go
All components expect to be able to create monitoring resources, so it must be installed before all other components.
> schedule monitoring first

- deploy/operator-source-template.yml
This field is required for creating the catalog source config in OSD
1. Ensure the catalogsourceconfig is created when running `make cluster/prepare/olm`.
> add source to catalogsourceconfig spec

- pkg/apis/integreatly/v1alpha1/installation_types.go
operator panics when removing an install with no status blocks for products that have added finalizers.
> fix panic when product status is absent

- pkg/apis/integreatly/v1alpha1/installation_types.go
Bumps the solution explorer operator version to `0.0.33`
Associated pull requests:
* https://github.com/integr8ly/manifests/pull/85
* https://github.com/integr8ly/tutorial-web-app-operator/pull/72
> INTLY-3245 - Bump Solution Explorer Operator Version

- pkg/apis/integreatly/v1alpha1/installation_types.go
Bump webapp operator version to 0.0.34 to point to new CSV in the manifest https://github.com/integr8ly/manifests/pull/88
> bump webapp operator version to 0.0.34

- pkg/controller/installation/products/config/monitoring.go
- pkg/controller/installation/products/monitoring/reconciler.go
- pkg/controller/installation/products/monitoring/resourceHelper.go
- pkg/controller/installation/products/monitoring/templateHelper.go
- templates/monitoring/test-secret-2.yaml
- templates/monitoring/test-secret.yaml
- https://issues.jboss.org/browse/INTLY-4076
Add templating support to the Integreatly Operator to allow the monitoring reconciler to apply monitoring configuration.
- Authenticate with Openshift
- Create ``integreatly`` namespace
- Create the secrets for preflight checks:
```
oc process -f ./deploy/s3-secrets.yaml -p INSTALLATION_NAMESPACE=integreatly -p AWS_ACCESS_KEY_ID=xxxx -p AWS_SECRET_ACCESS_KEY=xxxx -p AWS_BUCKET=xxxx-test -p AWS_REGION=eu-central-1 | oc create -f -
oc create secret generic github-oauth-secret --from-literal=clientId=xxxx --from-literal=secret=xxx -n integreatly
```
- Visit OperatorHub in the Openshift UI, search for integreatly and install it into the ``integreatly`` namespace. Scale the replicas to 0 in the operator deployment in the ``integreatly`` namespace.
- …
> Adding templating support to monitoring reconciler

- pkg/controller/installation/products/cloudresources/reconciler.go
Change the subscription name for the cloud resource operator to match the manifests repo.
- Create an operator source pointing to the integreatly registry 
```yml
metadata:
spec:
registryNamespace: integreatly
```
- Run the integreatly operator and ensure the `cloud-resources` stage completes
- Verify that the cloud resource operator is running in the `cloud-resources` namespace
> Change cloud resources subscription name

- pkg/controller/installation/products/amqonline/reconciler.go
- pkg/controller/installation/products/amqonline/reconciler_test.go
- pkg/controller/installation/products/config/amqonline.go
Adds a CronJob resource to amq-online for PV backups 
https://issues.jboss.org/browse/INTLY-3025
1. Run the integreatly-operator locally installing only the amq-online:
`operator-sdk up local --namespace=<integreatly_operator_namespace> --operator-flags=--products=amqonline`
2. Verify if amq-online has successfully reconciled 
3. Get a list of cronjobs available on amq-online namespace:
`oc get cronjob -n integreatly-amq-online` and look for a cronjob named `enmasse-pv-backup `
4. Create a job to test the cronjob manually:
`oc create job --from=cronjob/enmasse-pv-backup manual-pv-backup-001 -n integreatly-amq-online` 
5. Check if the created job has succeeded, the cmd below should return 1 :
`oc get job manual-pv-backup-001 -n integreatly-amq-online --output=json -o …
> feat: adds cronjob to amq-online for PV backups

- .gitignore
- scripts/ci/unit_test.sh
A recent PR that added new unit tests caused the coverage % to go down.
https://github.com/integr8ly/integreatly-operator/pull/205
It looks like any package that doesn't have a test file in it is omitted from the coverage report. In that PR, a  test file was added, which caused all files in the monitoring package to be included int he coverage report, and take the overall % of coverage down.
This PR changes the coverprofile so it include all packages (omitting generated files) in an attempt to get a better gauge on where coverage is missing. (It should show any 0% covered packages, which were omitted from results before)
See https://github.com/golang/go/issues/24570 for some discussion on this topic.
> Include all packages in coverprofile, but omit generated files

- deploy/role.yaml
This is needed to create 3scale smtp configmap in the 3scale namespace which was added in this [PR](https://github.com/integr8ly/integreatly-operator/pull/197)
1. Run the operator using the operator's service account
- `make code/run/service_account NAMESPACE=<namespace>`
2. Ensure installation of all products has been completed successfully
> add permission to create configmaps to the cluster role

- pkg/controller/installation/products/config/monitoring.go
- templates/monitoring/cluster-resources.yaml
- templates/monitoring/endpointsdetailed.yaml
- templates/monitoring/endpointsreport.yaml
- templates/monitoring/endpointssummary.yaml
- templates/monitoring/resources-by-namespace.yaml
- templates/monitoring/resources-by-pod.yaml
https://issues.jboss.org/browse/INTLY-4022
Ports all resources (below) from the create_grafanadashboards.yml file in the installer:
```
- endpointsdetailed.yml
- endpointsreport.yml
- endpointssummary.yml
- resources-by-namespace.yml
- resources-by-pod.yml
- cluster-resources.yml
```
- Authenticate with Openshift
- Create the `integreatly` namespace
- Create the secrets for preflight checks:
```
oc process -f ./deploy/s3-secrets.yaml -p INSTALLATION_NAMESPACE=integreatly -p AWS_ACCESS_KEY_ID=xxxx -p AWS_SECRET_ACCESS_KEY=xxxx -p AWS_BUCKET=xxxx-test -p AWS_REGION=eu-central-1 | oc create -f -
oc create secret generic github-oauth-secret --from-literal=clientId=xxxx --from-literal=secret=xxx -n integreatly
```
- Visit OperatorHub in the Openshift UI, search for integreatly and install it …
> Grafanadashboard resource templates added

- deploy/role_binding.yaml
- pkg/controller/installation/products/fuse/reconciler.go
- pkg/controller/installation/products/fuse/reconciler_test.go
The following changes ensures that all users belonging to the group `rhmi-developers` can access and view the Fuse namespace. 
1. Run the operator locally
2. Login as a non-admin user
- User should get added to the `rhmi-developers` group
- Verify that this user gets added as a subject to the `rhmi-developers-view-fuse` role binding located in the Fuse namespace. (This may take a couple of seconds to reconcile)
- Verify that the role binding references the cluster role `view`
- User should only be able to see Fuse and their own namespaces.
3. Verify that the user only has view access to the Fuse namespace
- Click on the Fuse namespace
- Ensure that the user can view the *Overview*, *YAML* and *Workload* pages.
- Ensure that the user is not able to update any resources within the namespace
> INTLY-4131: Ensure rhmi-developers group has view access to Fuse namespace

- openshift-ci/Dockerfile.tools
Latest version of the SDK does not use dep, updates the Dockerfile accordingly.
```
$ docker build -t registry.svc.ci.openshift.org/openshift/release:intly-golang-1.13 - < Dockerfile.tools
$ IMAGE_NAME=registry.svc.ci.openshift.org/openshift/release:intly-golang-1.13 test/run 
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.1 linux/amd64"
go version go1.13.1 linux/amd64
hello world
SUCCESS!
```
> Update CI Dockerfile, fix make target for operator SDK

- deploy/role.yaml
- deploy/role_binding.yaml
When installing operator via OperatorSource, the operator does not have the necessary permissions for granting the fuse only view from https://github.com/integr8ly/integreatly-operator/pull/204 
* Install OperatorSource pointed to my registry
```
metadata:
spec:
registryNamespace: kevfan
```
* Install integreatly
* Login as a non-admin user
* User should get added to the rhmi-developers group
* Verify that this user gets added as a subject to the rhmi-developers-view-fuse role binding located in the Fuse namespace. (This may take a …
> Add permissions for granting fuse only view

- cmd/manager/main.go
commented out metrics due to permission errors
> commented out metrics due to permission errors

- pkg/controller/installation/products/threescale/objects_test.go
- pkg/controller/installation/products/threescale/reconciler.go
Use cro to generate a postgres database and redis caches to be used by 3scale (in HA mode)  
- Create an operator source pointing to the integreatly registry 
```yml
metadata:
spec:
registryNamespace: integreatly
```
- Create a configmap in the integreatly namespace for the cloud resource operator which specifies in-cluster only deployments: 
```yml
kind: ConfigMap
apiVersion: v1
metadata:
name: cloud-resource-config
namespace: intly
data:
managed: |
{"blobstorage":"openshift", "smtpcredentials":"openshift", "redis":"openshift", …
```
> Use cro to deploy postgres and redis for 3scale 

- pkg/controller/installation/products/codeready/reconciler.go
- pkg/controller/installation/products/codeready/reconciler_test.go
Use cro to generate an postgres to be used by codeready.
Create an operator source pointing to the integreatly registry
```yaml
metadata:
spec:
registryNamespace: integreatly
```
Create a configmap in the integreatly namespace for the cloud resource operator which specifies in-cluster only deployments:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
name: cloud-resource-config
namespace: intly
data:
managed: |
{"blobstorage":"openshift", "smtpcredentials":"openshift", "redis":"openshift", "postgres":"openshift"}
workshop: | …
```
> INTLY-3146 add cloud resources codeready

- templates/monitoring/kube_state_metrics_3scale_alerts.yaml
- templates/monitoring/kube_state_metrics_alerts.yaml
- templates/monitoring/kube_state_metrics_launcher_alerts.yaml
- templates/monitoring/kube_state_metrics_monitoring_alerts.yaml
- templates/monitoring/kube_state_metrics_rhsso_alerts.yaml
- templates/monitoring/kube_state_metrics_solution_explorer_alerts.yaml
- test/e2e/integreatly_test.go
Adds a check for alerts which are firing to the e2e test by exec'ing into the prometheus pod to curl the alerts endpoint.
To Verify:
Check out this branch
Run make test/e2e
> Intly 3770 monitoring e2e

- Makefile
- cmd/manager/main.go
- go.mod
- go.sum
- pkg/controller/installation/installation_controller.go
- test/e2e/integreatly_test.go
This PR allows the creation of the installation CR by the integreatly operator in case there is none installation CR created in the desired namespace
https://issues.jboss.org/browse/INTLY-4219
1. Prepare the cluster for a local install
`make cluster/prepare/local`
2. Run the operator locally against a cluster
`operator-sdk up local --namespace=<namespace>`
3. Ensure a installation CR named `integreatly-operator` is being created and the install starts
`oc get installation integreatly-operator -o yaml`
4. Uninstall the operator with the operator-sdk running and wait until integreatly operator and the products have been removed
`make cluster/cleanup NAMESPACE=integreatly-operator`
5. Prepare the cluster for a local install again 
`make cluster/prepare/local`
6. Create an installation CR
`oc …
> feat: creates installation CR by the operator

- Makefile
If someone isn't logged in to a cluster that they can connect to, then
they won't be able to execute any targets (or even see what targets
are available).
Also, these don't appear to even be used any longer.
> Don't make network calls in Make target variables

- cmd/manager/main.go
- pkg/apis/3scale/v1alpha1/apimanager_types.go
- pkg/controller/installation/products/amqonline/addressplans.go
- pkg/controller/installation/products/amqonline/addressspaceplans.go
- pkg/controller/installation/products/amqonline/authservices.go
- pkg/controller/installation/products/amqonline/infraconfigs.go
- pkg/controller/installation/products/amqonline/reconciler_test.go
- pkg/controller/installation/products/amqstreams/reconciler.go
- pkg/controller/installation/products/codeready/reconciler.go
- pkg/controller/installation/products/config/manager.go
- pkg/controller/installation/products/config/manager_test.go
- pkg/controller/installation/products/fuse/reconciler.go
- pkg/controller/installation/products/monitoring/reconciler.go
- pkg/controller/installation/products/rhsso/reconciler.go
- pkg/controller/installation/products/rhsso/reconciler_test.go
- pkg/controller/installation/products/rhssouser/reconciler.go
- pkg/controller/installation/products/rhssouser/reconciler_test.go
- pkg/controller/installation/products/solutionexplorer/object_test.go
- pkg/controller/installation/products/solutionexplorer/reconciler_test.go
- pkg/controller/installation/products/threescale/reconciler.go
- pkg/controller/installation/products/ups/reconciler_test.go
- pkg/controller/subscription/subscription_controller_test.go
- pkg/resources/creators.go
- pkg/resources/finalizers.go
- pkg/resources/pullSecret.go
- pkg/resources/reconciler.go
- test/e2e/integreatly_test.go
JIRA: https://issues.redhat.com/browse/INTLY-4187
Like #268, this doesn't solve everything. It just does the following:
> Always use corev1 & metav1; fix context imports

- templates/monitoring/backup-monitoring-alerts.yaml
The following pr is to verify the following [Jira](https://issues.redhat.com/browse/INTLY-4351)
OSD4 cluster with integreatly based of the pr branch 
1.Create 2 jobs using the ui (example job works fine)
2.Modify the yaml to include the label `monitoring_key=middleware` as well as include sleep(400) like the following:
```
command:
- perl
- '-Mbignum=bpi'
- '-wle'
- sleep(400)
- print bpi(2000)
```
3. Navigate to prometheus alert JobRunningTimeExceeded (300 seconds and 600 seconds)
4. When the job has been running for 5 mins execute the query and the two jobs show be returned.
> added to query to fix error

- cmd/manager/main.go
- deploy/role.yaml
https://issues.redhat.com/browse/INTLY-4276
Example of errors that were occurring constantly in the logs: https://gist.github.com/obrienrobert/8fd9fc755f808ce52b0a2e6b6d88837b
- Openshift 4.2 RHPDS cluster
- Login into your cluster using `oc login`
- Prepare your cluster using the make file:
`make cluster/prepare/local`
- A public image containing the code changes in this PR has been pre-built and resides in the `robrien` Quay registry. Create a new operator source file locally:
```
metadata:
spec:
registryNamespace: robrien
```
- …
> metrics error workaround added

- manifests/integreatly-3scale/3scale-0.4.0/3scale-operator.v0.4.0.clusterserviceversion.yaml
- manifests/integreatly-3scale/3scale-0.4.0/apps_v1alpha1_apimanager_crd.yaml
- manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_api_crd.yaml
- manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_binding_crd.yaml
- manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_limit_crd.yaml
- manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_mappingrule_crd.yaml
- manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_metric_crd.yaml
- manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_plan_crd.yaml
- manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_tenant_crd.yaml
- manifests/integreatly-3scale/3scale.package.yaml
- pkg/apis/integreatly/v1alpha1/installation_types.go
- pkg/controller/installation/products/threescale/reconciler.go
- templates/monitoring/kube_state_metrics_3scale_alerts.yaml
Updates the 3scale operator to use 3scale 2.7. 
CSV files were copied from https://github.com/3scale/3scale-operator/tree/3scale-2.7.0/deploy/olm-catalog/3scale-operator with edits to point to the `registry.redhat.io` instead of `registry.stage.redhat.io` and removing the old `0.3.0` csv and the `replaces` label
Jira:
* https://issues.redhat.com/browse/INTLY-4327
* Clone this branch
* Run the operator locally against cluster with at least these products installed:
```
operator-sdk up local --namespace=integreatly --operator-flags=--products=rhsso,rhssouser,cloud-resources,3scale
```
* Ensure 3scale gets installed correctly
* Run the `setup-htpass-idp.sh` script and note the outputed password for `customer-admin`
```
./scripts/setup-htpass-idp.sh
```
* Login in to 3scale using the Single …
> INTLY-4327 - Update 3scale operator to use 2.7 3scale

- Makefile
- README.md
- deploy/role.yaml
- deploy/s3-secret.yaml
- pkg/client/sigs_client_moq.go
- pkg/controller/installation/marketplace/MarketplaceManager_moq.go
- pkg/controller/installation/products/Reconciler_moq.go
- pkg/controller/installation/products/amqonline/reconciler.go
- pkg/controller/installation/products/amqonline/reconciler_test.go
- pkg/controller/installation/products/cloudresources/reconciler.go
- pkg/controller/installation/products/codeready/reconciler.go
- pkg/controller/installation/products/codeready/reconciler_test.go
- pkg/controller/installation/products/config/ConfigReadWriter_moq.go
- pkg/controller/installation/products/config/ConfigReadable_moq.go
- pkg/controller/installation/products/config/amqonline.go
- pkg/controller/installation/products/config/codeready.go
- pkg/controller/installation/products/config/manager.go
- pkg/controller/installation/products/monitoring/reconciler.go
- pkg/controller/installation/products/solutionexplorer/OauthResolver_moq.go
- pkg/resources/backup.go
- pkg/resources/backup_test.go
JIRA: https://issues.redhat.com/browse/INTLY-4237
Changes made in this PR:
- switching to Roles instead of ClusterRoles for backup ServiceAccount.
- syncing S3 backups secret from integreatly ns -> product namespaces that have backup jobs
- fixing postgres credentials secret for the backups
- addintg template and steps for providing S3 credentials into clusters that can't create S3 bucket automatically
- fixing a small issue in monitoring finalizer (a bit of offtopic, but it might give false negative result on e2e tests, so better fix it sooner rather than later). I've put it in a separate commit for easier review.
**Verification steps:**
Install Integreatly using this PR. Make sure to use ServiceAccount if running locally (`make code/run/service_account`).
Following newly added Readme …
> INTLY-4237 - use Roles for backups

- Makefile
In https://github.com/integr8ly/integreatly-operator/pull/282 we're
changing the operator to watch all namespaces, and it's not possible
to run the e2e tests with the "--up-local" flag & also set the
namespace variable to an empty string.
----
#
> 💚 Run e2e on image in cluster, not local binary

- Makefile
- cmd/manager/main.go
- pkg/resources/oauthResolver.go
I've also removed the manual leader election toggle. Leader election
will be skipped if running locally anyway now:
```
{"level":"info","ts":1578480384.2597575,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1578480384.2597752,"logger":"leader","msg":"Skipping leader election; not running in a cluster."}
```
There was one other reference to it, which didn't seem like a great
usage of it (it looks like we wanted to check if we were running
locally, rather than if leader election should be disabled).
> ☸ Run e2e tests with image deployed on cluster

- cmd/manager/main.go
- go.mod
https://issues.redhat.com/browse/INTLY-3137
- Openshift 4.2 RHPDS cluster
- Login into your cluster using `oc login`
- Prepare your cluster using the make file:
`make cluster/prepare/local`
- The operator must be installed via OLM in order for custom metrics to work. A public image containing the code changes in this PR has been pre-built and resides in the `robrien` Quay registry. Create a new operator source file locally:
```
metadata:
spec:
registryNamespace: robrien
```
- Apply the above operator source to the `openshift-market` …
> created integreatly info custom metric

- pkg/products/amqonline/reconciler.go
`//` are being added to the blackbox target url 
1) Install the operator
2) Go to middleware-monitoring namespace, route and acess grafana
3) Verify if all components are up
> fix: correct BlackboxTargetPath for monitoring in amq-online

- pkg/controller/subscription/subscription_controller.go
- pkg/controller/subscription/subscription_controller_test.go
Now, that the integreatly operator will only be installed in cluster mode, it will automatically watch all Subsriptions on the cluster.
This PR should ensure that it will only change it's own subscription to Manual.
> Filter integreatly in subscription controller

- pkg/controller/subscription/subscription_controller_test.go
I made a small mistake in my previous PR (https://github.com/integr8ly/integreatly-operator/pull/293) - the names of the new test cases were swapped. Fixing that here.
@philbrookes can you approve please? :)
> Fix swapped unit test names

- pkg/apis/integreatly/v1alpha1/installation_types.go
- pkg/controller/installation/bootstrapReconciler.go
- pkg/controller/installation/installation_controller.go
- pkg/products/amqonline/reconciler.go
- pkg/products/amqonline/reconciler_test.go
- pkg/products/amqstreams/reconciler.go
- pkg/products/amqstreams/reconciler_test.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/codeready/reconciler.go
- pkg/products/codeready/reconciler_test.go
- pkg/products/fuse/reconciler.go
- pkg/products/fuse/reconciler_test.go
- pkg/products/fuseonopenshift/reconciler.go
- pkg/products/fuseonopenshift/reconciler_test.go
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- pkg/products/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/products/solutionexplorer/reconciler.go
- pkg/products/solutionexplorer/reconciler_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/products/ups/reconciler.go
- pkg/products/ups/reconciler_test.go
- pkg/resources/events.go
- pkg/resources/events/events.go
- pkg/resources/events/events_test.go
Add an event recorder to the bootstrap and product reconcilers to emit events on failed and successful installations. 
[INTLY-3037](https://issues.redhat.com/browse/INTLY-3037)
1. Install integreatly using this branch
2. Check for integreatly operator events on your cluster. This can be seen in the `Events` page.
- Events should be emitted for each product's successful installation
- Events should be emitted when an error occurs resulting to a failed installation
> INTLY-3037: Emit events on failed/successful installation

- pkg/products/fuse/reconciler.go
JIRA: https://issues.redhat.com/browse/INTLY-4817
We don't need to keep track of individual users in rhmi-developers group to give them view access to Fuse ns. We can create a role binding for the group instead.
P.S: I also added small fix of import name.
> INTLY-4817 - create Fuse view binding for whole Group

- pkg/products/threescale/three_scale_client.go
https://issues.redhat.com/browse/INTLY-4907 
- Before changes 
``` sh
golint $(find . -type d  -not -path "./vendor/*") | grep "method parameter"
pkg/products/threescale/three_scale_client.go:19:13: interface method parameter userId should be userID
pkg/products/threescale/three_scale_client.go:20:17: interface method parameter userId should be userID
pkg/products/threescale/three_scale_client.go:21:18: interface method parameter userId should be userID
pkg/products/threescale/three_scale_client.go:22:13: interface method parameter userId should be userID
pkg/products/threescale/three_scale_client.go:149:41: method parameter userId should be userID
pkg/products/threescale/three_scale_client.go:167:45: method parameter userId should be userID …
```
> Change method parameter userId to userID

- pkg/products/threescale/asserts_test.go
- pkg/products/threescale/clients_test.go
https://issues.redhat.com/browse/INTLY-4982
Fixes
```sh
[hstefans@localhost integreatly-operator]$ golint `find . -type d -not -path "./vendor/*"` | grep  "should replace errors"
pkg/products/threescale/asserts_test.go:48:10: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
pkg/products/threescale/asserts_test.go:55:10: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
pkg/products/threescale/asserts_test.go:62:10: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
pkg/products/threescale/asserts_test.go:69:10: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
pkg/products/threescale/asserts_test.go:72:10: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
pkg/products/threescale/asserts_test.go:82:10: should …
```
> Fix replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- templates/monitoring/kube_state_metrics_rhsso_alerts.yaml
Deploying RHSSO in a HA fashion by deploying with 3 replicas for both the cluster SSO and Application SSO
Removed the alert for number of pods running in the namespace as this is actually taken care of by an alert included in Keycloak now anyway - https://github.com/keycloak/keycloak-operator/blob/master/pkg/model/prometheus_rule.go#L86-L94
> Update SSO replicas to 3

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
The URL for the API is being malformed, create it manually, based on the routing URL instead.
Made a technical debt issue to handle this more elegantly in the future:
https://issues.redhat.com/browse/INTLY-5134
> build api url based on apps url

- manifests/integreatly-rhsso/rhsso-8.0.1/keycloakoperator.8.0.1.clusterserviceversion.yaml
- pkg/products/fuse/reconciler.go
JIRA: https://issues.redhat.com/browse/INTLY-4671
Resources are created:
```bash
$ oc get servicemonitors,prometheusrules,grafanadashboards -n redhat-rhmi-fuse
NAME                                                         AGE
servicemonitor.monitoring.coreos.com/syndesis-infra          36m
servicemonitor.monitoring.coreos.com/syndesis-integrations   36m
NAME                                                                        AGE
prometheusrule.monitoring.coreos.com/ksm-fuse-online-alerts                 32m
prometheusrule.monitoring.coreos.com/syndesis-infra-db-alerting-rules       36m
prometheusrule.monitoring.coreos.com/syndesis-infra-meta-alerting-rules     36m
prometheusrule.monitoring.coreos.com/syndesis-infra-server-alerting-rules   36m …
```
> ✨ Enable 'ops' addon on Syndesis for monitoring

- README.md
- make/ocm.mk
- templates/ocm-cluster/cluster-template.json
See [readme](https://github.com/integr8ly/integreatly-operator/pull/327/files#diff-04c6e90faac2675aa89e2176d2eec7d8) for more details
JIRA ticket: https://issues.redhat.com/browse/INTLY-5046
Changes were tested locally (cluster template generation -> cluster creation -> RHMI addon installation -> cluster deletion)
The only step that had to be done separately was creation of smtp secret (`make cluster/prepare/smtp`), which operator requires to be present in the namespace, but afaik that should be automated as a part of RHMI addon installation too.
Hi @philbrookes, is my assumption correct? ^
> feat: ocm fixes/updates, rhmi installation

- Makefile
renamed olm install make target
because the old make target is misleading
> renamed olm install make target

- Makefile
- make/ocm.mk
This change is based on discussion with @philbrookes yesterday.
We would need to generate a dummy smtp secret after integreatly-operator's namespace is created, so the operator is able to start with installation.
> fix: generate smtp secret after addon installation

- Makefile
- deploy/crds/examples/installation.cr.yaml
- pkg/controller/installation/installation_controller.go
- test/e2e/integreatly_test.go
OLM nightly pipeline is failing with `preflightMessage: Could not find redhat-rhmi-smtp secret in redhat-rhmi-operator namespace` 
It's missing to create the stmp secret and also the installation CR [integreatly-installation-cr.yaml](https://github.com/integr8ly/integreatly-operator/blob/1.16.0/deploy/crds/examples/integreatly-installation-cr.yaml#L10) uses `INSTALLATION_PREFIX` to name the secret 
1) Run `make test/e2e/olm`
2) Ensure `redhat-rhmi-smtp` secret is created
3) Ensure installation completes successfully
> fix: fixes olm pipeline

- deploy/operator.yaml
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/installation_controller_test.go
Add logic to `pkg/controller/installation/installation_controller` to set the
`Installation.Spec.UseClusterStorage` flag to the value defined in an
`USE_CLUSTER_STORAGE` environment variable.
If the environment variable is not set, set this value to `true`.
> Add env var to determine wheter to use CRO or not

- pkg/apis/enmasse/v1beta1/zz_generated.openapi.go
- pkg/apis/enmasse/v1beta2/zz_generated.openapi.go
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.openapi.go
- pkg/apis/monitoring/v1alpha1/zz_generated.openapi.go
Command operator-sdk generate openapi seems to use the file path in generated files which resulted in github.com/briangallagher references.
> fix generated files

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
Reducing rhsso replicas from 3 to 2. Two replicas is sufficient to provide HA.
> Reduce rhsso replicas to 2

- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/resources/rhsso.go
- pkg/resources/rhsso_test.go
currently the rhsso custom resources are not setting their
external database flags to enabled in rhmi. both rhsso instances
should be using the cloud resource operator to provision any
requried storage services.
this change ensures that the cloud resource operator provisions a
postgres instance for both rhsso and user rhsso.
verification:
- run an installation
- ensure that rhsso is provisioned successfully
- ensure that user rhsso is provisioned successfully
- ensure logging into to both sso succeeds and some resource
(e.g. users) can be created
- ensure the keycloak cr for rhsso and user rhsso have external
storage enabled
- ensure that the cloud resource operator successfully provisioned
storage for rhsso and user rhsso
ensure these checks are done against aws and in-cluster setups for …
> add external database support for rhsso and user rhsso

- openshift-ci/Dockerfile.tools
- openshift-ci/test/run
- scripts/process-image-manifests
**JIRA**
https://issues.redhat.com/browse/INTLY-4795
**Pre-req**
yq v3
The script verifys yq is installed. ~Replace the line inside check_yq function to `slkfjsdf >/dev/null` and the script will fail with an error. Or run it on a machine that doesn't have yq installed.~ no verification required here. It's working here https://integreatly-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Delorean%202.0/job/delorean-2-ews/job/3scale/job/discovery/23/console
**What**
Adding script which will be called by Jenkins pipeline. 
Extract the manifest 
Get the current version of the csv on the branch
Get the most recent version of the csv on from the manifest
Create a new folder for the new version and move the csv there.
Update csv to remove `replaces` and updates the namespace env var.
NOTE: For …
> Automated Manifest Updates:

- pkg/products/amqonline/reconciler.go
- pkg/products/amqonline/reconciler_test.go
https://issues.redhat.com/browse/INTLY-4805
Giving the dedicated-admins group all permissions on AMQ Online configurations in the AMQ Online managed namespace. This will give them the ability to modify infra configs, authentication services, address space plans and address plans without the need to open up a JIRA with CS-SRE.
> Allow dedicated-admins group to modify amq online configs

- scripts/process-image-manifests
Removing the --confirm flag. As per the `oc image extract --help` this command `--confirm=false: Pass to allow extracting to non-empty directories.` As we've just created the directory I'd expect it to be empty. If it's not we probably want the script to fail.
> remove --confirm flag

- scripts/process-csv-images
* Update csv with delorean registry image urls
* Generates a image_mirror_mapping in the operators manifest directory
Verify using:
```
$ ./scripts/process-image-manifests registry-proxy.engineering.redhat.com/rh-osbs/3scale-amp2-3scale-rhel7-operator-metadata:1.11.0-3 3scale 3scale-operator
$ ./scripts/process-csv-images manifests/integreatly-3scale/3scale-0.5.0/3scale-operator.v0.5.0.clusterserviceversion.yaml 3scale
$ cat manifests/integreatly-3scale/image_mirror_mapping 
registry-proxy.engineering.redhat.com/rh-osbs/3scale-amp2-apicast-gateway-rhel8:3scale2.8 quay.io/integreatly/delorean/3scale-amp2-apicast-gateway-rhel8_3scale2.8
registry-proxy.engineering.redhat.com/rh-osbs/3scale-amp2-backend-rhel7:3scale2.8 quay.io/integreatly/delorean/3scale-amp2-backend-rhel7_3scale2.8 …
```
> Add process-csv-images script 

- scripts/csv_helper
- scripts/process-csv-images
* Add csv_helper bash script
* Update process-csv-images script:
* Use helper method to get current csv file for the product
* Fix delorean image path/tag
Process CSV script now executes like:
```
./scripts/process-csv-images 3scale
```
Helper method can be used outside of other bash scripts like:
```
$ . ./scripts/csv_helper && get_current_csv_file 3scale
/home/mnairn/go/src/github.com/integr8ly/integreatly-operator/scripts/../manifests/integreatly-3scale/3scale-0.4.0/3scale-operator.v0.4.0.clusterserviceversion.yaml
$ . ./scripts/csv_helper && get_current_csv 3scale
3scale-operator.v0.4.0
$ . ./scripts/csv_helper && get_current_csv_file codeready-workspaces
/home/mnairn/go/src/github.com/integr8ly/integreatly-operator/scripts/../manifests/integreatly-codeready-workspaces/codeready-worksp …
```
> process-csv-images script updates

- scripts/mirror-images.sh
**JIRA**
https://issues.redhat.com/browse/INTLY-5340
Create multiple mapping files locally using the file name `image_mirror_mapping under product manifest folders `manifest/integreatly-3scale/image_mirror_mapping` and `manifest/integreatly-fuse/image-mirror-mapping` 
On mac:
`scripts/mirror-images.sh --filter-by-os=.*`
On linux:
`scripts/mirror-images.sh`
The images should be mirrored to quay.io
> add script to mirror images

- scripts/process-csv-images
Will produce a mapping which is valid of oc image mirror:
```
registry-proxy.engineering.redhat.com/rh-osbs/3scale-amp2-3scale-rhel7-operator@sha256:0208475c26aac01766244dc7e32aec576c484646838790d4f65d8c2e63f6611b quay.io/integreatly/delorean:3scale-amp2-3scale-rhel7-operator_latest
```
> Update process-csv-images script to deal with images using a sha56 digest

- Makefile
- README.md
- test/README.md
- test/functional/integreatly_test.go
- test/functional/main_test.go
verification:
1. Login to an existing openshift cluster.
2. Run `make test/functional`. The test may pass or fail depending on if the CRD exists in the cluster.
> add support to invoke functional tests locally

- README.md
- make/ocm.mk
- templates/ocm-cluster/cluster-template.json
https://issues.redhat.com/browse/INTLY-5451
* `make ocm/aws/create_access_key` to generate access key via aws CLI
* expects following env vars to be exported/passed as a parameter:
* `AWS_ACCESS_KEY_ID`,      `AWS_ACCOUNT_ID`,         `AWS_SECRET_ACCESS_KEY`
* `make BYOC=true ocm/cluster.json` to generate a cluster config with aws credentials
I'll update the readme shortly
> feat: ocm template - byoc support

- pkg/products/codeready/reconciler.go
jira: https://issues.redhat.com/browse/INTLY-5490
- Run the integreatly-operator locally
```bash
make cluster/prepare/project
make cluster/prepare/crd
make cluster/prepare/smtp
oc create -f deploy/crds/examples/rhmi.cr.yaml
make code/run
```
- go to the `redhat-rhmi-middleware-monitoring-operator` project
- check the prometheus route for monitoring alerts e.g. https://prometheus-route-redhat-rhmi-middleware-monitoring-operator.apps.aucunnin.h4m0.s1.devshift.org/alerts
- make sure there are only two alerts for codeready as shown below 
- check that there is no postgres pod running in codeready workspaces namespace
> Removed cronjob for postgres in codeready workspaces as never required

- pkg/products/solutionexplorer/reconciler.go
UPS and AMQ Online were not included in the `INSTALLED_SERVICES` env var that is added to the webapp.
> add all products to installed_services env var

- .gitignore
- scripts/setup-sso-idp.sh
JIRA: https://issues.redhat.com/browse/INTLY-5166
I am updating the existing script to get it working on non-OSD clusters.
The script will edit "cluster" OAuth config if it can't detect cluster ID via OCM CLI.
> Add OCP support into setup-sso-idp.sh

- make/ocm.mk
For some reason, Linux slaves do not like line endings with slash in `jq` commands:
```
12:20:05  + make BYOC=true OCM_CLUSTER_LIFESPAN=5 ocm/cluster.json
12:20:05  jq: error: syntax error, unexpected INVALID_CHARACTER, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
12:20:05  \
12:20:05  jq: 1 compile error
12:20:05  make: *** [ocm/cluster.json] Error 3
```
Removing the slashes fixes it. Verified on Jenkins slave.
> fix: jq compile error on linux OS

- cmd/manager/main.go
- deploy/crds/integreatly.org_rhmis_crd.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/controller/installation/installation_controller.go
- pkg/metrics/metrics.go
ISSUE: https://issues.redhat.com/browse/INTLY-5312
Add top level stage indicator to the status block in the RHMI CR. This stage indicator shows the current stage of installation and is marked as complete when all stages have been completed.
Add a metric which indicates the availability of the install. 
* Start the operator install process
* Watch the RHMI CR for updates.
* During the installation, the `status.stage` should display the current stage been installed.
* Once install is complete `status.stage` == `complete`
* polling the metric url `curl <cluster>:8383/metrics | grep rhmi` the `rhmi_status_available` metric will be displayed.
* `rhmi_status_available` will state `0` while the installation process continues
* `rhmi_status_available` should `1` once the install is complete
* …
> Stage Reporting And Availability Metric

- pkg/products/solutionexplorer/reconciler.go
The solution explorer expects a cluster type for some features to work. Set the cluster type to 'osd' on OS4.
> set cluster type to osd for solution explorer

- README.md
**Summary**
The current instructions on how to configure a Github IDP are out of date. The purpose of this PR is to reflect the latest configuration steps
> Updating README Github Oauth instructions

- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/userHelper.go
- pkg/products/rhsso/userHelper_test.go
- pkg/products/rhssouser/reconciler.go
Currently `@example.com` is appended to the username and used as the email as the user created in the openshift realm. Instead we should try to fetch the email from the associated `Identity` resource, from the Openshift user and use this value when creating the `KeyCloakUser`. 
If for some reason no email is found in the associated `Identity`, an `Update Profile` action is added to the created `KeyCloakUser` forcing them to add an email when first try to login to CodeReady or 3Scale Products
Jira:
* https://issues.redhat.com/browse/INTLY-5500
* Install Integreatly onto cluster from this branch
* Run the IDP Script to create sample users 
```
```
* Login into RHSSO as admin (credentials can be found at `credential-rhsso` secret)
* Remove the …
> INTLY-5500 - Get email from identity when creating keycloak user

- pkg/controller/subscription/subscription_controller.go
subscription has different name when installed as an addon
> subscription has different name when installed as an addon

- templates/monitoring/kube_state_metrics_alerts.yaml
- test/e2e/integreatly_test.go
https://issues.redhat.com/browse/INTLY-5466
- Perform an install via this branch
- Ensure that the below alerts were successfully created within `prometheus`, in the `rhmi-middleware-monitoring` namespace:
- View the expression in Prometheus for both the `PVCStorageWillFillIn4Days` and `PVCStorageWillFillIn4Hours` alerts, and remove the `<= 0` part of the expression. The expression should return a value for all of the available PVCs.
> Add missing pvc alerts

- make/ocm.mk
[Previous fix](https://github.com/integr8ly/integreatly-operator/pull/436/files#diff-c90e3921bdbf84a8bb9bb3e7179702e5) wasn't working properly. For some reason (I couldn't figure out why) [this call](https://github.com/integr8ly/integreatly-operator/pull/436/files#diff-c90e3921bdbf84a8bb9bb3e7179702e5R91) was run at the beginning of the target when the CR was not present, so [RHMI_NAME variable](https://github.com/integr8ly/integreatly-operator/pull/436/files#diff-c90e3921bdbf84a8bb9bb3e7179702e5R27) contained empty string.
Then the function wasn't called as it should have had on [this line](https://github.com/integr8ly/integreatly-operator/pull/436/files#diff-c90e3921bdbf84a8bb9bb3e7179702e5R91). So the [wait_command](https://github.com/integr8ly/integreatly-operator/pull/436/files#diff-c …
> fix: oc getting CR name

- go.mod
- go.sum
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/client.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/types.go
- vendor/modules.txt
Add phase in reconciliation that:
1. Creates a `rhmi-developers` group
2. Makes it a default group
3. Maps the `query-realms` role to the group
This allows the developer users to view the realm by default instead
of getting a `Forbidden` message on first login.
This operation is idempotent.
> INTLY-2850: Create default `rhmi-developers` group in User SSO

- pkg/products/threescale/reconciler.go
Check for workshop mode also when assigning `member` role to 3scale users: we want to make sure that users who got admin permissions but are not Openshift admins get to keep the permissions in workshop mode. This is required to be able to complete the Walkthroughs.
> dont unassign 3scale admin role in workshop mode

- templates/monitoring/kube_state_metrics_3scale_alerts.yaml
*JIRA:* https://issues.redhat.com/browse/INTLY-5290
- run rhmi locally 
- check the application monitoring prometheus alerts for the following alerts
ThreeScaleZyncPodAvailiblity, ThreeScaleZyncDatabasePodAvailiblity
- Test the alerts going to the deployment configs and scaling down the zync and zync-database pods for 5 minutes to confirm the alert triggers
>*NOTE*: zync pods may scale up again so may need to stop the 3scale operator.
> Add alerts for zync and zync-database availability 

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/resources/user/userHelper.go
- pkg/resources/user/userHelper_test.go
Jira
* https://issues.redhat.com/browse/INTLY-5468
* Checkout this branch and install integreatly
* Run the IDP sccript
```
PASSWORD=Password1 ./scripts/setup-sso-idp.sh 
```
* Create a keycloak user with special characters to the testing-ipd realm
```
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
name: test-user-irregular-username
namespace: redhat-rhmi-rhsso
spec:
realmSelector:
matchLabels:
sso: testing-idp
user:
lastName: Tester01
enabled: true
emailVerified: true
clientRoles:
account:
- manage-account
- view-profile
broker:
- read-token
username: tester@example.com!!
firstName: Test
credentials:
- type: password
value: Password1
email: tester@example.com!!!
```
* In a private window, sign into openshift console with this user
* Check that the generated keycloak user …
> INTLY-5468 - Fix invalid characters used in keycloak user meta name

- Makefile
- make/manifest.mk
Add manifest/check command to Makefile so we can check if any image_mirror_mapping files exist and block them from getting back to master
To verify:
1. Checkout this branch
1. run `make manifest/check`
2. run `touch manifests/integreatly-3scale/image_mirror_mapping`
3. make manifest/check
4. rm manifests/integreatly-3scale/image_mirror_mapping
> add manifest/check command to Makefile

- Makefile
https://issues.redhat.com/browse/INTLY-5809
Preflight checks was failing when using `make code/run`
Change `USE_CLUSTER_STORAGE` to boolean version over string
> Fix(env type): Chnage USE_CLUSTER_STORAGE to Boolean true

- manifests/integreatly-rhsso/rhsso-8.0.1/keycloakoperator.8.0.1.clusterserviceversion.yaml
Instead of pointing to a fork and image in a private account, this PR updates the keycloak operator image to one based on a fork in the integreatly org (https://github.com/integr8ly/keycloak-operator-rhmi/tree/all-branches) hosted on the integreatly quay repo.
> update keycloak operator image

- go.mod
- go.sum
- pkg/controller/installation/installation_controller.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/client.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/types.go
- vendor/modules.txt
Implement functionallity in RHSSO User operator to create a dedicated-admins group
with a realm-managers child group.
The dedicated-admins group has the manage-users and view-realm client roles,
and the realm-managers group has a manage-realm role for each role that is
created.
Implement functionallity to add the dedicated admin generated users from
Openshift to the dedicated-admins and realm-managers groups.
Refactor the logic to reconcile Keycloak groups based on a `keycloakGroupSpec`
struct that contains the desired status of the group.
Running on a cluster, set up the SSO IdP
```sh
```
Log in the User SSO as the `customer-admin01` user and check that (_Note: it might take a couple of minutes for the admin permissions to propagate after …
> INTLY-5589: Create dedicated-admins and realm-managers groups

- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- test/e2e/integreatly_test.go
RHSSO version is set as an empty string in the RHMI CR. This is due to the Keycloak operator does not set the version in the `KeyCloak` CR status 
I have created a Jira for this is the Keycloak backlog - https://issues.redhat.com/browse/KEYCLOAK-13234
So for now, just going to use a harded value like the other products
Jira:
* https://issues.redhat.com/browse/INTLY-5783
> INTLY-5783 - Fix RHSSO version not reported on CR

- test/common/alerts_exist.go
- test/common/tests.go
- test/common/types.go
- test/e2e/integreatly_test.go
- test/functional/integreatly_test.go
Check all alerts exist as part of e2e and functional tests 
- Alerts we expected that weren't found 
- Alerts that were found and not expected 
- Log in to an existing Openshift 4 cluster 
- Install integreatly from master
- Check out this branch and run `make test/functional`. The test is common to both e2e and functional tests, so running the functional ones is just quicker 
- See that the output of the test is as expected (e.g. try comment out some of the expected alerts, verify that the report output is correct)
>  [INTLY-5214] Check all alerts as part of e2e & functional tests

- pkg/config/monitoring.go
https://issues.redhat.com/browse/INTLY-5638
The new values match what's used for RHMI 1.x by SRE.
After install, to verify:
```
oc get pvc -n redhat-rhmi-middleware-monitoring-operator
```
Verify the pvc is 50GB.
The retention size can be verified via the Prometheus UI > Status > Configuration.
Also, verify the PVCStorageWillFillIn4Days and PVCStorageWillFillIn4Hours alerts are not triggering for the prometheus pvc
> INTLY-5944 Increase prometheus pvc storage & retention

- pkg/config/amqonline.go
- pkg/products/amqonline/reconciler.go
- pkg/products/amqonline/reconciler_test.go
- test/common/alerts_exist.go
issue: https://issues.redhat.com/browse/INTLY-4360
Add in a backup cron job for postgres to amq online 
- deploy rhmi
- check prometheus alerts route for the following alert rule for amq online postgres
to see if the cron job exists
and check all projects/cron jobs to confirm enmasse-postgres-backup present. 
- Setup the s3 bucket and access as outline in the [readme](https://github.com/integr8ly/integreatly-operator#local-setup)
- Create the job
```sh
oc create job enmasse-postgres-backup-$(date +"%Y-%m-%d-%H%M%S") --from=cronjob/enmasse-postgres-backup -n redhat-rhmi-amq-online
```
This should create a job in the form `enmasse-postgres-backup-2020-03-03-`
- Check the jobs pod logs to confirm that the backup was successful
e.g.
> INTLY-4360  add a postgres backup cronjob to amq online

- deploy/role.yaml
Adds missing permission for the rhmi-operator service account to get `Identity` resource
Jira:
* https://issues.redhat.com/browse/INTLY-5943
* Run `make cluster/prepare/local`
* Install integreatly using this branch running the service account `make code/run/service_account`
* When RHSSO has been installed, run the IDP script `PASSWORD=Password1 ./scripts/setup-sso-idp.sh`
* Sign into openshift console using one of these generated users
* Ensure RHSSO in RHMI CR does not fail
* Check the logged in user has been added to RHSSO openshift realm
* Admin credentials can be found in the `credential-rhsso` secret
> INTLY-5943 - Add permission for getting identities resource

- pkg/products/rhssouser/reconciler.go
**Description**
Adds missing field to reconciler
Jira:
- https://issues.redhat.com/browse/INTLY-5993
**Verification** 
- run `make/code/compile`
- run `make/code/run`
- Install integreatly 
- Once installed, run `oc get pdb --all-namespaces | grep rhmi`
- Ensure both `redhat-rhmi-rhsso` and `redhat-rhmi-user-sso` namespaces are returned
> INTLY-5993 - No pdb has listed for redhat-rhmi-user-sso namespace

- templates/monitoring/cluster-resources.yaml
- templates/monitoring/jobs/openshift_monitoring_federation.yaml
The `Resource Usage for Cluster` dashboard has several metrics which are not displaying any data. This is due to changes in label names and rules in newer versions of Kubernetes and Prometheus. 
Jira: https://issues.redhat.com/browse/INTLY-5501
- Install Integreatly from this branch 
- Navigate to the Grafana console > Resource by cluster usage dashboard
- Verify that all data is displaying correctly
> [INTLY-5501] Fix broken expressions for cluster usage dashboard 

- go.mod
- go.sum
- pkg/products/rhssouser/reconciler.go
Fixes a crash when users are added to OpenShift but have not yet logged in (and thus the federated identities array is empty).
Verification steps:
1) Install Integreatly
2) Run the `setup-sso-idp.sh` script to create an IDP and some users
3) leave the operator running: it will crash after a while
> fix: check array length before indexing

- test/OWNERS
@b1zzu @pawelpaszki Who from QE do you think should be added as an owner of the test folder?
> Update OWNERS for test folder

- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
Backup the 3scale system seed and master apicast secrets into the rhmi-operator namespace and restore them from there (in case the namespace gets removed).
> backup and restore 3scale secrets for namespace restoration

- test/common/alerts_exist.go
- test/common/dashboards_exist.go
- test/common/shared_functions.go
- test/common/tests.go
https://issues.redhat.com/browse/INTLY-5729
These changes automate the following test: https://gitlab.cee.redhat.com/integreatly-qe/integreatly-test-cases/blob/master/tests/dashboards/e02-verify-that-all-dashboards-are-installed-and-all-the-graphs.md
- Login to an OS4 cluster with RHMI installed
- Using this branch, run the functional tests: `make test/functional`, the test should initially pass, as the expected dashboards should match the list of dashboards in Grafana.
- Modify the list of  `expectedDashboards` in the `dashboards_exits` file by changing the names of the some of the existing dashboards in the list, and also by adding new dashboard to the list. Ensure that the tests fails accordingly, and that the failure message is clear and concise.
- Login to Grafana as the admin user …
> creation of grafana dashboards test

- go.mod
- go.sum
- pkg/config/rhssouser.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
JIRA: https://issues.redhat.com/browse/INTLY-5840
Verify that:
User SSO reconciler adds roles to "rhmi-developers" Keycloak group only once, during the installation.
If a role is removed, it should not be re-added by the operator.
Verify that redhat-rhmi-installation-config contains:
`DEFAULT_ROLES_CONFIGURED: "true"` in "rhssouser" section.
> INTLY-5840 - setup default roles in User SSO only once

- pkg/resources/backup.go
Bumps the backup container image version to fix an error on AMQ PV backups where container doesn't exit with an error on permissions error
https://issues.redhat.com/browse/INTLY-4625
- Ensure the version of backup container image is 1.0.13
> bumps backup container image version

- test/common/alerts_exist.go
- test/common/constants.go
- test/common/crd_exists.go
- test/common/cro_cr_success.go
- test/common/dashboards_exist.go
- test/common/deployment_types.go
- test/common/shared_functions.go
- test/common/types.go
https://issues.redhat.com/browse/INTLY-6301
The functional tests are failing under two circumstances:
1. The AWS alert names are wrong, they have the text `example` in the name
2. The deployment check is checking the storage deployments assuming they are always created on cluster. This is not the case for BYOC clusters.
> Functional tests failing due to incorrect alert names and storage deployment check

- pkg/products/amqonline/addressplans.go
AMQ Online does not allow empty strings in an address plan resouce. Router or Broker can be either left out be defined. The spec however does not include `omitempty` which means even empty strings will be serialized to yaml. Instead of modifying the spec, this PR sets the previously undefined strings to `"0.0"`. This is the equivalent of not having them in the yaml.
Verification steps:
1. Create an address space in the AMQ Online console
2. Create one address of each type, standard and brokered
3. Make sure that all addresses are created successfully
> fix: no empty strings in address space resources

- pkg/apis/integreatly/v1alpha1/rhmi_types.go
Some of the product and operator versions in `rhmi_types.go` contained inconsistent/incorrect product versions. These are the updated versions after talking to several engineering teams (syndesis, enmasse, strimzi). 
The operator versions seem to refer to the version in the CSV and in general not the actual operator release image, so I've left that as is.
> [INTLY-5947] Update product and operator versions

- pkg/products/rhsso/reconciler.go
add default rhsso email address when one not present:
This is to support the syncing of users in 3Scale. 3Scale fails to create a user without an email address and subsequently the product fails to install. 
run ./scripts/setup-htpass-idp.sh
Verify that the 2 users, customer-admin and test-user are created in cluster RHSSO with default email addresses, customer-admin@rhmi.io, test-user@rhmi.io
Log into 3Scale as the admin (use system-seed secret) and verify that the keycloak users have synced from Keycloak, customer-admin as a 3Scale admin and test-user as a member
> add default rhsso email address when one not present:

- Makefile
I was noticing a cached response when running functional tests even when I switched the target cluster which should have failed the tests.
```
ok      github.com/integr8ly/integreatly-operator/test/functional       (cached)
```
Cleaning the cachetest before each run is the change here as per https://golang.org/cmd/go/#hdr-Build_and_test_caching
> Clean test cache before running functional tests

- go.mod
- go.sum
- pkg/controller/user/user_controller.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/resources/user/userHelper.go
- scripts/setup-htpass-idp.sh
The RHMI developer group is a catchall for developers on the cluster, it used to ensure developers have the right cluster perms and the right access to products. At the moment it is also adding SRE users, these users don't need to be set up in 3scale etc.
Create a user in the following groups:
user1: dedicated-admins
user2: osd-sre-admins
Create a third user in no group. 
user3:
Run the RHMI-Operator and **log in with all 3 users**
1. Verify that user1 and user3 get added to the rhmi-developers group
2. Verify that user2 does not get added to the rhmi-developers group
3. Verify that user1 and user3 get added to the RHSSO OpenShift realm
4. Verify that user2 does not get added to the cluster RHSSO OpenShift realm
5. Verify that user1 and user3 get added as 3Scale users
6. Verify that user2 …
> remove sre users from rhmi group

- pkg/products/amqonline/addressplans.go
- pkg/products/amqonline/addressspaceplans.go
Two changes here:
- Fixing router number from 1000 to 10000 on unlimited address space plans
- Removing `router: 0.0` on address plans now that the type has changed back to Number.
> Fix router numbers on AMQ Online address and address space plans

- test/common/deployment_types.go
https://issues.redhat.com/browse/INTLY-6434
The common tests are not reporting the replica count of workloads on failure. Changing to use the correct type conversion
> Fix replicas not reporting on test failure

- test/common/routes_exist.go
- test/common/tests.go
- test/common/types.go
- test/e2e/integreatly_test.go
Create and add test to the `AFTER_INSTALL_TESTS` list that enumerates the expected routes
that must have been created and checks that they exist in the cluster.
Remove test logic that becomes redundant after adding this test.
> INTLY-5436: Tests to verify that all routes have been created

- templates/monitoring/kube_state_metrics_3scale_alerts.yaml
- templates/monitoring/kube_state_metrics_amqonline_alerts.yaml
- test/common/alerts_exist.go
JIRA: https://issues.redhat.com/browse/INTLY-6496
More than one Pod in the namespace could have a shared container name,
leading to incorrect alerts.
For example, if a container was exceeding 90% of its memory limit and
we wanted to alert on that; we wouldn't get alerted if it was summing
the usage and limits of more than one container (unless the sums also
happened to exceed 90% of the total limits for all of those containers
combined).
This change also renames the relevant alerts to make it clearer that
they're per Container rather than per Pod, and adds more context to
the descriptions.
Since these alerts pick up on _all_ pod/containers in their respective namespaces, the following commands will cause all 3 to trigger:
```
oc run intly-6496-trigger-amq-memory -n redhat-rhmi-amq-online …
```
> 🚨 Fix alerts that only group by container

- pkg/resources/backup.go
The `cronjob_exists` alert in 1.x was firing due to slow response times from the kube apiserver, which in turn caused problems with the data being gathered by kube-state-metrics.
This in turn caused the alert expression to evaluate to a truthy value, and trigger.
The duration of the trigger for the alert was increased from 1 to 5 minutes to account for this, and the severity of the alert was reduced from `critical` to `warning`
JIRA: https://issues.redhat.com/browse/INTLY-6371
- Clone this repo
- Run the operator and wait for install
- Wait for reconcile to update alert trigger and severity
- Verify that alert has updated triggers and severity
> INTLY-6371-updated-cronjob_exists-alert-trigger-and-severity

- pkg/products/threescale/reconciler.go
- pkg/resources/metrics.go
https://issues.redhat.com/browse/INTLY-6490
This PR addresses 2 issues:
1. When installing RHMI using external AWS resources resources, the Threescale Postgres/Redis alerts would trigger initially, and then resolve when the resources were in an available state. This PR refactors the existing Threescale alert creation flow to ensure that the alerts are created only when the resources are in an available state.
2. AWS Postgres and Redis alerts were noticed to be firing continuously, on what looked to be every hour. Any AWS resource related Prometheus alerts are now created with `for = '5m'`.
- Using this branch, run an install using external Postgres/Redis AWS resources
- Ensure the Postgres/Redis Threescale alerts are created only once the accompanying AWS resources are in an available …
> Refactored threescale external resource metric creation

- go.mod
- test/common/grafana_routes.go
- test/common/shared_functions.go
- test/common/tests.go
- test/common/user_dedicated_admin_permissions.go
- test/common/user_rhmi_developer_permissions.go
- test/resources/openshift_auth.go
add initial grafana dashboard tests from the external route
exposed in openshift.
this commit also adds functionality for logging in via the
openshift oauth proxy.
the two tests added in this commit:
- ensure the external route returns a 200 response code when a
user is authenticated.
- ensure dashboards are returned from the external grafana route.
> add initial grafana dashboards route functional tests

- test/common/alerts_exist.go
- test/common/alerts_firing.go
- test/common/dashboards_exist.go
- test/common/tests.go
- test/common/types.go
- test/e2e/integreatly_test.go
There is an existing test in the `e2e` package which ensures that no alerts are firing apart from `DeadMansSwitch`. 
This moves all remaining monitoring tests to the `common` package, which is executed for both e2e and functional tests, ensuring that these tests are run in both BYOC and non-BYOC environments. 
Jira: https://issues.redhat.com/browse/INTLY-6019
- Log in to an existing Openshift 4 cluster
- Install integreatly from master
- Check out this branch and run make test/functional. The test is common to both e2e and functional tests, so running the functional ones is just quicker
- See that the output of the test is as expected, for example: 
- If `DeadMansSwitch` is firing, the test continues, and if it's not firing the test fails
- If any other alert is firing or pending, the …
> [INTLY-6019] Verify that no alerts are firing apart from DeadMansSwitch 

- manifests/integreatly-amq-online/amq-online-1.4.0/addresses.crd.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/addressplans.crd.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/addressspaceplans.crd.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/addressspaces.crd.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/addressspaceschemas.crd.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/amq-online.1.4.0.clusterserviceversion.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/authenticationservices.crd.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/brokeredinfraconfigs.crd.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/consoleservices.crd.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/iotconfigs.crd.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/iotprojects.crd.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/messagingusers.crd.yaml
- manifests/integreatly-amq-online/amq-online-1.4.0/standardinfraconfigs.crd.yaml
- manifests/integreatly-amq-online/amq-online.package.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/products/amqonline/reconciler.go
- test/common/alerts_exist.go
- test/common/deployment_types.go
https://issues.redhat.com/browse/INTLY-5516
Upgrading AMQ Online to version 1.4. I have tested both install and upgrade using the steps in the JIRA. This has caused an issue with the first walkthrough in solution explorer which I have created a follow on JIRA for.
Unfortunately, it is still not possible to include the Enmasse operator as a dependency in Go mod due to this issue - https://github.com/EnMasseProject/enmasse/issues/4156
1. Get login details for both fresh install and upgrade cluster from me directly
2. Test using AMQ Online, creating address spaces, addresses etc.
> Upgrading AMQ Online to 1.4

- test/BEST_PRACTICES.md
This best practice comes from the experience with many new tests we created which verify multiple resources in the loop and therefore is better to check all resource before failing and report multiple errors if needed
> Add 'Don't fail immediately' to the test Best Practices

- Makefile
- deploy/crds/examples/integreatly-rhmi-cr.yaml
https://issues.redhat.com/browse/DEL-208
- A copy of the delorean pull secret downloaded from quay in the root dir of the operator.
- An openshift cluster to run it against and logged in with a user with cluster-admin privileges
NOTE: The verification can be done very early on in the install. You can kill it by deleting the cr but keep the operator running locally until you see `INFO[xxxx] uninstall completed`
1. Checkout this branch
2. `git rebase fuse-online-next-del195 `
3. oc login with kubeadmin user to OSD cluster (I can provide one if needed) 
Run steps 1-3 above (if not done already)
4.  make code/run/delorean 
Run steps 1-3 above (if not done already)
4. sed 's/TAG=2.0.0/TAG=2.0.0-rc1/g' Makefile
5. -make test/e2e
In both cases, verify that the entry 
1. `pullSecret` is populated …
> Automate configuration of ews branches

- Makefile
- test/functional/main_test.go
Capturing and the output of the tests and print it all only at the end make it difficult to debug a test
While capturing the output into a byte Buffer we are also writing it back to the original stdout and stderr files
> Collect the functional test suite output while printing it to the console

- test/common/default_email.go
- test/common/tests.go
Add test to ensure that users from the IDP have an email address
in the KeycloakUser CR that's generated by the operator.
If the user from the IDP has no email address, a dummy one will be
generated as <user name>@rhmi.io. Otherwise, the user email address
will remain:
Create two Openshift users, one with email address and one without it,
and test that the KeycloakUser CRs have the expected email addresses.
> With testing IDP related code borrowed from [INTLY-5437 PR](https://github.com/integr8ly/integreatly-operator/pull/510/)
1. Run the `TestDefaultUserEmail` test on a cluster with the operator running
2. While the test is still running:
1. Check that 2 new users are created (`oc get users`)
2. Check that 2 new identities are created (`oc get identities`) and assert that …
> INTLY-6399 Add test for default user email address

- go.mod
- pkg/products/amqonline/reconciler.go
- pkg/products/amqstreams/reconciler.go
- pkg/products/apicurito/reconciler.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/codeready/reconciler.go
- pkg/products/fuse/reconciler.go
- pkg/products/monitoring/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/solutionexplorer/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/products/ups/reconciler.go
- pkg/resources/backup/aws.go
- pkg/resources/backup/aws_test.go
- pkg/resources/backup/backup_executor.go
- pkg/resources/backup/backup_executor_test.go
- pkg/resources/backup/cronjob.go
- pkg/resources/backup/cronjob_test.go
- pkg/resources/installPlan.go
- pkg/resources/reconciler.go
- pkg/resources/reconciler_test.go
Implement components to perform and wait for backups on AWS resources or by creating
`Jobs` of backup `CronJobs`.
Add logic to perform the backups required for the different products before approving
an `InstallPlan`
The behaviour of this feature is different for installations using cluster storage than AWS storage. In order to fully verify this PR, it must be done on both kinds of installations. Repeat the following steps with: 1. `useClusterStorage = true` 2. `useClusterStorage = false`
* In a cluster, install RHMI and verify that the installation is not affected (no backup jobs are created either from CronJobs or PostgresSnapshot/RedisSnapshot)
* For each product listed in the [backup SOP](https://github.com/RHCloudServices/integreatly-help/tree/master/sops/2.x/backup):
* Simulate a …
> INTLY-3686 Perform backup of products before upgrade

- test/common/tests.go
Add missing test ID `B06` to automated test for default email address
* [Link to JIRA](https://issues.redhat.com/browse/INTLY-6399)
* [Link to test PR](https://github.com/integr8ly/integreatly-operator/pull/546)
* [Link to MR in `integreatly-test-cases` repo](https://gitlab.cee.redhat.com/integreatly-qe/integreatly-test-cases/merge_requests/107)
> INTLY-6399 Add missing test ID

- pkg/resources/metrics.go
JIRA: https://issues.redhat.com/browse/INTLY-6613
There are Duplicate Alert names for system and backend redis in 3scale , This pr is to generate unique names 
- Confirm that the alert rules are updated as follow
> change the alert name to include what redis is being alerted on using the cr name

- scripts/jenkins/nightly-report.sh
@psturc @pawelpaszki Wdyt?
I decided to improve weekly report generated based on the results of nightly jobs.
Now the "Build information" text is added as a "Note" in the weekly report.
This way we can communicate additional information about the particular build.
Output of the script now looks like this: https://gist.github.com/matskiv/1d2e16d9300ac01fe210e9bc43571b1d
I started adding "Build information" into the results of failed builds this week. It can be seen in Jenkins as well:
Script for pipeline. No impact on product.
> Add build description to weekly jobs report

- test/common/alerts_exist.go
Fix for test failures seen on the last nightly build of master:
https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-master/40/console
Test failures were caused by a change in #573 and went unnoticed in the PR because the tests are only executed when cloud resources are used, which is not the case with PROW. 
Ping @pawelpaszki @psturc @jjaferson
> Fixing alerts names in e2e tests on AWS

- test/resources/openshift_auth.go
Some nightly tests failed on:
`failed to login to openshift: error occurred during oauth login: failed to get permissions form: Form not found matching expr '[action=approve]'.`
Logs: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-master/36/console
Fix based on our discussion in GChat: https://chat.google.com/room/AAAAP43TtLA/D1-eUVsomnE
Successful prow/e2e run should verify this change
> Fixing login flow issue in E2E tests

- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/products/fuseonopenshift/reconciler.go
Upgrade Fuse on OpenShift to version 7.6.
Fuse on OpenShift does not have an operator and installation and reconciliation are done in a unique way. 
The install in the RHMI operator is essentially as documented here:
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.6/html-single/fuse_on_openshift_guide/index#install-fuse-on-openshift4
- Install RHMI
- Verify that all templates are installed as documented in above reference.
- Verify that the samples operator has skipped the templates:
- oc get configs.samples.operator.openshift.io -n openshift-cluster-samples-operator -o yaml
> update Fuse on Openshift to 7.6

- pkg/resources/metrics.go
- pkg/resources/sop_url.go
New sops been written for 
https://issues.redhat.com/browse/INTLY-6613
https://issues.redhat.com/browse/INTLY-6612
sop_url is not present in the alert at present. 
- set the  useClusterStorage: 'false' in the rhmi cr
- deploy branch to cluster
- go to the prometheus route
- go to alerts
- check product alerts `-PostgresConnectionFailed` , `-PostgresInstanceUnavailable`, `-RedisCacheUnavailable` and `-RedisCacheConnectionFailed` for the sop_url in annotations
> add sop_url to alerts for postgres and redis connectivity and availability alerts

- Makefile
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
`make gen/csv` command crashes on fedora system as there is differences in using the `sed -i` command for mac vs gnu systems.
A csv annotation was also added to include the custom resource display name as it was previously missing when generating a new csv which would prevent installation via OLM
Also made changes to allow setting the `ORG`, `PREVIOUS_TAG` and `TAG` makefile arguments by passing them through command line so that these do not need changed in the makefile when testing
* Generate a new csv via
```
PREVIOUS_TAG=2.0.0 TAG=2.0.1 make gen/csv
```
* Verify new csv has `RHMI Installation` as the `displayName` of `customresourcedefinitions`
* Verify the operator image tag in the new csv  is `v2.0.1`
> update csv generation

- deploy/role.yaml
- go.mod
- pkg/config/monitoring.go
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- pkg/resources/reconciler.go
Federate metrics about alerts to the cluster monitoring stack
Adds a new service monitor in a new namespace to be scraped by the cluster monitoring stack (exposing metrics about rhmi alerts).
1. Install RHMI using this branch
2. Make sure a namespace `redhat-rhmi-middleware-monitoring-federate` is created
3. Make sure the namespace contains a service monitor named `rhmi-alerts-federate`
4. Check the config of the prometheus instance in `openshift-monitoring`: a job to scrape the `rhmi-alerts-federate` service monitor should be present
The cluster prometheus should now have a target for the federated endpoint:
> federate alert metrics to cluster monitoring

- scripts/setup-sso-idp.sh
- scripts/testing-idp-template.yml
Realm display name was previously hardcoded to `Testing IDP` in the realm template used by the idp-script. This change adds an additional optional `REALM_DISPLAY_NAME` parameter to the IDP script to allow specifying the display name of the realm created
Jira:
* https://issues.redhat.com/browse/INTLY-6724
Assoicated SOP update PR:
* https://github.com/RHCloudServices/integreatly-help/pull/450
* Install RHMI from this branch
* Should only need up till RHSSO is install
* Run the IDP script, passing the `REALM_DISPLAY_NAME` parameter
```
REALM_DISPLAY_NAME=RHSSO NUM_ADMIN=1 NUM_REGULAR_USER=0 ./scripts/setup-sso-idp.sh
```
* In an incognito tab, select the created idp in the openshift sign in page, and verify the display is in the one passed in via the script
> INTLY-6742 - Add realm display name parameter to idp setup script

- templates/monitoring/critical_slo_alerts.yaml
https://issues.redhat.com/browse/INTLY-6779
- Perform an install using this branch
- Trigger multiple `Threescale` and `UPS` alerts
- Navigate to the `Critical SLO Summary` Grafana Dashboars in `middleware-monitoring` namespace.
- Ensure that for both the `Threescale` and `UPS` sections of the dashboard, the correct information is displayed, i.e. the number of alerts is correct, and the accompanying graph is displaying data.
> Updating query to correctly match product name

- test/common/testing_idp.go
- test/common/user_rhmi_developer_permissions.go
- test/resources/openshift_auth.go
This is a fix for the e2e tests failure we've seen on nightly pipeline
JIRA: https://issues.redhat.com/browse/INTLY-6766
This issue has been caused by the tests code that is adding/updating "testing-idp" related resources. Main problem was with the KeycloakClient CR, which was overridden with a different secret, but OAuth CR was not being updated to use this secret.
Minor bug fixes around error handling and KeycloakUser CR updates.
I also reverted my previous "fix".
> INTLY-6766 - fix auth issues affecting nightly tests

- pkg/products/threescale/reconciler.go
https://issues.redhat.com/browse/INTLY-6843
With the inclusion of 3scale 2.8, PDBs will now be created if you enable in the API Manager CR
This change will also allow us to delete this SOP - https://github.com/RHCloudServices/integreatly-help/blob/master/sops/2.x/create_cluster_3scale_pod_disruption_budget.md
1. Verify 3scale PDBs exist on cluster https://console-openshift-console.apps.dffrench.h8q1.s1.devshift.org/search/ns/redhat-rhmi-3scale?kind=policy%7Ev1beta1%7EPodDisruptionBudget
> Adding 3scale PDB creation

- Makefile
Currently when running the test/functional target we are defaulting to 10 minutes. We have a number of polls in our functional tests adding up to a combined 57 minute timeout. This change adds the timeout flag to our target, increasing the timeout to 80 minutes to allow for the maximum timeout of the test polls and giving some wiggle room to any additional tests to be added.
> Add test timeout to test/functional target

- test/common/alerts_exist.go
Key changes:
91ebbdc - Fuse Online AWS alerts
Verification:
- Run `make test/functional` against an RHMI cluster using AWS resources
> ensure fuse online aws expected alerts are added

- Makefile
- scripts/setup-delorean-pullsecret.sh
As part of the delorean setup to ensure pods can pull from the private delorean repo we can edit the pull-secret secret in the openshift-config namespace to include our secret. The operator will then deploy this to each node and they can then by default pull from the private repo.
1. Download token from `docker configuration` tab here https://quay.io/organization/integreatly?tab=robots and place it in the integreatly-operator root directory
2. Run `make cluster/prepare/delorean/pullsecret`
3. Run `make code/run/delorean`
4. Verify that the delorean pull secret is in the pull-secret secret in the openshift-config namespace
5. Verify that the installation completes
> add delorean pullsecrets script

- pkg/apis-products/enmasse/v1beta1/brokeredinfraconfig_types.go
- pkg/products/amqonline/infraconfigs.go
https://issues.redhat.com/browse/INTLY-6837
With the inclusion of AMQ Online 1.4, PDBs will now be created if you specify a particular value in the standardInfraConfig.
This change will also allow us to delete this SOP - https://github.com/RHCloudServices/integreatly-help/blob/master/sops/2.x/on_request_amqonline_addressspace_pod_disruption_budget.md
Out of 4 InfraConfigs, only 2 should create PDBs for its brokers and routers. The brokered and minimal standard addressspace will not have PDBs created for them.
1. Login to https://console-openshift-console.apps.dffrench.h8q1.s1.devshift.org/
2. Verify 4 PDBs exist. 1 router and 1 broker PDBs for 2 different address spaces
-- https://console-openshift-console.apps.dffrench.h8q1.s1.devshift.org/search/ns/redhat-rhmi-amq-online?kind=policy%7Ev1 …
> Adding AMQ Online PDB creation for brokers and routers

- templates/monitoring/kube_state_metrics_3scale_alerts.yaml
[JIRA](https://issues.redhat.com/browse/INTLY-6769) the following PR is to fix certain alerts that are counting deploy pods which have already completed and are not running which stops the alerts from triggering.
#Verifcation 
1. install integreatly from this branch
2. Run the following command to bring the relevant pods down 
```
while true; do
if oc get deployment -n redhat-rhmi-3scale-operator -o json | jq '.items[0].spec.replicas' | grep 1; then
oc scale deployment 3scale-operator --replicas=0 -n redhat-rhmi-3scale-operator
fi
if oc get dc apicast-production -n redhat-rhmi-3scale -o json | jq '.spec.replicas' | grep 2; then
oc scale dc apicast-production --replicas=0 -n redhat-rhmi-3scale
fi
sleep 5
done
```
Substituting apicast-production with a deployment config from below:
- …
> Certain 3scale alerts not firing when pods are down

- pkg/products/monitoring/reconciler.go
[Jira](https://issues.redhat.com/browse/INTLY-6951) This Pr is to ensure that  the redhat-rhmi-monitoring-federate namespace will be removed when rhmi is uninstalled. 
1. install the monitoring product
2. uninstall the monitoring product
3. redhat-rhmi-monitoring-federation namespace should be removed without manual interference
> redhat-rhmi-monitoring-federate namespace not removing when rhmi is uninstalled

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- test/common/scale_up_replicas_rhsso.go
- test/common/tests.go
https://issues.redhat.com/browse/INTLY-7054
Allowing RHSSO and user SSO replicas to be scaled beyond the default of 2.
> Allowing rhsso and user sso replicas to be scaled

- templates/monitoring/kube_state_metrics_fuse_online_alerts.yaml
- test/common/alerts_exist.go
https://issues.redhat.com/browse/INTLY-6839
This change also includes the removal of the `FuseOnlinePodCount` alerting rule.
- Install via this branch
- Use the below command to bring the relevant pods down - this needs to be done for both the `syndesis-server` and `syndesis-ui` pods:
**Syndesis-UI**
```
while true; do
if oc get deployment syndesis-operator -n redhat-rhmi-fuse-operator -o json | jq '.items[0].spec.replicas' | grep 1; then
oc scale deployment syndesis-operator --replicas=0 -n redhat-rhmi-fuse-operator
fi
if oc get dc syndesis-ui  -n redhat-rhmi-fuse -o json | jq '.spec.replicas' | grep 1; then
oc scale dc syndesis-ui --replicas=0 -n redhat-rhmi-fuse
fi
sleep 5gp
done
```
**Syndesis-Server**
```
while true; do
if oc get deployment syndesis-operator -n …
```
> Removed fuseonlinepodcount alert and updated server and ui queries

- test/common/codeready_crudl.go
- test/resources/codeready_login.go
Jira link: https://issues.redhat.com/browse/INTLY-6679
Added more logging information for the code ready login flow flake. Theoratical understanding is
the code received from oauth is not valid or expired. One possible reason could be username in IDP
is not yet synced correctly (fixed in: https://issues.redhat.com/browse/INTLY-6766).
> Functional test:  Code ready login - Add more logging information

- test/common/alerts_exist.go
https://issues.redhat.com/browse/INTLY-7157
Removal of the `redhat-rhmi-amq-online-enmasse-console-rules.yaml` alerts exist test
- Execute the functional tests against a cluster using this branch - you may have to comment out some of the other test cases in order to solely test the `alerts_exist` test case (please ask if unsure) 
- Confirm that the test **does not** fail with the following message:
```
File Name: redhat-rhmi-amq-online-enmasse-console-rules.yaml
Missing Rules: []
Unexpected Rules: []
Status: File expected but not found
```
> Removing amq-online-enmasse-console-rules alert test

- test/common/codeready_crudl.go
- test/common/grafana_routes.go
Temporary workaround until [INTLY-6738](https://issues.redhat.com/browse/INTLY-6738) and [INTLY-6679](https://issues.redhat.com/browse/INTLY-6679) are addressed.
Logs last request and response in case of failure, and marks the test as skipped.
> Ignore failure of a flaky grafana route test

- Makefile
- test/common/3scale_crudl.go
- test/common/codeready_crudl.go
- test/common/default_email.go
- test/common/fuse_crudl.go
- test/common/grafana_routes.go
- test/common/network_policy_access_ns_to_svc.go
- test/common/testing_idp.go
- test/common/user_dedicated_admin_permissions.go
- test/common/user_rhmi_developer_permissions.go
- test/resources/openshift_auth.go
Fix  *B03 - Verify RHMI Developer User Permissions are Correct* test flake
- Increase timeout to 5 minutes to prevent timeout test flake
- Reverse logic and change subdomain on approval page check function to prevent `Form not found matching expr "[action=approve]" ` test flake
- Add some logging to help troubleshoot if further flakes exist
- Add error handling for io.EOF error returned when checking for openshiftIDP, this error handling is needed to prevent the test flake, the check function will finish and not run again if an error is returned at any stage, this means that in this case the error is returned before the IDP becomes fully available (or such is the theory)
- [:heavy_check_mark: ] Bug fix (non-breaking change which fixes an Issue
- Run `make test/e2e/prow` on OSD cluster
- …
> [W.I.P]INTLY-6737-e2e-verify-user-permissions-test-flake

- pkg/products/amqonline/reconciler.go
- pkg/resources/backup.go
- test/e2e/integreatly_test.go
AMQ Online resources are not backed up. This adds a cronjob to back them up to s3.
> resources backup for AMQ Online

- pkg/controller/installation/types.go
- pkg/products/threescale/reconciler.go
- test/common/3scale_crudl.go
- test/common/codeready_crudl.go
- test/common/default_email.go
- test/common/fuse_crudl.go
- test/common/grafana_routes.go
- test/common/network_policy_access_ns_to_svc.go
- test/common/shared_functions.go
- test/common/testing_idp.go
- test/common/user_dedicated_admin_permissions.go
- test/common/user_rhmi_developer_permissions.go
- test/resources/3scale_api.go
- test/resources/codeready_login.go
- test/resources/openshift_auth.go
- test/resources/types.go
Copy of https://github.com/integr8ly/integreatly-operator/pull/650 so I can see the OpenShift cluster the e2e tests are running on, for debugging
> INTLY-6748 disable 3scale resource requirements for pds

- manifests/integreatly-amq-online/1.4.1/amq-online.1.4.1.clusterserviceversion.yaml
- test/common/alerts_exist.go
- test/common/dashboards_exist.go
- Successful installation of monitoring resources using this branch
- Successful installation of monitoring resources when upgrading from `2.1.0` -> `2.2.0` via OLM
- Tests updated to account for the new dashboards/alerts
https://issues.redhat.com/browse/INTLY-5111
Verification requires both an install (which can be done locally), and an install and upgrade (via OLM) to test that the upgrade works as expected
- `oc login` to your OS4 cluster
- Using this branch, run a local install
- Ensure the following alerts are created, and are not triggering:
```
/etc/prometheus/rules/prometheus-application-monitoring-rulefiles-0/redhat-rhmi-amq-online-enmasse.yaml
ComponentHealth
AddressHealth
AddressSpaceHealth
AuthenticationService
RouterMeshConnectivityHealth
RouterMeshUndeliveredHealth …
```
> Installation of AMQ monitoring resources

- deploy/role.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/installation_controller_test.go
https://issues.redhat.com/browse/INTLY-6170
Adding ability for RHMI operator to approve its own manual approval install plan when the release is non-service affecting. Currently, the detection for service affecting or not is based on an annotation for the new integreatly-operator CSV.
Verification is a little complicated since this is dealing with OLM and upgrades.
1. Run `PREVIOUS_TAG=2.0.0 TAG=2.0.1 make gen/csv`
2. Manually modify new CSV
-- Change containerImage and operator deployment image field to my image `quay.io/davidffrench/integreatly-operator:vINTLY-6170`
-- Add `displayName: RHMI Installation` to spec.customresourcedefinitions.owned
3. Push the CSV to your application registry. `QUAY_USERNAME=<your username> QUAY_PASSWORD=<your password> REPO=<your repo name, I used my …
> Allow integreatly operator to approve its own install plan

- pkg/controller/installation/bootstrapReconciler.go
- pkg/controller/installation/bootstrapReconciler_test.go
- test/common/network_policy_access_ns_to_svc.go
- test/common/user_dedicated_admin_permissions.go
- test/common/user_rhmi_developer_permissions.go
- test/functional/integreatly_test.go
- test/resources/openshift_api.go
Dedicated admins should have view and update access to RHMI Config resource
Jira:
* https://issues.redhat.com/browse/INTLY-6744
(Already covered as part of e2e test)
* Install RHMI from this branch 
* Should only need to wait till the `bootstrap` phase is complete
* Verify `rhmiconfig-dedicated-admins-role` Role is created
* Verify `rhmiconfig-dedicated-admins-role-binding` Role Binding is created
* Install testing IDP
```
```
* Login as a dedicated admin (e.g `customer-admin01`)
* Verify dedicated admin **can** view and update RHMI Config in only the `redhat-rhmi-operator` namespace
* Verify dedicated admin **cannot** delete or create RHMI config resource
* Login as developer user (e.g `test-user01`)
* Verify test user has no access to the …
> INTLY-6744 - Role for RHMI Config

- scripts/setup-sso-idp.sh
Added parameter on the 'ocm get' command for clusters, to filter by managed clusters only, otherwise all of the clusters in the world are included
> Filter the command for ocm get clusters to only include managed/SRE

- deploy/operator.yaml
Adds resource limits to operator deployment
Jira:
* https://issues.redhat.com/browse/INTLY-6739
* Generate a new csv
* ` PREVIOUS_TAG=2.1.0 TAG=2.2.0  make gen/csv`
* Check generated csv that the limits has been added to the container deployment
Optional:
* Install RHMI from this branch
```
oc create -f deploy/operator.yaml -n redhat-rhmi-operator
```
* Check the deployment and operator pod for limits
> INTLY-6739 - add resource limit to operator deployment

- Makefile
- cmd/manager/main.go
- deploy/operator.yaml
- deploy/role.yaml
- deploy/webhook-service.yaml
- go.sum
- pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
- pkg/controller/installation/installation_controller.go
- pkg/webhooks/operator_webhooks.go
- pkg/webhooks/operator_webhooks_test.go
- pkg/webhooks/reconciller.go
- pkg/webhooks/rules.go
- pkg/webhooks/webhook_register.go
- scripts/prepare-release.sh
- test/e2e/integreatly_test.go
In order to add the ability to implement custom validation for the new customer config CR, set up a Webhook server running with the operator.
Kubernetes allows to create validation webhooks pointing to a service in the cluster. The `controller-runtime` library contains the logic to register webhooks in the server provided by the `Manager` interface, but in order to set up the webhook a `ValidatingWebhookConfiguration` CR must be created pointing to the webhook service. 
These changes create a single source of truth for both the Webhooks endpoint and the CRs that are reconciled, therefore there's no need for manual synchronization between the webhook server and the `ValidatingWebhookConfiguration` CRs.
The webhook server requires TLS certificates to run. The following changes were made to …
> INTLY-6728 Add support for a webhook server running with the operator.

- manifests/integreatly-amq-online/1.4.1/amq-online.1.4.1.clusterserviceversion.yaml
https://issues.redhat.com/browse/INTLY-7442
Reverting specific tags for AMQ Online
Specific tags may give us deterministic deploys for AMQ Online but makes it much more difficult to quickly roll out an AMQ Online CVE fix as it will require a new release of the integreatly operator.
> Reverting using specific AMQ tags

- scripts/prepare-release.sh
1. Added an option to specify custom container image tag in CSV (required for upgrade pipeline which runs the upgrade `2.x.x -> master`)
2. Added support for Mac OS (sed)
3. Few fixes based on recommendations from [shellcheck](https://github.com/koalaman/shellcheck)
4. Fixed semver regex (replaced `\d` by `[0-9]`, since `\d` is not supported in bash - try out the fixed regex [here](https://regexr.com/53u9s))
5. Used in [RHMI upgrade pipeline](https://gitlab.cee.redhat.com/integreatly-qe/ci-cd/merge_requests/135)
```
export SEMVER=2.9.9 IMAGE_TAG=master
make release/prepare
grep ":master" deploy/olm-catalog/integreatly-operator/$SEMVER/integreatly-operator.v$SEMVER.clusterserviceversion.yaml
```
You should get the following output:
```
containerImage: …
```
> feat: support custom release image version

- pkg/products/threescale/reconciler.go
allow additional keys to be appended to 3scale S3 secret. allows 3scale to be used with Minio
verification:
- run the operator against a cluster
- wait for the installation to complete
- update the cro blobstorage secret in the `redhat-rhmi-operator` namespace with some additional keys
- wait for threescale to reconcile
- ensure the `s3-credentials` secret in the threescale namespace contains additional keys
> set additional secret keys for 3scale s3

- deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
- pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
- test/common/rhmi_config.go
- test/common/tests.go
> Link to JIRA: https://issues.redhat.com/browse/INTLY-7158
Following the implementation of the webhooks server, implement validation for the RHMIConfig.Spec.Upgrade section, and add logic to e2e tests to verify that the validation
is being performed successfully via the `ValidatingWebhookConfiguration` reconciled by
the operator
1. Follow the verification steps of #652 
2. On the console, find the RHMIConfig CR and attempt to perform the following changes:
| Change | Expected result after save |
| ----------- | ----------------------------------- |
| Set the `applyOn` value to an invalid date format | Error |
| Set the `applyOn` value to a past date (example `2 Jan 2006 15:04`) | Error |
| Set the `applyOn` value to a future date and leave the other values as `false` | Success |
| Set …
> INTLY-7158 Semantic validation for RHMIConfig

- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
when multiple tenants are in the 3scale namespace, the current
approach to selecting routes will return the first route found.
this may not be the managed tenant.
verification:
- run an installation
- create an additional 3scale tenant 'evals'
- ensure the 3scale hostname provided to the solution explorer is
the correct hostname
- ensure blackbox targets for 3scale are pointed at the main
developer route
> update 3scale provider route selector to be more specific

- test/common/user_dedicated_admin_permissions.go
- test/resources/openshift_api.go
> Link to JIRA of bug this PR fixes: https://issues.redhat.com/browse/INTLY-7626
Add missing `TypeMeta` field to `RHMIConfig` that is marshalled and sent directly
to the Openshift API. This field is not required when using the Kubernetes client,
but when performing requests directly to the API it might fail if not provided.
Use `http.MethodDelete` to perform DELETE requests to Openshift API, as opposed to
hardcoded `"Delete"`, which can be rejected with "405 Method Not Allowed"
> INTLY-7626 Fix RHMI Config dedicated admin permission test

- deploy/operator.yaml
This reverts commit 7137c6c338229e70c4d34508272331f76cb2ed25.
Reverts this PR - https://github.com/integr8ly/integreatly-operator/pull/648
> Revert "add resource limit to operator deployment"

- scripts/prepare-release.sh
At the moment, when the pre-release script is executed, it will only regenerate the csv files when the minor versions are changed. This means if there are changes made to the `operator.yaml` file between RC releases, these changes are not reflected in the csv files.
The changes here will make sure the CSV file will always be regenerated.
> always regenerate the csv files

- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/config/ConfigReadWriter_moq.go
- pkg/config/manager.go
- pkg/config/monitoringspec.go
- pkg/controller/installation/types.go
- pkg/products/monitoringspec/reconciler.go
- pkg/products/monitoringspec/reconciler_test.go
- pkg/products/reconciler.go
- test/common/monitoringspec.go
- test/common/tests.go
- test/common/types.go
Jira link:  https://issues.redhat.com/browse/INTLY-7034
Clones service monitors from other namespaces that have "middleware-monitoring=true" in the new
redhat-rhmi-monitoring namespace. Creates rolebindings in the other namespaces (where servicemonitors were cloned)
for prometheus to scrape metrics from the corresponding services.
> New product in the monitoring stage

- go.mod
- pkg/config/apicurito.go
- pkg/config/fuse.go
- pkg/config/rhssouser.go
- pkg/products/apicurito/reconciler.go
- pkg/products/apicurito/reconciler_test.go
- pkg/products/fuse/reconciler.go
- pkg/products/fuse/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
This PR will create new Blackbox targets for Apicurito, RHSSOUser and Syndesis which are currently missing from the Operator
- [:heavy_check_mark:  ] Bug fix (non-breaking change which fixes an issue)
- Set up OSD cluster and login through cli
- Checkout this branch locally
- Run `make cluster/prepare/local` and `make code/run`
- After Integreatly has finished installation ensure that Integreatly-apicurito, Integreatly-RHSSOUser, Integreatly-Syndesis exist in Prometheus under `Probe_success` query
- Ensure that Integreatly-apicurito, Integreatly-RHSSOUser, Integreatly-Syndesis exist in grafana, under detailed summary
> INTLY-6778-Add new BlackboxTargets for Apicurito, RHSSOUser and Syndesis

- Makefile
- deploy/crds/examples/integreatly-rhmi-cr.yaml
- openshift-ci/Dockerfile.tools
- openshift-ci/test/run
- scripts/setup-delorean-pullsecret.sh
* Update setup-delorean-pullsecret script to check DELOREAN_DOCKER_CONFIG for delorean docker config content. Note: This env var will be set on prow jobs.
* Run setup-delorean-pullsecret script for cluster/prepare/delorean make target to add delorean secret to openshift pull-secret.
* Remove logic that adds the delorean pull secret to the rhmi CR
* Comment out check for mirror images files (DO NOT MERGE)
* Dockerfile.tools update:
* Add yq
> Enable pre release PR testing

- pkg/config/monitoringspec.go
JIRA Link: https://issues.redhat.com/browse/INTLY-7853
Servicemonitors type was added to the watchable CRDs previously.
RHMI operator cannot watch for service monitors.
[gryan@localhost ~]$ oc auth can-i list servicemonitors -n redhat-rhmi-monitoring
yes
[gryan@localhost ~]$ oc auth can-i watch servicemonitors -n redhat-rhmi-monitoring
no
> Remove the servicemonitors from watchable CRDs

- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- test/common/user_dedicated_admin_permissions.go
- test/common/user_rhmi_developer_permissions.go
- test/resources/openshift_api.go
Add a new Role that allows the dedicated admin group edit routes in the rhmi 3scale namespace
**Verification1** 
Patch the route as dedicated admin and verify success:
Patch the route as rhmi developer and verify permission denied error:
`oc patch route backend -p '{"metadata":{"labels":{"test":"version1"}}}' -n redhat-rhmi-3scale`
**Verification2**
Wait a period of time to verify that the rhmi reconciler does not revert the patch change
**Verification3**
Check that zync:domains:resync command won't case the changes to be reverted (run the following command within the system-app pod - bundle exec rake zync:resync:domains ).
> INTLY-7398 allow dedicated admins modify 3scale routes

- test/common/grafana_routes.go
Adding skip to verify grafana route test, to avoid test flakes
> add Skip to EO1, verify grafana route

- test/common/alerts_exist.go
https://issues.redhat.com/browse/INTLY-7878
Addition of the new `BrokerMemory` AMQ alert to the tests. 
- Update to the `C04_-_Verify_Alerts_exist` test case
- Ensure that the e2e test pass, and do not fail due to the `BrokerMemory` alert not being present
- `oc login` to an OS4 cluster with RHMI installed from master
- Using this branch, run the functional tests
- Ensure that all tests in `alerts_exists.go` pass successfully
> Addition of brokermemory amq alert in alert exists test

- pkg/products/monitoringspec/reconciler.go
- pkg/products/monitoringspec/reconciler_test.go
- test/common/monitoringspec.go
JIRA Link: https://issues.redhat.com/browse/INTLY-7854
Operator did not have permissions to create cluster role bindings, since
it runs with service account privileges. Code has been modified to create
a new role with the minimal required permissions and create a corresponding rolebinding
for them, so that prometheus can scrape metrics from the services.
> Fix the rolebinding permission issue

- cmd/manager/main.go
- deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
- pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
- test/common/rhmi_config.go
- test/common/tests.go
> Link to JIRA: https://issues.redhat.com/browse/INTLY-7392
Register a mutating webhook for the RHMIConfig CRD that adds to the CR the following annotations
| Annotation | Value |
| ------------- | --------- |
| `lastEditUsername` | Name of the user that performed the update to the CR (ignoring the RHMI operator as it would override the value at reconciliation) |
| `lastEditTimestamp` | Time (in UTC) when the update is performed |
Add test to log in as a customer admin and verify that their name is stored when performing a change to the CR, as well as the timestamp.
> INTLY-7392 RHMIConfig mutating webhook

- Makefile
- test/common/shared_functions.go
- test/common/user_dedicated_admin_permissions.go
- test/common/user_rhmi_developer_permissions.go
- test/functional/integreatly_test.go
- test/resources/openshift_api.go
* Verifies CRUDL Dedicated Admin Permissions for in `redhat-rhmi-amq-online`nNamespace:
* StandardInfraConfig
* BrokeredInfraConfig
* AddressSpacePlan
* AddressPlan
* AuthenticationService
* Verifies `github-oauth secret` access in `redhat-rhmi-operator` namespace
* Verifies role binding / role vebs and resources for amq online resourcs in `
redhat-rhmi-amq-online` namespace
Test cases:
* https://gitlab.cee.redhat.com/integreatly-qe/integreatly-test-cases/blob/master/tests/authorization/b04-verify-dedicated-admin-user-permissions-are-correct.md
* https://gitlab.cee.redhat.com/integreatly-qe/integreatly-test-cases/blob/master/tests/authorization/b02-verify-the-permissions-of-the-users.md#check-dedicated-admin-permissions
Jira:
* https://issues.redhat.com/browse/INTLY-7418
> INTLY-7418 - e2e verify dedicated admin permissions

- pkg/controller/installation/bootstrapReconciler.go
**Jira** https://issues.redhat.com/browse/INTLY-7749
Update: Dedicated Admin Permission
Added permission to a line local development with OLM deployments.
Use `kubectl auth can-i --list | grep rhmi` to check permissions
To verify
- Run the operator locally
- Set up the testing IDP
- Log in as a dedicated admin
- View the rhmi config
-- Expected: you should be able to `get, list, watch` the cr
> INTLY-7749 Dedicated Admin Permission

- test/common/user_dedicated_admin_permissions.go
Comment out AuthService CRUDL test - seems to causing an e2e flake as creating an `AuthenticationService` of type `external` crashes the enmasse-operator, so sometimes the pod doesn't recover fast enough for the following deployment replicas test
> comment out AuthService CRUDL test - seems to be causing e2e flake

- deploy/role.yaml
https://issues.redhat.com/browse/DEL-261
Error faced
```
failed to initialize service object for metrics: replicasets.apps \"rhmi-operator-5b7847c84\" is forbidden: User \"system:serviceaccount:redhat-rhmi-operator:rhmi-operator\" cannot get resource \"replicasets\" in API group \"apps\" in the namespace \"redhat-rhmi-operator\""}
```
Note: I didn't deploy this using olm.
I used `make cluster/prepare` `make cluster/prepare/crd` and oc deployed the required resources in the rhmi namespace
Please contact me for the cluster where I have this deployed.
> Adding in additional permissions to resolve metrics error in the logs

- make/manifest.mk
Add manifest/check/registries target, runs as part of manifest/check command.
Ensure no internal registries are being referenced in any of the manifests.
/cc @wei-lee
> Add manifest/check/registries make target

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
Update the keycloak metrics spi to 2.0.0 to fix an issue where the metrics endpoint can return a huge amount of data when there are many users in the keycloak instance.
This happened because the request_duration metric was recorded for every endpoint and there is an endpoint for every user. With thousands of users the amount of metrics data can slow down Prometheus and cause congestion.
In 2.0.0 we do no longer record the route for request durations. You still get the metric but no longer broken down by route.
> update keycloak metrics spi to 2.0.0

- cmd/manager/main.go
- go.mod
- pkg/controller/installation/bootstrapReconciler.go
- pkg/controller/installation/installation_controller.go
- pkg/metrics/metrics.go
- test-cases/tests/monitoring/m01-verify-rhmi-cr-metric-exposed.md
- test/common/rhmicr_metrics.go
- test/common/tests.go
Exposes two metrics for the RHMI installation CR
rhmi_status and rhmi_info 
https://issues.redhat.com/browse/INTLY-6667
1) Install operator via OLM
2) Go to the rhmi-operator pod
3) In the terminal tab curl the metric endpoint to verify if metrics are present 
- `curl 0.0.0.0:8383/metrics | grep rhmi_status{` 
-  `curl 0.0.0.0:8383/metrics | grep rhmi_info{`
4) Check if metrics have all the labels created and if their values match with installation CR
```
rhmi_info{installation_type="", master_url="", namespace="", operator_name="", use_cluster_storage=""}
rhmi_status{namespace="", last_error="", operator_name="", preflight_message="", preflight_status="", stage="", <product_name>-status="" ...}
```
5) Go to redhat-rhmi-middleware-monitoring-operator namespace 
6) Access Prometheus and …
> Expose metrics for the rhmi installation CR

- test/common/user_dedicated_admin_permissions.go
The `verifyDedicatedAdminAuthenticationServicePermissions` test previously caused the enmasse operator to crash and subsequently sometimes fail the deployment replica check as it might not have recovered causing flakiness in the e2e tests.
The crash was due to the `AuthenticationService` spec was empty, so this was added to the test. In addition a status was also added to hopefully prevent `409` conflict that may occur when the enmasse operator reconciles the CR in the `Update` part of the test ([relevant comment in previous PR](https://github.com/integr8ly/integreatly-operator/pull/699#issuecomment-629186926)).
Jira:
* https://issues.redhat.com/browse/INTLY-7932
> INTLY-7932 - fix + re-enable AuthService test causing enmasse operator crash & test flake

- test/common/user_rhmi_developer_permissions.go
This check:
a) doesn't provide much value considering all other tests that check Fuse status
b) fails if there are any deployed integrations
> Remove fuse pod count check from user permissions test.

- deploy/operator-subscription-template.yml
Role aggregation occurs for dedicated admins when operator is installed via OLM. Because we are not using an Operator group name ignored in staging/production in the upgrade pipeline, dedicated admins would have full access to RHMI CRs and so would fail these specific e2e tests.
* https://issues.redhat.com/browse/OSD-3636?focusedCommentId=14090821&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14090821
This update would use `rhmi-registry-og` as the default operator group name in the template
Jira:
* https://issues.redhat.com/browse/INTLY-7949
Assicated Pipeline PR:
* https://gitlab.cee.redhat.com/integreatly-qe/ci-cd/merge_requests/163
> INTLY-7949 - update default operator group name in template

- pkg/products/codeready/reconciler.go
- pkg/products/fuse/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/products/ups/reconciler.go
- pkg/resources/metrics.go
- pkg/resources/rhsso.go
- pkg/resources/sop_url.go
Jira: https://issues.redhat.com/browse/INTLY-8116
The creation of status phase alert pending check should be moved to after the CR phase is complete. We know that the resource will be pending until then, but do not know how long it'll last.
The pending check time should also be extended to 10 minutes.
> Pending alerts should not be created before RDS/Elasticache are created

- pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
- pkg/apis/integreatly/v1alpha1/rhmiconfig_types_test.go
currently the backup and maintenance windows are allowed to end
and start on the same minute. this is not permitted by the cloud
resource operator and validation on the rhmi operator side should
fail.
verification:
- run the operator on-cluster to ensure webhooks work as expected
- update rhmiconfig '.spec.backup.applyOn' to '01:00' and
'.spec.maintenance.applyFrom' to '02:00' and ensure an error is
returned by openshift through the validation webhook.
- update rhmiconfig '.spec.backup.applyOn' to '01:00' and
'.spec.maintenance.applyFrom' to '02:01' and ensure no error is
returned by openshift through the validation webhook
- update rhmiconfig '.spec.backup.applyOn' to '03:00' and
'.spec.maintenance.applyFrom' to '02:00' and ensure an error is
returned by openshift through the validation …
> fix backup maintenance window overlap check

- pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
Restoring code that was deleted in[1] commit of #795 
It was deleted because GH was showing incorrect diff on PR that was not rebased.
https://github.com/integr8ly/integreatly-operator/pull/795/commits/727c92206ac3fcb1ed222ae1f9a98db620d65a18#diff-13000454a7f0fc659c7c887cb6a0b140
This code has been part of RC1, and I would like to merge it before RC2, so there will not be any impact on testing.
> Restore code accidentally deleted in #795

- pkg/controller/subscription/rhmiConfigs/main.go
- pkg/controller/subscription/rhmiConfigs/main_test.go
The days difference calculated from a date to the next maintenance window uses a
`map[string]int` with the different week days in lowercase. If the value
from the maintenance window is not in lowercase it will fail silently to
match a value from that `map`, so it'll default to 0 as the zero value
of the map, which is Sunday, resulting in the day difference until the
next Sunday.
Convert the week day to lower case before indexing the map.
> Make maintenance window for RHMIConfig case insensitive

- templates/monitoring/cluster-resources.yaml
- templates/monitoring/endpointsdetailed.yaml
- templates/monitoring/endpointsreport.yaml
- templates/monitoring/endpointssummary.yaml
- templates/monitoring/resources-by-namespace.yaml
- templates/monitoring/resources-by-pod.yaml
JIRA: https://issues.redhat.com/browse/DEL-292
Depends on https://github.com/integr8ly/integreatly-operator/pull/798
Change to GrafanaDashboard json to add annotations which show upgrade data based on the pr above.
I've deployed this to a cluster using image quay.io/laurafitzgerald/integreatly-operator:v2.3.4
You can see Dashboards  [here](https://grafana-route-redhat-rhmi-middleware-monitoring-operator.apps.lfitzger.h1a9.s1.devshift.org/d/c84ae905b9f54268be6be82c9a5b7dd6/resource-usage-by-pod?orgId=1&refresh=10s&from=now-6h&to=now) - contact me for creds
You should see the tags as well if you hover on the annotations.
Note: upgrade verification depends on Upgrade Depends on https://issues.redhat.com/browse/INTLY-6831
> DEL-292 - GrafanaDashboard Upgrade Visulisation

- make/prow.mk
Add prow make targets:
prow/e2e/credentials: Extract the cluster credentials from an e2e test container in a known CI namespace
```
make prow/e2e/credentials CONTAINER_ENGINE=podman CI_NAMESPACE=ci-op-hndh5cb6
```
prow/e2e/tail: Tail the logs of the test container running the e2e tests in a known CI namespace
```
make prow/e2e/tail CONTAINER_ENGINE=podman CI_NAMESPACE=ci-op-hndh5cb6
```
Assumes you are oc logged into the correct CI cluster where the e2e test is running (https://api.ci.openshift.org)
> Add prow make targets

- test/e2e/integreatly_test.go
Remove e2e test for checking PVCs as this has been moved to the common tests.
Remove e2e test for checking PVCs as this has been moved to the common tests based on comments in  https://issues.redhat.com/browse/INTLY-7427.
- [ X] Bug fix (non-breaking change which fixes an issue)
> INTLY-7427-Remove-e2e-test

- pkg/products/amqonline/reconciler.go
The code ordering was fixed to check for the error first and then access the postgres object returned.
Error check was done after accessing the variable returned. Ordering has been changed to check for errors first.
> Fix for nil pointer exception in amqonline reconciler.

- test/e2e/integreatly_test.go
e2e test updated to quit if any part of the Cluster test fails. This causes the test run to exit early and not cause any failures later test due to the cluster install not been fully complete.
**JIRA** https://issues.redhat.com/browse/INTLY-7964
> INTLY-7964  e2e test flake: TestIntegreatly/integreatly/Cluster

- test/common/network_policy_access_ns_to_svc.go
The `get3ScaleAPIcasePod` function in the `TestNetworkPolicyAccessNSToSVC` test retrieves
a list of the APICast pods in the 3scale namespace, and returns the first element on the
list. This has caused some tests to fail, possibly because the test is executed before
any pod has been created.
Modify the `get3ScaleAPIcasePod` function to wait for the pod list to have at least one
element, or fail with timeout.
> INTLY-7831 Fix attempt to index first element of possibly empty list

- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- pkg/products/threescale/reconciler.go
Remove block on smtp credentials. Added check to ensure credentials match and restart threescale pods safely if credentials are updated.
> INTLY-8270_Do_not_block_smtp_secret

- test-cases/tests/dashboards/e02-verify-that-all-dashboards-are-installed-and-all-the-graphs.md
- test/common/dashboards_data.go
- test/common/tests.go
This PR adds common test covering [E02](https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/dashboards/e02-verify-that-all-dashboards-are-installed-and-all-the-graphs.md) test case.
It does not check Grafana UI itself, but gets dashboards definitions via Grafana API, extracts from them expressions used as queries for Prometheus and then checks that those queries when run against Prometheus return any data.
More info: https://issues.redhat.com/browse/INTLY-6234
> added dashboards data test

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
Update metrics spi to 2.0.1 to remove the `route` parameter from the request error metrics (see https://github.com/aerogear/keycloak-metrics-spi/pull/66).
The existing monitoring and metrics test will cover this change.
> update keycloak metrics spi to 2.0.1

- test-cases/tests/alerts/c05-verify-that-no-alerts-were-firing-during-and-after-installat.md
- test-cases/tests/alerts/c07-verify-rhmi-alerts-metrics-exposed-via-telemtry.md
- test-cases/tests/authorization/b01-verify-that-the-users-can-login-in-all-products.md
- test-cases/tests/authorization/b03-verify-rhmi-developer-user-permissions-are-correct.md
- test-cases/tests/dashboards/e04-verify-slo-dashboard.md
- test-cases/tests/high-availability/f04-verify-aws-s3-resources-exist-and-are-in-expected-state.md
- test-cases/tests/installation/a07-all-operand-versions-are-correct.md
- test-cases/tests/products/h01-ups-verify-that-ups-can-send-push-notification.md
- test-cases/tests/products/h03-verify-integration-between-3scale-and-openshift.md
- test-cases/tests/products/h04-verify-integration-between-amq-online-and-openshift.md
- test-cases/tests/products/h05-verify-integration-between-fuse-online-and-openshift.md
- test-cases/tests/products/h06-verify-integration-between-codeready-and-openshift.md
- test-cases/tests/products/h07-verify-3scale-user-promotion-works-and-stays-permanent.md
- test-cases/tests/products/h08-verify-amq-online-crs-can-be-modified-and-are-not-reset.md
- test-cases/tests/products/h11-verify-3scale-smtp-configuration.md
Added `automation-jira-created` tag, so that it is easier to filter manual test cases for which automation jira does not exist yet. This could be improved by updating tooling to allow creating jiras for test cases that are not covered yet by jira ticket.
> added automation-jira tag

- manifests/integreatly-3scale/0.5.2/3scale-operator.v0.5.2.clusterserviceversion.yaml
- manifests/integreatly-3scale/0.5.2/apps_v1alpha1_apimanager_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_api_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_binding_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_limit_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_mappingrule_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_metric_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_plan_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_tenant_crd.yaml
- manifests/integreatly-3scale/3scale.package.yaml
- manifests/integreatly-3scale/image_mirror_mapping
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
Upgrade 3scale operator to 0.5.2 to test component patch release process. https://issues.redhat.com/browse/INTLY-7936
- create operator namespace:
```sh
oc new-project redhat-rhmi-operator
```
- prepare secrets on cluster:
```sh
make cluster/prepare/smtp && make cluster/prepare/pagerduty && make cluster/prepare/dms
```
- create CatalogSource for install:
```
metadata:
spec:
image: quay.io/damurphy/integreatly-index:2.3.1
```
- UI -> Operators -> Operator Hub -> RHMI Operator -> Install (ns: redhat-rhmi-operator, approval: manual)
- UI -> Home -> Search -> InstallPlan -> approve 
- Monitor RHMI CR until last stage (Solution Explorer) installed:
```sh
watch -d …
```
> 3scale update to 0.5.2

- cmd/manager/main.go
- pkg/controller/installation/installation_controller.go
- pkg/metrics/metrics.go
- test/common/rhmicr_metrics.go
- test/common/tests.go
https://issues.redhat.com/browse/INTLY-8120
Removes all labels from the `rhmi_status` metric so the number of series is kept to a minimum (more info in jira & linked document).
These changes will ensure a limit of 8 series (1 for each status).
A metric series will be exposed at all times for the current stage, with a value of 1.
For example:
```
rhmi_status{stage="complete"} 1
```
An expression to determine if the RHMI install is complete would be:
```
rhmi_status{stage="complete"} == 1
```
If you want to get the currently active stage:
```
rhmi_status == 1
```
and use the value of the `stage` label
This approach seems more inline with how metrics are used to expose non numerical data, but comes with caveats (hence the need to limit the possible values of labels).
More info on metric …
> INTLY-8120 Strip down rhmi_status metric to only have the overall stage

- test/common/grafana_routes.go
https://issues.redhat.com/browse/INTLY-6738
This change uses new http client to authenticate and send request to grafana to avoid possible issue with cookies remaining from last session.
As suggested by @HubertStefanski I've left the test as skipped if failed as it is hard to verify that this change really fixed the issue. I will observe prow tests and if the test flake won't show up in ~1 week, I will change it so that it won't be skipped in case of error.
> fix test flake - grafana route

- pkg/products/monitoring/dashboardsHelper.go
- pkg/products/monitoring/reconciler.go
JIRA Link: https://issues.redhat.com/browse/INTLY-8566
When moving the grafana dashboard definition from yaml to code, the plugins
for endpointsdetailed dashboard was missed. The code changes have been made to
add the plugins list.
> Fix for missing plugins in endpointsdetailed grafana dashboard.

- manifests/integreatly-amq-online/1.4.4/addresses.crd.yaml
- manifests/integreatly-amq-online/1.4.4/addressplans.crd.yaml
- manifests/integreatly-amq-online/1.4.4/addressspaceplans.crd.yaml
- manifests/integreatly-amq-online/1.4.4/addressspaces.crd.yaml
- manifests/integreatly-amq-online/1.4.4/addressspaceschemas.crd.yaml
- manifests/integreatly-amq-online/1.4.4/amq-online.1.4.4.clusterserviceversion.yaml
- manifests/integreatly-amq-online/1.4.4/authenticationservices.crd.yaml
- manifests/integreatly-amq-online/1.4.4/brokeredinfraconfigs.crd.yaml
- manifests/integreatly-amq-online/1.4.4/consoleservices.crd.yaml
- manifests/integreatly-amq-online/1.4.4/iotconfigs.crd.yaml
- manifests/integreatly-amq-online/1.4.4/iotprojects.crd.yaml
- manifests/integreatly-amq-online/1.4.4/messagingusers.crd.yaml
- manifests/integreatly-amq-online/1.4.4/standardinfraconfigs.crd.yaml
- manifests/integreatly-amq-online/amq-online.package.yaml
Update amq-online manifest to 1.4.4 
This is an automatically generated branch to track the '1.4.4' version of the 'amq-online' OLM manifests.
This branch will be automatically updated with any changes related to this version until it finally GAs. 
Changes required to fix installation issues should be applied to this branch following the usual [PR Workflow](https://github.com/integr8ly/delorean/blob/master/docs/integrealy-ci/prow-pr-workflow.md)
More details about the Early Warning System that generated this can be found [here](https://github.com/integr8ly/delorean/tree/master/docs/ews)
> amq-online update to 1.4.4

- pkg/controller/subscription/subscription_controller.go
- pkg/controller/subscription/webapp/main.go
- pkg/resources/catalogsource/catalogsource_client.go
An issue with kubernetes clients instantiated when the reconciler is created is occurring
as it can't find certain custom resources. This client was being passed to the webapp
UpgradeNotifier, so it fails to notify upgrades to the WebApp CR.
Fix by creating an implementation of UpgradeNotifier that delegates its behaviour to a lazily instantiated upgrade notifier. This notifier is instantiated the first time it's used, guaranteeing that the kubernetes client will only be created when needed and avoiding the initial issue.
> Fix error with k8sclient for UpgradeNotifier

- pkg/controller/installation/installation_controller.go
- pkg/products/Reconciler_moq.go
- pkg/products/amqonline/reconciler.go
- pkg/products/amqstreams/reconciler.go
- pkg/products/apicurito/reconciler.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/codeready/reconciler.go
- pkg/products/datasync/reconciler.go
- pkg/products/fuse/reconciler.go
- pkg/products/fuseonopenshift/reconciler.go
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoringspec/reconciler.go
- pkg/products/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/solutionexplorer/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/products/ups/reconciler.go
- version/version.go
Refactored code around rhmi_version metric based on this PR https://github.com/integr8ly/integreatly-operator/pull/776
1) install the operator via OLM using CSV 2.3.0
2) create a new version for the operator using the script 
`SEMVER=2.3.1 ./scripts/prepare-release.sh`
3) build a new image and push to quay.io using your own account 
`make image/build/push ORG= QUAY_USERNAME= QUAY_PASSWORD="" TAG=2.3.1`
4) change the image field in the csv 2.3.1 to point to your quay.io account and push the csv
https://github.com/integr8ly/integreatly-operator/blob/2e975e9ec2fc7a2beb0f1fe478b6d6f08f9b426d/deploy/olm-catalog/integreatly-operator/2.3.0/integreatly-operator.v2.3.0.clusterserviceversion.yaml#L306
5) change the rhmi_config CR to always approve an upgrade
6) Verify if the version field in the …
> refactor rhmi_version logic

- go.mod
- go.sum
- vendor/modules.txt
fixes CVE-2019-5736 by adding a replace rule for affected runc versions
> CVE-2019-5736: update runc to v1.0.0-rc91

- pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
- pkg/controller/subscription/rhmiConfigs/main.go
- pkg/controller/subscription/subscription_controller.go
Fixes a bug that prevents the rescheduling of upgrades when there is a pending upgrade waiting to be approved
Follow the steps described in this PR to verify the install of patch upgrades https://github.com/integr8ly/integreatly-operator/pull/879
* When the latest CSV is published and a pending installplan is available go to the rhmiconfig crd change the `notBeforeDays` to 0 and `waitForMaintenance` to false, notice that a `recalculateSchedule: ''` annotation will be added and the status block of the cr will change. Go to the pending installplan and check if will get approved and installed by the operator 
* CSV are already created in my quay.io 
CSV 2.3.0 - quay.io/jjaferson/integreatly-index:2.3.0
CSV 2.4.0 - quay.io/jjaferson/integreatly-index:2.4.0
CSV 2.3.1 (patch upgrade) - …
> Intly-8185-fix

- deploy/role.yaml
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/prometheusRules.go
- test-cases/tests/alerts/c11-verify-rhmi-installation-alerts-are-firing.md
- test/common/alerts_exist.go
Adds 3 alerts around the `rhmi_status` metric: 
- **RHMIInstallationControllerIsNotReconciling**
Fires if the rhmi operator hasn't reconciled successfully in an interval of 15m over the past 1h.
- **RHMIInstallationControllerStoppedReconciling**
Fires if the rhmi operator hasn't reconciled successfully in an interval of 30m over the past 2h.
- **RHMIOperatorInstallCompleted**
Fires if the rhmi operator is not in its complete stage in the past 2h.
* This rule is created in the prometheus of the `openshift-monitoring` 
https://issues.redhat.com/browse/INTLY-7395
1. Install the operator via OLM
2. Verify if RHMIOperatorInstallCompleted alert is present and firing:
- Go to Deployments, in the `redhat-rhmi-operator` namespace and click on `rhmi-operator`
- Scale down to 0 the pod count by …
> [Intly-7395] Adds alerts around the rhmi_status metric

- pkg/resources/backup.go
Update backup container image to fix a bug with CRW 2.0 backups (the pods have many containers with their own project directories)
> update backup container image to 1.0.15

- manifests/integreatly-monitoring/1.2.1/application-monitoring-operator.v1.2.1.clusterserviceversion.yaml
Add a limited permission to bypass OLM bug.
The important thing about this change is that the rules for the alertmanager-service-account is different is some way than the rules for the grafana-serviceaccount.
This ensures the generated names of the corresponding clusterRoles & clusterRoleBindings will be different.
Related OLM issue https://github.com/operator-framework/operator-lifecycle-manager/issues/1625
The granted additional permission is to `get` `subjectaccessreviews`,
which will allow the SA to read an individual subjectaccessreviews resource by id.
Although not ideal, this permission is fairly limited.
https://issues.redhat.com/browse/INTLY-9201
> INTLY-9201

- manifests/integreatly-amq-online/1.4.4/amq-online.1.4.4.clusterserviceversion.yaml
Similar to https://github.com/integr8ly/integreatly-operator/pull/983 but applies to the AMQ Online manifest. I had to grant `update` permissions because both sas already have get, list and watch.
> workaround olm bug when sas have the exact same rules

- deploy/role.yaml
- pkg/controller/installation/installation_controller.go
- pkg/controller/subscription/csvlocator/csvlocator.go
- pkg/controller/subscription/csvlocator/csvlocator_test.go
- pkg/controller/subscription/rhmiConfigs/main.go
- pkg/controller/subscription/rhmiConfigs/main_test.go
- pkg/controller/subscription/subscription_controller.go
- pkg/controller/subscription/subscription_controller_test.go
Due to an OLM upgrade, CSVs are no longer embedded directly in the InstallPlan, causing the `GetCSV` function
to fail silently and return an empty CSV.
Decouple the logic to retrieve the CSV into an interface `CSVLocator` and create two implementations:
* `EmbeddedCSVLocator`: with the old logic, as the unit tests currently rely heavily on that logic
* `ConfigMapCSVLocator`: with the updated logic
Make the subscription controller reconciler depend on the interface and use correct implementation.
1. Create a release 2.5.0 from this branch. Follow [the OLM guide to install RHMI](https://github.com/RHCloudServices/integreatly-help/blob/master/guides/olm/installing-rhmi-bundle-format.md)
2. Install RHMI from this release and wait for the installation to be complete
2. Simulate an upgrade to …
> fix: Change logic to retrieve CSV from InstallPlan

- Makefile
- scripts/setup-delorean-pullsecret.sh
Editing the cluster pull-secret to allow pulls from the private delorean repository doesn't work for imagestreams. This change makes the delorean setup script also setup a secret and linking for 3scale and fuse so they can successfully create imagestreams based on private images.
1. Run `./scripts/setup-delorean-pullsecret.sh`
2. Verify the redhat-rhmi-3scale and redhat-rhmi-fuse namespaces are created
3. Run `oc get serviceaccount default -o yaml -n redhat-rhmi-3scale` and verify `regsecret` is a linked secret
4. Install rhmi from the 3scale-next-0.6.0 branch
5. Verify the imagestreams are created and pull seccessfully from the private delorean repo
> Create and link secrets for 3scale and fuse imagestreams

- test/common/grafana_routes.go
https://issues.redhat.com/browse/INTLY-6738
Both of the Grafana test cases are flaky, caused by an incorrect cookie is being sent in the GET request intermittently (~2-4% of the time - please see the JIRA for details). As a result, the test cases have been updated as such:
`TestGrafanaExternalRouteAccessible:` this test case has been refactored to check the the `/metrics` Grafana endpoint is accessible. The `/metrics` endpoint is accessable without the need to authenticate due to the following auth-skip in place: `- '-skip-auth-regex=^/metrics'`
`TestGrafanaExternalRouteDashboardExist:` test will now be skipped on failure, and the response from the Grafana GET request printed out to help with debugging. This is a temporary measure and a follow-up issue will address the flakiness of this …
> Refactoring grafana test cases

- test/common/alerts_mechanism.go
https://issues.redhat.com/browse/INTLY-8454
Updated the `TestIntegreatlyAlertsMechanism` test to allow the alerting mechanism for multiple Fuse alerts to be tested, as opposed to a single Fuse alert.
The test checks that the `FuseOnlineSyndesisUIInstanceDown` and `RHMIFuseOnlineSyndesisUiServiceEndpointDown` Fuse alerts go through the following process: `not firing before test execution -> pending -> firing -> not firing`
**This PR should be tested using both a 4.3 and 4.4 OS4 cluster**
- Install via this branch
- Run the `TestIntegreatlyAlertsMechanism` locally against your cluster: `go clean -testcache && go test -v ./test/functional -run=//^C03 -timeout=80m`
- Ensure the that test passes and that the logging is clear and concise
- During the execution of the test, when the alerts are …
> [INTLY 8454] Update alerting mechanism test to accept multiple alerts

- test/e2e/integreatly_test.go
By checking the Stage.Phase for completion, if the timeout elapses the correct failing stage is reported.
**JIRA**
https://issues.redhat.com/browse/INTLY-9061
**VERIFY**
* Change the timeout delay for `productsStageTimout` in `test/e2e/integreatly_test.go` to a value that a would not allow the products to be installed. eg 2 minutes
* Run the e2e tests
**expected:**
* `FAIL: TestIntegreatly/integreatly/Cluster` e2e test fails
* in the logs `integreatly_test.go:281: Waiting for completion of products` should be repeated followed by `integreatly_test.go:100: error in fuction integreatlyManagedTest: timed out waiting for the condition` and `integreatly_test.go:106: cluster not in a testable state, quiting test run`
> INTLY-9061 FIX(e2e): Stage completion more specific

- test-cases/OWNERS
Added 'trepel' (myself) to the test-case owners.
To verify I think it is enough to check there's no typo there.
> Added trepel to test-case owners

- test/common/shared_functions.go
INTLY-8771
Adding a utility method to detect the profile based on the CR instance. It can help in sorting the test cases based on profiles.
> detect profile type for the integration test based on created CR

- test-cases/tests/installation/a21-verify-maintenance-and-backup-windows.md
- test-cases/tests/installation/a22-verify-rhmiconfig-maintenance-and-backup-validation.md
- test-cases/tests/performance/k03-run-performance-test-against-rhsso.md
Updating steps of k03 - RHSSO performance test case for three reasons:
- An additional option for getting ec2 instance access
- Use the same keycloak version on cluster to run the performance tests
- Added workaround for running against RHSSO 7.4 (will work with 7.3 as well). This workaround will need to exist until 7.5 which likely won't be out for a while.
> Updating steps for k03 - RHSSO performance test case

- test/common/scale_up_replicas_threescale.go
The `wait.Poll` was using incorrectly because it breaks on the first error
> Fix wait for 3scale replicas to be ready

- pkg/controller/add_uninstall.go
- pkg/controller/uninstall/uninstall_controller.go
1. Install from this branch and wait for installation to be complete. 
2. Set uninstall label by using the command 
`oc label namespace redhat-rhmi-operator api.openshift.com/addon-rhmi-operator-delete=true
`
3. Verify the RHMI CR has a deletion timestamp and that the RHMI operator uninstalls as normal.
> INTLY-8358-Update RHMI operator to uninstall based on label on namespace

- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/prometheusRules.go
> * Initial PR: https://github.com/integr8ly/integreatly-operator/pull/935
> * Link to Jira: https://issues.redhat.com/browse/INTLY-8421
There's still a few alerts firing during uninstall. This fix ensures that no unwanted alerts are firing
* Add logic to remove all PrometheusRules with the `integreatly` label during
uninstall.
* Refactor new installation alerts to use AlertReconciler.
Install RHMI and run the following script, outputing the result into a Markdown file:
```bash
#!/usr/bin/env bash
echo '# Deleting RHMI CR'
echo "Time of deletion: $(date)"
oc delete rhmis rhmi -n redhat-rhmi-operator > /dev/null 2>&1 &
echo '# Alerts during uninstall'
echo '| Timestamp | Alerts |'
echo '| --------- | ------ |'
while true
do
oc get rhmis rhmi -n redhat-rhmi-operator > /dev/null 2>&1
if [ $? …
```
> INTLY-8421: Ensure that no alerts are left during uninstall

- pkg/products/amqonline/reconciler.go
- pkg/products/amqonline/reconciler_test.go
- pkg/products/amqstreams/reconciler.go
- pkg/products/amqstreams/reconciler_test.go
- pkg/products/apicurito/reconciler.go
- pkg/products/apicurito/reconciler_test.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/codeready/reconciler.go
- pkg/products/codeready/reconciler_test.go
- pkg/products/fuse/reconciler.go
- pkg/products/fuse/reconciler_test.go
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- pkg/products/monitoringspec/reconciler_test.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/products/solutionexplorer/reconciler.go
- pkg/products/solutionexplorer/reconciler_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/ups/reconciler.go
- pkg/resources/marketplace/MarketplaceManager_moq.go
- pkg/resources/marketplace/manager.go
- pkg/resources/reconciler.go
- pkg/resources/reconciler_test.go
This PR removes IntegreatlyOwnerAnnotations from products Subscription objects.
Explanation/Motivation:
In marketplace.Manager type the method InstallOperator currently adds the IntegreatlyOwnerAnnotations to
the Subscription that is created for each product. It is created using an Owner provided as a parameter of the
InstallOperator method.
The InstallOperator method is called on each of the products reconciler indirectly via calling the resources.Reconciler ReconcileSubscription method.
The Owner that is sent is the 'Namespace' K8s object belonging to the the product's namespace (which sometimes is the same as the operator's namespace like in the case of
the cloudresources product).
This means that the following annotations are set to the product's Subscription k8s object's object that …
> Remove IntegreatlyAnnotations setting products Subscriptions objects

- README.md
As part of a change triggered by https://issues.redhat.com/browse/INTLY-8098 
we need to add details on supported versions of RHMI and byoc clusters supported versions.
I noticed there was a section in this README and a section here: https://github.com/integr8ly/delorean/tree/master/docs/ocm
Seems the linked one is updated more regularly so pointing to that here and removing the duplicated steps.
> updating ocm section to link to existing up to date doc

- test/functional/main_test.go
The JUnit report was reporting more failures than the actual ones. The reason is that the output collected from the `teeOutput` function is incomplete, and this is happening because the testing module of go us usually flushing all the test results at the end and therefore the tee function is taking more than a cycle for writing it back to the stdout and to the output buffer and by converting the output buffer to a string before the function was completing it was actually cutting it.
**What:**
Add the forgotten `wg.Wait()` to the tee function to wait for all output to be flushed before returning the string
**How I tested it**
I simulated a huge amount of output with a single print:
```
func main() {
_ = teeOutput(func() {
fmt.Println(strings.Repeat("a huge amout of text ", 100000))
})
} …
```
> DEL-253 Fix the JUnit report for the functional test suite

- pkg/products/cloudresources/reconciler.go
https://issues.redhat.com/browse/INTLY-9101
1. Clone this branch
2. Log in to the provided OpenShift cluster as kubeadmin
3. In terminal window # 1, run:
```
make code/run USE_CLUSTER_STORAGE=false
```
4. In a terminal window # 2, run this command to show the status of postgres, redis and blobstorage CRs
```
watch "echo 'postgres CRs status:' && oc get postgres -o json | jq -r '.items[].status.phase' && echo 'redis CRs status:' && oc get redis -o json | jq -r '.items[].status.phase' && echo 'blobstorage CRs status:' && oc get blobstorages -o json | jq -r '.items[].status.phase'"
```
(all should have the status: `complete`)
5. In a terminal window # 3, trigger RHMI CR deletion
```
oc delete rhmi rhmi -n redhat-rhmi-operator
```
6. In about one minute, in terminal window # 2, you should see …
> fix: delete redis, postgres and blobstorages at the same time

- Makefile
- README.md
- deploy/catalog-source-template.yml
- scripts/bundle-rhmi-operators.sh
Add a new mechanism to deploy the RHMI operator, i.e. the bundle format. This is an alternative to using an OperatorSource. As OperatorSource is being deprecated and the bundle format will become the standard packaging for operators, this updates installs the RHMI operator through OLM, by creating bundles and indices and a CatalogSource. Mainly for development/testing purposes.
See detailed manual steps [here](https://github.com/RHCloudServices/integreatly-help/blob/master/guides/olm/installing-rhmi-bundle-format.md)
- New feature (non-breaking change which adds functionality)
See details in README.md on how to run the scripts and make target
Suggested testing:
- On a new cluster, deploy the latest bundle and verify the installation through Operator Hub
> (ORG=<YOUR_ORG> make …
> deploy RHMI with bundle format

- test-cases/tests/authorization/b03-verify-rhmi-developer-user-permissions-are-correct.md
Update wording of test for clarity - removed 'Go to the **redhat-rhmi-operator** namespace' step as this option is not available to RHMI developer user.
> Update test wording for clarity

- make/versions.mk
Add version check to catch when a CHANGEME string is in the rhmi_types file
> add versions check

- pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
- pkg/controller/rhmiconfig/rhmiconfig_controller.go
> Link to JIRA: https://issues.redhat.com/browse/INTLY-9693
This annotation is not needed anymore, after the refactor carried for INTLY-8450,
however it's still being set by the mutating webhook, and removed when setting
the upgrade status. However, in the case that the status is updated and no
annotations have been added to the CR, a panic may arise as the Annotations field
is `nil`.
Removing all usage of this annotation solves this.
> INTLY-9693: Remove usage of recalculateSchedule annotation

- deploy/olm-catalog/integreatly-operator/2.6.0/integreatly-operator.v2.6.0.clusterserviceversion.yaml
- pkg/products/cloudresources/reconciler.go
- test-cases/tests/uninstallation/o02-verify-if-cro-operator-removes-remaining-snapshots-for-rds-e.md
- test/common/3scale_smtp.go
adds delete strategy to remove snapshots to the `cloud-resources-aws-strategies` configmap in the rhmi operator namespace
https://issues.redhat.com/browse/INTLY-7184
> Requires a BYOC cluster
- Install the rhmi operator with the `USE_CLUSTER_STORAGE` field set to true 
- Uninstall the operator 
- Verify if the `cloud-resources-aws-strategies` configmap in the rhmi operator namespace has gotten the following fields:
- `blobstorage.production.deleteStrategy.forceBucketDeletion` set to true
- `postgres.production.deleteStrategy.SkipFinalSnapshot` set to true 
- `'redis.production.deleteStrategy.FinalSnapshotIdentifier` set to empty 
- Make sure there are not snapshots created
> feat(CroReconciler): adds delete strategy to remove snapshots

- test-cases/tests/authorization/b05-verify-codeready-crudl-permissions.md
- test-cases/tests/authorization/b08-verify-user-rhsso-permissions.md
- test-cases/tests/backup-restore/j10-verify-amq-backup-and-restore.md
- test-cases/tests/performance/k01-run-performance-test-against-amq-online.md
- test-cases/tests/performance/k03-run-performance-test-against-rhsso.md
- test-cases/tests/products/h01-ups-verify-that-ups-can-send-push-notification.md
- test-cases/tests/products/h05-verify-integration-between-fuse-online-and-openshift.md
- test-cases/tests/products/h08-verify-amq-online-crs-can-be-modified-and-are-not-reset.md
- test-cases/tests/uninstallation/o01-verify-cloud-resources-can-be-properly-cleaned-up-in-case-of.md
- test-cases/tests/uninstallation/o02-verify-if-cro-operator-removes-remaining-snapshots-for-rds-e.md
- test-cases/tests/walkthroughs/g02-verify-sso-walkthrough.md
- test-cases/tests/walkthroughs/g04-verify-api-management-walkthrough.md
Updated test case targets based on what was tested in 2.6.0.
No need to verify. If you really want, look at the test plan (https://docs.google.com/document/d/1d1_J6gPulw38llMV_xzTlb5iUR11jY3fWPJQ6nxtTuE/edit#heading=h.ragbu4u7yagw) and go through the testing epics to see what was tested in 2.6.0 and what was not (so it was moved to 2.7.0).
> Updated test case targets post 2.6.0 GA

- test-cases/tests/dashboards/e04-verify-slo-dashboard.md
- test-cases/tests/upgrade/n02-upgrade-rhmi.md
E04 updates:
Small notes on how to use the scripts and that it might be slightly tricky to bring stuff back up. Based on my experience doing the test case during 2.6.0
N02 updates:
Removed step 8 - CLUSTER_ID is not used in subsequent steps
Added steps 14 and 15 - these describe how to use workload-web-app to see the downtimes. These steps were just copy-pasted from H21.
The rest of the diff is just due to changing the step numbers, no content changes there.
Not sure how to verify this. Probably just read through the changes if that makes sense.
> N02 and E04 test case descriptions updated

- test-cases/tests/upgrade/n01-mesure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n02-upgrade-rhmi.md
Partially resolving https://issues.redhat.com/browse/DEL-387. The measure-downtime.js script should no longer be used. Workload-web-app and Delorean's downtime report command should be used instead.
> measure-downtime script removal from test cases

- test-cases/tests/upgrade/n02-upgrade-rhmi.md
Updated N02 (Upgrade RHMI) test case. Most notable modifications done
- It is no longer required to prevent the available upgrade to start automatically since by default it won't start sooner than 7 days after cluster creation (`notbeforedays` value is `7` by default)
- Updated section how to actually trigger the upgrade and added few notes what might go wrong and how to workaround it.
- Added note about N09 test case
- Small note on how to verfiy workload-webapp was deployed OK
- rest are just step numbering modifications
Verification
I think just reading through the test case is sufficient.
> Updated test case on how to trigger RHMI upgrade

- go.mod
- pkg/controller/subscription/subscription_controller.go
https://issues.redhat.com/browse/INTLY-9817
Install the operator via OLM using the CSV below:
- CSVs for upgrade with skipRange
`quay.io/jjaferson/integreatly-index:2.6.0` -> install the operator from this CSV
`quay.io/jjaferson/integreatly-index:2.7.0` -> skipped CSV
`quay.io/jjaferson/integreatly-index:2.8.0` -> skipped CSV
`quay.io/jjaferson/integreatly-index:2.8.1` -> CSV with skipRange (olm.skipRange: '>=2.6.0 <2.8.1') after the install point the catalogsource to this CSV
- CSVs for patch upgrade 
`quay.io/jjaferson/integreatly-index2.6.0` -> install the operator from this CSV
`quay.io/jjaferson/integreatly-index2.6.1` -> replaces 2.6.0 and is non service affecting
`quay.io/jjaferson/integreatly-index2.6.2` -> replaces 2.6.1
`quay.io/jjaferson/integreatly-index2.6.2-rc` -> replaces …
> Fixes a bug in the upgrades when a CSV has the skipRange present

- test-cases/tests/products/h07-verify-3scale-user-promotion-works-and-stays-permanent.md
- test/common/3Scale_user_promotion.go
- test/common/tests.go
- test/resources/3scale_api.go
Rebased off from https://github.com/integr8ly/integreatly-operator/pull/717
Automated e2e test for user promotion in 3scale does not get reverted by the operator
Jira:
* https://issues.redhat.com/browse/INTLY-7435
> INTLY-7435 - e2e test verify 3Scale user promotion does not revert

- test-cases/fixtures/test-template.md
- test-cases/tests/alerts/c16-verify-ocm-sendgrid-service-alerts.md
- test-cases/tests/installation/a26-verify-sendgrid-credentials-are-configured-properly.md
- test-cases/tests/uninstallation/o03-verify-sendgrid-credentials-are-removed.md
add test cases for the external ocm sendgrid service around cluster creation, deletion and alerts.
de2025fb933ce31e3fcfd40bd4aa801679c23894
add test cases to confirm the functionality of the ocm sendgrid
service on both rhmi installation and cluster deletion.
verification:
- install rhmi via the addon flow
- follow a26
- delete the cluster
- follow o03
26278d62d3b604e0d5775db1617dacdc81eabdc9
fix typo in test template
fix minor typo in tags of test template file
f2e2af37cf33d5b825cab1a968196f695d4d1df1
add sop c16 for verifying external ocm sendgrid alerts
currently we will have alerts for the external ocm sendgrid service
that will not appear in the integreatly prometheus stack but in the
ocm prometheus stack.
this new sop ensures we check that alerts have been synced correctly
to the …
> add ocm sendgrid service test cases

- .gitignore
- Makefile
- deploy/role.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/products/apicurito/reconciler_test.go
- test/common/rhmicr_metrics.go
JIRA: https://issues.redhat.com/browse/INTLY-9832
Fixing the pull secret source because originally used secret is not available on OSD 4.5.
I fixed a logical error in test/common/rhmicr_metrics.go
I edited `make code/run` target to use service account via temporary kubeconfig file. This should prevent unexpected RBAC issues during local development and testing.
Verify this installs correctly on OSD 4.5.x (maybe use `make code/run` to test secondary changes at the same time)
Check that monitoring is green
Verify that you are able to create and deploy an integration in Fuse
> INTLY-9832 Fix installation on OSD 4.5

- test/common/alerts_exist.go
https://issues.redhat.com/browse/INTLY-8382
adding alert_exists check for redis cpu usage alert
> adding alert_exists check for redis cpu usage alert

- pkg/controller/installation/installation_controller.go
- pkg/controller/subscription/rhmiConfigs/main.go
- pkg/controller/subscription/rhmiConfigs/main_test.go
- pkg/controller/subscription/subscription_controller.go
- pkg/controller/subscription/subscription_controller_test.go
Change from previously adding logic in the subscription controller. 
Perform an install and upgrade and verify that the 'toVersion' is set on the CR during install and upgrade 
and unset after. 
Verify 'version' is set appropriately after install and upgrade
> use code base version as apposed to csv version, on upgrade

- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/installation_controller_test.go
Adds ability to pass installType as env var
https://issues.redhat.com/browse/MGDAPI-7
1) export an env var
`export INSTALLATION_TYPE=managed`
2) install the operator locally
3) verify if the installation type in the RHMI CR is the same as the one in the env var
`oc get rhmi rhmi -o json -n redhat-rhmi-operator | jq .spec.type`
> feat(InstallationController): Adds ability to pass installType as env var

- pkg/controller/installation/bootstrapReconciler.go
- pkg/controller/installation/bootstrapReconciler_test.go
- test/common/rhmi_config.go
- test/common/user_dedicated_admin_permissions.go
> 🔨 Link to JIRA: https://issues.redhat.com/browse/INTLY-9953
> ℹ️ Link to JIRA **that added this permission**: https://issues.redhat.com/browse/INTLY-6744
Remove reconciliation logic of a Role and RoleBinding that granted dedicated admins
permissions to update RHMIConfig CRs, and add logic to ensure that if this
permission exists it is removed.
Update unit tests and e2e tests.
* An image of the operator based on this PR
```sh
git checkout master
TAG=2.6.1 ORG=<your quay username> make image/build/push
```
* An image of the operator based on master
```sh
git checkout INTLY-9953
TAG=intly9553 ORG=<your quay username> make image/build/push
```
1. Install RHMI using the master-based operator image
1. Edit the `deploy/operator.yaml` file to point to `quay.io/<your quay …
> INTLY-9953: Remove permission of dedicated admins over RHMIConfig

- test-containers-managed-api.yaml
add a new test containers config specifically for managed apis. Only contains reference to 3scale at the moment. RHSSO can be added in future.
> add test containers for managed apis

- pkg/controller/installation/installation_controller.go
- pkg/products/monitoring/reconciler.go
- pkg/resources/metrics.go
- pkg/resources/sop_url.go
- test/common/alerts_exist.go
Jira: https://issues.redhat.com/browse/INTLY-9980
The ocm sendgrid service creates the sendgrid credentials and secret as such we need to add an alert to confirm the secret is setup. The pr adds an alert to check for the presents of the `redhat-rhmi-smtp` secret in the `redhat-rhmi-operator` namespace
Additional the preflight check for smtp secret is removed
`make code/run` and `make cluster/prepare/local` have `cluster/prepare/smtp` as part of the make targets which creates dummy smtp credentials. Which we don't want, edit the make targets to remove this 
```make
.PHONY: cluster/prepare/local
cluster/prepare/local: cluster/prepare/project cluster/prepare/crd cluster/prepare/dms cluster/prepare/pagerduty cluster/prepare/delorean cluster/prepare/croaws
@oc create -f …
```
> INTLY-9980: Add alert to check for the sendgrid smtp secret is present

- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
Depending on the origin of a ThreeScale user i.e. via sso or via rhmi threescale reconcile, the username and email fields can have a different case. This results in a potentially endless loop of creating and deleting the same user, just with different case. 
More details here: https://issues.redhat.com/browse/INTLY-9971
The fix is to always create the user with lower case and to ignore case while reconciling/syncing users between keycloak and threescale
Create a user in GitHub with **uppercase** Email and Username
Setup a GitHub IDP. 
Test 2 Scenarios:
1. Creating the threescale user via RHMI Operator, Threescale to Keycloak user sync
2. Creating the threescale user by logging in via SSO (with operator shut down) 
Ensure in both cases the user is created with lowercase email and username …
> fix for 3Scale username case issue

- manifests/integreatly-3scale/0.5.2/3scale-operator.v0.5.2.clusterserviceversion.yaml
- manifests/integreatly-3scale/0.5.2/apps_v1alpha1_apimanager_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_api_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_binding_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_limit_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_mappingrule_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_metric_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_plan_crd.yaml
- manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_tenant_crd.yaml
This reverts commit 44865eff5c41c742e90e60d05cc1e12f9c987d02.
JIRA: https://issues.redhat.com/browse/INTLY-10089
During upgrade from 2.4.0 OLM si unable to find upgrade path for 3Scale operator. Installed version is 0.5.2, but lowest version it has is 0.5.4 (with no replaces field).
To verify, install RHMI 2.4.0 using budles and upgrade it to this PR.
> INTLY-10089: Revert "Remove 3scale-operator.v0.5.2 OLM manifests"

- test-cases/tests/backup-restore/j07-verify-cluster-sso-backup-and-restore.md
- test/scripts/backup-restore/j07-verify-rhsso-backup-and-restore.sh
I've used a script recently created by @sergioifg94 to also automate rhsso Postgres backup and restore.
Addresses ticket https://issues.redhat.com/browse/INTLY-9981
- BYOC cluster
- The AWS CLI configured with the credentials for the cluster
- Install RHMI with `useClusterStorage` set to false
- Wait for installation to complete
- Create the testing IdP
```
```
Perform the J07 test and verify that it's completed successfully
> Automate backup and restore for rhsso

- deploy/cro-configmaps.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/controller/installation/bootstrapReconciler.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/types.go
- pkg/controller/namespacelabel/namespacelabel_controller.go
- pkg/controller/subscription/subscription_controller.go
- pkg/resources/rhmi.go
- test/common/alerts_exist.go
- test/common/shared_functions.go
- test/common/tests.go
- test/e2e/integreatly_test.go
rename from managed-3scale to managed-api
**Install managed-api**
1. Install the managed-api operator and verify 
1.1 `export INSTALLATION_TYPE=managed-api`
3. Run the functional tests `make test/functional`
4. Verify all the tests in the managed api install type test suite ran
**Install rhmi**
1. Install the rhmi operator and verify 
1.1 `export INSTALLATION_TYPE=rhmi`
3. Run the functional tests `make test/functional`
4. Verify all the tests in the rhmi install type test suite ran
> rename from managed-3scale to managed-api

- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- pkg/resources/podHelper.go
- test-cases/tests/backup-restore/j03-verify-that-namespaces-get-recreated-by-the-integreatlyopera.md
- test/common/namespace_restoration.go
Previously there was a need to resync routes after a 3Scale restoration by running the following command in a 3Scale pod:
`bundle exec rake zync:resync:domains`
This is now built into the 3Scale product reconcile. 
- Install RHMI 
- Then, delete the redhat-rhmi-3scale namespace and ensure it restores (verify product)
- Then, delete the redhat-rhmi-3scale-operator namespace and ensure the operator and product work as expected.
> resync routes 3Scale

- scripts/disableAz.sh
Jira: https://issues.redhat.com/browse/MGDAPI-53
Need a method to disable an aws availability zone. This script creates dummy ACL(deny all traffic) on aws and points all subnets on a particular AZ to these dummy ACL. 
Script to disable and AZ and re-enable again
- Deploy a multi AZ byoc
- Change the rhmi cr to deploy `type: managed-api` and `useClusterStorage: 'false'` 
- run ` oc create -f deploy/crds/examples/rhmi.cr.yaml`
- run `make code/run`
Before running the script check the ACL for the account 
should look something like
Disable AZ
```bash
./disableAz.sh
No option set expect params true/false, the default option is disable which is true
true - disable the AvailabilityZone
false - restore the original configuration (run only after a successful …
```
> disabling AZ script

- scripts/podsAz.sh
Script for determining what pods are on what Availability Zone
- deploy a multi AZ byoc cluster
- deploy managed api
- run the script for a namespace e.g. 3scale
```bash
./podsAz.sh redhat-rhmi-3scale
Pods distribution for 'redhat-rhmi-3scale'
| Pod name | Availability Zone |
| -------- | ----------------- |
| apicast-production-1-pg9zl | eu-west-1b |
| apicast-production-1-xfvt2 | eu-west-1a |
| apicast-staging-1-fv9lq | eu-west-1a |
| apicast-staging-1-szddq | eu-west-1b |
| backend-cron-1-9cdc8 | eu-west-1a |
| backend-cron-1-c7jgr | eu-west-1b |
| backend-cron-1-deploy | eu-west-1a |
| backend-listener-1-deploy | eu-west-1b |
| backend-listener-1-p6zjr | eu-west-1b |
| backend-listener-1-xrz5w | eu-west-1a |
| backend-worker-1-9jlxp | eu-west-1b |
| backend-worker-1-deploy | …
```
> script for determining Az for pods in namespace

- test/functional/integreatly_test.go
- test/functional/multiaz_pod_distribution.go
- test/functional/tests.go
https://issues.redhat.com/browse/MGDAPI-59
* this test verifies the correct pod distribution of 3scale, User SSO and RHSSO services (by default)
* it allows to test a pod distribution in a custom namespace (by passing in an env var with the list of namespaces)
1. Clone this branch
2. Target multi-az cluster with managed-api installed (ping me if you need such cluster)
1. Run
```
go clean -testcache && MULTIAZ=true go test -v ./test/functional -run="//^F09"
```
2. Verify that the test has passed (see something like `--- PASS: TestIntegreatly/API_Managed_Multi-AZ_Tests/F09_-_Verify_correct_pod_distribution_on_Multi-AZ_cluster (3.16s)` in the log)
1. Run
```
go clean -testcache && go test -v ./test/functional -run="//^F09"
```
2. Verify that the test wasn't run because the env var `MULTIAZ` …
> test: pod distribution on Multi-AZ cluster

- pkg/products/cloudresources/reconciler.go
- test/common/cro_cr_success.go
Add condition in CRO reconciler to only reconcile the backups blob storage when
the InstallationType is `managed`.
Modify e2e test to not check for this blob storage when the installation type
is `managed-api`
1. Install the Managed API Operator
2. Check that the installation completes successfully
3. Check that only the 3scale blobstorage has been created:
```sh
$ oc get blobstorages -n redhat-rhmi-operator
NAME                                 AGE
threescale-blobstorage-managed-api   17h
```
> MGDAPI-193: Only reconcile backups blob storage on Managed type

- pkg/products/marin3r/rateLimitService.go
- pkg/products/marin3r/rateLimitService_test.go
- pkg/products/marin3r/reconciler.go
Create RateLimitServiceReconciler component to reconcile the resources for the rate limit service. It expects a secret that points to the Redis instance to be used by the service, and creates a ConfigMap, Deployment and Service to configure, run and expose this service.
Create unit tests for reconciler.
Uncomment the line with the `integreatlyv1alpha1.ProductMarin3r` reconciler to include the product in the ManagedAPI installation:
https://github.com/integr8ly/integreatly-operator/blob/master/pkg/controller/installation/types.go#L48
```sh
make code/run
```
> This step will be automated by [MGDAPI-88](https://issues.redhat.com/browse/MGDAPI-88). Meanwhile, create the in-cluster Redis instance and a Service to expose it
```sh
cat << EOF | oc create -f - -n …
```
> MGDAPI-92 Reconcile rate limit service

- test/common/3Scale_user_promotion.go
- test/common/3scale_crudl.go
- test/common/3scale_smtp.go
- test/common/alerts_mechanism.go
- test/common/deployment_types.go
- test/common/shared_functions.go
Skipping h07/h11/h03 failure message after failing to log in to 3scale. Issue reported in https://issues.redhat.com/browse/INTLY-10087
Skipping B04 due to flaky behavior on managed-api installation via addon. Issue reported in https://issues.redhat.com/browse/INTLY-10156
Editing A14 to accept equal or greater than the expected number of replicas. During managed-api installation via an addon, at some stage, system-app replicas go up to 3 for a brief moment, while the expected value is 2. Issue reported in https://issues.redhat.com/browse/INTLY-10157
Increasing timout on alerting mechanism test from 25mins to 40mins as the test requires more time on osde2e to complete
> Managed-api via addon e2e test flakes

- cmd/manager/main.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/subscription/rhmiConfigs/main_test.go
- pkg/controller/subscription/subscription_controller.go
- pkg/metrics/metrics.go
- pkg/products/grafana/reconciler.go
- pkg/products/solutionexplorer/reconciler.go
- version/version.go
PR addressing ticket https://issues.redhat.com/browse/MGDAPI-179 and other 2 issues discovered.
Currently, 
1. Managed-API CR version is the same for managed-api and managed installation
2. We are setting our `version` field as soon as one of the product reports completed ( monitoring is usually marked as completed first ) and removing the `toVersion`. 
3. Grafana Reconciler was reporting `completed` although it did not finish the installation and it did not complete, the `operatorVersion`, `version` and `host` fields in the managed-api CR were not set.
- added managed-api version field in version.go, version is now returned when version.GetVersion() is called
- added a check for `productVersionMismatch` - once all of the products report completed - the `version` is set and `toVersion` …
> MGDAPI-179 Adding Managed-API version

- pkg/products/marin3r/reconciler.go
- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/resources/constants/croConstants.go
- test/common/alerts_exist.go
- Install manged-api and verify it's as expected 
- Verify that the rate-limiting Deployment exists
`oc get deployments/ratelimit -n redhat-rhmi-marin3r`
- Verify redis installed
`oc get redis ratelimit-service-redis-managed-api`
- Check the Pod logs of rate-limiting service and confirm no error when it connects to redis.
> add redis to rate limiting service

- deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
- pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
- pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/rhmiconfig/helpers/update_status.go
- pkg/controller/rhmiconfig/helpers/update_status_test.go
- test/common/rhmi_config.go
Removes the maximum days validation for upgrade schedule
https://issues.redhat.com/browse/INTLY-10150
1. Install the operator from this index `quay.io/jjaferson/integreatly-index:2.8.0`
2. Change the catalogsource to point to `quay.io/jjaferson/integreatly-index:2.9.0` 
3. Modify the schedule field in the RHMIConfig CR to true 
```
spec:
upgrade:
schedule: true
```
4. Change the notBeforeDays field to a number grater than 14 
```
spec:
upgrade:
notBeforeDays: 30
```
5. Verify if the upgrade is scheduled for a date equivalent to the number of days defined in the `notBeforeDays`
```
status:
upgrade: {}
```
6. Change the schedule field in the RHMIConfig CR to false
```
spec:
upgrade:
schedule: false
```
7. Check if the scheduled date for the upgrade is removed from the status clock
``` …
```
> Removes validation for maximum days for upgrade schedule

- test-cases/tests/backup-restore/j07-verify-cluster-sso-backup-and-restore.md
- test-cases/tests/backup-restore/j08-verify-user-sso-backup-and-restore.md
- test/scripts/backup-restore/j07-verify-rhsso-backup-and-restore.sh
- test/scripts/backup-restore/j08-verify-user-sso-backup-and-restore.sh
- test/scripts/backup-restore/postgres.sh
* SOP update to use `throwaway-postgres` container instead
* Script update to pull credentials and region from cluster 
* Small script bug fixes when dumping restored db and doing diff between db dumps
Successful output log attached in Jira:
* https://issues.redhat.com/browse/MGDAPI-268
* https://issues.redhat.com/browse/MGDAPI-290
> MGDAPI-268 - J08 sop script update

- deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
- deploy/crds/integreatly.org_rhmis_crd.yaml
- go.mod
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/controller/installation/installation_controller.go
- pkg/products/marin3r/reconciler.go
- version/version.go
Updated logic around updating version number in RHMI CR.
Cleaned  up logic at end of main reconcile as it was getting confusing to read.
Testing I performed locally:
- installing: toVersion: 0.1.0, version: ""
- Installed: toVersion: "", Version: 0.1.0
- Slow Upgrade pending: toVersion: 0.2.0, Version: 0.1.0
- Slow Upgrade complete: toVersion: "", Version: 0.2.0
- Fast Upgrade pending: --- too fast ---
- Fast Upgrade complete: toVersion: "", Version: 0.3.0
> set version based on install type

- scripts/alerts-during-perf-testing.sh
Script to determine what alerts fire during a performance test
- deploy managed api
- log into oc on the command line
- clone this branch
- run the script
```bash
./scripts/alerts-during-perf-testing.sh
```
- scale down the user-sso operator
- scale down the user-sso statefulSet pods
- wait for the alerts to fire
- you should get 2 csv files for firing and pending alerts
with the alert that is triggered and a time stamp e.g.
```csv
"DeadMansSwitch","firing","2020-10-12T08:06:05.755551085Z"
```
- scale backup the user-sso statfulSet pods and the user-sso operator
- once alerts stop firing confirm that the two file still contain the alerts data gathered during the downtime.
- you can test the Passing in an arg with the script
it does accept 
```
- 3scale
- user-sso
- rhsso
- marin3r
``` …
> MGDAPI-172: script for firing/pending alerts

- Makefile
- test/common/shared_functions.go
Add a new Makefile target to run RHOAM e2e tests.
- Create a fresh OSD cluster
- Wait for certs to be valid
- Login to it with oc
- run `make test/e2e/rhoam SELF_SIGNED_CERTS=false`
> add rhoam e2e makefile target

- Makefile
- deploy/sku-limits-configmap.yaml
- pkg/controller/installation/bootstrapReconciler.go
- pkg/products/marin3r/config/config.go
- pkg/products/marin3r/config/config_test.go
- pkg/products/marin3r/rateLimitService.go
- pkg/products/marin3r/rateLimitService_test.go
- pkg/products/marin3r/reconciler.go
- test/e2e/integreatly_test.go
Add package `marin3r/config` with the functionality to retrieve the rate limit configuration from a ConfigMap that's expected to be already defined with the rate limits for multiple SKUs
Add make target to create this ConfigMap for development purposes. This ConfigMap is expected to be reconciled by hive from managed-tenants
1. Begin an installation of Managed API type from this PR
3. Create the ConfigMap
```sh
make cluster/prepare/ratelimits
```
4. Verify that the installation progresses and completes successfully
5. Open a terminal in the Rate Limit pod in the marin3r namespace, and check that the config matches the ConfigMap
```sh
cat /srv/runtime_data/current/config
```
6. Modify the SKU Rate Limits ConfigMap to a different value
7. Wait a minute and repeat step 4 to verify that the …
> MGDAPI-242: Support rate limit configuration via SKU ConfigMap

- manifests/integreatly-rhsso/10.0.0/keycloak-operator.v10.0.0.clusterserviceversion.yaml
The following change is to update the image of RHSSO from 7.4-1 to the latest which is 7.4-3 [Jira](https://issues.redhat.com/browse/INTLY-10126)
Image upgrade
1. install RHMI from this branch
2. Verify the env var is showing the rhsso operator
2. Verify the keycloak operator deployment in the rhsso-operator namespace is showing this new image version from 7.4-1 to 7.4-3
3. check the container associated with the 2 keycloak pods in the rhsso namespace is showing the new version to 
4. Run through the sso walkthroughs as well
> Updating RHSSO image to latest patch

- Makefile
- cmd/manager/main.go
- deploy/role_binding.yaml
- pkg/resources/prometheusRules.go
https://issues.redhat.com/browse/MGDAPI-326
On a clean cluster - please uninstall any previous installation and delete any integreatly-operator namespaces.
In the Makefile ->
Update `NAMESPACE_PREFIX=redhat-mgdapi-`
Update `export INSTALLATION_TYPE   ?= managed-api`
Update `export INSTALLATION_PREFIX ?= redhat-managed-api`
Run `make cluster/prepare/local`
Run `yq w -i deploy/operator.yaml 'spec.template.spec.containers[0].image' quay.io/laurafitzgerald/integreatly-operator:v2.8.6`
Run `oc apply -f deploy/operator.yaml -n redhat-mgdapi-operator`
Verify that the errors faced in [this gist ](https://gist.github.com/psturc/86df94fd4fac09c3d32a3e94e3c7d806)are no longer present.
Please go to prometheus and ensure no alerts are firing. There's a change include which fixes an issue with alert …
> Fix errors around permissions on objects due to operator-sdk version bump metrics change

- .gitignore
- Makefile
- README.md
- deploy/olm-catalog/managed-api-service/0.1.0/integreatly.org_rhmiconfigs_crd.yaml
- deploy/olm-catalog/managed-api-service/0.1.0/integreatly.org_rhmis_crd.yaml
- deploy/olm-catalog/managed-api-service/0.1.0/managed-api-service.v0.1.0.clusterserviceversion.yaml
- deploy/olm-catalog/managed-api-service/managed-api-service.package.yaml
- scripts/README.md
- scripts/bundle-rhmi-operators.sh
- scripts/prepare-release.sh
The prepare release script now accepts more arguments with all the user to sepicfiy the `olm-catalog` resource be released. 
Also is the ability to set the quay.io org that will point to the catalogue images. This is useful when doing upgrade testing of bundles. Short readme added with a description of how to use the script and the arguments that can be set, plus the current defaults.
**JIRA** https://issues.redhat.com/browse/MGDAPI-31
**Requires https://github.com/integr8ly/delorean/pull/148 to be merged**
> Mgdapi 31 Updating the prepeare release script 

- pkg/products/grafana/prometheusRules.go
- pkg/products/grafana/reconciler.go
- pkg/products/marin3r/prometheusRules.go
- pkg/products/marin3r/reconciler.go
- test/common/alerts_exist.go
- test/common/alerts_firing.go
This PR implements identified alerts for rate-limiting service in https://issues.redhat.com/browse/MGDAPI-106, addresses ticket https://issues.redhat.com/browse/MGDAPI-107.
With the implementation of the rate-limiting service, there is a set of alerts required that will monitor the state of each individual component and trigger in case of component failure.
- Marin3rDiscoveryServiceEndpointDown
- Marin3rPromstatsdExporterServiceEndpointDown
- Marin3rRateLimitServiceEndpointDown
- Marin3rOperatorRhmiRegistryCsServiceEndpointDown
- Marin3rOperatorPod
- Marin3rDiscoveryServicePod
- Marin3rPromstatsdExporterPod
- Marin3rRateLimitPod
- Marin3rEnvoyApicastStagingContainerDown
- Marin3rEnvoyApicastProductionContainerDown
- GrafanaOperatorRhmiRegistryCsServiceEndpointDown
- …
> Rate-limiting alerts

- pkg/config/marin3r.go
- pkg/controller/installation/bootstrapReconciler.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/watch.go
- pkg/products/marin3r/apiUsagePrometheusRules.go
- pkg/products/marin3r/config/config.go
- pkg/products/marin3r/config/config_test.go
- pkg/products/marin3r/reconciler.go
- pkg/products/marin3r/reconciler_test.go
- pkg/resources/prometheusRules.go
- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
- test/common/alerts_exist.go
Modify AlertReconciler instantiation for the marin3r product to create the AlertConfiguration items from the marin3rconfig.AlertConfig elements that are obtained from a ConfigMap.
Modify bootstrap phase to create this ConfigMap with default values, as well as owner annotations to trigger a reconciliation when the ConfigMap is updated.
1. Begin an installation from this PR
2. Once the bootstrap phase is complete, check that the alerts ConfigMap has been created
```sh
oc get cm rate-limit-alerts -n redhat-rhmi-operator
```
3. Wait for the installation to complete
4. Check that the alerts have been reconciled
```sh
oc get prometheusrules -n redhat-rhmi-marin3r
NAME                     AGE
api-usage-alert-level1   123m
api-usage-alert-level2   123m
api-usage-alert-level3   123m
```
5. Modify …
> MGDAPI-378: Support rate limit alerts configuration via ConfigMap

- deploy/redhat-managed-api/role_binding.yaml
Before switching to a new operator namespace prefix we'll need to address a number of tasks as part of RHOAM Sprint 3.
For now, this PR reverts our rolebinding changes to work with `redhat-rhmi-operator`
> Updating managed-api rolebinding to use redhat-rhmi-operator

- test/common/rhmi_config.go
- test/functional/aws_shared_functions.go
- test/functional/aws_standalone_vpc.go
- test/functional/multiaz_pod_distribution.go
Fix (workaround) for a flaky tests A18 and A25
https://issues.redhat.com/browse/MGDAPI-395
https://issues.redhat.com/browse/MGDAPI-394
This test sometimes fails on an error:
```
TestIntegreatly/Integreatly_Happy_Path_Tests/A18_-_Verify_RHMI_Config_CRs_Successful: rhmi_config.go:310: Expected error to be nil. Got Operation cannot be fulfilled on rhmiconfigs.integreatly.org "test-rhmi-config": the object has been modified; please apply your changes to the latest version and try again
```
that happens between the mutations of RHMIconfig CR
I've put the `verifyRHMIConfigValidation` function calls inside `wait.Poll` method to keep retrying the mutation until it finally passed without an error.
This test was failing on multi-az cluster due to hardcoded number of route tables a cluster VPC …
> fix: tests: A18, A25

- pkg/products/marin3r/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/resources/ratelimit/envoyconfig.go
This PR addresses a bug where during the uninstallation of managed-api there was a race condition between 3scale and the marin3r reconciler, leading to uninstallation being stuck in 3scale.
Because the bug has a chance to trigger there is no way of recreating it every time. Best way to verify it would be to install managed-api, uninstall it and expect it to be removed from the cluster.
- Cluster provisioned
- Logged in to the cluster
- run `export INSTALLATION_TYPE=managed-api`
- run `make code/run`
- wait for the installation to complete
- once completed remove managed-api CR from `redhat-rhmi-operator` namespace
- expect uninstallation to be completed
> MGDAPI-404 Deleting enabled ns CRs

- pkg/products/marin3r/rateLimitService.go
- pkg/resources/topologyConstraints.go
- test/common/deployment_types.go
> Link to Jira: https://issues.redhat.com/browse/MGDAPI-240
In order to enable Multi-AZ support for the rate limit service:
* Set the number of replicas to 3
* Set the Deployment topology spread constraints for multi AZ
1. Install MGDAPI from this PR
2. Once the installation completes, verify that the replicas and topologySpreadConstraints field have been set
```sh
oc get deployments ratelimit -n redhat-rhmi-marin3r -o json | jq -r '{ "replicas": .spec.replicas, "topologySpreadConstraints": .spec.template.spec.topologySpreadConstraints }'    
```
The output should look like:
```json
{
"replicas": 3,
"topologyConstraints": [
{
"labelSelector": {
"matchLabels": {
"app": "ratelimit"
}
},
"maxSkew": 1,
"topologyKey": "topology.kubernetes.io/zone",
"whenUnsatisfiable": "ScheduleAnyway"
}
]
} …
```
> MGDAPI-240: Set topology spread constraints to rate limit service

- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
JIRAs: 
https://issues.redhat.com/browse/MGDAPI-497
https://issues.redhat.com/browse/MGDAPI-500
After this change, alert manager receivers config looks like this:
```
receivers:
- name: default
email_configs:
- send_resolved: true
to: cssre-noreply@redhat-rhmi.com
- name: critical
pagerduty_configs:
- service_key: test
email_configs:
- send_resolved: true
to: cssre-noreply@redhat-rhmi.com
- name: deadmansswitch
webhook_configs:
- url: https://dms.example.com
- name: BUandCustomer
email_configs:
- send_resolved: True
to: 'bu-noreply@redhat-rhmi.com'
- name: SRECustomerBU
email_configs:
- send_resolved: True
to: 'cssre-noreply@redhat-rhmi.com, bu-noreply@redhat-rhmi.com'
```
Notice that it now has correct name for the "emails_config" field and it contains BU email address.
For verification, …
> MGDAPI-497, MGDAPI-500 - fix alert manager recievers

- pkg/products/rhssocommon/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/resources/podPriority.go
This fixes a hard coded pod priority class name value. 
to validate :
1. install this branch as a `managed-api` type
2. Confirm podPriority class exists with the name `rhoam-pod-priority`
3. Confirm the RHSSO/UserSSO keycloak stateful sets have the priority class name set
4. Confirm the threescale deployment configs have the priority class name set
> Fix podPriorityClassName variable

- pkg/products/grafana/reconciler.go
- pkg/products/marin3r/apiUsagePrometheusRules.go
- pkg/products/marin3r/reconciler.go
Expose the Grafana URL in the alert notifications for the API usage
https://issues.redhat.com/browse/MGDAPI-228
1) Install the operator locally from this branch
2) Get the Prometheus Rules CRs
```oc get prometheusrules -n redhat-rhmi-marin3r``` 
3)  Verify if the `grafanaConsole` is present in the annotation block of the Prometheus Rules CRs
```oc get prometheusrules [prometheus_rule_cr_name]  -o json -n redhat-rhmi-marin3r | jq .spec.groups[0].rules[0].annotations[0].grafanaConsole```
> Expose Grafana URL in API usage notifications

- pkg/products/grafana/customerDashboard.go
- pkg/products/grafana/reconciler.go
- test/common/dashboards_exist.go
- test/common/grafana_routes.go
- test/common/tests.go
https://issues.redhat.com/browse/MGDAPI-91
Adding customer grafana dashboard
Adding tests
E06 - verify customer dashboard exists
E07 - verify customer route is accessible
Run the operator against an openshift cluster
Create an application in 3scale using the following steps
Navigate to `https://3scale-admin.[your_admin_domain].devshift.org/p/admin/onboarding/wizard/intro` and follow the steps outlined in the wizard to create a 3Scale service. You can get your admin domain from Routes under `redhat-rhmi-3scale` namespace, use the admin user credentials from the `system-seed` secret in the 3scale namespace
Navigate to `https://3scale-admin.[your_admin_domain].devshift.org/apiconfig/services/2/integration`
Copy curl command from API Cast staging.
Simulate load on the cluster using some …
> Adding customer grafana dashboard

- cmd/manager/main.go
- deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
- deploy/crds/integreatly.org_rhmis_crd.yaml
- pkg/metrics/metrics.go
Add RHOAM version metric
Jira:
* https://issues.redhat.com/browse/MGDAPI-495
* Install using prebuilt image from this branch
```
cat << EOF | oc create -f - -n redhat-rhmi-operator                              
apiVersion: apps/v1
kind: Deployment
metadata:
name: rhmi-operator
spec:
replicas: 1
selector:
matchLabels:
name: rhmi-operator
template:
metadata:
labels:
name: rhmi-operator
spec:
serviceAccountName: rhmi-operator
volumes:
- name: webhook-certs
emptyDir: {}
containers:
- name: rhmi-operator
image:  quay.io/kevfan/integreatly-operator:MGAPI-495
ports:
- containerPort: 8090
command:
- rhmi-operator
imagePullPolicy: Always
resources:
limits:
memory: 1536Mi
cpu: 150m
requests:
memory: 64Mi
cpu: 100m
volumeMounts:
- name: webhook-certs
mountPath: …
```
> MGDAPI-495 - Add rhoam version metric

- scripts/capture_resource_metrics.sh
JIRA: https://issues.redhat.com/browse/MGDAPI-368
Monitoring stack metrics should be captured separately based on suggestion from Craig.
[The spreadsheet](https://docs.google.com/spreadsheets/d/1v_bZIk8B_thZi93hGBNiOOnbSix0gmpwy3LV_s4WFPw/edit#gid=231944674) has been updated to reflect this change.
Current script output:
```
$ ./scripts/capture_resource_metrics.sh 
60
36
370.32443618774414
278.5992774963379
7209.878211805554
116.46827256944448
1981.523480902778
2518.197352430556
2486.900868055555
14831.480555555558
0.45457553151360897
0.022072775865353913
0.021481257596153224
5.356680045147766
0.06664203723568832
6.000041681219844
7574.71875
116.45703125
1981.671875
2525.53515625
2575.02734375
15181.6328125
0.4640411898223442
0.02274905165420596
0.021607092761040114
5.913627247923801 …
```
> MGDAPI-368 - capture monitoring stack metrics

- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
Previously 3scale phase can report complete before being truly ready. This is due to when the deployment configs changes (from adding topologySpreadConstraints, podPriority etc), there is no check that the rollout has completed before returing complete. 
This causes the products stage to become `PhaseComplete`, then back to `InProgress` before returning to `PhaseComplete` again.
Due to this, tests can run early, where 3scale is not fully ready, causing some flaky failure in tests such as product version, deployment replicas etc
* OSDE2E - https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/osde2e-stage-aws-addon-integreatly-operator/1321421556915638272
To prevent this, we should check that the deployment config rollout has completed before returning phase complete in the 3scale …
> MGDAPI-521 - Ensure 3scale deployment config rollout is ready before returning complete

- pkg/products/marin3r/reconciler.go
Marin3r namespaces are not removed during uninstall
This is due to checking for the wrong phase returned by `DeleteEnvoyConfigsInNamespaces` function
* Install managed-api
```
```
* Once installation completed, trigger uninstall by deleting RHMI CR
* Verify `redhat-rhmi-marin3r-operator`  and `redhat-rhmi-marin3r` are deleted during uninstall
> Fix marin3r namespace not removed on uninstall

- pkg/controller/installation/bootstrapReconciler.go
- pkg/products/marin3r/apiUsagePrometheusRules.go
- pkg/products/marin3r/reconciler_test.go
- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
- test-cases/tests/alerts/c18-validate-api-usage-alerts.md
- test/common/alerts_exist.go
Renaming the following API usage alerts:
```
Level1ThreeScaleApiUsageThresholdExceeded -> RHOAMApiUsageLevel1ThresholdExceeded
Level2ThreeScaleApiUsageThresholdExceeded -> RHOAMApiUsageLevel2ThresholdExceeded
Level3ThreeScaleApiUsageThresholdExceeded -> RHOAMApiUsageLevel3ThresholdExceeded
```
This ensures consistency with what we've done with RHMI in the past
1. Install RHOAM from this branch on an OSD cluster
2. Login to the middleware-monitoring prometheus instance
3. Verify that the new alert names are in place and that the old ones are not listed
> Renaming API usage alerts to reference RHOAM

- pkg/products/grafana/customerDashboard.go
- test/common/dashboards_exist.go
https://issues.redhat.com/browse/MGDAPI-91
Updating text - SKU -> Requests
Adding two additional panels which are percentages of rejected/total per last 24 hours and last 1 minute.
Making timescale of last 1 minute and last 24 hours clearer
Run the operator against an openshift cluster with the installType set to `managed-api`
Create an application in 3scale using the following steps
Navigate to `https://3scale-admin.[your_admin_domain].devshift.org/p/admin/onboarding/wizard/intro` and follow the steps outlined in the wizard to create a 3Scale service. You can get your admin domain from Routes under `redhat-rhmi-3scale` namespace, use the admin user credentials from the `system-seed` secret in the 3scale namespace
Navigate to `https://3scale-admin.[your_admin_domain].devshift.org/apiconfig …
> updates to grafana dashboard based on feedback

- pkg/controller/installation/installation_controller.go
- pkg/products/marin3r/rateLimitService.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/resources/objectQueries.go
- pkg/resources/podAntiAffinity.go
- pkg/resources/podPriority.go
- pkg/resources/podTemplate.go
- pkg/resources/topologyConstraints.go
- pkg/resources/topologyConstraints_test.go
Add logic to include anti affinity rules in the products pod templates (SSO, User SSO, Rate limit and 3scale)
Refactor logic that updates pod template of product components by unifying into a `UpdatePodTemplateIfExists` function that receives composable mutations.
Add anti affinity rules to 3scale APIManager CR to delegate this logic in the 3scale operator
The behaviour of the operator in regards to the anti affinity rules is different depending on whether the `FORCE_ZONE_DISTRIBUTIO` env var is set. Install the operator and run it with both combinations
1. Install RHOAM from this PR
1. Preferred
> By default the pod affinity rule will be set to preferred
```sh
```
2. Required
```sh
FORCE_ZONE_DISTRIBUTION=true INSTALLATION_TYPE=managed-api make …
```
> MGDAPI-532: Include anti affinity rules for Multi-AZ support

- scripts/disableAz.sh
- scripts/podsAz.sh
I optimized scripts/podsAz.sh a bit, now it does only 2 API requests.
This made feasible support for all namespaces.
Also small improvement to scripts/disableAz.sh - it will print timestamp(UTC) when it finishes disabling an AZ.
> Improvements to scripts, mainly podsAz.sh

- pkg/products/marin3r/rateLimitService.go
- pkg/products/marin3r/rateLimitService_test.go
- pkg/products/marin3r/reconciler.go
This PR addresses ticket https://issues.redhat.com/browse/MGDAPI-551. 
#Verification
Install from this branch and verify that the pod priority class name of `rhoam-pod-priority` is set in `rate-limit` deployment under marin3r namespace.
> Add rate limit pod priority

- test/common/dashboards_exist.go
Addresses https://issues.redhat.com/browse/MGDAPI-528, fixes the E09 e2e test.
Currently, customer monitoring grafana pod does not support "curl" command. I am re-using monitoring grafana pod to curl customer monitoring grafana in order to get customer monitoring dashboards. Also, as the rate limit dashboard is within a top-level dashboard, the top-level dashboard must be skipped. 
PR e2e for RHMI/verified manually
rhoam e2e needs manual verification
> E09 e2e flaky test fix

- cmd/manager/main.go
- deploy/role.yaml
- pkg/addon/addon.go
- pkg/addon/operator_run.go
- pkg/addon/operator_run_test.go
- pkg/addon/uninstall.go
- pkg/controller/installation/installation_controller.go
Add logic to uninstall the operator (delete the CSV and Subscription) when
the uninstallation has finished.
Include utility logic to interact with the addon (infer if the operator is run via an addon installation, in-cluster, or local)
In order to verify this PR, install the operator with the add-on, replace the image in the CSV from an image based on this PR, delete the installation and verify that the operator is uninsalled when the CR is deleted
1. ### Install add-on
1. On a fresh cluster, install the Managed API Service add-on. Fill the parameters with dummy data (e.g. `10.1.0.0/23` for the CIDR)
> The installation via the add-on is curently broken. In order to progress it for the sake of this PR take the following steps:
>  1. Replace the operator image in the CSV for …
> MGDAPI-543: Automatic uninstall operator in OLM

- pkg/products/threescale/reconciler.go
The finalizer for 3scale attempts to delete the EnvoyConfig CR without checking the installation type. If the installation type is not Managed API, it will try to delete a CR that has no CRD so will fail with a "no match for kind" error. Wrap the deletion in an `if` block to do it only in Managed API installations
> Attempt to clear EnvoyConfig only in ManagedApi install

- cmd/manager/main.go
- pkg/controller/installation/prometheusRules.go
- pkg/metrics/metrics.go
- test/common/alerts_exist.go
Addresses https://issues.redhat.com/browse/MGDAPI-564.
Currently, when RHOAM is installed and/or running the following alerts could trigger:
```
RHMIInstallationControllerIsNotReconciling
RHMIInstallationControllerStoppedReconciling
```
and the following alerts triggers and don't go away after installation completes:
```
RHMIOperatorInstallDelayed
RHMIUpgradeExpectedDurationExceeded
```
The reason for it is because the alerts expect rhmi_status and rhmi_version present, while we are having rhoam installed. 
Both `RHMIOperatorInstallDelayed` and `RHOAMUpgradeExpectedDurationExceeded` fired during installation and remained in firing state after installation reports completed. The reason for it is because we were checking RHMI installation stage status instead of RHOAM.
Added metrics for …
> MGDAPI-564 RHOAM/RHMI Installation/upgrade/reconciler alerts

- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssocommon/reconciler.go
Reconcile OpenShift IDP client secret. This is required to cover the accidental changing of this secret through
the Keycloak GUI. This scenario happened for a customer in production. See below.
JIRA: [INTLY-10308](https://issues.redhat.com/browse/INTLY-10308)
Production Issue: [OHSS-2019](https://issues.redhat.com/browse/OHSS-2019)
- Install RHMI and verify 3Scale SSO works.
- Modify the Openshift-v4 IDP Client Secret. In rhsso , browse to Identity Providers in the OpenShift Realm. Select openshift-v4 and modify the client secret.
- Verify Login to 3Scale SSO failing
- Wait for a RHSSO Reconcile to run
- Verify Login to 3Scale SSO working
> Sync OpenShift-IDP client secret

- pkg/products/grafana/customerDashboard.go
- pkg/products/marin3r/apiUsagePrometheusRules.go
- pkg/products/marin3r/softLimitPrometheusRules.go
> Link to Jira: https://issues.redhat.com/browse/MGDAPI-565
The metrics exposed by the rate limiting service include in their labels information about the statsd Pod such as it's host and Pod name. When the statsd Pod is restarted, a different vector is exposed with the counter restarted to 0, which affects the Grafana dashboard as well as the alerts that rely on these metrics.
Wrap the `increase()` function calls to `sum()`. When the metric is not exposed anymore the value of `increase()` will remain and, by using `sum()`, the values of the different vectors will be added up.
This PR modifies the promql queries for the Grafana dashboard, the API Usage alerts, and the soft limit alerts. In order to verify this, verify that the alerts still work and the Grafana dashboard works after …
> MGDAPI-565: Modify API Usage queries for statsd pod restart support

- pkg/products/marin3r/rateLimitService.go
- pkg/products/marin3r/reconciler.go
- pkg/products/threescale/reconciler.go
Moves the rate limit images registry to Quay
- quay.io/integreatly/ratelimit:v1.4.0
- quay.io/integreatly/envoy:v1.14.1
- quay.io/integreatly/statsd-exporter:v0.18.0
Jira: https://issues.redhat.com/browse/MGDAPI-580
1) Install the operator from this branch 
2) Verify if the rate limit image comes from quay
```bash
$ oc get deployment ratelimit -n redhat-rhoam-marin3r -o json | jq  ".spec.template.spec.containers[0] .image"
> "quay.io/integreatly/ratelimit:v1.4.0"
```
3) Verify if the prom statsd exporter image comes from quay
```bash
oc get deployment prom-statsd-exporter -n redhat-rhoam-marin3r -o json | jq  ".spec.template.spec.containers[0] .image"
> "quay.io/integreatly/statsd-exporter:v0.18.0"
```
4) Verify if the envoy image for the sidecar containers come from quay
```bash
oc get …
```
> Moves the rate limit images registry to Quay

- pkg/products/threescale/prometheusRules.go
- test/common/alerts_exist.go
Add an alert to detect when 3scale apicast worker restarts
Jira: https://issues.redhat.com/browse/MGDAPI-322
PS.: this PR is in WIP because the existing SOP to troubleshoot the alert but it needs to be improved with more details on how to fix the issue in case the alert start firing and be approved by SRE. 
1) Install the operator from this branch
2) Check if the alert is created in prometheus
3) Go to one of the production APICast pod and run the command below to restart nginx worker
```for k in /proc/[0-9]*; do grep -i "^nginx: worker process" $k/cmdline 2>&1 >/dev/null; if [[ $? == 0 ]]; then echo ${k##*/}; fi; done | xargs kill -9```
4) Verify if the alert is in a pending state
> Add alert for 3scale ApiCast worker process restart

- pkg/products/grafana/customerDashboard.go
- pkg/products/grafana/reconciler.go
- pkg/products/marin3r/apiUsagePrometheusRules.go
- pkg/products/marin3r/config/config.go
- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
https://issues.redhat.com/browse/MGDAPI-585
Addressing Feedback from https://github.com/integr8ly/integreatly-operator/pull/1368
Updating Grafana Dashboard to dynamically create variables and graph queries based on array of soft limits provided in the operator namespace.
1. Verify that the soft limits are loaded as expected from the default copy of the `sku-limits-managed-api-service` config map.
1.1 Install RHOAM
`INSTALLATION_TYPE=managed-api make cluster/prepare/local `
`INSTALLATION_TYPE=managed-api make code/run/service_account`
1.2 Verify that the dashboard is created
Wait for the grafana stage to complete
Navigate to `http://<grafana-route>/d/66ab72e0d012aacf34f907be9d81cd9e/rate-limiting`
1.3 Verify that the Dashboard Variables have been dynamically loaded
Log in as admin using …
> Mgdapi 585

- scripts/testing-idp-template.yml
@philbrookes  cc
Removal of the id field from client spec is a workaround for keycloak-operator behavior.
Currently, if id is set, then the set secret is ignored.
> Fix testing IDP issues with new keycloa-operator version

- test-cases/tests/alerts/c16-verify-ocm-sendgrid-service-alerts.md
This test case is no longer tight to RHOAM or RHMI releases
> fix: remove c16 from rhoam

- pkg/products/monitoring/prometheusRules.go
- test/functional/multiaz_pod_distribution.go
Update alert and e2e test to meet the requirement for minimum pod distribution. Minimum pod distribution states that a replica count > 1 on clusters with > 1 zone should not all be on the same zone. 
[JIRA](https://issues.redhat.com/browse/MGDAPI-596)
Install RHOAM on a multi-az cluster.
**Verify method 1:**
When installed check the initial pod distribution. All 3 methods of checking should align: 
1. - Run ./scripts/podsAz.sh and manually scan the various pods
2. - Run multiaz_pod_distribution.go
3. - Check the prom alert/expression MultiAZPodDistribution 
If the pods are not distributed to meet the minimum requirements, verify that OCM is firing warning alerts 'MultiAZPodDistribution'
Scale the offending pods to zero and let the operator bring them back up
Rerun the 3 checks above. …
> Update pod distribution e2e test and alert

- pkg/products/monitoring/dashboards/criticalSLOAlerts.go
- pkg/products/monitoring/dashboardsHelper.go
- test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
`nsPrefix` is not set in dashboard json when using as a package variable resolving to an empty string and therefore using the wrong namespace in the alerts counts for the product panels 
Jira
* https://issues.redhat.com/browse/MGDAPI-695
* https://issues.redhat.com/browse/MGDAPI-658
```
export INSTALLATION_TYPE=managed-api 
make code/run
```
* Once installation completes, visit middleware grafana - **Critical SLO** Dashboard
* Verify namespace prefix is used by the product panels
* Run through E04B test case from this branch, noting the script update for scaling down user sso pods
* Verify alert count is expected
* **NOTE:** Total alert count include marin3r alerts but there is a missing panel which is why the sum total of …
> MGDAPI-695 - fix nsPrefix not used in slo dashboards affecting counts

- pkg/products/threescale/reconciler.go
Adds productised envoy image 
https://issues.redhat.com/browse/MGDAPI-701
1) Install the operator from this branch 
2) Verify if the envoy image for the sidecar containers is the productised one
```bash
oc get pods -l deploymentConfig=apicast-production -n redhat-rhoam-3scale -o json | jq  ".items[] .spec.containers[1] .image"
> "registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.0"
```
3) Create an API in 3scale and verify if the requests are being limited
```bash
// verify the number of requests allowed
oc get configmap sku-limits-managed-api-service -n redhat-rhoam-operator -o json | jq ".data"
```
> Adds a productised envoy image

- pkg/products/grafana/customerDashboard.go
- pkg/products/grafana/reconciler.go
- pkg/products/marin3r/apiUsagePrometheusRules.go
An issue was found with the OverLimit alert and supporting Grafana queries where we don't need to compensate for the prometheus signalling issue when dealing with higher request counters (counts are not being doubled).
The purpose of this PR is to update the queries to not half the reported count
1. Configure a cluster to support 20M requests per day (13860 requests per minute)
2. Run load tests against the cluster and verify that Grafana dashboard counters are accurate and that the OverLimit alert triggers when exceeding the upper limit
> Updating OverLimit and Grafana queries

- pkg/products/cloudresources/reconciler.go
Uninstallation is stuck due to remaining snapshots. Remove postgres and redis snapshots to allow for rhmi uninstall to complete.
Install rhoam on a CSS cluster.
Add 2 postgres snapshots and 2 redis snapshots
Delete the rhoam cr `oc delete rhmi rhoam`
Confirm postgres and redis snapshots are removed from the `redhat-rhoam-operator` namespace
Confirm rhoam cr deletion completes
[3Scale backup ](https://github.com/RHCloudServices/integreatly-help/blob/master/sops/2.x/backup_restore/3scale_backup.md)
[RHSSO backup](https://github.com/RHCloudServices/integreatly-help/blob/master/sops/2.x/backup_restore/rhsso_backup.md)
> remove snapshots on uninstall

- pkg/products/grafana/customerDashboard.go
The result is NaN when the dividing calcuation is 0/0.
This happens in the case where there has been 0 requests
in the last minute and as such 0 rejected requests.
Here's a screen capture of the change being tested and working:https://drive.google.com/file/d/1fnIgdo6Aq-rhOXEly78F9o3qsM0skX7r/view?usp=sharing
And a screen capture of the code change deployed to a cluster via the operator and the changes below present and in working order: https://drive.google.com/file/d/1eNKzXF9hQB-hRT6FDpXTKynlHQhMxmi8/view?usp=sharing
> update percentage query to produce 0 when the result is NaN.

- test/common/3Scale_user_promotion.go
- test/common/3scale_crudl.go
- test/common/3scale_smtp.go
- test/common/authdelay_first_broker_login.go
- test/common/testing_idp.go
Fixes IDP issues causing flakiness in e2e tests
https://issues.redhat.com/browse/MGDAPI-557
https://issues.redhat.com/browse/MGDAPI-558
1) Install the operator with the install type for rhoam
```bash
INSTALLATION_TYPE=managed-api make cluster/prepare/local && INSTALLATION_TYPE=managed-api make code/run
```
2) Run the functional e2e tests
```bash
INSTALLATION_TYPE=managed-api make test/functional
```
3) Verify if all the IDP based e2e tests `IDP_BASED_TESTS` pass
> Fix e2e tests around IDP

- pkg/products/threescale/prometheusRules.go
> Link to Jira: https://issues.redhat.com/browse/MGDAPI-810
Modify the alert reconciliation logic to use the `GetReplicasConfig` function to obtain the actual expected number of replicas of zync, and format the query with it
In order to verify this PR, check that the alert query is reconciled based on the `in_prow` annotation of the RHMI CR
1. Install the operator from this PR
```sh
git fetch upstream pull/1469/head
```
2. When the RHMI CR is created, add the `in_prow` annotation:
```yaml
annotations:
in_prow: 'true'
```
3. The operator will set the 3scale replicas to 1. Wait for the installation to complete, and verify that the query checks for 1 replica
```sh
oc get prometheusrules …
```
> MGDAPI-810: Dynamically set expected pod count for zync in alert

- pkg/products/grafana/reconciler.go
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- pkg/resources/constants/grafanaConstants.go
One of the requirements for RHOAM GA is that all images used in the product should be hosted in quay, so this PR updates the granafa image from dockerhub to quay
https://issues.redhat.com/browse/MGDAPI-809
1) install the operator from this branch
2) check if the granafa image used in AMO and `redhat-rhoam-customer-monitoring-operator` namespaces use the image from quay `quay.io/integreatly/grafana:7.1.1`
> Updates grafana image from dockerhub to quay

- Dockerfile.functional
- test/common/dashboards_data.go
- test/common/dashboards_exist.go
e02 and e03 have become unstable tests, apparently caused by this PR: https://github.com/integr8ly/integreatly-operator/pull/1470 marking them as flaky until we can address https://issues.redhat.com/browse/MGDAPI-815
Also slipping in a small change to the functional Dockerfile that was noticed in the rc3 release.
> E02 and e03 flaky tests

- test/common/3Scale_user_promotion.go
- test/common/3scale_crudl.go
- test/common/3scale_smtp.go
- test/common/codeready_crudl.go
- test/common/fuse_crudl.go
- test/common/grafana_routes.go
- test/common/network_policy_access_ns_to_svc.go
- test/common/testing_idp.go
- test/common/user_dedicated_admin_permissions.go
- test/common/user_rhmi_developer_permissions.go
- test/functional/integreatly_test.go
* scale down "system-app" and "system-sidekiq" in order to load new smtp configuration instead of redeploying them
* use `check3ScaleReplicasAreReady` shared function instead of using the local `checkThreeScaleReplicasAreReady` func that doesn't work in OSD
* [get installtype only once when running functional test suite](https://github.com/integr8ly/integreatly-operator/commit/17187e5e94874c40d7c3092b761c35592ede4202)
* align test user & customer admin user names format with sso-idp script (i.e., test-user0x, customer-admin0x)
1. Comment out these lines: https://github.com/integr8ly/integreatly-operator/blob/5ecb3c22a18927b39bd248c07ab6497f31500420/test/functional/integreatly_test.go#L22-L40
2. oc login to OSD cluster with RHOAM installed and SSO IDP configured with the script
```bash …
```
> Fix 3scale smtp flaky test

- pkg/controller/installation/installation_controller.go
Webhooks were only being reconciled after the preflight checks had passed. A webhook was set up to delete the operator
Subscription when the RHMI CR is deleted, however; in the chance that the CR is deleted before the preflight checks have passed (example: the `useClusterStorage` field hasn't been set), the webhook won't be in place and the Subscription won't be deleted.
This change ensures that the webhooks are created before the preflight checks
In order to verify this, install the add-on and use an image from this PR, then delete the add-on and check that the subscription is deleted
1. Create an image from this PR
2. Install the add-on
3. Update the operator CSV to reference the custom image
4. Wait for the operator Pod to be restarted
5. Uninstall the add-on
6. Verify that the RHMI CR …
> Reconcile webhooks before preflight checks

- pkg/products/marin3r/config/unit_conversion.go
- pkg/products/marin3r/reconciler.go
- pkg/products/marin3r/rejectedRequestsPrometheusRules.go
- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
- test/common/alerts_exist.go
> Link to Jira: https://issues.redhat.com/browse/MGDAPI-373
Create an alert that will fire when the rate of rejected requests doesn't match the expected rate based on the configuration
Example: The rate limit service is configured with a rate limit of `200 req/minute`, and the API is receiving `240 req/minute`. We'd expect ~16% of the requests to be rate limited. If this doesn't match, the alert will be triggered
1. Install RHOAM
1. Create a 3scale application
2. Set the rate limit configuration to 200 requests per minute
3. Wait for the configuration to be propagated
4. Verify that the alert was created
```sh
oc get prometheusrules rejected-requests -n redhat-rhoam-marin3r
```
5. Run the following script to force requests to be rate limited, and verify that the alert doesn't fire
> It …
> MGDAPI-373: Add alert for rate of rejected requests

- pkg/products/threescale/prometheusRules.go
This alert fired in production while 3scale admin ui was still responding correctly. Route cause is that the blackbox exporter didnt scrap metrics for a period of time. This update will check for when the exporter returns 0 rather than nothing
To validate 1. remove the url from the blackbox target and the alert should not fire. Once confirmed. replace the url and move on to step 2.
2. stop 3scale operator and scale down system-app replicas until the alert fires.
> INTLY-10307 ThreeScaleSystemAdminUIBBT alert update

- test/common/dashboards_data.go
- test/common/dashboards_exist.go
Grafana pod in monitoring no longer has `curl` command causing tests to fail.
Change test to allow performing curl to grafana pod ip from another pod and container
Jira:
* https://issues.redhat.com/browse/MGDAPI-815
* Run E02 & E03 functional test a few times
```
go clean -testcache && MULTIAZ=true WATCH_NAMESPACE=redhat-rhoam-operator go test -v ./test/functional -run="//(^(E02)|(E03))" -timeout=80m
```
* Verify tests passes
> MGDAPI-815 - Fix flaky E02 & E03 

- pkg/products/threescale/prometheusRules.go
With the increase of replicas for [3scale zync pods to 3](https://github.com/integr8ly/integreatly-operator/blob/master/pkg/config/threescale.go#L128), the time for all the pods to become ready has increased which is making the alert `ThreeScaleZyncPodAvailability` fire. We need to extend the length of time for this alert to avoid it from fire prior the installation is completed
https://issues.redhat.com/browse/MGDAPI-913
1) install the operator from this branch in a multi AZ cluster
2) verify that `ThreeScaleZyncPodAvailability` is not firing during the installation of 3scale.
> Increases ThreeScaleZyncPodAvailability alert firing time

- deploy/crds/integreatly.org_rhmis_crd.yaml
- deploy/operator.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/controller/installation/installation_controller.go
- pkg/resources/multiErr.go
- pkg/resources/poddistribution/poddistribution.go
- pkg/resources/poddistribution/poddistribution_test.go
Add pod distribution check and balance. On multiAZ clusters, the rhoam operator should reconcile pod distribution on deployments (and RS, SS) with > 1 replica count.  First check if the distribution meets the requirements i.e. Minimum pod distribution states that a replica count > 1 on clusters with > 1 zone should not all be on the same zone. If the minimum pod distribution is not satisfied for a given pod restart <=50% of the replica count. Limit this check and redistribution attempt to 3. If it fails after 3 attempts there may be another cause for the failing distribution, for example, resource usage.
More details on [JIRA](https://issues.redhat.com/browse/MGDAPI-680): 
- Clone this repo
- Modify the [replica numbers](https://github.com/integr8ly/integreatly-operator/blob/95d6b50918c693 …
> Add pod distribution check and balance

- pkg/products/grafana/reconciler.go
- pkg/products/marin3r/reconciler.go
- pkg/products/marin3r/reconciler_test.go
JIRA: https://issues.redhat.com/browse/MGDAPI-1002
Marin3r and customer monitoring [are in the same stage](https://github.com/integr8ly/integreatly-operator/blob/a78b3aaad51a74f32355b60b524bb7e12d4514aa/pkg/controller/installation/types.go#L48-L49),
and marin3r reconciler [tries to retrieve grafana URL](https://github.com/integr8ly/integreatly-operator/blob/master/pkg/products/marin3r/reconciler.go#L225-L263) before "redhat-rhoam-customer-monitoring" ns is created.
This results into an error message in logs which can in fact be ignored under specific circumstances (during installation, before grafana is installed). Error message:
> time="2020-12-17T00:29:28Z" level=error msg="failed to get Grafana console URL Failed to get route for Grafana: routes.route.openshift.io \"grafana-route\" is …
> MGDAPI-1002 - improve logging in marin3r reconciler

- pkg/products/amqonline/prometheusRules.go
- pkg/products/apicurito/prometheusRules.go
- pkg/products/codeready/prometheusRules.go
- pkg/products/fuse/prometheusRules.go
- pkg/products/solutionexplorer/prometheusRules.go
- pkg/products/ups/prometheusRules.go
JIRA: https://issues.redhat.com/browse/INTLY-10344
As requested by CS-SRE, I downgraded severity of "*RegistryCsServiceEndpointDown" alerts down to "warning".
Note: in the diff you might notice that not all products have been updated, that's because some had this alert marked as a "warning" already.
Prometheus config before my changes (installed RHMI v2.7.1):
https://gist.github.com/matskiv/86114be66931bcb37fd13081a2341aae/raw/6743c18123850f32cee8fe259b3ca3275cad9875/config-before
Prometheus config with the change (I just run locally with the new code, operator updated the alerts automatically):
https://gist.github.com/matskiv/86114be66931bcb37fd13081a2341aae/raw/6743c18123850f32cee8fe259b3ca3275cad9875/config-after
> INTLY-10344 Update all "RegistryCsServiceEndpointDown" alerts to warning

- pkg/resources/metrics.go
* Update `RedisMemoryUsageMaxIn4Days` & `RedisMemoryUsageMaxIn4Hours` to include and statement to only fire if `cro_redis_memory_usage_percentage_average` > 75 
* Sum metrics based on `instanceID` and use time series from this data for prediction as restarting CRO will create new metrics under different pod name 
Jira:
* https://issues.redhat.com/browse/MGDAPI-693
* Install RHOAM on a **BYOC** cluster
```
make cluster/prepare/local 
SELF_SIGNED_CERTS=false USE_CLUSTER_STORAGE=false make deploy/integreatly-rhmi-cr.yml
make code/run
```
* Verify `RedisMemoryUsageMaxIn4Days` is not firing during and after install
* Fill redis memory by following: https://github.com/integr8ly/cloud-resource-operator/tree/master/hack/redis
* Verify …
> MGDAPI-693 - Fix RedisMemoryUsageMaxIn4Days alert firing during install

- scripts/ec2_deploy_teardown/deployEC2.sh
- scripts/ec2_deploy_teardown/tearDown.sh
https://issues.redhat.com/browse/MGDAPI-986
Improvements of the script. The EC2 instance type is now parametrized thus EC2 instances of different types (not just t2.micro) can be created and removed using the scripts.
- [x ] New feature (non-breaking change which adds functionality)
The PR has been verified via Jenkins where I used the scripts in the pipelines (this is what the scripts are primarily for):
https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Playground/job/trepel-ec2/
see builds 2, 3 and 5.
I think it is sufficient to eye review the code changes and the build logs for verification.
> EC2 name and type parametrized

- pkg/config/rhsso.go
- pkg/config/rhssoUser.go
- pkg/config/threescale.go
- pkg/products/monitoring/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/threescale/reconciler.go
- test/common/scale_up_replicas_rhsso.go
RHOAM increased the number of replicas in RHSSO, User SSO and Three Scale, this requires more resources than RHMI needs, so this PR reverts back the number of replicas required by rhmi.
https://issues.redhat.com/browse/MGDAPI-732
1) Install RHMI from this branch `INSTALLATION_TYPE=managed make cluster/prepare/local && INSTALLATION_TYPE=managed make code/run`
2) Verify if the following number of replicas are applied:
**Three scale**
```
"systemApp":       2,
"systemSidekiq":   2,
"apicastProd":     2,
"apicastStage":    2,
"backendListener": 2,
"backendWorker":   2,
"backendCron":     2,
"zyncApp":         2,
"zyncQue":         2
```
**RHSSO and SSO**
```
"keycloak":       2
```
UPDATE
**Application monitoring operator (AMO)**
```
"alertmanager":     1,
"prometheus":   1,
```
> Fix RHOAM replicas applied to RHMI

- pkg/products/rhsso/reconciler.go
Jira: https://issues.redhat.com/browse/MGDAPI-1022
1. Install RHOAM from this branch
2. Ensure the RHSSO stateful set shows the cpu is 650m
3. Ensure the keycloak pods come up with no restarts
> Reduce CPU requested by cluster SSO

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- test-cases/tests/authorization/b01b-verify-that-the-users-can-login-in-all-products.md
- test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
- test/common/routes_exist.go
JIRA: https://issues.redhat.com/browse/MGDAPI-1026
Currently, we have 2 routes for user-sso for RHOAM, one called `keycloak` is KCO generated route, and another one, `keycloak-edge`, is managed by RHOAM operator. Both routes use re-encrypt TLS termination policy and it makes no point in keeping two as only the edge route is being used.
- KCO route has been disabled leaving only the `keycloak-edge` route available. 
- The name of the `keycloak-edge` route has been updated to `keycloak` since it is no longer using edge termination policy, and also since this work is preparing us for enabling user-sso rate-limiting in the future if it happens that we decide not to enable rate-limiting on user-sso, we can switch back to KCO managed routing without changing the host address.
- Unit test has …
> Remove keycloak route MGDAPI-1026

- Makefile
- deploy/crds/integreatly.org_rhmis_crd.yaml
- deploy/operator.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/controller/installation/installation_controller.go
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
$subject
As part of this change we will need to add a new parameter to the managed tenants repo see PR 471
Spin up a cluster and run the operator locally overriding ALERT_SMTP_FROM and setting it to a value of your choice.
Once the install is complete, check the smtp config in alert manager
```
oc get secret alertmanager-application-monitoring -n redhat-rhoam-middleware-monitoring-operator -o=yaml
```
it should have the ```smtp_from``` set to your chosen email address.
> Add support for a from alert email address

- deploy/cro-aws-config.yml
- pkg/products/cloudresources/reconciler.go
- Set the cidrvalue to nil if there is no addonParam after some time
- Remove the network block from the local dev setup to mimic addon installation
Against a byoc cluster
INSTALLATION_TYPE=managed-api USE_CLUSTER_STORAGE=false make cluster/prepare/local
INSTALLATION_TYPE=managed-api USE_CLUSTER_STORAGE=false make code/run/service_account
Verify cloud-resources-aws-strategies config map does not contain a default entry { "production": { "createStrategy": {} } }
Verify that the vpc in aws has been created with a sensible default.
Verify that the rds is created inside that vpc.
> set cidrvalue to empty rather than returning

- deploy/role.yaml
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
For CSSRE, it would nice to have the cluster id as part of the subject field in the emails sent by alertmanager to help them filter the alerts per cluster
Jira:
* https://issues.redhat.com/browse/MGDAPI-822
* Checkout this branch and install RHOAM
```
make code/run
```
* Check alertmanager config in `alertmanager-application-monitoring` secret in `redhat-rhoam-middleware-monitoring-operator` namespace and verify that the your cluster infra id is used as part of the reciever email_configs
* Check config is loaded properly and reflected in alertmanager status page
* Install as per above
* Update the RHOAM CR alerting emails addresses to your own email address
* Update `redhat-rhoam-smtp` with valid credentials (reach out if …
> MGDAPI-1028 - Add cluster infra id as part of alert email subject

- scripts/capture_resource_metrics.sh
JIRA: https://issues.redhat.com/browse/MGDAPI-1040
In this PR I:
a) added queries for capturing allocatable CPU and RAM on worker nodes (new rows in perf spreadsheet also added)
b) resource requests now only capture requests of Running pods
Original query includes requests of a failed pod for some period of time:
Fixed query doesn't include failed pod:
Details about pod status:
Details about pod requests:
> MGDAPI-1040 - ignore non-Running pods when capturing resource requests

- scripts/ec2_deploy_teardown/deployEC2.sh
- scripts/ec2_deploy_teardown/tearDown.sh
- Improved waiting for EC2 to become ready.
- Adding IP address from where there will be allowed full access to EC2 instance
- Adding rule to allow full access from localhost. Useful for Hyperfoil since both agent and controller might be hosted on the same EC2 instance (for now) and they use some non-standard ports and protocols (jgroups)
- Not using Elastic IP for publiIP of EC2 instance. It's not required and since there is a limit of just 5 Elastic IPs on AWS level it better not to use it unless really needed
- [x ] New feature (non-breaking change which adds functionality)
I used this script to create EC2 instance using 601144055808 AWS account, log in and have a look (sorry, removed already) :
https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#InstanceDetails:instanceId=i-0b8 …
> Prepare EC2 for Hyperfoil install

- pkg/products/marin3r/reconciler.go
Add Request and Limit resources to the statsd-exporter pod
Resources are higher than required to allow for initial spike in resources usages during start up.
*JIRA* https://issues.redhat.com/browse/MGDAPI-700
*Verify*
This is hard to Verify.
- On install the `prom-statsd-exporter` pod in the `redhat-rhoam-main3r` namespace should start correctly.
- Destroying and recreating the pod should not go into any crash off loops
- Metrics should show in grafana after about 3 minutes from pod creation
- Cluster metrics from a load test run shows the pod is does not increase under system load. https://snapshot.raintank.io/dashboard/snapshot/zPx50Zdzpn3tl0TrF1bGWHl27abgdChB?orgId=2 You are wanting to look at the charts for the `prom-statsd-exporter-6bf4478bdf-c58lq` pod. Note these charts do not have …
> MGDAPI-700 Add Request and Limit resources to the statsd-exporter pod.

- pkg/resources/constants/grafanaConstants.go
[MGDAPI-1005](https://issues.redhat.com/browse/MGDAPI-1005)
Update Grafana version to mirror what's used in the `openshift-monitoring` Grafana (7.2.0).
- Install RHOAM from this branch
- Check the correct Grafana version is being used in both the `middleware-monitoring` and `customer-grafana` namespaces (`7.2.0`).
- Check that the same image is being used (check the pod/deployment YAML definition image field) in both namespaces, and that it matches the image used in the `openshift-monitoring` ns
- Login to both of the above-mentioned namespaces and ensure that dashboards load correctly
- Check the Grafana pod logs in both the `middleware-monitoring` and `customer-grafana` namespaces and ensure there are no errors
> Grafana Image Update (7.2.0)

- pkg/resources/podAntiAffinity.go
Jira: https://issues.redhat.com/browse/MGDAPI-720
Add anti-affinity rules to nodes
- Install RHOAM from this branch on a ccs multi az cluster
- Keep an eye on RHMI CR and before envoy-side car containers are attached to apicast production pods run the following script:
```
#!/bin/sh
NODES_ARR=()
ZONES_ARR=()
nodes=$(oc get nodes -o json | jq -r '.items[].metadata | .name + " " + .labels["topology.kubernetes.io/zone"]')
while read -a line; do
NODES_ARR+=(${line[0]})
ZONES_ARR+=(${line[1]})
done <<< "$nodes"
get_zone() {
for i in ${!NODES_ARR[@]}; do
if [[ ${NODES_ARR[$i]} == $1 ]]; then
echo ${ZONES_ARR[$i]}
break
fi
done
}
NAMESPACE="redhat-rhoam-3scale"
if [[ $NAMESPACE == "" ]]; then
echo "Pods distribution for ALL namespaces"
NAMESPACE_ARG="--all-namespaces"
else
echo "Pods …
```
> Node anti-affinity rules for RHOAM

- test/common/3scale_crudl.go
- test/common/alerts_mechanism.go
Extra logging added to H03 & C03. These tests have been marked as flaky but is still showing failures in the nightly pipelines. These logs are to help identify the cause of the new failures.
> Adding logging to help debug e2e tests

- scripts/ec2_deploy_teardown/deployEC2.sh
Increasing the size of root volume to allow for taking of full heap snapshots (up to 32GB).
Adding "Name" tag, so the instance name is displayed in AWS console.
Test run:
https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Public/job/trepel-ec2-deploy/56/console
> Increase root volume size for the provisioned EC2

- test/functional/aws_shared_functions.go
- test/functional/aws_standalone_vpc.go
[MGDAPI-1077](https://issues.redhat.com/browse/MGDAPI-1077
)
The changes in [this](https://github.com/integr8ly/cloud-resource-operator/pull/201) PR caused the `A25` e2e test to fail. When installing RHOAM via the add-on the user must specify a CIDR block. If the user doesn't specify a CIDR block, CRO will dynamically allocate one. The test was updated to account for the dynamic CIDR block.
We want to make sure that the test works for both use cases:  
1. If the CIDR block is _**not**_ specified
2. If a CIDR block _**is**_ specified
- Provision a BYOC cluster
- Install RHOAM via the addon and when prompted to enter a CIDR block leave the field to its default empty state (_**important**_)
- Once the install is complete, we want to make sure the CIDR block in the …
> Updated A25 e2e test to accommodate dynamic CIDR blocks

- scripts/ec2_deploy_teardown/deployEC2.sh
- scripts/ec2_deploy_teardown/tearDown.sh
Updated error handling of EC2 deploy (and remove) script. It fails with non-zero return code early now.
It also prints info about entities that have been already created for manual clean up (not ideal, but better than nothing).
Verified in Jenkins already:
https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Public/job/trepel-ec2-deploy/57/ (success)
https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Public/job/trepel-ec2-deploy/58/ (early failure, duplicate key)
corresponding removal:
https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/ManagedAPI/job/ec2-remove/98
> Improved ec2 deploy script error handling

- deploy/role.yaml
- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/threescale/reconciler.go
- pkg/resources/user/userHelper.go
- pkg/resources/user/userHelper_test.go
Treat users attached to deleted IDP as if they were deleted.
- Provision OCM cluster
- Add github IDP through OCM
- Login to cluster using the IDP and see that a matching openshift user is created in the cluster
- Provision RHOAM
- See keycloakuser CR for your github user is created in redhat-rhoam-rhsso namespace
- Login to 3scale as admin, and see your user is created
- Delete your IDP from OCM
- Wait for operator to reconcile
- See keycloakuser CR is deleted
- See user is deleted from 3scale
> don't reconcile users from deleted IDPs

- cmd/manager/main.go
- pkg/metrics/metrics.go
- pkg/products/threescale/objects_test.go
- pkg/products/threescale/prometheusRules.go
- pkg/products/threescale/reconciler.go
- test/common/alerts_exist.go
expose new metric around user creation and deletion in 3scale
allow installation to complete when the user creation fails
add new alert that will fire when the user creation in 3scale fails
test updates
https://issues.redhat.com/browse/MGDAPI-1154
https://issues.redhat.com/browse/MGDAPI-1155
https://issues.redhat.com/browse/MGDAPI-1156
`INSTALLATION_TYPE=managed-api IN_PROW=true make cluster/prepare/local`
Create a User with the following yaml and `oc apply -f` you cannot create through the UI without configuring a OAuthClient or 
```
apiVersion: user.openshift.io/v1
kind: User
metadata:
name: alongusernamethatisabovefourtycharacterslong
```
and
```
apiVersion: user.openshift.io/v1
kind: User
metadata:
name: auserlessthanfourtycharacters
```
Run the operator in cluster - local run won't …
> 3scale user action failure metric and alert

- pkg/resources/reconciler.go
- pkg/resources/reconciler_test.go
Install plans can fail for operators that are installed in multiples namespaces such as keycloak. This looks to be due to transient errors / race condition by OLM. As this issue looks to be external to RHOAM and a flaky issue, we should have a way to try re-install the stuck products 
Logged OLM bugzilla ticket that will be investigated in their future sprint
* https://bugzilla.redhat.com/show_bug.cgi?id=1923111
Jira:
* https://issues.redhat.com/browse/MGDAPI-1098
```
export INSTALLATION_TYPE=managed-api  
make code/run
```
* Once RHSSO is installed, run script to update keycloak CRD to try reproduce install plan failure for User SSO
```
while true; do …
```
> MDGAPI-1098 - Retry to install product operators if failed install plan

- pkg/metrics/metrics.go
- pkg/products/threescale/reconciler.go
**What**
reset the threescale_user_action metric on each reconciliation
if the uses is resolved we want the metric to resolve so the alert will resolve
**JIRA**
Verification
It's installed to my cluster -> contact me for credentials
Create user in sso with too longer username (>40 characters)
Verify the alert fires
Delete the user as a resolution
Verify alert stops firing but history is still present in prometheus
> reset 3scale user metric on each reconcile

- pkg/products/monitoring/reconciler.go
A change to how the SMTP FromAddress is set in RHOAM has an impact on RHMI. Production RHMI instances have fromAddress domains set to the route domain of alert manager. This works with the SMTP Server / Service configured. This change prevents updates on clusters with an existing fromAddress configured in alert manager i.e. production RHMI clusters
export ALERT_SMTP_FROM=test@test.com
Install RHMI as far as the monitoring stage
Verify that the alert manager config has `smtp_from: test@test.com`
Stop the operator
export ALERT_SMTP_FROM=test2@test.com
Rerun the operator.
After the monitoring stage has reconciled 
Verify that the alert manager **still has** config has `smtp_from: test@test.com` i.e. smtp_from was not overwrote
Delete the RHMI CR and repeat the test for RHOAM but verify that …
> Prevent overriding RHMI production SMTP fromAddress value  in alert manager

- manifests/integreatly-monitoring/1.2.1/application-monitoring-operator.v1.2.1.clusterserviceversion.yaml
- manifests/integreatly-monitoring/1.2.1/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
- manifests/integreatly-monitoring/1.2.1/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
- manifests/integreatly-monitoring/1.2.1/grafana_crd.yaml
- manifests/integreatly-monitoring/1.2.1/grafana_dashboard_crd.yaml
- manifests/integreatly-monitoring/1.2.1/grafana_datasource_crd.yaml
AMO 1.2.1 Manifest folder was remove when 1.4.0 was added. 1.2.1 is present in RHMI 2.7.2, hence the removal breaks the upgrade of RHMI to 2.8.0
Install RHMI based on v2.7.2 tag. 
Verify 1.2.1 of AMO installed 
Checkout this branch
Install RHMI 
Verify 1.5.1 of AMO installed 
Log into Prometheus, Grafana and AlertManager and sanity check settings
> add back AMO 1.2.1

- deploy/role.yaml
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssouser/reconciler.go
remove unused keycloack pod monitors since v12.0.1 no longer uses them. 
1. Install 2.7.2 rhmi branch
2. verify keycloak-pod-monitor cr exists on cluster in both rhsso and user-sso namespaces
3. Verify alerts for keycloak-pod-monitor is firing in alertmanager
4. Install 2.8.0 from this branch 
5. Verify podmonitors are removed 
6. Verify alerts are no longer in alertmanager, this can take up to 3 minutes for alertmanager to rebuild its config.
> Remove unused podmonitors from keycloak namespaces

- pkg/products/monitoring/dashboards/clusterResources.go
- pkg/products/monitoring/dashboards/resourceByNamespace.go
- pkg/products/monitoring/dashboards/resourceByPod.go
- templates/monitoring/fuseonline/addon-ops-home-dashboard.yml
JIRA: https://issues.redhat.com/browse/MGDAPI-1248
There has been some confusion caused by the use of MB in some places, and MiB in other.
This PR would unify the unit used to represent memory.
MiB should be used from now on.
> MGDAPI-1248: Unify memory unit used in Grafana

- test/functional/aws_shared_functions.go
F04 was failing for RHMI (managed) install type
More info in https://issues.redhat.com/browse/INTLY-10435
* fix was verified on both RHOAM and RHMI
> fix: test: F04

- Makefile
- controllers/namespacelabel/namespacelabel_controller.go
Observed a panic during an uninstall due to RHMI CR no longer being present due to not checking for err or reference before continuing the namesapce label reconcile
```
INFO[2021-01-26T15:11:00Z] Looking for RHMI CR                           controller=namespacelabel_controller ns=
E0126 15:11:00.609530   72817 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1068 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1f190a0, 0x3aa2090)
/home/kevinfan/go/src/github.com/integr8ly/integreatly-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) …
```
> MGDAPI-1165 - Fix panic from namespace label controller 

- controllers/namespacelabel/enqueue.go
- controllers/namespacelabel/namespacelabel_controller.go
The namespace controller watches Namespaces and ConfigMaps, which will enqueue different requests since the namespaces have their name in theresource name, while the ConfigMap is namespaced. In order to ensure uniform requests, add an EventHandler for the ConfigMap watch that enqueues only its namespace, and add predicates for both types of resources to watch exclusivelly what we're interested in: the operator namespace and the add-on ConfigMaps.
1. Install RHOAM/RHMI from this PR
2. Create a ConfigMap called
* RHOAM: `managed-api-service`
* RHMI: `rhmi`
3. In the operator logs, verify that the following entry is immediately added (proof that the watch works for the ConfigMap):
```
Reconciling namespace labels
```
4. Add the following label to the ConfigMap
```yaml …
```
> MGDAPI-1289: Modify watches in namespace controller to enqueue correct requests

- Makefile
- scripts/prepare-release.sh
Fix `make release/prepare` to work with Kustomize when it's not installed. The Makefile will automatically install (in a temporal
directory) Kustomize if it's not found on the $PATH. However, when running `release/prepare`, it will invoke the `prepare-release.sh` script, which assumes Kustomize is in the $PATH.
Modify the script to use an optional environment variable with the path to Kustomize, and the Makefile to pass the temporal path when running the script.
> Fix make release/prepare

- config/manager/manager.yaml
- config/prometheus/monitor.yaml
- config/rbac/auth_proxy_service.yaml
Newly scaffolded operators include the following label on the manager Deployment as well as selectors:
```yaml
control-plane: controller-manager
```
When upgrading the operator from a pre-operator-sdk migration release that doesn't include this label, it fails due to the fact that the field is immutable.
Remove this label from the deployment as well as the selectors that
point to the operator (ServiceMonitor and metrics Service)
1. Tag the RHOAM 1.2.0 image to your org and push it to quay
2. Update the CSV for RHOAM 1.2.0 in `packagemanifests/1.2.0` to point to your quay org
3. Generate a bundle for it
```sh
ORG=<your org> OLM_TYPE=managed-api-service BUNDLE_VERSIONS=1.2.0 ./scripts/bundle-rhmi-operators.sh
```
4.  The script will create a CatalogSource pointing to 1.2.0. In your cluster, …
> MGDAPI-1292: Remove control-plane label from operator Deployment

- scripts/setup-sso-idp.sh
The issue with getting no result for a cluster ID was seen couple of times in nightly pipelines and is causing problems when running e2e test (IDP tests)
The command I'm introducing in this PR is a command that I was using lately in my local scripts and it was working for me every time.
I verified it's also working against the cluster where the issue with sso-idp script can be currently seen:
```
No CLUSTER_ID detected. IDP will be added directly into "cluster" OAuth resource.
```
In the new `ocm` command we're asking ocm directly to search for the specific cluster API URL instead of asking it to get the full list of managed clusters and then filter them. I thought that it doesn't really matter which approach we choose, but in this case it does. (But why - I have no idea.)
> fix: getting cluster id in sso-idp script

- Makefile
- scripts/bundle-rhmi-operators.sh
Addresses https://issues.redhat.com/browse/MGDAPI-1090
NOTE: Please verify this PR with changes in https://github.com/integr8ly/integreatly-operator/pull/1605 as the bundle script used the release/prepare which is fixed in the linked PR.
Go through the updates to readme and confirm that the commands generate correct bundles and indexes in your registry.
> Update to generate bundles - MGDAPI-1090

- pkg/products/amqonline/reconciler_test.go
- pkg/products/amqstreams/reconciler_test.go
- pkg/products/apicurioregistry/reconciler_test.go
- pkg/products/apicurito/reconciler_test.go
- pkg/products/codeready/reconciler_test.go
- pkg/products/fuse/reconciler_test.go
- pkg/products/monitoring/reconciler_test.go
- pkg/products/monitoringspec/reconciler_test.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/products/solutionexplorer/reconciler_test.go
- pkg/products/threescale/clients_test.go
- pkg/products/threescale/reconciler.go
- pkg/resources/marketplace/MarketplaceManager_moq.go
- pkg/resources/marketplace/manager.go
- pkg/resources/reconciler.go
- pkg/resources/reconciler_test.go
Currently, as part of the product operators installation, the retrieval of the InstallPlans associated with the product is done by
listing all InstallPlans in the Subscription namespace. OLM however might create multiple InstallPlans where only one is valid and is referenced in the Subscription status as an `InstallPlanRef` field. The current approach will loop through all the InstallPlans in the namespace, approve them an wait for the status to be `Complete`, but if an invalid InstallPlan comes first in the list, it will remain stuck in progress, never reaching the valid one.
Change the `MarketPlaceInterface` and its `Manager` implementation to retrieve only the InstallPlan that is referenced by the Subscription, and update the unit tests that depend on this method.
It's been noted that …
> MGDAPI-1170: Improve product operator installation

- packagemanifests/integreatly-operator/integreatly-operator.package.yaml
Update version as 2.8.0 was released the day before this file was merged with the operator sdk bump
> Fix rhmi version

- make/osde2e.mk
- test/common/alerts_mechanism.go
- test/osde2e/managed_api_test.go
- test/osde2e/pre-test.go
- test/osde2e/suite_test.go
Addresses: https://issues.redhat.com/browse/INTLY-10444
Enabled rhmi osde2e and changed the timeout on the alerts_mechanism tests as the RHMI installation takes longer, and in case if that test is flaky, we can't be giving it 40minutes before it fails as instead of failing single test, we might end up having an entire suite of tests timinig out.
> add osde2e rhmi support

- Makefile
added prow check for files generated by the kubebuiler 
to check that files were not edited manually 
https://issues.redhat.com/browse/MGDAPI-1349 
- modify files in the `config/crd/bases` or `config/rbac/role.yaml` 
- commit your changes
- run `kubebuilder/check`
- ensure check fails (or `echo $?` to get exit code of check)
> [MGDAPI-1349] adding prow check

- test/functional/suite_test.go
https://issues.redhat.com/browse/MGDAPI-525
A16 test was failing when the test container was running on OpenShift due to missing [sysadmin impersonationConfig](https://github.com/integr8ly/integreatly-operator/blob/d600ea4d1b964fa0d351b058dbd86a1bae8d3f9e/test/functional/integreatly_test.go#L15-L18), that was removed during operator-sdk migration
After the config was added back, [the test is passing again](https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Playground/job/psturc-rhoam-master/37/artifact/results/integreatly-operator-test/logs/container.log/*view*/)
> test: fix A16: readded sysadmin ImpersonationCfg

- Dockerfile.functional
- Dockerfile.osde2e
- Makefile
- README.md
* replaced `-test.run` with [`-ginkgo.focus`](https://onsi.github.io/ginkgo/#focused-specs) flag
* added `-ginkgo.v` and `ginkgo.progress` flags to "functional" and "osde2e" dockerfiles' entrypoints (for detailed log output and real time logging when ran locally)
* updated readme
> test: flags for real time logging, readme update

- scripts/capture_resource_metrics.sh
Fixes a bug in the ./scripts/capture_resource_metrics.sh
Now it will run "instant queries" at a time when a run ended,
instead of running them at a time when script runs.
This is useful if you run the script much later after the run finish time.
Edit: I also fix one query (Allocatable RAM on workers)
> Fix time for instant queries in capture_resource_metrics.sh

- test-cases/tests/upgrade/n01a-measure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
Adding info on have to change channel for OSD upgrades.
**Verification steps**
Eye review only, you can also check the article.
I verified this when working on https://issues.redhat.com/browse/MGDAPI-1088. I had to change the channel, otherwise I was told that there is nothing to do since 4.6.18 was the latest version of stable-4.6 channel.
> Small improvements to OSD upgrade test cases

- Makefile
- config/crd/bases/integreatly.org_rhmiconfigs.yaml
- config/crd/bases/integreatly.org_rhmis.yaml
- pkg/webhooks/operator_webhooks_test.go
- pkg/webhooks/reconciler.go
- pkg/webhooks/rules.go
- test/common/rhmi_config.go
> Link to JIRA: https://issues.redhat.com/browse/MGDAPI-1180
v1beta1 API version of CRDs and Admission resources (webhooks) will be deprecated soon. Update the project to use v1 instead.
* Update CRD generation options to enable v1 API version of CRD
* Update imports of ValidatingWebhookConfiguration and MutatingWebhookConfiguration to reference v1 API version instead of
v1beta1.
> MGDAPI-1180: Update CRD and webhook API versions

- pkg/products/threescale/reconciler.go
Small change in 3scale reconciler to stop "required number of routes do not exist" warning from triggering as part of MGDAPI-1308 https://issues.redhat.com/browse/MGDAPI-1308
- [:heavy_check_mark: ] Bug fix (non-breaking change which fixes an issue)
- [ :heavy_check_mark:] Verified independently on a cluster by reviewer
> Fixing 3scale routes warning

- pkg/products/monitoring/dashboards/clusterResources.go
- pkg/products/monitoring/dashboards/endpointsDetailed.go
- pkg/products/monitoring/dashboards/endpointsReport.go
- pkg/products/monitoring/dashboards/endpointsSummary.go
- pkg/products/monitoring/dashboards/resourceByNamespace.go
- pkg/products/monitoring/dashboards/resourceByPod.go
- pkg/products/monitoring/dashboardsHelper.go
- pkg/products/monitoring/reconciler.go
updated Grafana annotations to match the installation type (rhoam or rhmi)
https://issues.redhat.com/browse/MGDAPI-1310 
- get the image and deploy the cluster by running:
`IMAGE_FORMAT=quay.io/hudeb/managed-api-service:v1.2.0 INSTALLATION_TYPE=<managed-api/managed>  make cluster/deploy`
- log in to the console as admin
- navigate Home -> Search and search for the redhat-rhoam-middleware-monitoring-operator. 
- Open redhat-rhoam-middleware-monitoring-operator and navigate Routes -> grafana-route. Follow the link  
- In Grafana for all boards (except Critical SLO summary): Share board -> Export -> View JSON
- Verify that following line `"expr": "count by (stage,version,to_version)(rhoam_version{to_version!=\"\"})",` has a valid installation type (`rhoam_version` or `rhmi_version` depending …
> update Grafana annotations

- apis/v1alpha1/rhmi_types.go
- manifests/integreatly-rhsso/12.0.3/keycloak-operator.v12.0.3.clusterserviceversion.yaml
- manifests/integreatly-rhsso/12.0.3/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/12.0.3/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/12.0.3/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/12.0.3/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/12.0.3/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/rhsso.package.yaml
https://issues.redhat.com/browse/INTLY-10442
Probably should be merged after https://github.com/keycloak/keycloak-operator/pull/313.
Steps to test the changes:
1. Install RHOAM  from master using the Integreatly operator.
2. Verify that Keycloak operator 12.0.1 was installed. Use e.g.:
```
oc get rhmis rhoam -n redhat-rhoam-operator -o=jsonpath="{.status.stages.products.products.rhssouser.operator}"
oc get deployments keycloak-operator -n redhat-rhoam-rhsso-operator -o=jsonpath="{.spec.template.spec.containers[0].image}"
```
3. Stop the operator and run it again from this PR.
4. Verify Keycloak operator was updated to 12.0.3 using the steps from 2.
> Bump Keycloak operator version to 12.0.3

- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- pkg/products/monitoring/templateHelper.go
- pkg/products/threescale/clients_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/three_scale_client.go
- pkg/products/threescale/three_scale_moq.go
- pkg/resources/smtp.go
set 3scale outgoing email address to smtp_from field in the secret: alertmanager-application-monitoring
Currently the domain for the from email address defaults to the 3scale route. This is no longer compatible with send grid validation rules.
Install RHOAM based on this branch
After 3scale reconciles verify that the outgoing email on 3scale is the same as the smtp_from field in the secret: alertmanager-application-monitoring in ns redhat-rhoam-middleware-monitoring-operator
To find the outgoing email address in 3scale
- Log in as admin (system-seed secret)
- Browse to Audience => Settings => Domains & Access => Outgoing Email
> set 3scale outgoing email address to smtp_secret

- controllers/subscription/subscription_controller.go
WHAT
Edge should behave the same as Production with regard to auto or manual upgrade of integreatly operator. Hive automatically sets auto upgrade on install plans to true. It's the responsibility of the operator to change this if required. Integreatly does this in the subscription controller. But not currently for edge. 
HOW
Update the subscription controller to check for edge Subscriptions.
> add edge subscriptions checks to subscription controller

- pkg/products/monitoring/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/resources/smtp.go
RHMI fails to install due to fetching secret from hardcoded RHOAM namespace  `redhat-rhoam-middleware-monitoring-operator` which is not available in RHMI
```
ERRO[2021-03-11T14:50:53Z] Error getting application monitoring secret   error="secrets \"alertmanager-application-monitoring\" is forbidden: User \"system:serviceaccount:redhat-rhmi-operator:rhmi-operator\" cannot get resource \"secrets\" in API group \"\" in the namespace \"redhat-rhoam-middleware-monitoring-operator\"" product=middleware-monitoring
```
> fix RHMI installation - fetching monitoring secret from hardcoded namespace

- test-cases/tests/alerts/c05a-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
- test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
- test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
- test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
- test-cases/tests/upgrade/n01a-measure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n02a-upgrade-rhmi.md
- test-cases/tests/upgrade/n02b-upgrade-rhoam.md
Added note to avoid double deployment of workload-web-app. Also added steps to alerts/c05 testcases to actually use workload-web-app and that alerts firing and downtimes due to automated tests and destructive test cases can be ignored.
> Avoid workload-webapp double deployment

- main.go
- pkg/addon/uninstall.go
> Link to JIRA: https://issues.redhat.com/browse/MGDAPI-1361
Add the scheme when creating the k8s client that's used to handle requests in the deletion webhook. This is needed to be passed explicitly since the upgrade to operator-sdk v1.x
1. Prepare the cluster
```sh
```
2. Reproduce the conditions for the webhook to use the client by creating a RHMI CR that won't pass the pre-flight checks.
```sh
INSTALLATION_TYPE=managed-api IN_PROW=true make deploy/integreatly-rhmi-cr.yml
```
* Remove the `useClusterStorage` field from the spec of the created CR
3. Build an image of the operator (the operator needs to run in cluster in order to use the webhooks)
```sh
TAG=1.4.0 ORG=<your quay username> INSTALLATION_TYPE=managed-api make …
```
> MGDAPI-1361: Include scheme in deletion webhook client

- pkg/products/threescale/reconciler.go
3scale username is lowercased when added, so we should lower case KC Username when trying to get 3scale user. Installation may be stuck otherwise by being unable to get 3scale user that should have been added
* https://github.com/integr8ly/integreatly-operator/blob/master/pkg/products/threescale/reconciler.go#L1569
> fix 3scale installation with user with uppercase letters

- pkg/products/monitoring/dashboardsHelper.go
E04B Test case fails due to Critical SLO total alerts and overal slo % dashboard not reflected due to using `spec.type` instead of product in dashboard query
Jira:
* https://issues.redhat.com/browse/MGDAPI-1451
* Check out this branch 
* Run through test case E04B
* https://issues.redhat.com/browse/MGDAPI-1420
* Note: grep of number of replica for scaling down keycloak pods in test case may need to be changed to 1 if RHOAM is installed using the `IN_PROW` annotation
* Verify total slo dashboard is now reflected correctly
> MGDAPI-1451 - fix total alerts + budget query on critial slo dashboard

- Makefile
Adding a new command for blocking the on-cluster operator from reconciling.
Leader election ConfigMap is used for this.
Setting the value to empty will result in parsing error, which will block the leader election logic.
Also, added a command for unblocking the operator (by deleting the ConfigMap).
Related to: https://issues.redhat.com/browse/MGDAPI-1398
**Verification steps:**
Install RHOAM 1.3.0+ on a cluster (with operator running in the cluster)
Run `make block-operator-pod INSTALLATION_TYPE=managed-api`
Verify that operator stopped reconciling (check logs after 1 minute, and after some additional time - e.g. 10mins)
Run `make unblock-operator-pod INSTALLATION_TYPE=managed-api`
Verify that operator is reconciling again
> Add make cmd for stopping operator running on cluster

- README.md
Adds how to deploy the operator from a custom image to the readme.
> Readme - how to deploy the operator from a custom image

- config/rbac-rhoam/kustomization.yaml
- config/rbac-rhoam/patches/catalogsources.yaml
Remove unnecessary patch that renamed the resource `rhmi-registry-cs` to
`rhoam-registry-cs` in RHOAM installations. This is not needed because
the operator always uses `rhmi-registry-cs` regardless of installation
type.
1. Run `cluster/prepare/local`
```sh
```
2. Check that the role applied to the operator SA references `rhmi-registry-cs`
> Remove patch to CatalogSource in RBAC resource

- Makefile
This reverts commit a49d8f796e7760ff3bc15e952057fa250a28ca12.
Scaling down the operator deployment seems to work reliably, so there is no need in these make commands.
I don't think anyone started using these commands, so safe to remove.
Related to: https://issues.redhat.com/browse/MGDAPI-1398
> Revert "Add make cmd for stopping operator running on cluster"

- apis/v1alpha1/addtoscheme_integreatly_v1alpha1.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssocommon/reconciler_test.go
JIRA: https://issues.redhat.com/browse/MGDAPI-1253
There is a bug that blocks uninstallation if it was triggered during the installation process. It must be a precise time and only on a fresh cluster. 
The reason for this: https://github.com/integr8ly/integreatly-operator/blob/master/pkg/products/rhssocommon/reconciler.go#L104-L108
Those lines of code are producing an error `no matches for kind \"KeycloakUser\" in version \"keycloak.org/v1alpha1\`  if there is no Keycloak CRD in a cluster and uninstallation loops. The way to fix it right now is to remove `finalizer.rhsso.integreatly.org` finalized from RHOAM CR 
For complete verification, there will be two deletions: "traditional" with CRDs created and the "edge case". To make verification easier I propose to modify the code in …
> allow uninstall during installation

- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
The PR make changes to add custom details under PagerDuty config in alertmanager template.
**Related JIRA ticket:** https://issues.redhat.com/browse/MGDAPI-1186
**Files updated:** 
- `controllers/rhmi/rhmi_controller.go` ~ add rbac marker to include _clusterversions_ object verbs/permissions.
- `pkg/products/monitoring/reconciler.go` ~ add cluster information parameters (**cluster_name**, **cluster_ID**, **console**) in the `templateUtil` helper function.
- `pkg/products/monitoring/reconciler_test.go` ~ add tests around changes made in the above file.
-  `templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml` ~ add custom details under PagerDuty config to include cluster information passed as params in the _reconciler.go_ file.
- Install `RHOAM` using this PR branch. …
> Add alertmanager config changes

- pkg/products/monitoring/reconciler.go
- pkg/products/threescale/reconciler.go
There can be potential nil pointer when calling `err.Error()` for logging in certain conditional blocks that can cause a panic 
* `e2e` and `rhoam-e2e` prow tests should pass
> fix potential nil pointers when logging

- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/products/threescale/three_scale_client.go
Jira:
* https://issues.redhat.com/browse/MGDAPI-1450
**Note: Requires setting up GIthub IDP and signing in with Github User with uppercase letter in username. Reach out if you don't have one**
* Checkout this branch 
```
export INSTALLATION_TYPE=managed-api  
SELF_SIGNED_CERTS=false IN_PROW=true make deploy/integreatly-rhmi-cr.yml
make code/run
```
* Once installed, set up Github IDP on cluster via ocm
* Sign into 3scale as admin using `system-seed` secret credentials
* In incognito tab, sign in to 3scale as github user 
* Verify github username is lowercased
* Promote github user to admin
* As github user, update username to any value
* Verify username is updated back and is **lowercased** 
* Verify admin permissions are **not** reverted
> MDGAPI-1450 - Fix 3scale user updated back to original none lower cased username

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- Fix of Keyckloak Update Strategy, to avoid downtime.  https://issues.redhat.com/browse/MGDAPI-1386
[Test_MGDAPI-1386-Fix_UpdateStrategy_v2.zip](https://github.com/integr8ly/integreatly-operator/files/6272368/Test_MGDAPI-1386-Fix_UpdateStrategy_v2.zip)
* Rolling upgrade is not working for keycloak in Openshift project redhat-rhoam-user-sso.  
* It cause downtime of SSO / keycloak - around 2 mins.
* Rolling upgrade is working correctly for keycloak in Openshift project redhat-rhoam-user-sso.  
* No downtime. Keycloak Pods are replaced to new version according to Rolling Update Strategy.
*  Create Openshift Dedicated Cluster
*  Configure Keycloak to have 3 replicas
```
$ pwd
.../integr8ly/integreatly-operator
```
```
$ INSTALLATION_TYPE=managed-api make cluster/prepare/local
$ …
```
> set keycloak Update Strategy to Rolling as default

- controllers/rhmi/rhmi_controller.go
Install the operator using the following steps:
`INSTALLATION_TYPE=managed-api make cluster/prepare `
`INSTALLATION_TYPE=managed-api IN_PROW=true make deploy/integreatly-rhmi-cr.yml`
`INSTALLATION_TYPE=managed-api make code/run `
Verify that the toSKU value is set on initial install.
> fix in the logic which was causing cr to not be udpated

- controllers/rhmi/rhmi_controller.go
- main.go
- pkg/metrics/metrics.go
- pkg/products/monitoring/dashboards/clusterResources.go
- pkg/products/monitoring/dashboards/endpointsDetailed.go
- pkg/products/monitoring/dashboards/endpointsReport.go
- pkg/products/monitoring/dashboards/endpointsSummary.go
- pkg/products/monitoring/dashboards/resourceByNamespace.go
- pkg/products/monitoring/dashboards/resourceByPod.go
Added a new metric for the currrent SKU configuration for RHOAM. The metric stores the current config, and if the config is changing what it is changing to. This metric also has an annotation in Grafana so when the SKU config is changed it can be seen in Grafana.
- Install RHOAM based on an image with new changes (ask me for image details)
- Run make cluster/deploy with IMAGE_FORMAT set to the image details I will supply
- Run make cluster/prepare/sku to create the sku secret in the operator namespace
- Change the SKU configuration
- Select a value to change the sku value to. Any value that 'name' is set to in the sku-config config map in the operator namespace is a valid entry.
- Run make cluster/prepare/sku again with a QUOTA set to the new sku value (5 should work fine).
- Verify that …
> SKU metric

- test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
the command 
```
oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq -r .spec.alertingEmailAddress
```
returns `cloud-services-qe-reporting@redhat.com`
looking at the rhmi cr this is expected
fix for test case
> update c05b alerting email address

- Dockerfile.functional
- Dockerfile.osde2e
- test/common/3Scale_user_promotion.go
- test/common/3scale_crudl.go
- test/common/3scale_smtp.go
- test/common/authdelay_first_broker_login.go
- test/common/tests.go
H03 & H07 can be flaky if B04 is ran beforehand. Likely cause that that by running B04 first, there can be a small window in which the dedicated admin users used in the tests are not promoted to 3scale admins before the tests is ran.
To fix this we should wait for the dedicated admin user to be an admin before running the tests H03 and H07. This should allow B04 to be run before these tests again and ideally the IDP tests can be run in a randomised fashion without any failures
Jira:
* https://issues.redhat.com/browse/MGDAPI-1439
* [idp_random.log](https://github.com/integr8ly/integreatly-operator/files/6319366/idp_random.log)
* [idp_ordered.log](https://github.com/integr8ly/integreatly-operator/files/6319368/idp_ordered.log)
* PR `e2e` and `rhoam-e2e` prow tests passed
* Checkout this …
> MGDAPI-1429 - H03 & H07 test - wait for dedicated admin user to become 3scale admin

- test/osde2e/pre-test.go
Updated useClusterStorage in pre-test.go from true to false to better emulate a production environment.
- Access to a BYOC cluster with 2x c5.2xlarge nodes
- osde2e repo forked and cloned
- Generate a new integreatly-operator test-harness image with the changes from this PR and push to your quay repo with tag osde2e, alternatively you can use mine which is linked in the script below.
- Create an sh script in the root folder of your cloned osde2e repo with the following content:
```shell 
#!/usr/bin/env bash
make build
OSD_ENV="stage" \
CLUSTER_ID="Your BYOC cluster id" \
OCM_TOKEN="Your OCM Token" \
ADDON_IDS="managed-api-service" \
ADDON_PARAMETERS='{"managed-api-service":{"cidr-range": "10.1.0.0/26"}}' \
ADDON_TEST_HARNESSES="quay.io/jkiely/integreatly-operator-test-harness:osde2e" \ …
```
> MGDAPI-1463: Update OSDe2e useClusterStorage

- pkg/products/grafana/customerDashboard.go
With the addition of the dynamic sku configuration the idea of hard limits and soft limits are removed meaning relabeling the annotation to use limit.
Ticket:  https://issues.redhat.com/browse/MGDAPI-1602
You can check the change [here](https://grafana-route-redhat-rhoam-customer-monitoring-operator.apps.jd.i5vz.s1.devshift.org/d/66ab72e0d012aacf34f907be9d81cd9e/rate-limiting?orgId=1&refresh=1m) on my cluster. Log into `jd` and click the link.
- Install Rhoam on a cluster
- Go the the customer dashboard in grafana
- Go to grafana route exposed in *redhat-rhoam-customer-monitoring-operator*
- Go to customer dashboard in the rate limiting folder
- Verify that the annotation on the graph displays `Limit` and not `Hard-Limit`
> fix: Renamed label to use limit in customer dashboard

- controllers/namespacelabel/namespacelabel_controller.go
- pkg/products/cloudresources/reconciler.go
- pkg/resources/awsStrategyHelper.go
- pkg/resources/awsStrategyHelper_test.go
Add support for per instance aws config for Postgres and Redis in CRO. The motivation for this is initially to increate the NodeType on Redis for one of the ThreeScale instances. The changing of the node type is not included in the PR, rather the functionality to facilitate it. 
Essentially, the solution is to add a custom tier, using the existing production tier as a baseline before overriding selected properties. Adding new tiers to the redis and postgres resources types in cloud-resources-aws-strategies also required updating the _network entry containing the cidr value. 
- Create a 4 node CCS cluster 
- Pick a cidr range that does not overlap with the machine, service or pod cidr. Check the Networking tab in OCM. 
- Create a secret 
**NOTE:** The encoded value …
> add functionality for per instance aws tiers

- pkg/config/threescale.go
- test/common/3scale_smtp.go
- test/common/alerts_exist.go
- test/common/tests.go
Test changes related to https://issues.redhat.com/browse/MGDAPI-1488
H11 - Fixes
F08 - Removes for managed api
F05 - Fixes 
The e2e tests should pass and the rhoam-e2e tests will fail on A15 and A13 which are being address by @makslion in a sperate pr.
Install using the following commands
`INSTALLATION_TYPE=managed-api make cluster/prepare/local`
`INSTALLATION_TYPE=managed-api IN_PROW=true make deploy/integreatly-rhmi-cr.yml`
`INSTALLATION_TYPE=managed-api make code/run`
Wait for the installation to go complete
Run H11 with `INSTALLATION_TYPE=managed-api TEST=H11 make test/e2e/single` It should pass
Run  F05 with ` INSTALLATION_TYPE=managed-api TEST=F05 make test/e2e/single`
> remove check for alerts already removed

- pkg/products/grafana/reconciler.go
The PR removes references to a non-existent namespace from the grafana reconciler to fix an OLM Operator Pod Error.
**Related JIRA ticket:** https://issues.redhat.com/browse/INTLY-10561
- Install RHOAM using this PR branch.
- Confirm that the OLM operator pod is no longer logging the error: "no target CSV for namespace redhat-rhoam-customer-monitoring".
- Confirm that the customer grafana is still working as expected.
> Removed references to non-existent redhat-rhoam-customer-monitoring namespace

- test/common/deployment_types.go
Part of the 1488 JIRA
Fixed A13 and A15 tests to get replicas from CRs and compare them against a number of pods running on a cluster for products, configured by Quota 
1. ensure you have access to a cluster with RHOAM installed from a feature branch: log in to the cluster.
2. run the following commands in your terminal:
```
INSTALLATION_TYPE=managed-api TEST=A13 make test/e2e/single
INSTALLATION_TYPE=managed-api TEST=A14 make test/e2e/single
INSTALLATION_TYPE=managed-api TEST=A15 make test/e2e/single
```
> fixed A13 and A15 tests

- Makefile
- controllers/rhmi/rhmi_controller.go
- pkg/addon/quota.go
> Link to JIRA: https://issues.redhat.com/browse/MGDAPI-1620
This is a temporal solution to include the quota configuration in the installation. Add the logic to create the quota ConfigMap at
operator startup, after the RHMI CR is created/discovered.
Run the operator locally, ensuring that the quota ConfigMap doesn't exist in the cluster, and ensure that the installation progresses and finishes successfully
1. Checkout this PR
2. Prepare the cluster
```sh
```
3. Ensure the ConfigMap doesn't exist
```sh
oc delete cm/quota-config-managed-api-service -n redhat-rhoam-operator
```
4. Run the operator
```sh
```
5. Verify that the ConfigMap is created and the installation progresses
```sh
oc get …
```
> MGDAPI-1620: Add creation of quota config map at operator startup

- pkg/products/threescale/reconciler.go
Update envoy proxy to latest image for health rating: https://catalog.redhat.com/software/containers/openshift-service-mesh/proxyv2-rhel8/5d2cda455a134672890f640a
e2e tests are sufficient
> Update envoy proxy image

- Makefile
Removed oc command from cluster/prepare/quota target in Makefile that deleted the quota secret before updating and re-creating the secret with a new quota value. Now the target just updates the existing secret which prevents the error that would occur because the operator was looking for a secret that no longer existed.
**JIRA Ticket:** https://issues.redhat.com/browse/MGDAPI-1592
- Install the RHOAM operator
- Run Make command to update quota value: `INSTALLATION_TYPE=managed-api QUOTA=20 make cluster/prepare/quota`
- Confirm that the addon-managed-api-service value in the addon-managed-api-service-parameters secret updates to 20.
- Confirm that there are no errors in the operator logs.
> Fix error in operator logs when updating SKU from 1 to 20.

- .gitignore
- Makefile
- apis/v1alpha1/rhmi_types.go
- config/manager/manager.yaml
- controllers/rhmi/rhmi_controller.go
- pkg/addon/quota.go
- test-cases/tests/installation/a34-verify-quota-values.md
- test/common/tests.go
Adding an env to handle cases where the user is upgrading from lower versions.
Setting the default to 20
Install from 1.5.0 tag -> using all the fancy bundling stuff
Verify there is no QUOTA env in the rhmi-operator pod
Verify there is no quota or toquota entry in the rhmi cr.
Verify there is no rhoam_quota metric in prometheus
Verify that there is no QUOTA env and no reference to toQuota or Quota in the cr.
upgrade to this branch -> using all the fancy bundling stuff
verify that the QUOTA value is present in the deployment/pod and has the value 20. 
Verify that cr now has toQuota: 20 or Quota: 20 depending on how long you wait.
Verify there is a rhoam_quota metric in prometheus
Install from this branch using 
`INSTALLATION_TYPE=managed-api make cluster/prepare/local` …
> add QUOTA env to operator

- Makefile
- config/samples/integreatly-rhmi-cr.yaml
Removed the IN_PROW annotation from the RHMI CR sample and removed reference to IN_PROW from Makefile because it wont be needed after the SKU work is completed.
**JIRA Ticket:** https://issues.redhat.com/browse/MGDAPI-1472
- Run the relevant make command: `make deploy/integreatly-rhmi-cr.yml`
- Confirm that the generated sample, config/samples/integreatly-rhmi-cr.yml, doesn't have the in_prow annotation
> Remove the IN_PROW annotation from RHMI sample

- pkg/products/grafana/customerDashboard.go
- pkg/products/grafana/reconciler.go
- pkg/resources/quota/product_config_moq.go
- pkg/resources/quota/quota.go
Add active quota to rate limit graph
Run t he installation
`INSTALLATION_TYPE=managed-api make cluster/prepare/local`
`INSTALLATION_TYPE=managed-api IN_PROW=true make deploy/integreatly-rhmi-cr.yml`
`INSTALLATION_TYPE=managed-api make code/run`
Let the installation complete
Verify that the text `Active Quota - 1 Million Per Day - Rate Limit - 694 per minute` appears on the dashboard under the graph -> see image below.
Update the quota
`INSTALLATION_TYPE=managed-api DEV_QUOTA="20" make cluster/prepare/quota`
Wait for the quota to update, aka the install to go complete again
Recheck the graph, the text should be -> `Active Quota - 20 Million Per Day`
Rinse & Repeat for all quotas if the desire takes you.
> add active sku to grafana

- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- pkg/products/monitoring/templateHelper.go
- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
- templates/monitoring/alertmanager/alertmanager-email-config.tmpl
The PR make changes to add a custom alertmanager go template (as a second data item in the `alertmanager-application-monitoring` secret). The new custom go template is aiming to enhance the pre-existing email configuration.
**Related JIRA ticket:**  https://issues.redhat.com/browse/MGDAPI-1580
**Files updated:**
- `pkg/products/monitoring/reconciler.go`
- `pkg/products/monitoring/reconciler_test.go`
- `pkg/products/monitoring/templateHelper.go`
- `templates/monitoring/alertmanager/alertmanager-email-config.tmpl` ~ **(New alertmanager custom go template)**
- `templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml` 
- Install `RHOAM` using this PR branch.
- Verify the following fields in the alertmanager config:
-  email configs: 
- `Subject: '{{template …
> Add custom alertmanager go template to enhance email config

- .ci-operator.yaml
- Dockerfile
- Dockerfile.functional
- Dockerfile.osde2e
- Makefile
- README.md
- go.mod
- go.sum
- make/functional.mk
- make/osde2e.mk
- openshift-ci/Dockerfile.tools
- vendor/modules.txt
This is the feature branch that was used to check the configure for openshift/release and integr8ly/integreatly-operator for the goLang version bump.  The e2e will fail due to the change in the `docker.tools` file being required in the master branch to update the goLang version of the testing root images. 
The version bump can be seen in this closed PR https://github.com/integr8ly/integreatly-operator/pull/1694
**Jira:** https://issues.redhat.com/browse/MGDAPI-1355
> Mgdapi 1355  - Update Go version

- pkg/resources/backup.go
Current pull policy on the integreatly operator is "Always". Set to "IfNotPresent" to mitigate against the risk of quay being down
See JIRA: https://issues.redhat.com/browse/MGDAPI-1473
Install RHMI from this branch
Check the YAML on the Cronjobs in ns redhat-rhmi-amq-online for imagePullPolicy: IfNotPresent
Modify the cron time in the YAML 
Verify a new job runs as the specified time
Verify that the IfNotPresent is set in the pod yaml
Verify the the image pulls successfully and runs.
> set image pull policy to IfNotPresent

- pkg/products/threescale/prometheusRules.go
Closes https://issues.redhat.com/browse/MGDAPI-1476
3scale operator endpoint down alert was not triggering correctly, this should now be fixed.
- [ :heavy_check_mark:] Bug fix (non-breaking change which fixes an issue)
1. Install RHOAM onto a cluster locally using this branch.
2. Scale the 3scale operator deployment to zero by navigating to workloads -> deployments in the redhat-rhoam-3scale-operator namespace.
3. Verify that the alert fires in Prometheus after 5 mins.
4. Scale the operator back up and verify that the alert stops firing.
> MGDAPI-1476 Update 3scale operator alert so that it triggers correctly when down

- pkg/products/monitoring/prometheusRules.go
- pkg/products/monitoring/reconciler.go
- pkg/resources/prometheusRules.go
- test/common/alerts_exist.go
MiddlewareMonitoringPodCount alert (serverity = warning) are firing during installation and gets resolved in about 15 minutes. It was decided to remove the alert as it has no value for an SRE team rather then fixing it. 
rate-limit-soft-limits Prometheus rule was removed from creation as part of 1.6.0, but we newer ensured that this alert will not be present on a cluster while upgrading from 1.5.0 to 1.6.0, so it stayed on a cluster.
1. Ensure you have a cluster with 'ksm-monitoring-alerts" PrometheusRule [present](https://i.imgur.com/ZLhHLE0.png) and with "rate-limit-soft-limits" (you can run master of 1.5.0 against a cluster to obtain those) 
2. Run the reconciler from this PR 
3. Verify that the PrometheusRule CRs were [removed](https://i.imgur.com/QU70t5p.png) 
Optional step: grub a …
> removed "ksm-monitoring-arelts" and "rate-limit-soft-limits" alerts

- test/functional/suite_test.go
- test/utils/utils.go
This allows the reading of a `TEST_PREFIX` environment variable in a testing container. The variable is passed in by the nightly pipelines.
Not setting the variable has no affect on the naming on the junit or test suite.
**Jira:** https://issues.redhat.com/browse/MGDAPI-1593
Pipeline results with variable set: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Playground/job/Playground-jfitzpat/job/rhoam-upgrade-hf/2/artifact/results/integreatly-operator-test/results/
Pipeline results with not variable set: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Playground/job/Playground-jfitzpat/job/rhoam-upgrade-hf/1/artifact/results/integreatly-operator-test/results/
> Added the option to set prefixes to the test suites and junt files.

- scripts/ec2_deploy_teardown/deployEC2.sh
Removed the filter from the Getting image section of deployEC2.sh.  It is set as true as default and means we cannot use private images we create.
> Removed the filter for AMI public image

- scripts/patch-image-csv.sh
helper script that  during addon flow
- patches csv with a developer image 
- patches rhmi cr with useClusterStorage
- build/push a development image e.g.
```bash
ORG=austincunningham OLM_TYPE=managed-api-service INSTALLATION_TYPE=managed-api make image/build
ORG=austincunningham OLM_TYPE=managed-api-service INSTALLATION_TYPE=managed-api make image/push
```
- export the vars of the script e.g.
```bash
export VERSION=v1.6.0
export ADDON_VERSION=v1.6.0
export ORG=austincunningham
```
- run the script (need to be logged in to oc for the cluster)
- Install RHOAM via the addon flow
```bash
./patch-image-csv.sh
clusterserviceversion.operators.coreos.com/managed-api-service.v1.6.0 patched
clusterserviceversion.operators.coreos.com/managed-api-service.v1.6.0 patched
Verificaton the CSV has been …
```
> Add script to patch the csv with dev image and rhmi cr useClusterStorage during addon flow

- controllers/rhmi/prometheusRules.go
bug  see issue https://issues.redhat.com/browse/MGDAPI-1613
In production eng cluster rhoam_version returns two values
```
rhoam_version{endpoint="http-metrics",instance="10.128.4.177:8383",job="rhmi-operator-metrics",namespace="redhat-rhoam-operator",pod="rhmi-operator-fbf89f99-j4wqc",service="rhmi-operator-metrics",stage="complete",version="1.3.0"}
rhoam_version{endpoint="http-metrics",instance="10.128.4.177:8383",job="rhoam-operator-metrics-service",namespace="redhat-rhoam-operator",pod="rhmi-operator-fbf89f99-j4wqc",service="rhoam-operator-metrics-service",stage="complete",version="1.3.0"}
```
This causes an error in **RHOAMUpgradeExpectedDurationExceeded** when **csv_succeeded** returns also
This change uses wildcard and the installationName  on the job to only return one value for …
> MGDAPI-1613 Fix RHOAMUpgradeExpectedDurationExceeded so it doesnt throw many-to-one error

- controllers/rhmi/prometheusRules.go
- controllers/rhmi/rhmi_controller.go
Use of absent in the alert RhoamOperatorInstallDelayed can trigger if the metric is not present rather that the metric being in a certain state 
https://issues.redhat.com/browse/MGDAPI-1606
**Successful Installation**
- Deploy rhoam via  addon flow 
- patch the images in the csv
```bash
oc patch ClusterServiceVersion managed-api-service.v1.6.0 -n redhat-rhoam-operator --patch '{"metadata": {"annotations": {"containerImage": "quay.io/austincunningham/managed-api-service:v1.6.0" }}}' --type=merge
oc patch ClusterServiceVersion managed-api-service.v1.6.0 -n redhat-rhoam-operator --type='json' -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/0/image", "value":"quay.io/austincunningham/managed-api-service:v1.6.0"}]'
```
- patch the …
> MGDAPI-1606: Change the expression in RhoamOperatorInstallDelayed to no longer use absent

- pkg/products/threescale/reconciler.go
As we are rate limiting external requests to the 3scale backend listener any other managed 3scale components need to communicate with the backend listener via services.
1. Install the operator from this branch
2. When the installation completes, verify the system app deployment config and check if the `APICAST_BACKEND_ROOT_ENDPOINT` and `BACKEND_ROUTE` envvar are using the `service_endpoint`
> Changes 3scale system app to use service endpoint

- pkg/products/monitoring/dashboards/clusterResources.go
- pkg/products/monitoring/dashboards/endpointsDetailed.go
- pkg/products/monitoring/dashboards/endpointsReport.go
- pkg/products/monitoring/dashboards/endpointsSummary.go
- pkg/products/monitoring/dashboards/resourceByNamespace.go
- pkg/products/monitoring/dashboards/resourceByPod.go
Dynamically configured dashboards for: 
- Endpoint Report
- Endpoint Detailed
- Endpoint Summary 
- Resource usage by namespace
- Resource usage by pod
- Resource usage for cluster
depending on an installation type will include (for rhoam) quota details. 
Complete verification includes a check of RHOAM to have working dashboards with Quota and RHMI to have dashboards without quota information. 
1. Run reconciler from this PR. 
2. Navigate to the Grafana dashboard: Networking -> Routes -> grafana-route in `redhat-rhoam-middleware-monitoring-operator` namespace. 
3. Open dashboards, mentioned in the description. 
4. Validate dashboards wasn't broken bu this PR. 
1. Run reconciler from this PR 
2. Navigate to the Grafana dashboard: Networking -> Routes -> grafana-route in …
> removed quota from rhmi dashboards

- products/products.yaml
- scripts/prepare-release.sh
Addresses https://issues.redhat.com/browse/MGDAPI-1807
Adding relatedImages to the RHOAM CSV for CVE scanning purposes. 
- From this branch run `SEMVER=2.0.0 OLM_TYPE=managed-api-service make release/prepare`
- Navigate to packagemanifest/managed-api-service/2.0.0 and verify that the CSV has the relatedImages set. 
- Compare the images from each of the products quay images to confirm that they are pointing to correct tag
- Install RHOAM via OLM using the newly generated bundle and confirm that this change has no effect on the installation
- Run  `SEMVER=2.0.0 OLM_TYPE=integreatly-operator make release/prepare` and confirm that the relatedImages are not present in the CSV for RHMI.
> add relatedImages to the RHOAM CSV

- pkg/config/monitoring.go
- pkg/products/monitoring/dashboards/errorBudgetBurnSLOAlerts.go
- pkg/products/monitoring/dashboardsHelper.go
This PR is reference from https://github.com/integr8ly/integreatly-operator/pull/1767
See approvals and review comments at https://github.com/integr8ly/integreatly-operator/pull/1767
Improve Dashboard for SSO Availability alerts for 5xx Errors
Jira https://issues.redhat.com/browse/MGDAPI-1610
New Dashboard created, and suggested for discussion.
Dashboard images please see in Jira, and also here:
https://drive.google.com/file/d/12MoVkwIvFG_LbdQpp9paFfpuqJIs9wrh/view?usp=sharing
https://drive.google.com/file/d/1MiVtIZRIxlnE8JDP1OdiZoWRbx1L4pPY/view?usp=sharing
> Dashboard for SSO Availability alerts for 5xx Errors - MGDAPI-1610

- controllers/rhmiconfig/helpers/update_status.go
- controllers/rhmiconfig/helpers/update_status_test.go
[JIRA](https://issues.redhat.com/browse/INTLY-10517)
Fix potential nil pointer exception in rhmi
This nil pointer has been thrown in production occasionally 
Running unit tests (update_status_test.go) sufficient.
> fix nil pointer issue 

- controllers/rhmi/prometheusRules.go
Update the upgradExpectedDurationExceeded alert to 60 minutes from 10 minutes
This is to accomodate for a longer upgrade in 1.8.0 where a forced upgrade of RDS engine version happens.
checkout master
install everything - check the prometheus rule has 10 mintues set in the cr and in the Openshift Prometheus
Stop the operator
check the prometheus rule has 60 minutes set in the cr and in the Openshift Prometheus.
> increase upgrade alert time to 60 minutes

- pkg/products/cloudresources/prometheusRules.go
- pkg/resources/metrics.go
change service references to operator-metrics-service to match change in CRO
JIRA: [MGDAPI-2095](https://issues.redhat.com/browse/MGDAPI-2095)
Install a CCS cluster and rhoam or rhmi 
The following modified Alerts are still valid:
**PostgresStorageWillFillIn4Hours**
Verify in prometheus that `cro_postgres_free_storage_average{job='operator-metrics-service'}` returns a value
**RedisMemoryUsageMaxIn4Hours**
Verify in prometheus that `cro_redis_memory_usage_percentage_average{job='operator-metrics-service'}` returns a value
**RHMICloudResourceOperatorMetricsServiceEndpointDown**
Verify in prometheus that `kube_endpoint_address_available{endpoint='operator-metrics-service'}` returns a value
> change service references to operator-metrics-service

- test/functional/aws_rds_resources_exist.go
- test/functional/suite_test.go
If useClusterStorage in RHMI CR is set to true, skip functional AWS tests. 
1. Obtain cluster with RHOAM installed and `useClusterStorage` set to `true` (true by default) 
2. Run following command:
```
INSTALLATION_TYPE=managed-api make test/functional
``` 
3. Observe tests getting skipped with a following message 
```
Aborting functional tests: "UseClusterStorage" is set to true. 
Please, run another testing suite or reinstall operator with "UseClusterStorage" set to false
```
Optional: 
- Reinstall cluster with `useClusterStorage` set to false and see functional tests being executed
> skip functional aws tests when useClusterStorage is true

- Dockerfile
- build/Dockerfile
change to ubi minimal base image to reduce possible attach surface and CVE respins
[JIRA](https://issues.redhat.com/browse/INTLY-10574)
Install RHMI and RHOAM 
After 3Scale installs delete one route and confirm it recovers.
Uninstall 
Verify during the uninstall a Silence Alert is created.
Verify Uninstall successful
> change to ubi minimal base image

- products/products.yaml
- scripts/prepare-release.sh
Adding images list and related images from components csv to annotation in RHOAM CSV
- run `OLM_TYPE=managed-api-service SEMVER=1.9.0 make release/prepare` and confirm that the the list of containerImages is generated in rhoam CSV metadata.annotations.
- run `OLM_TYPE=integreatly-operator SEMVER=3.0.0 make release/prepare` and make sure that containerImages are not found in newly generated CSV
> update prepare/release to list related images by sha

- pkg/addon/operator_run.go
- pkg/addon/parameters.go
- pkg/resources/k8s/k8sutil.go
- pkg/resources/k8s/objectQueries.go
- pkg/resources/k8sutil.go
- pkg/resources/marketplace/catalog_source_reconciler.go
- pkg/resources/marketplace/configmap_catalog_source_reconciler.go
- pkg/resources/marketplace/grpc_image_catalog_source_reconciler.go
- pkg/resources/marketplace/implicit_catalog_source_reconciler.go
- pkg/resources/marketplace/manager.go
- pkg/resources/marketplace/products_installation.go
- pkg/resources/objectQueries.go
- pkg/resources/rhmi.go
- pkg/resources/rhmi/rhmi.go
- products/installation.yaml
> Link to JIRA: https://issues.redhat.com/browse/MGDAPI-2022
Extend product operator installation declaration file to support a new type by specifying the `implicit` `installFrom` value.
When using this value for a product, the operator won't attempt to reconcile a new CatalogSource for it, but instead will assume that the CatalogSource that provided the RHOAM operator also provides this product. Therefore, it will attempt to locate this CatalogSource and create a Subscription for the product using that CatalogSource and the specified `package` and `channel`
Refactor some logic in the `resources` package to avoid cyclic dependencies
In order to verify this change, we need to create an index that includes both bundles for RHOAM and for at least one of the product operators that are …
> MGDAPI-2022: Support "implicit" product operator installation

- test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
- test/common/namespace_restoration.go
* Update J03 test case command
* Update J03 to include removed finalizers from `EnvoyConfigRevision` resources that is preventing `redhat-rhoam-3scale` namespace from being deleted successfully
[test-results.log](https://github.com/integr8ly/integreatly-operator/files/6671724/test-results.log)
* Installation RHOAM from master
```
make cluster/prepare/local 
make code/run
```
* Run test 
```
DESTRUCTIVE=true INSTALLATION_TYPE=managed-api TEST="J03" make test/e2e/single
```
* Verify test passes successfully
> update test case and test for J03

- test-cases/tools/cmd/jira.ts
When there are destructive tasks in a test run link all non-destructive tasks as blockers
my changes were tested on [This JIRA](https://issues.redhat.com/browse/MGDAPI-2000) with `./tools.sh jira --epic MGDAPI-2000 --product rhoam --environment osd-fresh-install` command and changing a few non-destructive issues in the `osd-fresh-install` environment to destructive to verify that destructive issues are being chained together properly
> Added linking of destructive tasks as blockers in JIRA

- scripts/prepare-release.sh
Fixes issue with building bundles when using csv generated by the prepare/release script
- create a new rhoam release and confirm that a multiline string in json pattern is created for containerImages in metadata.annotation of rhoam CSV
- try creating a bundle and index using following guide lines (it should not fail) 
https://github.com/RHCloudServices/integreatly-help/blob/master/guides/olm/installing-rhmi-bundle-format.md
> Fix prep/release script

- scripts/prepare-release.sh
The release script updates the version in `version.go` by replacing the whole version string and thereby removing any whitespaces provided by `gofmt`
* https://github.com/integr8ly/integreatly-operator/blob/master/scripts/prepare-release.sh#L68-L75
This works for RHOAM but not for RHMI as RHOAM version string is longer with no extra whitespaces and so doesn't not fail the `prow` code format check when the release is generated.
* https://github.com/integr8ly/integreatly-operator/blob/master/version/version.go#L16-L17
To fix this, the code is formated at the end of the release script 
* Run `OLM_TYPE=integreatly-operator SEMVER=2.10.0 make release/prepare`
* Verify version string whitespace is removed and unformated in `version/version.go`
* Checkout this banch
* Run …
> MGDAPI-1846 - format code as part of release script

- manifests/integreatly-3scale/0.7.0/3scale-operator.v0.7.0.clusterserviceversion.yaml
MGDAPI-2177
- container image bump
- install rhoam locally
- confirm 3scale is up and running and check the following containers to see if they have the correct images
- any apicast-production pod, apicast-production container has this image  registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:fd22a4f059c691109e098dc47f4a44acecd66e069c89af9eb9630df65074a88d
> MGDAPI-2177: bump 3scale-amp2/apicast-gateway-rhel8 container image

- manifests/integreatly-3scale/0.7.0/3scale-operator.v0.7.0.clusterserviceversion.yaml
MGDAPI-2236 update 3scale-operator image
3scale operator image update
- install rhoam locally
- confirm 3scale is up and running and check the following containers to see if they have the correct image
- in the redhat-rhoam-3scale-operator namespace the operator pod and the 3scale-operator container has the following sha sha256:5063f838a8a7649626231edabf47debc3d4e36f69de37675d126b19fdbeb69c3 in the ui
```bash
kubectl get pods --all-namespaces -o=jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' | sort | grep 3scale-rhel7-operator
3scale-operator-6b4849b6f8-gtv65:       registry.redhat.io/3scale-amp2/3scale-rhel7-operator@sha256:5063f838a8a7649626231edabf47debc3d4e36f69de37675d126b19fdbeb69c3,
```
> *NOTE*: …
> MGDAPI-2236: update 3scale-operator image

- manifests/integreatly-3scale/0.7.0/3scale-operator.v0.7.0.clusterserviceversion.yaml
MGDAPI-2247 update postgresql-10-rhel7 image
container image bump
- install rhoam locally
- confirm 3scale is up and running and check the following containers to see if they have the correct images
- 3scale, zync-database pod and the postgresql container is in the ui sha256:ba7713d570c058e61bae1adc1591b1fe834d45fe5e1fba70721c93f4fd64d535
```bash
kubectl get pods --all-namespaces -o=jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' | sort | grep postgres
zync-database-2-klvkw:  registry.redhat.io/rhscl/postgresql-10-rhel7@sha256:ba7713d570c058e61bae1adc1591b1fe834d45fe5e1fba70721c93f4fd64d535, 
```
>*NOTE*: rhoam upgrade scenario doesn't change the image
> MGDAPI-2247: update postgresql-10-rhel7 image

- Makefile
- config/manager/manager.yaml
- config/secrets/quota-secret.yaml
- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/rhmi_controller.go
- pkg/addon/quota.go
- pkg/metrics/metrics.go
- pkg/products/grafana/customerDashboard.go
- pkg/products/monitoring/dashboards/clusterResources.go
- pkg/products/monitoring/dashboards/endpointsDetailed.go
- pkg/products/monitoring/dashboards/endpointsReport.go
- pkg/products/monitoring/dashboards/endpointsSummary.go
- pkg/products/monitoring/dashboards/errorBudgetBurnSLOAlerts.go
- pkg/products/monitoring/dashboards/resourceByNamespace.go
- pkg/products/monitoring/dashboards/resourceByPod.go
- pkg/resources/quota/quota.go
- pkg/resources/quota/quota_test.go
- test/common/quota.go
JIRA -> https://issues.redhat.com/browse/MGDAPI-2258
Changes in commit 1
- Remove stage from metric and dashboards
- Add param to config map to match new per 100k values 
- Update the env in the deployment config for 20m default
- Update to how isUpdated is being set in the bootstrap section
- Update e2e tests with new configuration
Verification does not require ccs cluster
On a fresh cluster
git checkout this branch
`INSTALLATION_TYPE=managed-api make cluster/prepare`
`INSTALLATION_TYPE=managed-api make code/run`
check the status of the installation `oc get rhmi rhoam -n redhat-rhoam-operator -o yaml | yq r - status`
The quota value should be set to `100K`
Verify that the grafana Dashboard gets updated as expected by navigating to the customer dashboard using the
`open "https://$(oc get …
> 100k quota

- controllers/rhmi/bootstrapReconciler.go
remove prefix from RoutingSubdomain. router-default. was added as a prefix to the canonical router hostname. 
We use this field to create 3Scale and OAuth routes. Remove prefix to revert to a known working state
End to end tests are sufficient here.
> remove prefix from RoutingSubdomain

- Makefile
- test/common/alerts_exist.go
- test/common/alerts_firing.go
- test/common/cro_cr_success.go
- test/common/dashboards_data.go
- test/common/dashboards_exist.go
- test/common/deployment_types.go
- test/common/integreatly_stages.go
- test/common/monitoringspec.go
- test/common/namespace_created.go
- test/common/namespace_restoration.go
- test/common/operand_versions.go
- test/common/operator_versions.go
- test/common/priority_validate.go
- test/common/pvc_validate.go
- test/common/routes_exist.go
- test/common/subscription_install_plan.go
- test/common/tests.go
- test/common/user_dedicated_admin_permissions.go
- test/common/user_rhmi_developer_permissions.go
- test/common/verify_metrics_scrapped.go
- test/e2e/suite_test.go
- test/functional/aws_s3_resources_exist.go
- test/functional/aws_shared_functions.go
- test/osde2e/pre-test.go
Update existing tests so they could run with the multitenant rhoam installation. Additionally, add multitenant installation type to the array of suitable install typoes for tests that were used on rhoam. Also, added new make command `make test/e2e/multitenant-rhoam/prow`
- watch e2e and multitenant e2e tests succeed on this PR 
Currently, this PR in progress due to the [new installation type](https://github.com/integr8ly/integreatly-operator/pull/1988) being in review. Once it merged, I'll rebase against master and would remove the "WIP". But code could be reviewed anyway,
> Ensure e2e tests cater for the multitenant rhoam

- controllers/rhmi/bootstrapReconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/resources/user/userHelper.go
Add Support for Multi Tenant User SSO
Install RHOAM with this branch
Immediately after rhmi CR creation, stop the operator and change type from "managed-api" to "multitenant-managed-api". 
Restart Operator
Add the testing-idp after RHSSO installed: 
``` NUM_REGULAR_USER=10 NUM_ADMIN=5 DEDICATED_ADMIN_PASSWORD=Password1 PASSWORD=Password1 ./scripts/setup-sso-idp.sh ```
Create an "sre-admin" user in the testing-idp and follow this [SOP](https://github.com/RHCloudServices/integreatly-help/blob/master/sops/2.x/cssre_info/info_cssre_user_sso_access_master_admin_console_2x.asciidoc) to get admin access to user-sso. NOTE: Do not log in prematurely to user-sso (as mentioned in the SOP)!!
Create dev sandbox user namespaces
``` oc new-project test-user01-dev && oc new-project test-user02-dev ``` …
> Add Support for Multi Tenant User SSO

- controllers/rhmi/bootstrapReconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/resources/user/userHelper.go
sanitise tentant user names before resources are created
Verify in the same way as [PR 2011](https://github.com/integr8ly/integreatly-operator/pull/2011) except use "invalid usernames".
Create users TEST_USER_1 and TEST_USER_2 in the testing IDP and use them in place of test-user01 and test-user02
> sanitise tentant user names

- templates/monitoring/alertmanager/alertmanager-email-config.tmpl
There is a difficulty in Gmail filtering due to spaces in Subject.
In this PR we are replacing " "(spaces) with | (Pipes) for easy filtering.
**CSSRE Jira**: https://issues.redhat.com/browse/CSSRE-1572  
**MGDAPI Jira**: https://issues.redhat.com/browse/MGDAPI-2368
> fix: Updating alerting email subject for easy email filtering.

- pkg/config/threescale.go
- pkg/products/grafana/customerDashboard.go
- pkg/products/marin3r/apiUsagePrometheusRules.go
- pkg/products/marin3r/prometheusRules.go
- pkg/products/marin3r/rateLimitService.go
- pkg/products/marin3r/rateLimitService_test.go
- pkg/products/marin3r/reconciler.go
- pkg/products/marin3r/rejectedRequestsPrometheusRules.go
- test-cases/tests/alerts/c18-validate-api-usage-alerts.md
- test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
- test-cases/tests/products/h28-validate-self-managed-apicast-rate-limiting.md
- test/common/alerts_exist.go
- test/common/deployment_types.go
- test/common/monitoringspec.go
- test/common/quota.go
- test/common/verify_metrics_scrapped.go
Migration to use Limitador as rate limiting solution
Jira:
* https://issues.redhat.com/browse/MGDAPI-2351
* Install RHOAM from master
* Run from this branch
* Ensure installation completes successfully and rate limiting solution is migrated 
* Rate limit deployment in `redhat-rhoam-marin3r` is using limitador image
* StatsD deployment is deleted in `redhat-rhoam-marin3r`
* StatsD service is deleted in `redhat-rhoam-marin3r`
* Sign into 3scale and complete tutorial api 
* Curl the tutorial endpoint to ensure rate limiting is still functional
```
i=0
while [ $i -le 75 ] 
do 
curl "<3scale_api>" -v  
echo Number: $i
((i++))
done
```
* Deploy workload web app
* https://github.com/integr8ly/workload-web-app#rhoam-clusters
* Check the customer grafana …
> MGDAPI - 2351 - Limitador

- pkg/products/marin3r/rateLimitService.go
- pkg/products/threescale/envoyconfig.go
- pkg/products/threescale/reconciler.go
This PR covers adding rate limiting configuration for multitenant Managed Api Service. 
Updated are:
1. Envoy configuration - additional lua filter that adds an extra header
2. Descriptors - an additional descriptor that allows rate limiting per tenant
3. Config map - additional config map that allows for manual setting of the rate limit per tenant or (by default) sets rate limit per tenant based on current quota / 3k users.
Verification will be required on both RHOAM and RHOAM multitenant
- prepare 6 m5xlarge cluster
- from this branch run `INSTALLATION_TYPE=multitenant-managed-api make cluster/prepare/local`
- run `DEV_QUOTA=1 INSTALLATION_TYPE=multitenant-managed-api make code/run`
- Wait for RHOAM to install (verify by looking RHMI CR that it is installed)
- Follow the documentation …
> Add multitenant rate limiting

- test-cases/tests/alerts/c18-validate-api-usage-alerts.md
Minor fix of typos discovered during C18 test case
* Quota of 1 million is represented by [10](https://github.com/integr8ly/integreatly-operator/blob/master/pkg/addon/quota.go#L312) 
* Make command without the specification of Installation type default to `managed` that lead to [this](https://github.com/integr8ly/integreatly-operator/blob/master/envs/managed.env#L4) envs being used. In the case of the RHOAM, it uses wrong namespace 
* Missing closing bracket after the Prometheus query
> fixing typos

- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- test-cases/tests/alerts/c19-validate-creation-of-invalid-username-triggers-alert.md
- test/common/3scale_crudl.go
- test/common/alerts_invalid_username.go
- test/common/testing_idp.go
- test/common/tests.go
- test/functional/suite_test.go
* Fix installation blocked bug when 3scale user could not be found
* e2e test for c19 test case
Jira:
* https://issues.redhat.com/browse/MGDAPI-1260
* Install from this branch by deployment operator image to cluster (required for fix and to properly expose metrics from operator to cluster)
* Update to use image built from this branch and apply to cluster
```
export INSTALLATION_TYPE=managed-api 
cd config/manager
kustomize edit set image controller=quay.io/kevfan/managed-api-service:vMGDAPI-1260
kustomize build ../redhat-rhoam | oc create -f - 
cd -
```
* Once installation completes,  run C19 test and ensure it passes
```
INSTALLATION_TYPE=managed-api BYPASS_STORAGE_TYPE_CHECK=true TEST="C19" make test/e2e/single 
```
> MGDAPI-1260 - C19 e2e Test

- Makefile
- pkg/products/monitoring/reconciler.go
- pkg/products/threescale/reconciler.go
- test/common/alerts_mechanism.go
- test/common/sendgrid_credentials_valid.go
- test/common/types.go
- test/resources/util.go
There is a issue when creating new tenant accounts in 3scale and smtp is not configured correctly the 3scale API create the tenant account but returns an error, to avoid this from happening the smtp secret needs to be created with empty values so the 3scale API doesn't attempt to send an email after the creation of the new tenant account.
https://issues.redhat.com/browse/MGDAPI-2489
1) Install the operator from this branch INSTALLATION_TYPE=multitenant-managed-api make cluster/prepare/local && INSTALLATION_TYPE=multitenant-managed-api make code/run
2) Go to the 3scale API under the master account and create a new tenant account or run this curl command below
```
curl -v  -X POST "https://master.<CLUSTER-URL>/master/api/providers.xml" -d …
```
> MGDAPI-2489 - 3scale api error

- apis/v1alpha1/rhmi_types.go
- manifests/integreatly-unifiedpush/0.5.2/push_v1alpha1_unifiedpushserver_crd.yaml
- manifests/integreatly-unifiedpush/0.5.2/unifiedpush-operator.v0.5.2.clusterserviceversion.yaml
- manifests/integreatly-unifiedpush/unifiedpush-operator.package.yaml
- products/products.yaml
https://issues.redhat.com/browse/INTLY-10785
Bumping UPS operator to include the updated grafana-operator dependency:
https://github.com/aerogear/unifiedpush-operator/pull/109
Install RHMI 2.9.1 via a index+bundle.
Start an API proxy `oc proxy --port 1234`
Update the namespace part("redhat-rhmi-ups") in the command below and execute it:
```
curl -s localhost:1234/apis/integreatly.org/v1alpha1/namespaces/redhat-rhmi-ups/grafanadashboards/unifiedpushserver-dashboard/status -XPATCH  -H "Accept: application/json" -H "Content-Type: application/merge-patch+json" -d '{"status": {"hash": "3de09b7d992c2cdac355954dd6c3f2f8", "id": 15, "message": "success", "phase": "reconciling", "slug": "unifiedpush-server", "uid": "ZckQWaPMk"}}'
```
This will add legacy status fields to the GrafanaDashboard CR. …
> Update unifiedpush-operator to 0.5.2

- scripts/prepare-release.sh
Fix a bug in prepare-release.sh script.
This is the error message that was received:
> 10:48:33  Update CSV for release 2.9.3-rc1 to be 'serviceAffecting: true'
> 10:48:33  Error: stat packagemanifests/integreatly-operator/2.9.3/integreatly-operator.clusterserviceversion.yaml}: no such file or directory
> 10:48:33  Error: exit status 1
Generate a new service affecting release to and see that the script finishes successfully, and "serviceAffecting" annotation is set as expected.
> Remove extra char in prepare-release.sh

- test-cases/tests/alerts/c19-validate-creation-of-invalid-username-triggers-alert.md
- test/common/alerts_invalid_username.go
- test/common/tests.go
https://issues.redhat.com/browse/MGDAPI-1260
Running H11 before C19 can cause C19 to timeout waiting for alert to fire (seen in nightly runs)
The reason for this is that at the end of H11, the smtp secret is [restored](https://github.com/integr8ly/integreatly-operator/blob/master/test/common/3scale_smtp.go#L102-L106) and this causes 3scale deployments to be [rescaled](https://github.com/integr8ly/integreatly-operator/blob/62da48db2fbb22bcbb61e63338a9fbc7277ebef1/pkg/products/threescale/reconciler.go#L522-L532). However, C19 will imediately run, but at 3scale reconcile, it will wait until these deployments are fully scaled before it can reach the code for reconciling openshift users. This can cause a timeout on C19 for waiting the alert to fire due to this.
Quickest fix for this is running …
> fix: run C19 before H11

- test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
- test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
Updates to A30 and H23 test cases.
A30 updates are due to the fact that the OCM UI has changed recently so cluster creation flow differs.
H23 is due to Limitador work - so CM name and few steps differ.
Eye review only. Optionally you can follow A30 (cluster creation flow) and H23.
> Updates to A30 and H23 test cases

- pkg/products/threescale/clients_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/three_scale_client.go
- pkg/products/threescale/three_scale_moq.go
- pkg/resources/password.go
[MGDAPI-2490](https://issues.redhat.com/browse/MGDAPI-2490) 
Generate a random password for the 3scale log in for multi tenant users.
Store tenant passwords in a secret 
Install a multi-tenant RHOAM `INSTALLATION_TYPE=multitenant-managed-api make code/run` based on this PR
Install the testing-idp with name "rhd"
Log into OpenShift as test-user01 and test-user02
Wait for 3scale to reconcile
Verify that test-user01 and test-user02 admin routes are created under the 3Scale namespace
Verify that secret, tenant-account-passwords, is also created under the 3scale namespace
Verify that 2 password exist in the secret for both users
Log into 3Scale as test-user01 and test-user02 with their respective routes and password.
Delete user cr for test-user01 and its related identity
Wait for 3Scale to …
> Mgdapi 2490 random password for 3Scale tenants

- test-cases/tests/alerts/c19-validate-creation-of-invalid-username-triggers-alert.md
- test/common/alerts_invalid_username.go
https://issues.redhat.com/browse/MGDAPI-1260
C19 is failing on nightly runs which looks to be only on fresh installs as subsequents runs succeed consistently. For now, skip the test if it fails at the flaky stage and include command to run manually in test case
This will be investigated in a follow up ticket:
* https://issues.redhat.com/browse/MGDAPI-2581
N/A
> test: mark c19 flaky for nightly runs

- scripts/prepare-release.sh
https://issues.redhat.com/browse/MGDAPI-2579
Wrong quotes prevent setting container image in the CSV.
Run `OLM_TYPE=managed-api-service SEMVER=1.99.0 make release/prepare`
In the newly generated CSV file (packagemanifests/managed-api-service/1.99.0/managed-api-service.clusterserviceversion.yaml) check:
- `.metadata.annotations.containerImage` 
- `.spec.instal.spec.deployments[0].spec.template.spec.containers[0].image`
both of these should have correct image - `quay.io/integreatly/managed-api-service:rhoam-v1.99.0`
_Note:_ you may see the following error, but in the context of this PR it can be ignored. It will be fixed in MGDAPI-2572.
```
Adding related images to the CSV
./scripts/prepare-release.sh: line 232: -1: substring expression < 0
make: *** [release/prepare] Error 1
```
> Fix prepare-release.sh - wrong quotes prevent setting container image

- scripts/prepare-release.sh
[MGDAPI-2572](https://github.com/Patryk-Stefanski/integreatly-operator/tree/MGDAPI-2572)
containerImages generation during prepare release was generated in YAML format due to yq bump, this caused the validation of bundles to fail.containerImages are now  generated in JSON format and pass validation.
1. Check out this branch and make sure you have a  `managed-api-service-bundle` repo in your quay org.
2. Generate CSV :  `ORG=<your org>  OLM_TYPE=managed-api-service SEMVER=<release version> ./scripts/prepare-release.sh`
3. `cd` to manifests directory for the release version.
4. Generate bundle : `opm alpha bundle generate -d . --channels alpha --package managed-api-service --output-dir bundle --default alpha`
5. Build and push the image : 
`docker build -f bundle.Dockerfile -t quay.io/<quay …
> fix CSV generation for containerImages

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssocommon/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
https://issues.redhat.com/browse/MGDAPI-1584
For major and minor version upgrades on keycloak, use the recreate strategy before upgrading to the new version.  Once the upgrade completes revert back to use rolling strategy.
If a patch version is detected, rolling strategy is kept and used
* Checkout branch
```
export INSTALLATION_TYPE=managed-api 
make code/run
```
* Once installed, verify `rolling` strategy is used in KeyCloak CRs for RHSSO and User SSO
```
oc get keycloak rhsso -n redhat-rhoam-rhsso -o json | jq '.spec.migration'
oc get keycloak rhssouser -n redhat-rhoam-user-sso -o json | jq '.spec.migration'
```
* Stop the operator
* Create a 15.0.0 directory in manfiests/integreatly-rhsso
* Copy manifests from Keycloak github to this …
> MGDAPI - 1584 - feat: keycloak migration strategy dependant on release type

- templates/monitoring/alertmanager/alertmanager-email-config.tmpl
**Related Jira:** [https://issues.redhat.com/browse/MGDAPI-2484](https://issues.redhat.com/browse/MGDAPI-2484)
Currently, the way the custom email subject template ["__intlysubject"](https://github.com/integr8ly/integreatly-operator/blob/master/templates/monitoring/alertmanager/alertmanager-email-config.tmpl) is written, it produces unwanted tabs & extra whitespaces on the PagerDuty receiver end, which breaks the CI/CD pipelines (used by CS-SRE teams) consuming Pagerduty incident webhooks.
Before PR changes, the title looks like ~
- improve the custom email template ( [__intlysubject](https://github.com/integr8ly/integreatly-operator/blob/master/templates/monitoring/alertmanager/alertmanager-email-config.tmpl)) to remove white-spaces & indentation when the template are resolved to actual …
> Fix alertmanager custom email template

- pkg/config/threescale.go
The A14 and F05 tests fails if using 1M quota. The reason is that due to mismatch in quota names the default value (3 replicas) is expected for apicast-production. But the actual value is two so the tests fails (since the actual is less than expected).
Assuming you have the RHOAM cluster ready just run the A14 and F05 tests. It is enough to do this for 100k, 1M and 50M quotas (other quotas has the same replicas as the default values so no real change here).
* change the quota via OCM
* oc login into the cluster
* clone this PR
* INSTALLATION_TYPE=managed-api TEST=A14 make test/e2e/single
* INSTALLATION_TYPE=managed-api TEST=F05 make test/e2e/single
Or maybe just check that the values matches the quota from rhoam RHMI CR would be sufficient.
> Fixed Quota name in 3scale.go

- controllers/rhmi/rhmi_controller.go
[MGDAPI-2559](https://issues.redhat.com/browse/MGDAPI-2559)  There was an issue when changing email to an empty string that wouldn't update the parameter in the rhoam cr.
Removed a check that stoped empty strings from being passed to rhoam cr. 
1. Check out this branch and run rhoam locally.
2. Add `notification-email: bWFpbEBleGFtcGxlLmNvbQ==` to yaml file in `addon-managed-api-service-parameters` .
3. Check that `alertingEmailAddress: mail@example.com `  is in the rhoam cr.
4. Change notification email to `notification-email: '' ` 
5. Check that  `alertingEmailAdress: ` is no longer in the rhoam cr.
> fix for updating empty email address

- products/installation-cpaas.yaml
The wrong image had been set for this field (operator image instead of the bundle image). Revert the change as we know now that the registry will be replaced for a valid one when building in OSBS
> Update 3scale bundle in installation-cpaas.yaml

- pkg/products/monitoring/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/threescale/reconciler.go
3 small JIRAs covered in this PR:
https://issues.redhat.com/browse/MGDAPI-2595
https://issues.redhat.com/browse/MGDAPI-2564
https://issues.redhat.com/browse/MGDAPI-2597
Install multi tenant RHOAM and the testing idp
```
INSTALLATION_TYPE=multitenant-managed-api make cluster/prepare/local
INSTALLATION_TYPE=multitenant-managed-api make code/run
NUM_REGULAR_USER=10 NUM_ADMIN=5 REALM_DISPLAY_NAME="DevSandbox" REALM="devsandbox" DEDICATED_ADMIN_PASSWORD=Password1 PASSWORD=Password1 ./scripts/setup-sso-idp.sh
```
Create 2 tenants by logging test-user01 and test-user02 into OpenShift
Wait for tenants to reconcile
Create "Sandbox Namespaces for tenants"
```
oc new-project test-user01-dev
oc adm policy add-role-to-user admin test-user01 -n test-user01-dev
oc new-project test-user02-dev
oc adm …
```
> Mgdapi 2564 alert config

- config/redhat-sandbox/kustomization.yaml
- config/redhat-sandbox/manager_auth_proxy_patch.yaml
- config/redhat-sandbox/manager_env_installation_type.yaml
- config/redhat-sandbox/manager_webhook_patch.yaml
- config/redhat-sandbox/webhookcainjection_patch.yaml
n/a
When installing rhoam via `make cluster/deploy` operator would not be deployed due to missing configuration
From this branch run:
`INSTALLATION_TYPE=multitenant-managed-api USE_CLUSTER_STORAGE=true INSTALLATION_TYPE=multitenant-managed-api IMAGE_FORMAT=quay.io/integreatly/managed-api-service:master make cluster/deploy` and confirm that RHMI operator is running on the cluster as well as multitenant installation completes successfully.
> add config for sandbox install type

- test/common/alerts_invalid_username.go
https://issues.redhat.com/browse/MGDAPI-2581
C19 consistently fails on nightly runs due to a timeout waiting for `ThreeScaleUserCreationFailed` to fire.
The current theory to why this happens is that for some reason when `alongusernamethatisabovefourtycharacterslong2` logs into openshift, the associated User CR is never created, and so causes the alert to never fire as the user hasn't truly logged in.
This is supported by the fact that  in the operator logs, the user controller never picks up the `alongusernamethatisabovefourtycharacterslong2` user. 
* https://master-jenkins-csb-intly.apps.ocp4.prod.psi.redhat.com/job/Nightly/job/managed-api-install-master/82/artifact/operators-pods-logs-post-tests/redhat-rhoam-operator_rhmi-operator-798c9fccbd-2vrz8_rhmi-operator.log
* Search for …
> [MGDAPI-2581] C19: Ensure user cr is created before progressing test

- config/manifests-rhmi/bases/integreatly-operator.clusterserviceversion.yaml
- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
The `operatorframework.io/suggested-namespace` is supported by OLM and operator-sdk to specify the default/recommended namespace where the operator might be installed. This provides a better user experience, as well as advantages when testing using the scorecard format.
Include this annotation in the base CSVs of both RHOAM and RHMI. The CSV generated will also include the annotation.
Verify that generating a new set of manifests will result in the generated CSV containing the new annotation
> Perform this test both for RHMI and RHOAM 
1. Run the prepare release script
2. Check that the generated CSV has the corresponding value for the `operatorframework.io/suggested-namespace` annotation
> Include suggested-namespace annotation in base CSV

- pkg/products/rhsso/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/resources/user/userHelper.go
- pkg/resources/user/userHelper_test.go
- test/common/default_email.go
https://issues.redhat.com/browse/MGDAPI-2654
When a user signs into openshift via IDP, the `Identity` resource created on openshift may not have an `email` field assoicated with it. In this case, a default email using their username and appending `@rhmi.io` is used when creating the keycloak user.
This normally is fine, but when the username is an email (e.g. `test@test.com`), `@rhmi.io` is still appended to it (e.g. `test@test.com@rhmi.io`) and when the operator attempts to create the user in 3scale, it will fail due to the double domain appended email address as it is is not valid. This will give a `422` error during the 3scale user creation and cause the `ThreeScaleUserCreationFailed` alert to fire
To further prevent this scenario:
* Use username directly as email if following standard …
> [MGDAPI-2654] fix: do not append default domain to users with username that are email compliant

- controllers/rhmi/rhmi_controller.go
- pkg/addon/operator_run.go
- scripts/patch-image-csv.sh
Disabling automatic creation of RHMI CR in case of the installation via OLM. This would allow specifying `multitenant-managed-api` installation type and proceeding with multitenant RHOAM. 
Verification includes two independent checks: ensure that `RHMI CR` is _not_ created in case of the installation via OLM (bundles) and ensure that `RHMI CR` is created in case of the installation via OCM (addon)
Bundles:
1. Build an image from this PR. I would suggest you using ```docker build -t quay.io/mvavilov/managed-api-service:rhoam-v1.12.0 .``` instead of   relying on the `make image/build` 
2. Push an image to your repository 
3. Follow [this](https://github.com/RHCloudServices/integreatly-help/blob/master/guides/olm/install-upgrade-rhoam-bundle.md#generation-of-release-manifest-directory-structu …
> only manual deployment of RHMI CR for OLM installation type

- test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
The previous rate-limit-testing machine was accidentally deleted. New instance was created and the IP has changed.
> test: test-case: h23: update machine IP

- Makefile
- scripts/setup-private-git-access.sh
Adding an additional prow check in order to provide the steps required by prow to configure git/go to be able to pull a private repository. The reason we need this change is because the observability-operator repo is private. This will be needed on master soon.
Run `make vendor/check/prow`
If you do not have the variables exported you the script should tell you.
export the values.
The don't really matter for now.
Run the script
There should be a new block of configuration in you `~/.gitconfig` file which looks like
```
[url "https://<the username>:<the token>@github.com@github.com"]
insteadOf = https://github.com
```
> add prow vendor check with config to pull private repos

- products/installation-cpaas.yaml
The current bundle being referenced is from 2.10, which includes images in the CSV that cause IIB to fail when running the Managed Service release pipeline. 
Update the 3scale bundle on the CPaaS installation spec to the 2.11 build from `3scale-operator-bundle-container-2.11.0-3`
> Update 3scale bundle to 2.11 on installation-cpaas

- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/resources/pullSecret.go
https://issues.redhat.com/browse/MGDAPI-2555
patches credentials-rhsso and credentials-rhssouser with an ownerref from the Keycloak cr
Required for installation to complete with rhsso 7.5 images
- Install the operator locally
- make sure that rhsso and user-sso installations complete and there routes are available
> rhsso-next-7.5.0-patch-ownerref-admincredentials

- pkg/products/threescale/clients_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/three_scale_client.go
- pkg/products/threescale/three_scale_moq.go
- test/functional/integreatly_test.go
- test/functional/suite_test.go
Fix 3scale issue when API return an error for new tenant accounts creation
https://issues.redhat.com/browse/MGDAPI-2647
The 3scale API returns a random error when creating new tenant accounts and it prevents the operator from getting the access token to set up the new account properly to overcome this issue, this PR deletes the accounts those tenant accounts and attempt to recreate them 
1. Install the operator from this branch
2. User the testing-idp script to create new 3scale users ```NUM_REGULAR_USER=1000 NUM_ADMIN=5 REALM=rhd DEDICATED_ADMIN_PASSWORD=Password1 PASSWORD=Password1 ./scripts/setup-sso-idp.sh```
3. Stop the operator
4. Login those users on the cluster by running a functional test, you can use [this functional test](https://gist.github.com/jjaferson/86c1f56abb7560209aa7764 …
> Fix 3scale issue creating tenant account

- controllers/rhmi/bootstrapReconciler.go
- go.mod
- go.sum
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_multitenant.go
- pkg/products/rhssouser/reconciler_multitenant_test.go
- pkg/products/rhssouser/reconciler_test.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/client.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClientFactory_moq.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/types.go
- vendor/modules.txt
Implement on demand approach to keycloak realm provisioning for multi tenant Rhoam in user sso. 
Install MT RHOAM from this branch
Install IDP:
`NUM': NUM_REGULAR_USER=20 NUM_ADMIN=0 DEDICATED_ADMIN_PASSWORD=Password1 PASSWORD=Password1 REALM_DISPLAY_NAME="devsandbox" REALM="devsandbox" ./scripts/setup-sso-idp.sh` 
Log into OpenShift with 4 users test-user01, test-user02, test-user03, test-user04
This will create user and identity CRs
Wait for multi-tenant users to reconcile
Log in as admin to User SSO and verify that the Staging Realm exists with 4 users
Create projects and related privileges for each user
`oc new-project test-user01`
`oc adm policy add-role-to-user admin test-user01 -n test-user01-dev`
repeat for users 2
Log into OpenShift as test-user01 
Go to the test-user01-dev …
> Implement on demand approach to keycloak realm provisioning for multi tenant Rhoam in user sso.

- pkg/products/observability/prometheusRules.go
DMS creation will be handled by Observability Operator itself 
- https://github.com/redhat-developer/observability-operator/pull/87
If we do not remove the manually created one, there will be 2 DMS alerts created
Just a code review should be good enough as this is just a deletion of the alert
> fix: remove manual creation of DMS alert

- scripts/alerts-during-perf-testing.sh
- scripts/capture_resource_metrics.sh
https://issues.redhat.com/browse/MGDAPI-1886
Replaces https://github.com/valerymo/integreatly-operator/pull/12
Update scripts to observability namespace
* Verify `capture_resource_metrics.sh` completes without errors
* Verify `alerts-during-perf-testing.sh` can be run
* Currently an issue with 2 DMS alerts creates, so script will not complete until https://github.com/integr8ly/integreatly-operator/pull/2173 is merged
> [MGDAPI-1886] refactor: update scripts with migration to observability operator 

- pkg/products/rhssouser/reconciler.go
https://issues.redhat.com/browse/MGDAPI-2798
Add sub-group name to create group call in user-sso
This PR must be ran alongside with https://github.com/integr8ly/integreatly-operator/pull/2146, so suggest to only test it after merge of the 2146
1. Install RHOAM from this branch
2. Run `PASSWORD=Password1 DEDICATED_ADMIN_PASSWORD=Password1 scripts/setup-sso-idp.sh`
3. Log in as kubeadmin in one browser
4. In private window login as `customer-admin01`  `Password1`
5. In kubeadmin open user-sso ns and select keycloakUser CRs
6. Confirm that there is a generated user CR for customer-admin and it's state is "reconciled" and groups have "dedicated-admin" and "dedicated-admins/realm-managers"
7. As dedicated admin login to `API Management SSO`
8. In your terminal run:
```
cat << EOF | oc create …
```
> add childgroup name to setgroupchild call

- pkg/resources/metrics.go
[MGDAPI-2939](https://issues.redhat.com/browse/MGDAPI-2939)
Prom rules can not be reconciled by OO unless in the observability operator.
Create rules in OO namespaces
There will be a separate JIRA to remove unneeded prometheus rules in the rhoam-operator namespace
- Install 1.12 on byoc cluster
- Confirm CRO prom rules created under redhat-rhoam-operator ns.
- Upgrade using this branch
- Verify that rules created under OO namespace 
- Verify that all expected alerts exist - including CRO alerts
- Install from this branch on byoc cluster
- Verify that rules created under OO namespace 
- Verify that all expected alerts exist - including CRO alerts
- Verify that no prom rule CRs exist in the redhat-rhoam-operator ns.
> move Prom rules to OO namespace

- pkg/products/marin3r/apiUsagePrometheusRules.go
https://issues.redhat.com/browse/MGDAPI-3025
See ticket for verification steps and previous verification done on cluster `lfitzger`
Threshold Alerts should be `(sum(increase(authorized_calls[1m])) >= (13889 / 100 * 95))` rather than `(sum(increase(authorized_calls[1m]) >= (13889 / 100 * 95)))` note the difference in the brackets
OverLimit (Spike) Alert query should be `max_over_time((sum(increase(authorized_calls[1m])) + sum(increase(limited_calls[1m])))[10m:]) > 13889` for 20M cluster
After running the script from the test against the cluster the following alerts are observed
Load test output
```
scenarios: (100.00%) 1 scenario, 200 max VUs, 10m30s max duration (incl. graceful stop):
* default: 200 looping VUs for 10m0s (gracefulStop: 30s)
running (10m00.8s), 000/200 VUs, 150137 complete …
```
> update to premetheus rules to use sum() as expected

- test/e2e/suite_test.go
https://issues.redhat.com/browse/MGDAPI-2892
- fixed name of the deployment of the 3scale operator for RHOAM, to be "threescale-operator-controller-manager"
- added waitForProductDeployment(...) and waitForInstallationStageCompletion (...) for Observability Operator for RHMO; added condition to Support both AMO and OO
run e2e tests for RHMO (and RHMI ? )
> MGDAPI-2892 - fix tests - suite_test.go

- test-cases/tests/upgrade/n02b-upgrade-rhoam.md
N/A
Small improvement of RHOAM upgrade test case. About checking that the installPlan installs the proper RC before the installPlan approval.
Eye review only, you can potentially run the command against the cluster.
> Examine the installPlan before approval in RHOAM upgrade test case

- test-cases/tests/installation/a25-verify-standalone-rhmi-vpc-exists-and-is-configured-properly.md
- test/functional/aws_standalone_vpc.go
https://issues.redhat.com/browse/MGDAPI-3011
https://issues.redhat.com/browse/MGDAPI-2309
This test fails frequently in our pipelines on following error:
```
Update Cidr Block in AWS Strategy Map errors:
failed to update aws strategy map: Operation cannot be fulfilled on configmaps "cloud-resources-aws-strategies": the object has been modified; please apply your changes to the latest version and try again
```
This is caused by the the unsuccessful attempt to update `cloud-resources-aws-strategies` configmap by the test. The object has changed because rhmi-operator updated the configmap first. It can be fixed by fetching the configmap content just before the update, but there's still a slight chance that rhmi-operator might still be able update it between get & update actions and cause the …
> test: a25: remove updating cidr range from test

- config/scorecard/kuttl/rhoam-install/01-create-secrets.yaml
- config/scorecard/kuttl/rhoam-install/resources/secret-addon.yaml
Related to https://issues.redhat.com/browse/MGDAPI-2370
As a part of install test, change RHOAM quota to "100k" from "20M" (which is the default value), so that RHOAM install requires less cluster resources
Verified against OSD cluster by running `operator-sdk scorecard`
> fix: change RHOAM quota in CVP to minimum value

- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
- packagemanifests/managed-api-service/1.14.0/managed-api-service.clusterserviceversion.yaml
[JIRA](https://issues.redhat.com/browse/MGDAPI-3090)
Scorecard tests are failing validation because of issues in the CSV
Checkout this branch
Ensure targeting an OSD cluster
From the root of the branch run `make bundle`
Copy the manifest files from the [1.14](https://github.com/briangallagher/integreatly-operator/tree/MGDAPI-3090-scorecard/packagemanifests/managed-api-service/1.14.0) folder into the manifests subfolder of the bundle folder generated from the previous command.
Create [config.yaml](https://gist.github.com/briangallagher/e8760d23530a746115cb0aaf79551cb6) under bundle > tests > scorecard > config.yaml
Run `operator-sdk scorecard ./` from the bundle folder and ensure no errors. Search for "errors" in the output. 
Confirm that the errors specified in the JIRA do not appear. …
> add required fields to CSV to pass scorecard tests

- pkg/products/threescale/reconciler.go
Update UIBBT alert for threescale route to allow for routes without "3scale."
https://issues.redhat.com/browse/MGDAPI-2910
3scale system-developer  route , that have label with key "uibbt" (for example uibbt: system-developer) - will be recognized for monitoring by ThreeScaleDeveloperUIBBT alert
3scale system-developer  route hostname could be changed, to not have prefix 3scale; need add label "uibbt" (like uibbt: system-developer) to this route.
Tenant system-developer route will be used for monitoring if have label "uibbt" even if 3scale original system-developer  route present.
Adding custom route for 3Scale developer portal
* Method 1 of verification:  Change 3scale system-developer's route host prefix from default (3scale) to custom, and add label with key "uibbt" to customized …
> MGDAPI-2910 Update UIBBT alert for threescale route to allow for route without "3scale."

- pkg/products/rhsso/reconciler.go
- pkg/resources/user/userHelper.go
- pkg/resources/user/userHelper_test.go
[MGDAPI_3087](https://issues.redhat.com/browse/MGDAPI-3087)
Install RHOAM based on this branch
Install the testing IDP with 10 users
Login to OpenShift as testuser01, testuser02, testuser03
Verify a User CR and Identity CR exist for each
For test_user01, delete the identity id on the user 
For test_user02, delete the identity cr 
Leave test_user03 as is
Ensure only test_user03 gets created as a Keycloak User CR in rhsso
After confirming delete the identity for test_user03
Verify that the Keycloak User CR also gets deleted
> ensure missing identities do not block the install

- pkg/config/cloudresources.go
- pkg/products/cloudresources/reconciler.go
fix to add additional reconciles on start up of the operator, allows for additional time on the upgrade
should be removed at a later date
https://issues.redhat.com/browse/MGDAPI-3192
Add a hack to give cloud resources reconciler 5 reconciles before it reports that it's completed.
Using CCS Cluster
For full upgrade verification which is recommended follow steps in -> #2291
> MGDAPI-3192

- Makefile
- README.md
- config/rbac/dedicated_admins_rbac.yaml
- test/common/shared_functions.go
- test/common/user_dedicated_admin_permissions.go
- test/functional/suite_test.go
https://issues.redhat.com/browse/MGDAPI-1163
When installed via addon-flow, manual creation of catalogSource or local deployment the dedicated admins get permissions on the rhmi ans rhmiconfig types.
This PR brings in line the permissions give to dedicated admins for local development with that give for installs via the addon-flow. 
The manual creation of the catalogSource gives higher permissions than installing via the addon-flow. This has not being address in this case. One of the extra permissions is `Create` which the addon-flow will never have. 
Best to test with fresh clusters, you will need two.
- Install rhoam using the addon-flow
- set up the testing IDP 
- run ` ACK_GINKGO_DEPRECATIONS=1.16.4 BYPASS_STORAGE_TYPE_CHECK=true INSTALLATION_TYPE=managed-api TEST=B04 make …
> mgdapi-1163: update rbac rules

- apis/v1alpha1/rhmi_types.go
- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- go.mod
- go.sum
- manifests/integreatly-observability-operator/3.0.8/observability-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- manifests/integreatly-observability-operator/3.0.8/observability-operator-priority-class_scheduling.k8s.io_v1_priorityclass.yaml
- manifests/integreatly-observability-operator/3.0.8/observability-operator-webhook-service_v1_service.yaml
- manifests/integreatly-observability-operator/3.0.8/observability-operator.clusterserviceversion.yaml
- manifests/integreatly-observability-operator/3.0.8/observability.redhat.com_observabilities.yaml
- manifests/integreatly-observability-operator/observability-operator.package.yaml
- pkg/products/observability/reconciler.go
- products/installation-cpaas.yaml
- products/installation.yaml
- products/products.yaml
- test-cases/tests/installation/a41-verify-migration-to-observability-operator-was-successful.md
- vendor/github.com/redhat-developer/observability-operator/v3/api/v1/observability_types.go
- vendor/modules.txt
JIRA: https://issues.redhat.com/browse/MGDAPI-2282
This fix adds a bearer token to the `black-box-config` ConfigMap in the `redhat-rhoam-observability` namespace. The bearer token belongs to a new ServiceAcccount `blackbox-exporter` which is granted `get` permissions to `namespaces`. This allows the `probe_success` query that is emitted by the Prometheus Probes to be authenticated by the proxy that is in front of the `grafana-ui` service. This fixes the bug in the `Endpoints Detailed` grafana dashboard that incorrectly showed the `grafana-ui` service as `DOWN`. 
This fix also includes bumping the `observability-operator` version to v3.0.8 in order to pull in the new feature that was added to the observability-operator repo in this …
> Bumps OO to v3.0.8 and adds bearer token to blackbox exporter

- Makefile
https://issues.redhat.com/browse/MGDAPI-1710
The pipeline for deploying RHOAM with 3scale images was failing on logging into a cluster as rhmi-operator serviceaccount.
```bash
$ make cluster/deploy
...
You must obtain an API token by visiting https://oauth-openshift.apps.<REDACTED>.org/oauth/token/request
make[1]: *** [Makefile:111: setup/service_account] Error 1
make[1]: Leaving directory '/home/jenkins/agent/workspace/ManagedAPI/managed-api-install-3scale/integreatly-operator'
make: *** [Makefile:383: cluster/prepare/delorean/pullsecret] Error 2
ERROR: script returned exit code 2
```
The error was caused by [`oc serviceaccounts get-token`](https://github.com/integr8ly/integreatly-operator/pull/2351/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L111) command …
> MGDAPI-1710 fix: 3scale pipeline

- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssocommon/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
MGDAPI-3270
Force the use of new RHSSO images. All of this code needs to be removed whenever the next release of the keycloak-operator comes out.
- Install RHOAM from branch `rhoam-release-v1.15`. See that RHSSO is using upstream images in both `redhat-rhoam-rhsso` and `redhat-rhoam-user-sso` namespaces.
- Stop the operator
- Checkout this branch and start the operator
- After a few minutes, see that both RHSSO are now using `quay.io/integreatly/rhsso:7.5-11` images.
> use new RHSSO 7.5 images

- openshift-ci/Dockerfile.tools
https://issues.redhat.com/browse/MGDAPI-3029
B01B still fails with the following error in the pipeline
```
/go/src/github.com/integr8ly/integreatly-operator/test/functional/integreatly_test.go:77 ChromeDP test failed with error: exec: "google-chrome": executable file not found in $PATH /go/src/github.com/integr8ly/integreatly-operator/test/common/product_login.go:36
```
The error looks to be due that base images in prow are replaced by image built by `Dockerfile.tools` and then mirrored. So installing `chrome` to this dockerfile should fix the issue
* Build the docker image
```
docker build -t registry.svc.ci.openshift.org/integr8ly/intly-operator-base-image:latest - < openshift-ci/Dockerfile.tools             
```
* Run the container 
```
docker run -it …
```
> MGDAPI-3029 - fix: install chrome onto base prow image

- scripts/prepare-release.sh
https://issues.redhat.com/browse/MGDAPI-2585
This is a cherry pick of : https://github.com/integr8ly/integreatly-operator/pull/2122
With the bump to `yq v4`, `null` seems to be returned when trying to get a field that does not exist in a yaml file.
This had caused the `-z ` check to always be true in  the `check_csv_replaces_field()` function, which caused the `replaces` field to be missing whenever existing CSVs need to be re-generated such as from RC releases to final releases.
To fix this:
* The above checks for null being returned instead
Additionally:
* Removed some unneeded extra whitespaces
* Generate new release
```
SEMVER=1.13.0 OLM_TYPE=managed-api-service ORG=kevfan scripts/prepare-release.sh
```
* Verify `replaces` field is **present**
* Re-generated release …
> fix prepare release script

- test/osde2e/pre-test.go
- test/osde2e/suite_test.go
https://issues.redhat.com/browse/MGDAPI-1162
* changed useClusterStorage to `true` for osde2e (RHOAM) job based on agreement in a team discussion
* fixed c04 & a26 tests that were failing because of missing variables in osde2e tests
I updated `:osde2e` image tag in quay.io with the image I built from this PR and triggered osde2e job [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/24200/rehearse-24200-osde2e-stage-aws-addon-integreatly-operator/1478506829406277632). If it passes, then it should be safe to merge this PR
> MGDAPI-1162 fix c04 a26, osde2e: useclusterstorage

- test/common/scale_up_replicas_apicurito.go
- test/osde2e/pre-test.go
https://issues.redhat.com/browse/MGDAPI-1162
* changed useClusterStorage to `true` for osde2e (RHMI) job based on agreement in a team discussion
* fixed apicurito scaling test that was failing in osde2e
I updated `:osde2e-rhmi` image tag in quay.io with the image I built from this PR and triggered osde2e job [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/24200/rehearse-24200-osde2e-stage-aws-addon-integreatly-operator-rhmi/1478506829561466880). If it passes, then it should be safe to merge this PR
> fix: osde2e, clusterStorage=true

- test-cases/tests/upgrade/n02b-upgrade-rhoam.md
This is related to https://issues.redhat.com/browse/MGDAPI-3087
Adding corrupted users to the cluster before RHOAM upgrade. Existence of such users must not break the RHOAM upgrade.
Eye review. You can also try the commands, whether they work manually.
> Adding corrupted users before RHOAM upgrade

- test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/h22-validate-that-rate-limit-service-is-working-as-expected.go
[MGDAPI-3038](https://issues.redhat.com/browse/MGDAPI-3038)
There are two issues being fixed: 
1. The test doe not clean up resources in case of failure (added `delete` calls)
2. The test was flaky - wasn't waiting for the endpoint to become working and was not ensuring that the counter returns a valid (non zero) value. This was addressed. 
Over ~20 runs it has failed once tho, but it most likely was due to a large timeout on the counter. About 10 successes in a row should be sufficient enough. 
1. Get your hands on the cluster with RHOAM
2. Run `./test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/test.sh`
3. Watch the test complete 
4. After ~10 minutes after the test succeeded check that resources in the 3sclae were cleaned up.
> MGDAPI-3038 fix h22

- pkg/products/cloudresources/prometheusRules.go
- pkg/resources/sop_url.go
[MGDAPI-3203](https://issues.redhat.com/browse/MGDAPI-3203)
Addition of an alert that fires when the `cro_vpc_action` metric shows a failure for 5m. Links to appropriate SOP.
Requires a cluster deployed in a region with no space for a new VPC:
* Try deploy RHOAM with `useClusterStorage: 'false'` and CRO version from integr8ly/cloud-resource-operator#249
* See new Prometheus alert firing
> MGDAPI-3203 - emit metric around vpc limits hit

- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
[JIRA](https://issues.redhat.com/browse/MGDAPI-3237)
Added a `blackhole` receiver to dump alerts with `info` severity 
1. Run the operator from this branch 
1.1 You might update [these](https://github.com/integr8ly/integreatly-operator/blob/master/pkg/products/threescale/prometheusRules.go#L351-L352) lines to decrease the "alert" threshold and timeout to speed up verification:
```
Expr:   intstr.FromString(fmt.Sprintf("sum by(container, pod) (container_memory_usage_bytes{container!='', container!='system-provider', namespace='%[1]v'}) / sum by(container, pod) (kube_pod_container_resource_limits{namespace='%[1]v',resource='memory'}) * 100 > 0", namespace)),
For:    "1m",
``` 
2. Open alertmanager (Networking -> Routes -> `alertmanager` in `redhat-rhoam-observability` namespace) and check …
> MGDAPI-3237 don't send emails on info level alerts

- test/common/alerts_exist.go
https://issues.redhat.com/browse/MGDAPI-3203
* fixes the test that is failing since https://github.com/integr8ly/integreatly-operator/pull/2377 was merged
```
go clean -testcache && WATCH_NAMESPACE=redhat-rhoam-operator BYPASS_STORAGE_TYPE_CHECK=true go test -v ./test/functional -timeout=80m -ginkgo.focus="C04" -ginkgo.v -ginkgo.progress -ginkgo.trace
```
> MGDAPI-3203 fix test

- scripts/prepare-release.sh
Update channels to stable for both RHOAM and RHMI to meet MTR requirements (we use stable channel for both, stage and prod)
```
annotations:
operators.operatorframework.io.bundle.mediatype.v1: registry+v1
operators.operatorframework.io.bundle.manifests.v1: manifests/
operators.operatorframework.io.bundle.metadata.v1: metadata/
operators.operatorframework.io.bundle.package.v1: managed-api-service
operators.operatorframework.io.bundle.channels.v1: stable
operators.operatorframework.io.bundle.channel.default.v1: stable
operators.operatorframework.io.metrics.builder: operator-sdk-v1.11.0+git
operators.operatorframework.io.metrics.mediatype.v1: metrics+v1
operators.operatorframework.io.metrics.project_layout: go.kubebuilder.io/v2
operators.operatorframework.io.test.mediatype.v1: scorecard+v1 …
```
> MGDAPI-2909 update channel for rhoam and rhmi to stable

- controllers/subscription/subscription_controller.go
- go.mod
- vendor/modules.txt
https://issues.redhat.com/browse/MGDAPI-2660
Also related https://issues.redhat.com/browse/MGDAPI-3091
Some of our past work around the rhmiConfig CR were causing issue with the upgrade cycle. This change removes our custom logic and gives that responsibility back to OLM.
Use a openshift 4.8 cluster for Verification.
There are multiply upgrade case that will need to be covered.
While some case may seem the same they are based around service and non-service affecting upgrades.
**Important Note:** Existing installPlans on a cluster has an effect on how OLM builds the installPlans.
In cases 2 and 7 this is especially important.
In all cases the catalog source is used for create the installation.
This guide [Installing RHOAM Through OLM with Bundle …
> MGDAPI-2660 Removing installPlan checks

- controllers/rhmi/types.go
https://issues.redhat.com/browse/MGDAPI-3080
Remove the monitoring and monitoring-spec reconcilers
Remove the monitoring and monitoring-spec reconcilers from the installation types which now have migrated from AMO to OO  in RHOAM.
Remove monitoring and monitoring-spec in controllers/rhmi/types.go from  allMultitenantManagedApiStages and allManagedApiStages
- On fresh install and upgrade to a newer version than 1.14.0 the monitoring and monitoring-spec  reconcilers are not called anymore and are removed from the rhmi cr
- There is no more reference to any redhat-rhoam-monitoring namespaces on upgrade
> MGDAPI-3080 Remove the monitoring and monitoring-spec reconcilers #1

- openshift-ci/Dockerfile.tools
[MGDAPI-3256](https://issues.redhat.com/browse/MGDAPI-3256)
Updating `Dockerfile.tools` to configure prow jobs to use a new version of GO
> MGDAPI-3256 update Dockerfile.tools for prow

- test-dependancy/centos.repo
https://issues.redhat.com/browse/MGDAPI-3414
http://mirror.centos.org/centos/8/AppStream/x86_64/os/repodata/repomd.xml returns a 404 causing the image build to fail, possibly due to it being archived
We should switch to use centos 8 stream `centos.repo`
* Having the prow image build job passing in this job should be sufficient
> [MGDAPI-3414] fix: prow images

- test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
- test/common/selfmanaged_apicast.go
- test/common/tests.go
- test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/test.sh
https://issues.redhat.com/browse/MGDAPI-3146
Self-Managed Apicast test full Automation and Pipeline integration  
This task is based on Spike task - https://issues.redhat.com/browse/MGDAPI-3037  
This task is follow on https://issues.redhat.com/browse/MGDAPI-1920 
Test is integrated into Pipeline in functional tests:  {Description: "H24 - Verify selfmanaged Apicast", Test: TestSelfmanagedApicast} - test/functional/selfmanaged_apicast.go 
Standalone script is also available, and could be useful for investigation, has 2 modes - interactive and batch (similar to TestSelfmanagedApicast) - test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go
1. Run as E2E single step:  TEST=H24 INSTALLATION_TYPE=managed-api make …
> MGDAPI-3146 - Self-Managed Apicast test full Automation and Pipeline integration

- config/scorecard/kuttl/02-scalability/00-test-pod-template.yaml
Remove failing test (added on purpose in https://github.com/integr8ly/integreatly-operator/commit/755020ca5a91f8b2765531c028ff200656fca784)
> MGDAPI-2370 revert failing test after MSP demo

- config/scorecard/bases/config.yaml
- config/scorecard/kuttl/00-installation/07-assert.yaml
https://issues.redhat.com/browse/CVP-2642
* `logs/artifact` is a path used by CVP for archiving artifacts from scorecard tests
* increased install timeout for "products" stage
1. Target an OCP cluster with RHOAM installed using cluster storage (I can provide one)
2. From this branch run
```bash
kustomize build config/manifests-rhoam | operator-sdk generate bundle --kustomize-dir=config/manifests-rhoam
cp -r config/scorecard/kuttl bundle/tests/scorecard/
operator-sdk scorecard ./bundle --namespace=redhat-rhoam-operator --skip-cleanup --verbose --output json --service-account rhoam-test-runner  --wait-time 3000s --test-output logs/artifacts -b quay.io/quay/busybox
```
3. Tests should finish successfully and you should see logs and artifacts from tests stored in `./logs/artifacts` directory …
> CVP-2642 def mountpath for archiving test results

- config/scorecard/bases/config.yaml
- config/scorecard/patches/kuttl.config.yaml
https://issues.redhat.com/browse/CVP-2642
* add storage spec only to RHOAM tests, because archiving results from other custom tests does not work in CVP:
```
"errors": [
"tar contents corrupted"
],
```
> CVP-2642 add mountpoints only to rhoam tests

- Makefile
- README.md
- bundles/integreatly-operator/bundle.Dockerfile
- bundles/managed-api-service/1.15.1/metadata/annotations.yaml
- bundles/managed-api-service/1.15.2/metadata/annotations.yaml
- bundles/managed-api-service/1.16.0/manifests/managed-api-service.clusterserviceversion.yaml
- bundles/managed-api-service/bundle.Dockerfile
- scripts/bundle-rhmi-operators.sh
https://issues.redhat.com/browse/MGDAPI-3374
- update readme
- update bundle rhmi operator to support bundle format
From this branch run:
```
INSTALLATION_TYPE=managed-api make cluster/preapare/local
```
```
INSTALLATION_TYPE=managed-api make deploy/integreatly-rhmi-cr.yml
```
```
make create/olm/bundle OLM_TYPE=managed-api-service UPGRADE=false BUNDLE_VERSIONS=1.16.0,1.15.2 ORG=<YOUR_QUAY_ORG> OC_INSTALL=true`
```
- And confirm that a catalog source for 1.15.2 has been created on your cluster, navigate to operators hub, find RHOAM, install under redhat-rhoam-operator ns. 
- Once installation completes, navigate to same catalog source that 1.15.2 was referred from, update it to 1.16.0.
- Navigate to installed operators and click approve on RHOAM upgrade. 
- Confirm that the upgrade has …
> MGDAPI-3374 update bundle rhmi operators script and readme

- go.mod
- go.sum
- products/products.yaml
- vendor/modules.txt
Jira: [MGDAPI-3257](https://issues.redhat.com/browse/MGDAPI-3257)
Update keycloak-client version to latest commit (Go update to 1.17).
Unit and e2e tests are sufficient
> MGDAPI-3257 - update keycloak-client

- controllers/subscription/subscription_controller.go
[MGDAPI-3321](https://issues.redhat.com/browse/MGDAPI-3321)
When installed via OLM the subscription has a name `managed-api-service`. We were not reconciling that subscription and this led to a number of problems. 
You would need to build bundles and image from this PR (or, alternatively, you can use mine: `quay.io/mvavilov/rhoam-index:1.17.0`)
1. Create a `rhoam-operators.yaml` file with the following content:
```
metadata:
spec:
image: <index>
```
2. Against a clean cluster run:
```
oc apply -f rhoam-operators.yaml
INSTALLATION_TYPE=managed-api make cluster/prepare/project && \  
INSTALLATION_TYPE=managed-api make cluster/prepare/smtp && \ …
```
> MGDAPI-3321 add rhoam olm subscription to reconciler

- Makefile
- pkg/products/monitoringcommon/alertmanagerConfig.go
- pkg/products/monitoringcommon/alertmanagerConfig_test.go
- pkg/resources/metrics.go
- test/common/3scale_smtp.go
- test/common/alerts_firing.go
- test/common/sendgrid_credentials_valid.go
- test/resources/util.go
https://issues.redhat.com/browse/MGDAPI-3021
Provides dummy values for templateUtil which allows for RHOAM to be installed even when the SMTP secret is missing. Also includes unit tests for new get functions.
1. Run the RHOAM operator locally  by running the following commands : 
```sh
make code/run 
```
2. In a separate terminal remove the SMTP secret and check that its been removed by running the following command 
```sh
oc delete secret redhat-rhoam-smtp -n redhat-rhoam-operator
oc get secrets -n redhat-rhoam-operator
```
3. Check that the missingSmtp alert is firing in  observability -> Prometheus
4. Verify that RHOAM has been installed successfully.
> MGDAPI-3021

- test/common/alerts_mechanism.go
Fix spelling error in test logs
> fix spelling error in alerts firing test log

- test-cases/tests/monitoring/m02b-verify-rhoam-version-metric-is-exposed.md
- test/common/tests.go
- test/common/verify_prometheus_metrics.go
https://issues.redhat.com/browse/MGDAPI-3453
Check for the existence of a metric called `rhoam_version` in Prometheus.
Run the test called M02B: 
```
export BYPASS_STORAGE_TYPE_CHECK=true
export TEST=M02B
make test/e2e/single
```
> MGDAPI-3453 (M02B) test to verify rhoam_version metric is exposed in Prometheus

- controllers/rhmi/rhmi_controller.go
https://issues.redhat.com/browse/MGDAPI-3336
status.monitoring should be removed from RHMI CR after RHOAM upgrade
It is no longer present in case of installation, But need care to remove it also in case of Upgrade.
Done by adding removing Monitoring from Status of Rhoam CR, in rhmi_controller
Addition to function updateStatusAndObject() - new method cleanMonitoringStageInRhoamCRStatus()
* Prepare Rhoam bundle images and indexes in Quay for:
** Any existing Rhoam version, like rhoam-v1.15.2,
** Rhoam image that include the fix
* Check that Rhoam 1.15.2 is present in OperatorHub
* Install Rhoam v1.15.2 from OperatorHub, and check that it's running no errors
* Check that Upgrade to New version (with fix) is available in OperatorHub, and do Upgrade
* Check that new Rhoam version installed …
> MGDAPI-3336 - Remove the monitoring stage in the status

- pkg/products/marin3r/rateLimitService.go
- pkg/products/threescale/envoyconfig.go
- pkg/products/threescale/reconciler.go
- pkg/resources/ratelimit/envoy.go
- pkg/resources/ratelimit/envoyconfig.go
https://issues.redhat.com/browse/MGDAPI-1626
Envoy API v2 is depreacted and newer components that uses the envoy api will require use of Envoy v3 API such as higher versions of limitador and marin3r 
So we should migrate to use Envoy v3 API  
```
make code/run
```
* Verify install complete successfully
* Sign into 3scale as `admin` to complete 3scale tutorial to create echo example endpoint
* Using endpoint created (under Products -> API -> Integration -> Configuration), generate traffic to verify rate limiting still works correctly
* https://github.com/rakyll/hey
* Shoudl have 30 or 31 out of 100 requests that are rate limited - 429 status code
```
hey -c 1 -n 100 "<3scale_endpoint>" …
```
> [MGDAPI-1626] feat: upgrade to use envoy v3 API

- .codecov.yml
- Makefile
- README.md
- hack/codecov.sh
https://issues.redhat.com/browse/MGDAPI-2683
* add code coverage [badge](https://github.com/psturc/integreatly-operator/tree/MGDAPI-2683#readme)
* prepare for coverage reports on PRs via prow
When run locally, following command should pass and generate `coverage.out` report
```bash
make coverage
```
> Code coverage reports using codecov.io

- README.md
- test/functional/integreatly_test.go
- test/functional/suite_test.go
https://issues.redhat.com/browse/MGDAPI-3475
When running functional test suite, by default skip only AWS tests in case RHOAM is installed using cluster storage
(`useClusterStorage: true`)
```bash
```
**On a cluster with RHOAM installed using cluster storage (`useClusterStorage: true`):**
Test should pass
```bash
make test/e2e/single TEST="A01"
```
(AWS) Test should be skipped, because we're using cluster storage
```bash
make test/e2e/single TEST="F01"
```
(AWS) Test should fail, because we're using cluster storage, but it's overridden with `BYPASS_STORAGE_TYPE_CHECK`
```bash
BYPASS_STORAGE_TYPE_CHECK=true make test/e2e/single TEST="F01"
```
**On a cluster with RHOAM installed using AWS storage (`useClusterStorage: false`):**
All commands below should …
> MGDAPI-3475 skip only AWS tests

- test/common/user_dedicated_admin_permissions.go
https://issues.redhat.com/browse/MGDAPI-3164
Updated B04B test to include dedicated admin RHMI permission verification.
Run SSO IDP script `DEDICATED_ADMIN_PASSWORD=Password1 PASSWORD=Password1 ./scripts/setup-sso-idp.sh`
Run test `BYPASS_STORAGE_TYPE_CHECK=true TEST=B04 make test/e2e/single`
> added function for veryfing dedicated admin RHMI permissions

- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
https://issues.redhat.com/browse/MGDAPI-3483
All Info level alerts are being sent to the blackhole.
1. In pkg -> products -> threescale -> prometheusRules.go, on line: 242 (ThreescaleBackendWorkerPod) change the severity level to info.
2. Install RHOAM off of this branch. 
3. In your cluster go to Deployments under the 3cale-operator namespace and scale the pod to 0.
4. In Deployment Configs under the 3scale namespace find the backend worker pods and scale those down to 0.
5. In Routes under the Observability namespace, go to the prometheus location and go into alerts. After a few minutes you should see the backend worker alert change from inactive to pending and then to firing.
6. Once it's firing go to Pods under the observability namespace and go into alertmanager-alertmanager-0, then …
> MGDAPI-3483 Changed all info level alerts to blackhole

- test/common/3scale_backend_via_CR.go
- test/common/3scale_product_via_CR.go
- test/common/3scale_tenant_via_CR.go
- test/common/shared_functions.go
- test/common/tests.go
- test/e2e/integretly_test.go
- test/functional/integreatly_test.go
https://issues.redhat.com/browse/MGDAPI-3476 
Previously these tests were testing whether or not the run was cluster scoped within each individual test and skipping it during the test, therefore failing it. 
The tests are now grouped in a test suite and the suite checks whether or not the run is cluster scoped before running the tests. 
1. Install RHOAM off of master and make sure the tests fail.
2. Uninstall RHOAM
3. Install RHOAM from [here](https://github.com/integr8ly/integreatly-operator/pull/2409)
```
INSTALLATION_TYPE=managed-api USE_CLUSTER_STORAGE=false make deploy/integreatly-rhmi-cr.yml
```
4. Run the tests and make sure they now pass.
Note: If you are getting an error in …
> MGDAPI-3476 Added 3Scale cluster scoped tests to new test case

- pkg/products/grafana/reconciler.go
remove dashboard links for multi-tenant rhoam which should not be
accessible for tenants
> MGDAPI-3471 - remove links

- config/olm/operator-subscription-template.yml
- scripts/prepare-release.sh
https://issues.redhat.com/browse/MGDAPI-3295
* small fixes required in order to get rhoam-upgrade pipeline to function properly
1. Script for creating a new release should return no errors
```bash
OLM_TYPE=managed-api-service make release/prepare SEMVER=5.0.0 IMAGE_TAG=MGDAPI-3295
```
2. Creating a new RHOAM subscription should work
```bash
for i in project quota dms pagerduty smtp; do make cluster/prepare/$i ; done
oc process -p INDEX_IMAGE=quay.io/psturc/managed-api-service-index:1.18.2 -f config/olm/catalog-source-template.yml | oc apply -f - -n openshift-marketplace
oc process -p NAMESPACE=redhat-rhoam-operator CATALOG_SOURCE_CONFIG_NAME=rhmi-operators OPERATOR_GROUP_NAME=rhmi-registry-og SUBSCRIPTION_NAME=managed-api-service CHANNEL=stable -f …
```
> MGDAPI-3295 fix script/template used by RHOAM upgrade pipeline

- apis/v1alpha1/rhmi_types.go
- manifests/integreatly-3scale/0.8.3/3scale-operator.v0.8.3.clusterserviceversion.yaml
- manifests/integreatly-3scale/0.8.3/apps.3scale.net_apimanagerbackups.yaml
- manifests/integreatly-3scale/0.8.3/apps.3scale.net_apimanagerrestores.yaml
- manifests/integreatly-3scale/0.8.3/apps.3scale.net_apimanagers.yaml
- manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_activedocs.yaml
- manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_backends.yaml
- manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_custompolicydefinitions.yaml
- manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_developeraccounts.yaml
- manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_developerusers.yaml
- manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_openapis.yaml
- manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_products.yaml
- manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_tenants.yaml
- manifests/integreatly-3scale/0.8.3/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- manifests/integreatly-3scale/0.8.3/threescale-operator-controller-manager-metrics-service_v1_service.yaml
- manifests/integreatly-3scale/3scale.package.yaml
- products/installation-cpaas.yaml
Update 3scale manifest to 0.8.3+0.1645735250.p 
This is an automatically generated branch to track the '0.8.3+0.1645735250.p' version of the '3scale' OLM manifests.
This branch will be automatically updated with any changes related to this version until it finally GAs. 
Changes required to fix installation issues should be applied to this branch following the usual [PR Workflow](https://github.com/integr8ly/delorean/blob/master/docs/integrealy-ci/prow-pr-workflow.md)
More details about the Early Warning System that generated this can be found [here](https://github.com/integr8ly/delorean/tree/master/docs/ews)
- Install RHOAM via olm from this index image: ```quay.io/mstoklus/integreatly-index:1.18.2```
- Once installed, setup workload web app on your cluster
- Update catalog source to …
> 3scale update to 0.8.3+0.1645735250.p

- scripts/prepare-release.sh
MGDAPI-3377
make prepare/release is throwing an deprecation warning when run. Update the flag
```bash
OLM_TYPE=managed-api-service SEMVER=1.18.2 make release/prepare
Valid version string: 1.18.2
Generating bundle version 1.18.2
Generating bundle manifests
Bundle manifests generated successfully in bundles/managed-api-service/1.18.2
Generating bundle metadata
INFO[0000] Creating bundle.Dockerfile                   
INFO[0000] Creating bundles/managed-api-service/1.18.2/metadata/annotations.yaml 
INFO[0000] Bundle metadata generated suceessfully       
Updating descriptions
Updating permissions
Adding related images to the CSV
Flag --tojson has been deprecated, please use -o=json instead
Flag --tojson has been deprecated, please use -o=json instead
Flag --tojson has been deprecated, please …
```
> MGDAPI-3377 change deprecated flag --tojson

- Makefile
- controllers/rhmi/prometheusRules.go
- scripts/prepare-release.sh
[MGDAPI-1782](https://issues.redhat.com/browse/MGDAPI-1782)
Added a 10min warning alert as well as a 30min critical alert for when a rhoam version upgrade exceeds that time limit.
1. Get a cluster
2. Once ready > run 
```
```
So that redhat-rhoam ns is ready
3. have docker running and be quay.io logged in
5. When making an upgrade test, the first version of rhoam installed, should be the current master version - which now, is 1.18.2
6. WHEN installing the initial version, make sure to manually remove "replaces" field from the target version CSV, for example, for 1.18.2 - remove this field https://github.com/integr8ly/integreatly-operator/blob/master/bundles/managed-api-service/1.18.2/manifests/managed-api-service.clusterserviceversio …
> MGDAPI-1782 / Updated UpgradeDuration alerts

- Dockerfile.functional
- test-dependancy/centos.repo
https://issues.redhat.com/browse/MGDAPI-3786
Seems the image build errors might have been resolved by the mirror centos side, so reverting back to use the package repo for installing chrome
* Prow image build should pass and test image build log should contain no errorrs around installing chrome
> MGDAPI-3786 - fix: test image installing chrome

- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- controllers/tenant/apimanagementtenant_controller.go
- test/common/verify_prometheus_metrics.go
https://issues.redhat.com/browse/MGDAPI-3635
This change addresses an RBAC issue that was preventing multitenant installations of RHOAM from completing because the rhmi-operator ServiceAccount was unable to list Services at the cluster scope.
Passing the automated PROW tests should be enough for a verification. However this change can also be verified by checking out this PR, building the operator, bundle, and index images, and then installing RHOAM using OLM.
> MGDAPI-3635 Fixed RBAC issue for multitenant installs

- Dockerfile.scorecard
- make/scorecard.mk
https://issues.redhat.com/browse/MGDAPI-3595
* resolves an issue with scorecard image that doesn't contain kubectl and kubectl-kuttl binaries after it's built by openshift-ci (reason is that openshift-ci replaces `kudobuilder/kuttl:v0.11.1` base image with `registry.access.redhat.com/ubi8/ubi-minimal:latest`)
1. Create OCP/OSD cluster and deploy RHOAM from master branch
```bash
make cluster/deploy
```
2. Build the test scorecard test image and push it to your quay.io account
```bash
export IMAGE=quay.io/<YOUR-ACCOUNT-ID>/scorecard-test-kuttl:MGDAPI-3595
make scorecard/build/push IMAGE=$IMAGE
```
3. Prepare scorecard tests and update the happy path test image in scorecard test config (to point to your image in quay.io)
```bash
make …
```
> fix: scorecard - update scorecard base image

- products/installation-cpaas.yaml
> MGDAPI-3412 rollback 3scale operator to 0.8.2 for cpaas

- README.md
- test/common/selfmanaged_apicast.go
[MGDAPI-3517](https://issues.redhat.com/browse/MGDAPI-3517)
If the A08 test was run after H24 then it failed due to missing APIcast routes. Changed code to create a new product with the application for the H24 test and cleans both of them up at the end of the run.
1. Install RHOAM on a cluster 
2. Create IDP 
`PASSWORD=Password1 DEDICATED_ADMIN_PASSWORD=Password1 scripts/setup-sso-idp.sh`
3. Run H24 test  -  `Expected result : PASS` 
`INSTALLATION_TYPE=managed-api TEST=H24 make test/e2e/single`
4. Run A08 test  - `Expected result : PASS`
`INSTALLATION_TYPE=managed-api TEST=A08 make test/e2e/single`
> MGDAPI-3517 Refactor code to use new product

- Makefile
- openshift-ci/Dockerfile.tools
- openshift-ci/test/run
[MGDAPI-3793](https://issues.redhat.com/browse/MGDAPI-3793)
- Added new make command to exclude incomplete rules
- Added install command to `Dockerfile.tools`
- Comment out all but the newly added command to the `openshift-ci/test/run` file
- Run the two commands from the [openshift-ci README](https://github.com/integr8ly/integreatly-operator/tree/master/openshift-ci#build-and-test) while in the `openshift-ci` folder
- Check the resulting output of the second command prints the version of gosec in the beginning (it may throw errors but that doesn't matter for verification of gosec installation)
> MGDAPI-3793 - Implemented gosec install in Dockerfile.tools and added new make command

- test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/h22-validate-that-rate-limit-service-is-working-as-expected.go
N\A
If the first run of the test is skipped it locks `overallSuccess` at `false` and the test fails. 
You could modify the code to fail the first iteration and check that it is a success and then update the code to skip all and see it fail  :thinking:
> H22 bug fix

- Makefile
- apis/v1alpha1/addtoscheme_integreatly_v1alpha1.go
- config/rbac/role.yaml
- config/secrets/addon-params-secret.yaml
- controllers/rhmi/rhmi_controller.go
- controllers/rhmi/rhmi_controller_test.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/cloudresources/reconciler_test.go
- pkg/resources/sts/sts.go
- pkg/resources/sts/sts_test.go
- products/installation.yaml
https://issues.redhat.com/browse/MGDAPI-1728
Consume sts role addon parameter and create the secret required by CRO for sts enabled clusters
**Note**: 
- this currently uses own custom index to install CRO from the STS feature branch
- while 3scale installation will complete, 3scale could not provide access the S3 bucket provisioned by CRO as the STS implemenation does not provide any access keys to the provisioned buckets so some functionality that uses the S3 bucket is not expected to work at this stage. We're expecting this to be provided via an ARN by the user as part of the RHOAM installation and 3scale will support sts and can be configured to use this (https://issues.redhat.com/browse/THREESCALE-7132)
* Provision or borrow an STS Rosa cluster
* Create the RHOAM role on this account …
> MGDAPI-1728 - Consume addon parameter for the STS role in RHOAM 

- test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
- test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
- test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
- test/scripts/backup-restore/j05-verify-3scale-postgres-backup-and-restore.sh
- test/scripts/backup-restore/j07-verify-rhsso-backup-and-restore.sh
- test/scripts/backup-restore/j08-verify-user-sso-backup-and-restore.sh
https://issues.redhat.com/browse/MGDAPI-2657
For an STS cluster, AWS credentials are not available on cluster for the backup and restore scripts to run. In order to support STS clusters, we should allow passing in AWS credenitals to these scripts as an option 
* Provision ROSA STS cluster
* Ensure the prerequisite role is created
* Install RHOAM from https://github.com/integr8ly/integreatly-operator/pull/2535
* Once completed, following the test case changes, verify that the backup and restore scripts complete successfully by passing in the AWS credentials for the `osdCcsAdmin` user
> MGDAPI-2657 - Scripts STS support

- Makefile
- apis/v1alpha1/addtoscheme_integreatly_v1alpha1.go
- config/rbac/role.yaml
- config/secrets/addon-params-secret.yaml
- controllers/rhmi/rhmi_controller.go
- controllers/rhmi/rhmi_controller_test.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/cloudresources/reconciler_test.go
- pkg/resources/sts/sts.go
- pkg/resources/sts/sts_test.go
- products/installation.yaml
- test/functional/aws_shared_functions.go
https://issues.redhat.com/browse/MGDAPI-3806
For AWS functional tests, get the role arn and token file path from environment variables for use using sts authentication
* Provision / Borrow STS cluster
* Create the minimal policies using https://github.com/integr8ly/delorean/pull/261
```
make ocm/sts/rhoam-prerequisites CLUSTER_NAME=<cluster_name> OCM_ENV=<production|staging>
```
* Install RHOAM onto STS cluster using https://github.com/integr8ly/integreatly-operator/pull/2535
* Run the AWS functional test locally
```
ROLE_ARN="arn:aws:iam::408612754352:role/functional_test_role" TOKEN_PATH="/var/run/secrets/openshift/serviceaccount/token" INSTALLATION_TYPE=managed-api TEST="(AWS)|(VPC)" make test/e2e/single
```
* Verify the same by using deleoran and setting the same environment variables …
> MGDAPI-3806 - sts: get token path and role arn from env for functional test

- test-cases/tests/products/h32-verify-that-3scale-invitation-mail-is-set-correctly.md
- test-cases/tests/products/h33-verify-that-3scale-invitation-mail-works-as-expected.md
[MGDAPI-3854](https://issues.redhat.com/browse/MGDAPI-3854)
The addition of 2 new test cases to verify outgoing email in 3scale is set correctly and that sending out an invitation email works.
Read through steps and make sure it makes sense.
> MGDAPI-3854 add test cases for 3scale invitation mail

- README.md
- pkg/addon/quota.go
https://issues.redhat.com/browse/MGDAPI-3079
As part of the load testing new values were found for the resources on the backend listener on the 50M quota only.
Use this PR to verify the changes that are need in managed tenants in this [MR](https://gitlab.cee.redhat.com/service/managed-tenants/-/merge_requests/1918)
- install current RHOAM with the 50m Quota. If using cluster storage as True use 6 node m5.xlarge cluster
- run a load test for 50M requests for an hour. This [guide](https://docs.google.com/document/d/10yfhCT0yodQ1lSKFimFDorvpUB0lSjikXkE4GS0noLk/edit#heading=h.1zjmt7iulrnk) outlines the steps required. 
- expected: Alerts for high memory begin to start pending and firing after about half an hour. 
- Load test can be stopped at this point
- Upgrade rhoam to use the values …
> Mgdapi 3079 50M quota backend listener resouce bump 

- pkg/products/monitoringcommon/alertmanagerConfig_test.go
- pkg/products/threescale/reconciler.go
- pkg/resources/smtp.go
- pkg/resources/smtp_test.go
https://issues.redhat.com/browse/MGDAPI-3882
This function - https://github.com/integr8ly/integreatly-operator/blob/master/pkg/products/threescale/reconciler.go#L1095 looks for the secret in the observability operator ns while it should look for it under observability ns.
Check unit tests are passing and the coverage of `GetExistingSMTPFromAddress` is sufficient
> [MGDAPI-3882] use observability namespace and add unit tests

- controllers/rhmi/bootstrapReconciler.go
- main.go
- pkg/config/monitoring.go
- pkg/config/observability.go
- pkg/metrics/metrics.go
- pkg/products/monitoringcommon/dashboardHelper.go
- pkg/products/monitoringcommon/dashboardHelper_test.go
- pkg/products/monitoringcommon/dashboards/multitenancyDetailed.go
- pkg/resources/user/userHelper.go
- pkg/resources/user/userHelper_test.go
JIRA Link: https://issues.redhat.com/browse/MGDAPI-3637
We need a way to track multitenant installation specific metrics, namely the status of `APIManagementTenant` CRs on the cluster. This PR adds two custom Prometheus metrics and a new Grafana dashboard. The dashboard will only be created for multitenant installations of RHOAM.
1. [Provision](https://qaprodauth.cloud.redhat.com/openshift/) a non-CCS cluster
2. Checkout this PR and run `INSTALLATION_TYPE=multitenant-managed-api make cluster/prepare/local` on the command line once the cluster is ready
3. Create the following CatalogSource either using `oc` or the GUI:
```yaml
metadata:
spec:
image: …
```
> MGDAPI-3637 Added new metrics and dashboard for multitenant installations

- products/additional-images.yaml
- scripts/prepare-release.sh
[MGDAPI-3661](https://issues.redhat.com/browse/MGDAPI-3661)
Included extra images into the CSV.
1. Create cluster
2. In addons, install  Red Hat Openshift API Management.
3. Leave all the default values as they are.
4. In the rhoam yaml, add spec.useClusterStorage: 'true'
5. Run ```OLM_TYPE=managed-api-service SEMVER=1.21.0 make release/prepare``` 
6. Make sure the managed-api-service.clusterserviceversion.yaml contains the new images.
> MGDAPI-3661 / Added Additional images

- test/common/dashboards_exist.go
N/A
The `Verify middleware dashboards exist` test (E03) was broken for multitenant installs of RHOAM when a new dashboard was added for [MGDAPI-3637](https://issues.redhat.com/browse/MGDAPI-3637). This PR fixes E03 by checking if the install type is multitenant when comparing expected grafana dashboards.
Passing the automated tests should be sufficient. Alternatively, checkout this PR and install multitenant RHOAM then run the E03 test: `INSTALLATION_TYPE=multitenant-managed-api BYPASS_STORAGE_TYPE_CHECK=true TEST="E03" make test/e2e/single`
> MGDAPI-3637 Fixes test E03 for multitenant installations

- test/common/tests.go
- test/common/validate_resource_limits.go
[MGDAPI-3876](https://issues.redhat.com/browse/MGDAPI-3876)
New e2e test. It checks pods (see the `productsToTest` var) for valid requests and limits. Source of truth - quota config of active quota. It also ensures that the sidecar has requests and limits set. Right now the sidecar check will fail - limits will be introduced in [MGDAPI-3875](https://issues.redhat.com/browse/MGDAPI-3875). This test should be adjusted during the work on MGDAPI-3875. 
The test is included in a `HAPPY_PATH` suite for RHOAM only.
* Review the code
* Ensure that new tests passed on the PR
> MGDAPI-3876 add e2e test to validate resources on pods

- .codecov.yml
- test/common/multitenancy.go
- test/common/multitenancy_performance.go
- test/common/tests.go
- test/scripts/performance/mt02_verify_tenants_creation_performance.sh
Performance test that simulates 200 tenants created at once
https://issues.redhat.com/browse/MGDAPI-3627
1. Exising M01 test - `TestMultitenancy` allows you to create 2 tenants, as defined in `defaultNumberOfTestUsers`.
M01 updated - added env variable: `TENANTS_NUMBER`.   If `TENANTS_NUMBER env var is not defined - the number of tenants = defaultNumberOfTestUsers`
2. New Test created MT02 (common/multitenancy_performance.go) and new test script test/scripts/performance/mt02_verify_tenants_creation_performance.bash. Both for manual verification of Multitenants Performance. Tests allow to create large number of Tenants. Checked for 200 and 400 Tenants.
3. Testing report: https://docs.google.com/document/d/12fDMyoIyIBJ5Cy8YEWDLPAse1_Ai0dAW7a5neF78GOw/edit
1. Create cluster
2.  Install Rhoam …
> MGDAPI-3627 - Performance test that simulates 200 tenants created at once

- controllers/rhmi/bootstrapReconciler.go
- main.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/products/observability/prometheusRules.go
- pkg/resources/user/userHelper.go
- pkg/resources/user/userHelper_test.go
- test/common/alerts_exist.go
- test/common/multitenancy.go
JIRA: https://issues.redhat.com/browse/MGDAPI-3891
We need an alert that fires whenever a APIManagementTenant CR fails to reconcile. This PR creates a new metric `num_failed_tenants` and a new alert `ApiManagementTenantCRFailed`. The alert is only created for multitenant installations of RHOAM.
1. [Provision](https://qaprodauth.cloud.redhat.com/openshift/create) a non-CCS cluster
2. Checkout this PR and run `INSTALLATION_TYPE=multitenant-managed-api make cluster/prepare/local` on the command line once the cluster is ready
3. Create a CatalogSource either using `oc` or the GUI:
```yaml
metadata:
spec:
image: quay.io/ckyrillo/managed-api-service-index:1.22.0 …
```
> MGDAPI-3891 Added metric and alert to track failed APIManagementTenant CRs

- pkg/products/marin3r/prometheusRules.go
[MGDAPI-2589](https://issues.redhat.com/browse/MGDAPI-2589)
Changed alert threshold to 8 min from 5 min.
Install rhoam on cluster from this branch, make sure alert has changed to 8min.
> MGDAPI-2589 / Increased threshold duration for alert

- Makefile
- bundles/3scale-operator/bundles.yaml
- scripts/create-3scale-index.sh
[MGDAPI-3979](https://issues.redhat.com/browse/MGDAPI-3979)
- Added new bundles.yaml containing a list of all the 3scale bundle images used to build an index
- New script create-3scale-index which uses the bundle file and parameters to create an index
- Verify indexes can be successfully created by the script
note: I think it is best to verify the install / upgrade of these indices in the separate PR that changes the installation mode to use these indices.
~~[WIP] until referenced bundles exist.~~
> MGDAPI-3979 - add 3scale index build script

- products/installation.yaml
[MGDAPI-3979](https://issues.redhat.com/browse/MGDAPI-3979)
Update installation yaml to use 3scale-index instead of manifests.
- Install RHOAM is successful
- Upgrade completes successfully (maybe upgrade pipeline could be used?)
> MGDAPI-3979 - change install mode to use 3scale-index

- apis/v1alpha1/rhmi_types.go
- config/crd/bases/integreatly.org_rhmis.yaml
- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/bootstrapReconciler_test.go
[MGDAPI-3903](https://issues.redhat.com/browse/MGDAPI-3903)
- Added flag to the RHMI cr `AutoscalingEnabled`.
- Added logic to `bootstrapReconciler.go` to reconcile quota accordingly
- Added config map creation with HPA resource limits.
1. Provision a cluster large enough for a 50 Million quota install
2. Quota can be set to 20 mil or 50 mil for testing but ensure the cluster is large enough to handle a 50 mil install
3. Prepare your cluster as normal and then set quota with `INSTALLATION_TYPE=managed-api DEV_QUOTA="500" make cluster/prepare/quota`
4. Run the rhoam install and wait for the stage `complete`
5. Add the flag to the RHMI CR `autoscalingEnabled: true`, wait for bootstrap to reconcile and wait for quota to change to `50 Million` and stage `complete`. Set the flag to `false` or …
> MGDAPI-3903 Autoscaling RHMI CR Flag

- pkg/products/observability/prometheusRules.go
JIRA: https://issues.redhat.com/browse/MGDAPI-4133
This ticket's primary purpose was to fix Alertmanager on the DevSandbox stage and prod clusters so it would properly send emails when alerts were triggered. This required manually patching the credentials with proper values on each cluster and has since been completed and tested. However while investigating this, it was determined that the existing multitenant-specific alert that tracks failed APIManagementTenant CRs needed to be refactored.
Instead of firing whenever an APIManagementTenant CR reaches the `Won't Reconcile` `ProvisioningStatus`, the alert will now fire when a CR takes longer than 10 minutes to reach the `ThreeScaleAccountReady` `ProvisioningStatus`.
1. [Provision](https://qaprodauth.cloud.redhat.com/openshift/create) a …
> MGDAPI-4133 Refactored ApiManagementTenantCRFailed alert to be time based

- pkg/resources/ratelimit/envoy.go
- products/additional-images.yaml
https://issues.redhat.com/browse/MGDAPI-4148
Bump side car container image
```
make code/run
```
* Verify install complete successfully
* Verify image in used in annotations 
```
oc get dc apicast-production -n redhat-rhoam-3scale -o json | jq '.spec.template.metadata.annotations."marin3r.3scale.net/envoy-image"'
oc get dc apicast-staging -n redhat-rhoam-3scale -o json | jq '.spec.template.metadata.annotations."marin3r.3scale.net/envoy-image"'
oc get dc backend-listener -n redhat-rhoam-3scale -o json | jq '.spec.template.metadata.annotations."marin3r.3scale.net/envoy-image"'
```
* Run `./test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/test.sh` to ensure …
> MGDAPI-4148 - bump: envoy side car image

- apis/v1alpha1/rhmi_types.go
- manifests/integreatly-3scale/0.8.4/3scale-operator.clusterserviceversion.yaml
- manifests/integreatly-3scale/0.8.4/apps.3scale.net_apimanagerbackups.yaml
- manifests/integreatly-3scale/0.8.4/apps.3scale.net_apimanagerrestores.yaml
- manifests/integreatly-3scale/0.8.4/apps.3scale.net_apimanagers.yaml
- manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_activedocs.yaml
- manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_backends.yaml
- manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_custompolicydefinitions.yaml
- manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_developeraccounts.yaml
- manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_developerusers.yaml
- manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_openapis.yaml
- manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_products.yaml
- manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_tenants.yaml
- manifests/integreatly-3scale/0.8.4/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- manifests/integreatly-3scale/0.8.4/threescale-operator-controller-manager-metrics-service_v1_service.yaml
- manifests/integreatly-3scale/3scale.package.yaml
- products/installation.yaml
[MGDAPI-4145](https://issues.redhat.com/browse/MGDAPI-4145)
- Consume 3scale-index v0.8.4
- Add the manifests used for the release process
- Verify install / uninstall rhoam
- Test upgrading rhoam from 1.22 -> 1.23 (this PR) results in 3scale operator upgrade - use workload webapp to check for downtime
I have created the indices for upgrade testing, available here:
```
quay.io/acatterm/managed-api-service-index:1.22.0
quay.io/acatterm/managed-api-service-index:1.23.0
```
> MGDAPI-4145 - consume 3scale v0.8.4 index

- controllers/rhmi/prometheusRules.go
- pkg/products/observability/prometheusRules.go
- pkg/resources/sop_url.go
- test/common/alerts_exist.go
https://issues.redhat.com/browse/MGDAPI-4031
RHOAMIsInReconcilingErrorState is not working as expected.
Fixing the alert and bumping the severity of it to a critical level.
For the purpose of making the verification easier, I've built all the required bundles and indices, if you feel however that you would to build them yourself please don't hesitate to.
- Provision OSD cluster and be oc logged in into the cluster
- Run `INSTALLATION_TYPE=managed-api make cluster/prepare/local` from this branch against the cluster
- Create a catalog source for RHOAM built of this branch:
```
cat << EOF | oc apply -f - 
metadata:
spec:
image: …
```
> MGDAPI-4031 Reconciler Error Alert

- test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
[MGDAPI-4188](https://issues.redhat.com/browse/MGDAPI-4188)
I'm using `zsh` and noticed this issue can be fixed simply with putting quotes around the `jq` parameter
eye review is sufficient, ran it all in `zsh` without any issues.
> MGDAPI-4188: N10 fix: updated the commands to be compatible with zsh

- Makefile
- test-containers-managed-api.yaml
in [this PR](https://github.com/integr8ly/integreatly-operator/pull/2272) we agreed that this file will be generated dynamically and outside of our use it's no longer needed. This is the PR to remove that file.
> removed test-containers-managed-api because it is no longer needed

- pkg/products/grafana/reconciler.go
- pkg/products/monitoring/reconciler.go
- products/additional-images.yaml
n/a
Bump to Grafana proxy image
- osd cluster
- be oc logged in
- from this branch run
`INSTALLATION_TYPE=managed-api make cluster/prepare/local`
`INSTALLATION_TYPE=managed-api make code/run`
- wait for the installation to complete and verify that the Grafana pod under redhat-rhoam-customer-monitoring ns is using the `registry.redhat.io/openshift4/ose-oauth-proxy@sha256:9a5ee95f8e99a63a4ad0e8b01683ac03c75337bbbe3d504d199a97f9921eb0c1` as proxy image.
- verify that no alerts apart from DMS fired
- verify that you can access the Grafana dashboard under redhat-rhoam-customer-monitoring ns by navigating to routes under that namespace and opening the grafana route. Once in, click on manage and review the ratelimiting dashboard.
Upgrade will be done from the current MTR version to version 1.24 …
> MGDAPI-4241 bump Grafana oauth proxy image

- .codecov.yml
- hack/codecov.sh
- scripts/ci/unit_test.sh
https://issues.redhat.com/browse/MGDAPI-4266
The `coverpkg` flag was previously removed from the `go test ...` commands.
This caused the unit test coverage to drop significantly.
- Make sure all prow checks pass and that the coverage % has been restored back to normal levels
> [MGDAPI-4266] add coverpkg flag to the go test command

- pkg/resources/backup/aws_test.go
- pkg/resources/backup/backup_executor_test.go
- pkg/resources/backup/cronjob_test.go
[MGDAPI-4280](https://issues.redhat.com/browse/MGDAPI-4280)
Updated the `%w` with `%v`
Passing unit tests should be sufficient
> MGDAPI-4280 - fix errorf usage

- Makefile
- scripts/commits-check.sh
[MGDAPI-3097](https://issues.redhat.com/browse/MGDAPI-3097)
- Added a script and associated make target to check that all commits begin with a MGDAPI- ticket.
- Checkout PR
- Add some commits that fit or break the name structure
- `make commits/check`
> MGDAPI-3097 - add commit check function

- controllers/rhmi/rhmi_controller.go
- main.go
- pkg/metrics/metrics.go
- pkg/products/observability/prometheusRules.go
- test/common/alerts_exist.go
https://issues.redhat.com/browse/MGDAPI-4147
Create a metric and warning alert for when `rhmi_controller` Reconcile() takes longer than 12 mins
1. Create a fresh cluster and ocm log in to it
2. `INSTALLATION_TYPE=managed-api make cluster/prepare/local`
3. Create a catalog source pointing to my index where I added the following:
1. `time.Sleep(time.Minute * 3)` to this line to simulate an install delay https://github.com/integr8ly/integreatly-operator/blob/master/controllers/rhmi/rhmi_controller.go#L472
2. Tweaked the `RHOAMInstallationControllerReconcileLoopDelayed` alert to fire after 2 minutes, instead of 12, to save time
3. The rest of the code is the same as in the PR
```
metadata:
  name: …
```
> [MGDAPI-4147] add installation_controller_reconcile_duration_seconds metric and InstallationControllerReconcileLoopDelayed alert

- test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
- test-cases/tests/installation/a31-verify-installation-on-all-osd-versions.md
- test-cases/tests/installation/a34-verify-quota-values.md
- test-cases/tests/installation/a37-rhoam-on-rosa.md
- test-cases/tests/installation/a39-installation-verify-rhoam-on-private-cluster.md
- test-cases/tests/installation/a40-rhoam-on-osd-trial.md
- test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
- test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
- test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
[MGDAPI-4134](https://issues.redhat.com/browse/MGDAPI-4134)
Changed any step that required OCM UI (QE OCM permissions) to use OCM CLI
Read through the new steps and make sure that they are clear
Verify that the new CLI commands work.
1. Provision OSD trial Cluster, through [Jenkins](https://master-jenkins-csb-intly.apps.ocp-c1.prod.psi.redhat.com/job/ManagedAPI/job/managed-api-install-addon-flow/build?delay=0sec)
1.1  Set the ocmAccessToken to your own token, which can be found [here](https://qaprodauth.cloud.redhat.com/openshift/token/show#)
1.2   Check the osdTrial cluster checkbox
1.3 In pipeline steps check the provisionCluster and installProduct checkboxes , leave the rest empty 
1.4 Build the pipeline
2. Log in to OCM 
```bash
ocm login --url=https://api.stage.openshift.com …
```
> MGDAPI-4134 Changing OCM ui steps to OCM cli

- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssocommon/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
[MGDAPI-4311](https://issues.redhat.com/browse/MGDAPI-4311)
- Add check for `GrafanaDashboard` CRD in rhsso before continuing with installation
- Create cluster
- Complete installation
- Delete `GrafanaDashboard` CRD
- Should see reconcile events stating rhsso is awaiting `GrafanaDashboard` CRD
- RHMI CR will show awaiting components
> MGDAPI-4311 - add grafanadashboard CRD check to rhsso

- controllers/rhmi/rhmi_controller.go
- main.go
- pkg/metrics/metrics.go
- pkg/products/observability/prometheusRules.go
- test/common/alerts_exist.go
https://issues.redhat.com/browse/MGDAPI-4354
The alert that tracks if the rhmi controller reconcile function takes more than 12 minutes to complete was firing continuously which is not what we want. The issue was caused by not giving enough time to Prometheus to detect if the metric has a non-zero value. To address that I refactored the logic to not track the duration, but only track whether the function has completed in the specified time. The way this works is by using a goroutine which will execute in 12 minutes if the reconcile hasn't completed. The goroutine will be killed if the function completes before the timer runs out, so there's no possibility of false alerts.
> [MGDAPI-4354] improve reconcile delay tracking logic

- pkg/products/marin3r/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- pkg/resources/waitForResources.go
- pkg/resources/waitForResources_test.go
https://issues.redhat.com/browse/MGDAPI-4388
Wait for RHSSO postgres to be complete before provisioning other cloud resources
* Install RHOAM from this branch
* Verify other cloud resources are not provisioned until RHSSO postgres is complete
```
watch "oc get postgres -n redhat-rhoam-operator; oc get redis -n redhat-rhoam-operator; oc get blobstorage -n redhat-rhoam-operator"
```
> MGDAPI-4388 - fix: wait for rhsso postgres to be completed 

- test/functional/aws_rds_resources_exist.go
[MGDAPI-4373](https://issues.redhat.com/browse/MGDAPI-4373)
Eye review only. I validated this change during RHOAM v1.24.0 rc1 release testing. If you really want to try, have a RHOAM v1.24.0 cluster with useClusterStorage=false installed and execute:
INSTALLATION_TYPE=managed-api TEST=F01 make test/e2e/single
> MGDAPI-4373 Update expected postgres version in test

- scripts/commits-check.sh
[MGDAPI-4310](https://issues.redhat.com/browse/MGDAPI-4310)
Issue with commit check function - the git repo created by prow does not have remotes and performs a merge, making `git merge-base` return the current PR HEAD. This means the check is effectively skipped on every PR and will pass.
- Add environment variables that use the commit SHA's provided by prow
- Use these references to determine which commits belong to the PR
> MGDAPI-4310 - Fix commit check

- Makefile
- config/secrets/addon-params-secret.yaml
- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/resources/sts/sts.go
- pkg/resources/sts/sts_test.go
https://issues.redhat.com/browse/MGDAPI-1905
3Scale does not support STS mode of authentication with AWS, and we need to provide a temporary workaround.
Our workaround would be to ask customer to create an IAM account dedicated to 3Scale and pass credentials for this IAM account through two new addon parameters. This IAM account would allow access only to S3 bucket(s) with a predefined name(s). 
This logic is implemented in current PR
**STS Cluster**
- Prepare STS cluster
- Install Rhoam from this branch
- Open your cluster OSD UI
- Open Secret *addon-managed-api-service-parameters* in Project *redhat-rhoam-operator*
- Edit Secret, set your values for **s3-access-key-id** and **s3-secret-access-key** parameters
- Open Secret *s3-credentials* in Project *redhat-rhoam-3scale*
- Reveal …
> MGDAPI-1905 Implement a workaround for the lack of STS support in 3Scale

- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/bootstrapReconciler_test.go
https://issues.redhat.com/browse/MGDAPI-4458
It was noticed that alerts were firing and the rhmi cr was not reconciling in the following scenario: adding a custom domain parameter to the addon-params secret after 3scale has been installed.
In this scenario RHOAM should ignore the custom domain. It should fully reconcile RHOAM and no alerts should be firing. 
1. Provision/borrow an OSD cluster
2. `make cluster/prepare` from the master branch
3. Create a CatalogSource CR and install RHOAM from it:
```
oc apply -f - <<EOF
---
metadata:
spec:
image: quay.io/tdimov0/managed-api-service-index:1.25.0
EOF
```
4. Wait for the RHOAM installation to complete or at …
> [MGDAPI-4458] skip custom domain checks if 3scale is installed

- Makefile
- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/rhmi_controller.go
- controllers/rhmi/rhmi_controller_test.go
- controllers/rhmiconfig/helpers/update_status.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/ups/reconciler.go
- pkg/resources/marketplace/implicit_catalog_source_reconciler.go
- pkg/resources/marketplace/manifestHelper.go
- pkg/resources/openshift.go
- pkg/webhooks/webhook_register.go
- test/common/alerts_invalid_username.go
- test/common/user_dedicated_admin_synced_sso.go
- test/functional/multiaz_pod_distribution.go
- test/resources/codeready_login.go
- test/resources/oauth_proxy_auth.go
[MGDAPI-3795](https://issues.redhat.com/browse/MGDAPI-3795)
Removing G104 from gosec/exclude command showed a list of 22 unhandled errors. 
Error handling has been added in all cases.
1. On master branch edit makefile line 543 removing G104
2. Run make gosec/exclude command. This will show 22 issues.
3. Using this [PR,](https://github.com/integr8ly/integreatly-operator/pull/2782) run the gosec/exclude command which will show 0 issues.
> MGDAPI-3795 G104: Audit errors not checked. Error handling added where required. 

- controllers/tenant/apimanagementtenant_controller.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
JIRA: https://issues.redhat.com/browse/MGDAPI-4328
This PR updates the tenant reconciliation logic to confirm that the user's KeycloakUser and KeycloakClient CRs are reconciled and in a ready state before updating the APIManagementTenant CR to display the tenant's 3scale URL. This helps prevent the issue described in the JIRA ticket that was blocking the keycloak operator from running.
This fix has already been tested and deployed onto the stage and production RHOAM DeveloperSandbox clusters and was verified that it fixed the underlying issue on both. Therefore passing the e2e tests should be the only verification needed.
> MGDAPI-4328 Refactored tenant reconciliation logic to check that Keycloak CRs are ready

- Makefile
- test/common/selfmanaged_apicast.go
- test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go
[MGDAPI-3796](https://issues.redhat.com/browse/MGDAPI-3796)
- Changed how URLs are constructed with parameters in two tests
- Run `make gosec/exclude` from this branch and make sure there are no issues reported by gosec
> MGDAPI-3796: G107 Url provided to HTTP request as taint input

- Makefile
[MGDAPI-4309 ](https://issues.redhat.com/browse/MGDAPI-4309)
Support for login into OSD 4.11 clusters. 
You would need to verify that it is possible to login into 4.11 clusters as well as 4.10 clusters. The 4.11 oc client is required and can be downloaded from [here](https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.11.0-rc.2/)
1. Provision a cluster (current default for dev environment in 4.10.20 - will do nicely). 
2. Ensure you have 4.11 oc cli by `oc version`
3. Initiate installation 
4. Once reconcile loops have started - you were able to log into the cluster. 
1. Provision cluster. I've used elorean CLI for this. You could get the list of versions by `ocm get "/api/clusters_mgmt/v1/versions?size=2000" | jq '.items[] | select(.id | contains("nightly") | not).id | …
> MGDAPI-4309 token retrieval for 4.11 clusters

- test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
https://issues.redhat.com/browse/MGDAPI-4357
Fix script # 3 in Test E04B - Verify SLO dashboard - user-sso statefulset not scaling down
Issue was in doc (e04b-verify-slo-dashboard.md) of Manual test  `E04B - Verify SLO dashboard`, in script, `Code # 3 `
User-sso statefulset did not scale down, because of incorrect expected replicas number (`3`).
The fix was - change the number of expected replicas to `2` (`grep 2`  instead of `grep 3`).
It's a Manual test.
All test details are described in doc (file e04b-verify-slo-dashboard.md, in PR)
- To check that User-sso statefulset was scaled to zero:
$ oc get statefulset -n redhat-rhoam-user-sso
NAME READY AGE
keycloak 0/0 ....
-  Check Grafana Dashboard `Critical SLO summary`, see that user-sso panel shows the number of firing alerts.
(all panels …
> MGDAPI-4357 - Fix script #3 in Test E04B - Verify SLO dashboard - userr-sso statefulset not scaling down

- pkg/config/observability.go
- pkg/products/observability/reconciler.go
- test/common/pvc_validate.go
Implement persistent volume for alert manager
https://issues.redhat.com/browse/MGDAPI-3855
- It's new PR (instead of https://github.com/integr8ly/integreatly-operator/pull/2774). New PR is using OO v3.0.13 (OO includes fix of issue of duplicated Prometheus PVC in case of Upgrade)
- Implement persistent volume for alert manager
1. Check that Alertmanager PVC created in redhat-rhoam-observability namespace. For example:
```
$ oc get pvc -n redhat-rhoam-observability
NAME                                                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
alertmanager-alertmanager-db-alertmanager-alertmanager-0   Bound    pvc-214aa865-88bf-485f-8aa1-499635762fc9   1Gi        RWO            gp3            14m …
```
> MGDAPI-3855 - Implement persistent volume for alert manager

- test/common/3scale_smtp.go
https://issues.redhat.com/browse/MGDAPI-1729
The H34 functional test (verify 3scale custom SMTP full config) is failing on ROSA STS clusters installed using Jenkins pipeline [var installRhmi](https://gitlab.cee.redhat.com/integreatly-qe/ci-cd/-/blob/master/vars/installRhmi.groovy). The failure reason is that is still using the old rhmi stages structure, before single stage installation stage was introduced.
> MGDAPI-1729 fix H34 functional test

- test/functional/aws_elasticache_resources_exist.go
- test/functional/aws_rds_resources_exist.go
- test/functional/aws_s3_resources_exist.go
- test/functional/aws_shared_functions.go
- test/functional/aws_standalone_vpc.go
- test/functional/aws_strategy_override.go
[MGDAPI-3582](https://issues.redhat.com/browse/MGDAPI-3582)
- Add some checks to ensure that the resources have been tagged with `red-hat-managed` and the appropriate `red-hat-clustertype` if we are an STS cluster
- Fix some minor lint issues
Once you have some AWS credentials login with:
```
aws configure
```
Ensure you have the `rosa` cli and are logged into ocm, and from the related delorean branch integr8ly/delorean#279 create a cluster filling in appropriate settings:
```
CLUSTER_NAME=mycluster-sts AWS_REGION=us-east-1 make ocm/sts/cluster/create
```
Run the following to create the prereq roles:
```
CLUSTER_NAME=mycluster-sts AWS_REGION=us-east-1 make ocm/sts/rhoam-prerequisites
```
The output will include an ARN for the `rhoam_role` and the `functional_test_role`
You can then start …
> MGDAPI-3582 - Add checks for tags in e2e tests

- Dockerfile.functional
- Dockerfile.osde2e
- Makefile
- test/e2e/suite_test.go
- test/functional/suite_test.go
- test/osde2e/suite_test.go
[MGDAPI-4404
](https://issues.redhat.com/browse/MGDAPI-4404)
In Gingko v2 the default timeout was changed from 24hr to 1hr. This was not long enough, therefore we needed to specify a new timeout in the test suites. The timeout has been updated to 90 minutes. 
Ensuring that this PR is passing the automated tests along with reviewing the changed files should be sufficient verification.
> MGDAPI-4404 Increased timeout for all tests

- Makefile
- README.md
- config/rbac-local-rhoam/kustomization.yaml
- config/rbac-local-rhoam/patches/auth_proxy_role_binding.yaml
- config/rbac-local-rhoam/patches/leader_election_role_binding.yaml
- config/rbac-local-rhoam/patches/role_binding.yaml
- envs/managed-api.env
- envs/multitenant-managed-api.env
[MGDAPI-3923](https://issues.redhat.com/browse/MGDAPI-3923)
Addition of a new `LOCAL` variable. If set to true will change the namespace name to local-rhoam-operator
Changed default  `INSTALLATION_TYPE` value to managed-api 
Verify that you can install RHOAM locally and via OLM and that it works as expected (All products install successfully)
1. Local install 
1.1 Checkout this branch 
1.2 run `make cluster/prepare/local`
1.3 run `make code/run`
1.4 make sure that RHOAM installs as expected
2. OLM install guide
2.1 install RHOAM via OLM - [guide](https://github.com/RHCloudServices/integreatly-help/blob/master/guides/olm/installing-rhmi-bundle-format.md#installing-rhmi-through-olm-with-bundle-format)
2.2 make sure that RHOAM installs as expected
> MGDAPI-3923

- test-cases/tests/installation/a34-verify-quota-values.md
- test-cases/tests/installation/a38-installation-verify-rhoam-on-nonbyoc-cluster.md
- test-cases/tests/installation/a40-rhoam-on-osd-trial.md
- test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
- test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
- test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
[MGDAPI-4422](https://issues.redhat.com/browse/MGDAPI-4422)
While working on MGDAPI-4422  the command to retrieve the cluster-ID didn't work , this was because the display name was slightly different from the name. Seen as the openshift URL uses the actual name I think we should retrieve the cluster id by it name rather than the display  name
make sure the new command works
```
CLUSTER_ID=$(ocm get clusters --parameter search="name like '<CLUSTER_NAME>'" | jq -r '.items[0].id')
echo $CLUSTER_ID
```
Should return ID of  desired cluster
> MGDAPI-4422 Updating command to use cluster name instead of display_name

- controllers/rhmi/rhmi_controller.go
JIRA: https://issues.redhat.com/browse/MGDAPI-4287
As part of [MGDAPI-4150](https://github.com/integr8ly/integreatly-operator/pull/2729) (which squashed the installation stages into one stage), a small [function](https://github.com/integr8ly/integreatly-operator/pull/2729/files#diff-239eca6331989433c0101fe047f78aa8ce2dab5047a733719972e99206a6d9faR1686-R1692) was added to  `rhmi_controller.go` which removed the old installation stages in order to cover upgrade scenarios. Now that this work is complete, that function should be removed before the next release.
Passing the e2e tests should be sufficient verification but this PR can also be verified by installing RHOAM locally and/or via OLM. Then after verifying that the installation completed successfully, delete the rhmi CR and verify that …
> MGDAPI-4287 Removed code that deleted old stages during upgrade to 1.24 since no longer needed

- test/common/alerts_invalid_username.go
- test/common/user_dedicated_admin_synced_sso.go
[MGDAPI-4530
](https://issues.redhat.com/browse/MGDAPI-4530)
cleanUpTestDedicatedAdminUsersSyncedSSO function has been refactored to poll the keycloak user cr to ensure it has been deleted as expected.
- This can be verified by successfully running the test suite(or specifically B09 and C19) on a cluster with RHOAM installed.
> MGDAPI-4530 refactoring tests regarding deletion of users

- docs/custom_domain.md
https://issues.redhat.com/browse/MGDAPI-4504
Updated the custom domain guide location. 
* checkout branch locally 
* run `make mkdoc/serve`
* navigate to http://127.0.0.1:8000/custom_domain
* Check:
* Side bar navigation links to all sections within the guide.
* hyper links in the guide are still working
* There is no poorly or incorrectly formatted section in the guide.
> MGDAPI-4504 : Move custom domain guide for mkdocs support

- config/manager/manager.yaml
- main.go
[MGDAPI-4474](https://issues.redhat.com/browse/MGDAPI-4474)
Adding Liveness and Readiness probes. Using `ls` for both of them. 
1. Generate new index (or you could reuse `quay.io/mvavilov/rhoam-index:2.0.0`) - here is a [guide](https://github.com/RHCloudServices/integreatly-help/blob/master/guides/olm/installing-rhmi-bundle-format.md). You would also need to build your own rhoam image. 
2. Install RHOAM via bundles  
3. Once the pod was created `oc describe pod $(oc get pods -n redhat-rhoam-operator | grep 'rhmi-operator' | awk '{print $1}') -n redhat-rhoam-operator | grep -E 'Liveness|Readiness'` to check probes are present.
> MGDAPI-4474 add health probes to rhmi pod

- Makefile
- README.md
- controllers/rhmi/rhmi_controller.go
- openshift-ci/Dockerfile.tools
- pkg/products/observability/prometheusRules.go
- pkg/resources/sop_url.go
- prometheus-unit-testing/rules/rhoam_general.yml
- prometheus-unit-testing/tests/critical_metrics_missing.yml
- test/common/alerts_exist.go
https://issues.redhat.com/browse/MGDAPI-4407
- Create/borrow an OSD cluster
- Log in to the cluster
- Prepare the cluster:
```
```
- Deploy an RHMI resource:
```
LOCAL=false make deploy/integreatly-rhmi-cr.yml
```
- Install the RHOAM operator from my image: `quay.io/tdimov0/managed-api-service-index:1.26.0`
- Observe the alert `RHOAMCriticalMetricsMissing`. It may go into pending state for a brief period of time during fresh install/upgrade until all critical metrics become available, but it must not fire at any point
- After ensuring no alerts are firing and the RHOAM installation has completed, simulate a scenario where the alert must fire by scaling down the RHOAM operator deployment to 0:
```
oc patch deployment …
```
> MGDAPI-4407 critical metrics missing alert & prometheus unit tests

- controllers/rhmi/bootstrapReconciler.go
[MGDAPI-4578
](https://issues.redhat.com/browse/MGDAPI-4578)
deleteObsoleteService function has been refactored for rhoam in order to remove the rhmi-operator-metrics service if present as it is no longer needed and has been replaced by rhoam-operator-metrics service. This functionality is only required until all versions of rhoam are bumped to 1.27.
- Install RHOAM
- Create a fake service called rhmi-operator-metrics in the installation namespace via OSD.
- Verify that rhoam has deleted this service.
> MGDAPI-4578 delete rhmi-operator-metrics service

- Makefile
- config/secrets/custom-addon-secret.yaml
- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/bootstrapReconciler_test.go
- pkg/resources/custom-domain/custom-domain.go
https://issues.redhat.com/browse/MGDAPI-4498
In the bootstrap reconciler, there is no check for the domain parameter to be an empty string. Because of this, if an empty string is in the domain field in the addon parameters secret, the bootstrap reconciler will set the installation as a custom domain installation. 
This will prevent the installation from completing due to being an invalid domain.
What should happen is that if there custom domain is empty on installation, the default cluster route should be used instead
* Passing prow checks with e2e passing should be sufficient
However if you want to do a manual verification:
```
make code/run
```
* Verifiy installation completes …
> MGDAPI-4498 - fix: prevent using custom domain when addon param is empty string

- products/products.yaml
https://issues.redhat.com/browse/MGDAPI-4594
products/products.yaml was updated to support Productised RHSSO
Run following commands and check that it's working correctly
OLM_TYPE=managed-api-service SEMVER=1.28.0 make release/prepare
TYPE_OF_MANIFEST=master OLM_TYPE=managed-api-service  make manifest/prodsec
> MGDAPI-4594 - Update products/products.yaml - for productised RHSSO

- controllers/rhmi/rhmi_controller.go
- controllers/rhmi/rhmi_controller_test.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/cloudresources/reconciler_test.go
[MGDAPI-1727](https://issues.redhat.com/browse/MGDAPI-1727)
Remove arn checks as the secret is now created by a credentialsRequest in managed tenants 
The steps taken to install the addon with the feature branch
1. install the addon on an sts cluster with the rosa cli
```bash
rosa install addon --cluster <cluster_name> managed-api-service -y --cidr-range 10.1.0.0/26 --notification-email <your_email>@redhat.com --addon-managed-api-service 10 --addon-resource-required true --s3-access-key-id <aws_access_key> --s3-secret-access-key <aws_access_secret>
```
2. Patch the rhoam operator CSV with the following rbac (due to the bundle in the old addon not having these rbac permissions)
```yaml
- apiGroups: 
- operator.openshift.io
resources: 
- cloudcredentials
verbs: 
- get
- list
- watch
- …
```
> MGDAPI-1727 remove arn checks from feature branch for sts

- pkg/resources/ratelimit/envoy.go
- products/additional-images.yaml
https://issues.redhat.com/browse/MGDAPI-4749
Bump to envoy image to latest available
- provision OSD cluster
- run `INSTALLATION_TYPE=managed-api make cluster/prepare/local LOCAL=false`
- create catalog source:
```
metadata:
spec:
image: quay.io/mstoklus/managed-api-service-index:1.27.0
EOF
```
- install RHOAM via operator hub under rhoam namespace
- run `INSTALLATION_TYPE=managed-api USE_CLUSTER_STORAGE=true make deploy/integreatly-rhmi-cr.yml`
- wait for installation to complete
- update catalogue source to point to quay.io/mstoklus/managed-api-service-index:1.28.0
- wait for upgrade to complete
- scale down rhoam operator
- …
> MGDAPI-4749 bump envoy image

- config/rbac/role.yaml
- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/rhmi_controller.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/grafana/reconciler.go
- pkg/products/marin3r/reconciler.go
- pkg/products/marin3r/reconciler_test.go
- pkg/products/observability/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/resources/limitRange.go
- pkg/resources/limitRange_test.go
JIRA: https://issues.redhat.com/browse/MGDAPI-4727
In order to support RHOAM on autoscaled clusters, we need to provide a way to assign default CPU/memory request values for every pod/container that doesn't explicitly set them. This is required by the OpenShift autoscaler so it can accurately calculate each node's resource requirements which is a prerequisite for the autoscaler to scale up/down nodes as needed.
We can enforce default CPU/memory request values by creating a LimitRange object in each namespace that RHOAM manages. Note that the LimitRanges are intentionally set to only request a small amount of resources for each container (5m of CPU and 10 Mi of memory) . This is because certain containers need significantly less resources than others and the LimitRange enforces defaults …
> MGDAPI-4727 Added LimitRanges to each Namespace managed by RHOAM

- pkg/products/cloudresources/prometheusRules.go
- pkg/resources/metrics.go
- pkg/resources/sop_url.go
- test/common/alerts_exist.go
https://issues.redhat.com/browse/MGDAPI-4485
In an effort to help with root cause analysis of CRO alerts ensure that alerts do not fire due to missing or absent CRO metrics. Instead create a separate alert that will fire when metrics are absent.
- Provision an AWS CCS cluster
- Prepare the cluster and install RHOAM from the latest stable version `v1.27.0`:
```
git checkout tags/rhoam-v1.27.0 -b rhoam-v1.27.0
make cluster/prepare/local LOCAL=false
metadata:
spec:
image: quay.io/tdimov0/managed-api-service-index:1.27.0
EOF
make deploy/integreatly-rhmi-cr.yml LOCAL=false USE_CLUSTER_STORAGE=false
```
- Install the RHOAM operator …
> MGDAPI-4485 create alert for absent cro metrics

- pkg/products/monitoringcommon/dashboards/criticalSLOAlerts.go
- pkg/products/monitoringcommon/dashboards/errorBudgetBurnSLOAlerts.go
https://issues.redhat.com/browse/MGDAPI-4551
Reduce the Error Budget and SLO % dashboard to 7 days to align with weekly SRE / program updates
- Run the integreatly-operator locally
- Check that the following dashboards are updated from 28d to 7d:
- Critical SLO summary
- SLO SSO Availability - 5xx HAProxy Errors
- Additional verifications will have to be carried out on eng-long-lived once the changes go live and run for a few days ([JIRA](https://issues.redhat.com/browse/MGDAPI-4762))
> MGDAPI-4551 reduce the error budget and slo % dashboards to 7d

- controllers/subscription/subscription_controller.go
- controllers/subscription/subscription_controller_test.go
[MGDAPI-4355](https://issues.redhat.com/browse/MGDAPI-4355)
- Added new function which will update Postgres and Redis CRs to signify whether or not database updates are allowed
- Added unit test for this function
> **Note**: The new field `allowUpdates` is needed from CRO (via CRO Release and vendor updates) before tests will pass
> MGDAPI-4355: Allow configuration of CRO maintenance window

- .golangci.yaml
- Makefile
https://issues.redhat.com/browse/MGDAPI-4595
Configured the installation of `golangci-lint` binary.
Added linter presets and disabled all failing linters (temporary).
In subsequent tasks, the disabled linters will have to be re-enabled as we fix the issues that cause the failures.
- Run the lint make command:
```
make test/lint
```
- It should install the `golangci-lint` binary to the `bin` folder of your project if it doesn't already exist there
- The output of running the linting should be empty. If it isn't, there's a problem...
> MGDAPI-4595 add golangci-lint checks

- test/common/selfmanaged_apicast.go
- test/common/tests.go
[https://issues.redhat.com/browse/MGDAPI-3772](url)
Introduce a way to skip the Product removal call here:
[https://github.com/integr8ly/integreatly-operator/blob/3b24a8d67fb0c2af8ca6502ff7bd593e69ad5bf2/test/common/selfmanaged_apicast.go#L125](url)
E.g. something like:
LOCAL=false INSTALLATION_TYPE=managed-api SKIP_CLEANUP=true TEST=H24 make test/e2e/single
It is possible to run the H24 tests without Product removal.
Update the H24 test case to use this SKIP_CLEANUP env var
> MGDAPI-3772 introduced env var to allow skip cleanup

- pkg/products/grafana/reconciler.go
- products/additional-images.yaml
https://issues.redhat.com/browse/MGDAPI-4847
Bump oauth proxy image to latest available
* Verify customer grafana is still acessible using latest image
> MGDAPI-4847 - bump: oauth proxy image

- controllers/subscription/subscription_controller.go
- controllers/subscription/subscription_controller_test.go
- pkg/products/threescale/reconciler_test.go
- pkg/resources/ratelimit/envoy.go
- test/common/multitenancy.go
- test/common/tests.go
- test/common/validate_resource_requirements.go
JIRA: https://issues.redhat.com/browse/MGDAPI-4639
This PR includes 3 discrete changes which can be identified by their different commits:
1. Adds a function called `addResourceRequests()` to the 3scale reconciler that annotates the `apicast-production`, `apicast-staging`, and `backend-listener` DeploymentConfigs in order to set CPU/memory requests.
2. Adds a new e2e test called `ValidateResourceRequirements` which verifies that every container created in a RHOAM namespace has explicitly set values for CPU/memory requests.
3. Refactors the subscription_controller reconciler to **not** overwrite the `Resources` field in the Subscription's `Config` block with an empty struct `{}`
1. Checkout this PR
2. Provision an OSD cluster
3. Prepare the cluster by running: …
> MGDAPI-4639 - Add resource requests to Envoy sidecars and new e2e test

- apis/v1alpha1/rhmi_types.go
- bundles/rhsso-operator/bundles.yaml
- manifests/integreatly-rhsso/7.6.0-10/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.0-10/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.0-10/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.0-10/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.0-10/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.0-10/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/7.6.1-3/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.1-3/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.1-3/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.1-3/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.1-3/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.1-3/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/rhsso.package.yaml
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssouser/reconciler_test.go
- products/additional-images.yaml
- products/installation.yaml
JIRA: https://issues.redhat.com/browse/MGDAPI-4813
Updates RHSSO operator from `7.6.0-8` -> `7.6.0-10` -> `7.6.1-3`
1. Provision cluster
2. Checkout rhoam-v1.28.0: `git checkout tags/rhoam-v1.28.0`
3. Build RHOAM operator, bundle, and index images for rhoam-v1.28.0 and push them to your quay org
4. Prepare the cluster for the installation: `INSTALLATION_TYPE=managed-api LOCAL=false make cluster/prepare/local`
5. Install RHOAM via OperatorHub (OLM install)
6. Create the RHMI CR: `INSTALLATION_TYPE=managed-api USE_CLUSTER_STORAGE=true LOCAL=false IN_PROW=true make deploy/integreatly-rhmi-cr.yml`
7. Wait for the installation to complete
8. Check out this PR
9. Build RHOAM operator, bundle, and index images for rhoam-v1.29.0 and push them to your quay org
10. Update the CatalogSource to point …
> MGDAPI-4813 Update RHSSO operator to 7.6.1-3

- Makefile
- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
https://issues.redhat.com/browse/MGDAPI-4706
We want to have the CRO and 3scale namespaces to be created by Hive to speed up the sync sts secrets and subsequently the install itself.
However, the permission scope needs to be expanded when the namespace is externally created rather than by the Operator.
* Checkout this branch and install operator
```
make code/run
```
* Verify installation is successful
* Delete the RHMI CR and verify uninstall is successfull
* Prow e2e test for RHOAM and Multitenant is successfull
> MGDAPI-4706 - increase permissions for when ns is created by hive

- test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
- test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/test.sh
https://issues.redhat.com/browse/MGDAPI-4894
3scale does not support using templates for custom policies. The H24 test case needs to be updated accordingly.
It would be good to follow the steps to see if they are clear enough for somebody not so familiar with custom policy but just eye review might suffice. We will see during release testing.
> MGDAPI-4894 Updated H24 custom policy test case

- bundles/managed-api-service/1.30.0/manifests/managed-api-service.clusterserviceversion.yaml
https://issues.redhat.com/browse/MGDAPI-4706
Add missing permissions in CSV that is preventing OLM installs working correctly if release scipt is not run
* Prepare cluster
```
INSTALLATION_TYPE=managed-api make cluster/prepare LOCAL=false
```
* Install via OLM using following catalog source:
```
quay.io/kevfan/managed-api-service-index:1.30.0
```
* Deploy RHMI CR
```
make deploy/integreatly-rhmi-cr.yml
```
* Verify installation completes successfully
* Delete RHMI CR
* Verify uninstallation completes successfully
> MGDAPI-4706 - csv: add missing permissions

- pkg/addon/operator_run.go
- pkg/addon/operator_run_test.go
- pkg/products/observability/reconciler_test.go
https://issues.redhat.com/browse/MGDAPI-4942
change rhoam from hive.openshift.io/managed label to rhoam.addon.install/managed
- build operator image from this branch or use quay.io/austincunningham/managed-api-service:v1.30.0 
- start a rhoam addon install
- from the integreatly-operator repo set the following env var and run the patch-image-csv.sh script
```bash
export VERSION=v1.30.0
export ADDON_VERSION=v1.29.0
export ORG=austincunningham
export USE_CLUSTER_STORAGE=true
./scripts/patch-image-csv.sh
```
- You should see the script complete successfully
```bash
./scripts/patch-image-csv.sh
clusterserviceversion.operators.coreos.com/managed-api-service.v1.29.0 patched
clusterserviceversion.operators.coreos.com/managed-api-service.v1.29.0 patched
Verificaton the CSV has been patched : …
```
> MGDAPI-4942 change hive.openshift.io/managed label to rhoam.addon.install/managed

- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/bootstrapReconciler_test.go
https://issues.redhat.com/browse/MGDAPI-4909
make sure randomize strings are generated, and add a check to re randomize them if they already exist
- Install this branch from local
- once rhoam is installed go to the redhat-rhoam-operator namespace in the UI
- go to the `oauth-client-secrets`
- confirm the secrets are randomized 
- edit the 3scale value to be all the same character
e.g.
- it should revert to a randomized secret in time. This will handle the secrets in upgrade.
> MGDAPI-4909 make sure to randomize strings, and add a check to re randomize them

- scripts/prepare-release.sh
JIRA: https://issues.redhat.com/browse/MGDAPI-4920
This PR reverts a previous change to the `prepare-release.sh` script. Before the script supported mulitenant RHOAM, it would move the generated `bundle.Dockerfile` to `bundles/$OLM_TYPE/$VERSION` directory regardless of the `OLM_TYPE`. However when the script was refactored for MT RHOAM, it was changed to only move the `bundle.Dockerfile` when the `OLM_TYPE` was `managed-api-service`. This conditional isn't necessary and so we can include the bundle.Dockerfile in the `bundles/multitenant-managed-api-service/$VERSION` folder from now on. We don't need to retroactively add the `bundle.Dockerfile` into the existing multitenant bundle directories - adding it for future bundles is all we need.
1. Checkout the master branch of integreatly
2. …
> MGDAPI-4920 Updated prepare release script to also move bundle.Dockefile for MT RHOAM

- config/configmap/cro-configmaps.yaml
- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/bootstrapReconciler_test.go
- docs/tests/workshop.md
- mkdocs.yml
https://issues.redhat.com/browse/MGDAPI-4906
Add in the workshop type to the cloud-resource-config.
Used for creating on cluster Redis and Postgres for test cases.
- Prepare your cluster, run RHOAM locally and await installation complete:
```
LOCAL=false make deploy/integreatly-rhmi-cr.yml
LOCAL=false make code/run
```
- Create a `workshop` Postgres instance and await its completion:
```
cat << EOF | oc create -f - -n redhat-rhoam-operator                   
apiVersion: integreatly.org/v1alpha1
kind: Postgres
metadata:
name: throw-away-postgres
labels:
productName: productName
spec:
secretRef:
name: throw-away-postgres-sec
tier: development
type: workshop
EOF
```
- Proceed with cleanup and await its completion:
```
oc delete postgres …
```
> MGDAPI-4906 restore workshop type cloud resource config

- pkg/products/threescale/reconciler.go
https://issues.redhat.com/browse/MGDAPI-5013
Fixing A34 test by improving how the apim reconciliation works
Install RHOAM from this branch
Run A34 test case against the cluster
Confirm test passes
Checks on this PR are green
> MGDAPI-5013 fix apim recon

- test/functional/aws_elasticache_resources_exist.go
https://issues.redhat.com/browse/MGDAPI-4729
Only checked for managed tag for elasticache instances for sts clusters
* Ensure F03 passes on non sts ccs install
```
LOCAL=false NAMESPACE=redhat-rhoam-operator TEST=F03 make test/e2e/single
```
> MGDAPI-4729 - fix: F03 - only check for managed tag for sts clusters

- bundles/3scale-operator/bundles.yaml
- go.mod
- go.sum
- manifests/integreatly-3scale/0.11.0-mas/3scale-operator.clusterserviceversion.yaml
- manifests/integreatly-3scale/0.11.0-mas/apps.3scale.net_apimanagerbackups.yaml
- manifests/integreatly-3scale/0.11.0-mas/apps.3scale.net_apimanagerrestores.yaml
- manifests/integreatly-3scale/0.11.0-mas/apps.3scale.net_apimanagers.yaml
- manifests/integreatly-3scale/0.11.0-mas/capabilities.3scale.net_activedocs.yaml
- manifests/integreatly-3scale/0.11.0-mas/capabilities.3scale.net_applications.yaml
- manifests/integreatly-3scale/0.11.0-mas/capabilities.3scale.net_backends.yaml
- manifests/integreatly-3scale/0.11.0-mas/capabilities.3scale.net_custompolicydefinitions.yaml
- manifests/integreatly-3scale/0.11.0-mas/capabilities.3scale.net_developeraccounts.yaml
- manifests/integreatly-3scale/0.11.0-mas/capabilities.3scale.net_developerusers.yaml
- manifests/integreatly-3scale/0.11.0-mas/capabilities.3scale.net_openapis.yaml
- manifests/integreatly-3scale/0.11.0-mas/capabilities.3scale.net_products.yaml
- manifests/integreatly-3scale/0.11.0-mas/capabilities.3scale.net_proxyconfigpromotes.yaml
- manifests/integreatly-3scale/0.11.0-mas/capabilities.3scale.net_tenants.yaml
- manifests/integreatly-3scale/0.11.0-mas/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- manifests/integreatly-3scale/0.11.0-mas/threescale-operator-controller-manager-metrics-service_v1_service.yaml
- manifests/integreatly-3scale/3scale.package.yaml
- products/installation.yaml
- vendor/modules.txt
[MGDAPI-4810](https://issues.redhat.com/browse/MGDAPI-4810)
- Updated go.mod to latest commit
- Add 3scale operator v0.11.0-mas
- Removal of two bundles that were causing errors when building fresh (they are entirely pruned from dependency tree by replaces/skip)
> MGDAPI-4810 - Add 3scale-operator.v0.11.0-mas

- .golangci.yaml
- controllers/namespacelabel/namespacelabel_controller.go
- controllers/rhmi/bootstrapReconciler_test.go
- openshift-ci/test/e2e/suite_test.go
- pkg/products/grafana/reconciler.go
- pkg/products/marin3r/rateLimitService_test.go
- pkg/products/monitoringspec/reconciler_test.go
- pkg/products/observability/reconciler_test.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssocommon/reconciler_test.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/products/threescale/asserts_test.go
- pkg/products/threescale/objects_test.go
- pkg/resources/cluster_test.go
- pkg/resources/ratelimit/envoy.go
- pkg/resources/user/userHelper.go
- test/common/3scale_smtp.go
- test/common/grafana_routes.go
- test/common/namespace_restoration.go
- test/common/rhmicr_metrics.go
- test/common/routes_exist.go
- test/common/scale_up_replicas_rhsso.go
- test/common/validate_resource_requirements.go
- test/e2e/suite_test.go
- test/functional/multiaz_pod_distribution.go
- test/functional/suite_test.go
- test/osde2e/suite_test.go
- test/resources/oauth_proxy_auth.go
https://issues.redhat.com/browse/MGDAPI-4599
Enabled the `unused` golangci-lint linter and fixed all existing errors found by it.
Verify all prow checks are passing
> MGDAPI-4599 enable unused golangci-lint linter

- pkg/products/threescale/clients_test.go
- pkg/products/threescale/filters.go
- pkg/products/threescale/filters_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/products/threescale/three_scale_client.go
- pkg/products/threescale/three_scale_moq.go
https://issues.redhat.com/browse/MGDAPI-4549
This add a filter to ensure that the routes used for the dns bypass alerts are from an active tenant. 
* Install the current master of the operator via OLM. Index: quay.io/jfitzpat/managed-api-service-index:1.30.0-4549
* Create muitly tenants in 3scale.
* Check the routes in the 3scale namespace. If the system-provider and system-developer routes for the created tenants are listed above the default routes. In 3scale UI delete the tenants belonging to the routes.
* Expected: alerts for DnsBypassThreeScaleDeveloperUI or DnsBypassThreeScaleSystemAdminUI shoud start firing.
* Allow alert to go into a firing state before moving onto the upgrade verification
* Use index quay.io/jfitzpat/managed-api-service-index:1.31.0-4549
* Allow upgrade to finish …
> MGDAPI-4549 : Add filter for active tenants to dns bypass metrics

- bundles/managed-api-service/1.30.0/manifests/managed-api-service.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/grafana/reconciler.go
- pkg/products/marin3r/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/products/threescale/reconciler.go
- pkg/resources/k8s/objectQueries.go
- pkg/resources/k8s/objectQueries_test.go
- pkg/resources/reconciler.go
- pkg/resources/reconciler_test.go
https://issues.redhat.com/browse/MGDAPI-4655
The priority field for the rhmi-operator pod is currently set to 0 (the lowest possible value). This means that if there weren't enough free resources on a cluster, the rhmi-operator pod would be one of the first things to be scaled down in order to free up resources.
Audited the relevant pods created by RHOAM and standardized their priority values where needed.
- Provision an OSD cluster
- Prepare the cluster and install RHOAM from the latest stable version `v1.29.0`:
```
git checkout tags/rhoam-v1.29.0 -b rhoam-v1.29.0
make cluster/prepare/local LOCAL=false
metadata:
spec:
image: …
```
> MGDAPI-4655 apply priorityClassName to all rhoam crs

- Dockerfile.external
- build/bin/setup_external.sh
- make/functional.mk
- test/functional/suite_test.go
[MGDAPI-4471](https://issues.redhat.com/browse/MGDAPI-4471)
Repackaged the `Dockerfile.functional` file by changing the base image to include the `oc-cli` and made some other changes resulting in our test suite now being able to be ran from an image independent of delorean
run `make image/external/build` and take the image hash
have a cluster ready and fill in the `OPENSHIFT_HOST` and `OPENSHIFT_PASSWORD` credentials appropriately
```
docker run  -it \
-e OPENSHIFT_HOST='<openshift api url>' \
-e OPENSHIFT_PASSWORD='<password>' \
-e MULTIAZ=false \
-e DESTRUCTIVE=false \
-e NUMBER_OF_TENANTS='2' \
-e TENANTS_CREATION_TIMEOUT='3' \
-e RegExpFilter=''" \
-e OUTPUT_DIR=test-run-results
-v rhoam-test-run-results:/<same_as_OUTPUT_DIR> \
<image id>
```
I validated it working correctly by first …
> MGDAPI-4471 - Add support for running the functional test suite externally

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
https://issues.redhat.com/browse/MGDAPI-5001
- Bumped the version of keycloak-metrics-sbi to 2.5.3
- Added this configurations: https://github.com/aerogear/keycloak-metrics-spi#external-access
- Checkout this branch:
```
gh pr checkout 3058
```
- Install RHOAM on an OSD cluster by running the operator locally and wait for it to complete:
```
LOCAL=false make code/run
```
- Verify both keycloak pods in the rhsso and user sso namespaces have the new environment variable set. The output should be 4 identical entries with value `TRUE`:
```
oc get pods -n redhat-rhoam-rhsso -o json | jq '.items[].spec.containers[].env[] | select(.name == "DISABLE_EXTERNAL_ACCESS")'
oc get pods -n redhat-rhoam-user-sso -o json | jq '.items[].spec.containers[].env[] | …
```
> MGDAPI-5001 bump keycloak-metrics-sbi version

- pkg/products/threescale/reconciler.go
https://issues.redhat.com/browse/MGDAPI-4974
add the ability to overwrite the wildcard domain in the apimanager CR
- Run this branch against a cluster locally
- Wait for the install to finish
- Edit the apimanager CR in the redhat-rhoam-3scale NS
```yaml
spec:
wildcardDomain: <change this to anything doesn't have to be a valid domain> 
```
- The change should remain
> MGDAPI-4847 add logic to override wildcard domain in apimanger cr

- bundles/managed-api-service/1.31.0/manifests/managed-api-service.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
https://issues.redhat.com/browse/MGDAPI-5079
With https://issues.redhat.com/browse/MGDAPI-4706 some namespaces are now created externally and this change missed a permission for multi az clusters
* Provision multi az cluster
```
make code/run
```
* Verify install completes and there's no error on the CR
```
oc get rhmi rhoam -n local-rhoam-operator -o jsonpath={.status.stage}
oc get rhmi rhoam -n local-rhoam-operator -o jsonpath={.status.lastError}
```
> MGDAPI-5079 - fix: missing permssion for balancing pods

- controllers/rhmi/bootstrapReconciler.go
[MGDAPI-4582
](https://issues.redhat.com/browse/MGDAPI-4582)
Removing the deleteObsoleteService function which is no longer needed.
Not sure if verification is needed, this is what I did before removing the code - 
- Installed RHOAM locally 
`INSTALLATION_TYPE=managed-api LOCAL=false make cluster/prepare/local`
`INSTALLATION_TYPE=managed-api LOCAL=false make code/run`
Ensured that the "rhmi-operator-metrics" service has not been created/does not exist: 
- removed the code in question.
> MGDAPI-4582 removed deleteObsoleteService function

- scripts/prepare-release.sh
MGDAPI-5125
Reverted the change to finding kustomize as release pipeline is failing on `which`
> MGDAPI-5125 - revert release-prepare kustomize change

- openshift-ci/Dockerfile.tools
- openshift-ci/test/run
https://issues.redhat.com/browse/MGDAPI-5135
Installing kustomize into the path. This will fix the prow test/scripts failures.
The test script check will fail. These changes need to be merged before prow can make use of the change.
* Build the openshift-ci container image.
`podman build -f openshift-ci/Dockerfile.tools -t openshift-ci`
* Check that kustomize is in the path
`podman run --rm --entrypoint=/bin/sh openshift-ci -c 'which kustomize'`
> MGDAPI-5126 Ensure Kustomize is in path

- pkg/products/mcg/prometheusRules.go
- pkg/products/mcg/reconciler.go
- pkg/products/mcg/reconciler_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
[MGDAPI-5085](https://issues.redhat.com/browse/MGDAPI-5085)
Add alerts for various MCG resources - requires rebase once #3052 is merged.
Provision a GCP CCS cluster - if you do not have an access key,  request one from myself - place in root of delorean repo and run:
```
OCM_CLUSTER_NAME=acatterm-ccs OCM_CLUSTER_LIFESPAN=24 COMPUTE_NODES_COUNT=4 BYOC=true CLOUD_PROVIDER=gcp make -f make/ocm.mk ocm/cluster.json
make -f make/ocm.mk ocm/cluster/create
```
Once provisioned we can deploy RHOAM from this branch:
```
LOCAL=false USE_CLUSTER_STORAGE=true make code/run
```
Navigate to alerting in `redhat-rhoam-observability` namespace:
Networking -> Routes -> Prometheus (location) -> Alerts
Verify that the alerts are listed and are not firing.
* …
> MGDAPI-5085 - Add alerting for MCG on GCP

- test/functional/aws_rds_resources_exist.go
JIRA: https://issues.redhat.com/browse/MGDAPI-5092
Updates the `verifyRDSInstanceConfig()` function to check that the Postgres RDS engine is `13.8` instead of `13.4` following changes made in this [CRO PR](https://github.com/integr8ly/cloud-resource-operator/pull/621)
- Eye review and passing the e2e prow checks should be sufficient
> MGDAPI-5092 Fixed F01 test after switching from Postgres 13.4 to 13.8

- .golangci.yaml
- pkg/products/cloudresources/prometheusRules.go
- pkg/products/marin3r/reconciler.go
- pkg/products/monitoringcommon/alertmanagerConfig.go
- pkg/products/monitoringcommon/alertmanagerConfig_test.go
- pkg/products/observability/prometheusRules.go
- pkg/products/rhssocommon/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/resources/metrics.go
- test/functional/aws_elasticache_resources_exist.go
- test/osde2e/pre-test.go
JIRA: https://issues.redhat.com/browse/MGDAPI-4603
This PR fixes the existing S1039("unnecessary use of fmt.Sprintf") errors that were previously not checked by the gosimple linter and enables the linter to check for these errors going forward.
An eye review of the changes and passing prow checks should be sufficient verification but if you want to manually verify:
- Run `make test/lint` and confirm there are no errors in the output
> MGDAPI-4603 Fixed S1039 issues caught by gosimple linter

- test/common/namespace_restoration.go
https://issues.redhat.com/browse/MGDAPI-4456
Fix watches on installation stages
Test on both managed-api and multitenant-managed-api.
* Install the operator for the installation type
* Follow the test case for [J03B](https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md)
* Expected result: test case should pass for insatallation type.
Repeated above steps for each installation type.
> MGDAPI-4456 Fix installation stage watches for J03

- pkg/products/threescale/prometheusRules.go
[MGDAPI-5096](https://issues.redhat.com/browse/MGDAPI-5096)
Update 3scale operator metrics endpoint
* Deploy RHOAM from master
* Scale down 3scale-operator deployment
* After some time, see that the alert `RHOAMThreeScaleOperatorServiceEndpointDown` does not fire
</br>
* Deploy RHOAM from this branch
* Scale down 3scale-operator deployment
* After some time, see alert `RHOAMThreeScaleOperatorServiceEndpointDown` firing
> MGDAPI-5096 - fix 3scale operator metrics location

- bundles/managed-api-service/1.31.0/manifests/managed-api-service.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- pkg/products/threescale/clients_test.go
- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/products/threescale/three_scale_client.go
- pkg/products/threescale/three_scale_moq.go
- pkg/resources/podHelper.go
- pkg/resources/pod_executor_moq.go
- pkg/resources/smtp.go
- pkg/resources/smtp_test.go
https://issues.redhat.com/browse/MGDAPI-5000
Set outgoing email address as oulined in the following guide. https://access.redhat.com/solutions/4112341
* Install this branch, pre-built index: quay.io/jfitzpat/managed-api-service-index:1.32.0-5000
* Set up extra tenants after the install, [guide](https://gitlab.cee.redhat.com/rhcloudservices/integreatly-help/-/blob/master/sops/3scale_create_tenants.md)
* Follow the [knowledge article](https://access.redhat.com/solutions/4112341) 
* Check what the current value for the email is.
* Change the current email to something else. 
** The reonciler should revert all email address to the initial values. 
* Make sure to check the UI for the extra tenants
> MGDAPI-5000 : Set Outgoing email address

- test/functional/aws_shared_functions.go
- test/functional/aws_standalone_vpc.go
https://issues.redhat.com/browse/MGDAPI-3562
Updated [test A25](https://github.com/integr8ly/integreatly-operator/blob/52a4634ee77e24ab8cbedfa6943cb2338227e8b4/test/functional/aws_standalone_vpc.go#L132) so it will pass when run against RHOAM installed on BYOVPC cluster
- Provision an AWS BYOVPC CCS cluster, as well as regular AWS CCS cluster
- Install RHOAM on both clusters
- Run the A25 functional test against both clusters and confirm they both pass
> MGDAPI-3562 update test a25 to be compatible with byovpc clusters

- test-cases/tests/installation/a28-verify-pod-priority-class-name-is-set-on-products.md
- test/common/priority_validate.go
- test/common/types.go
https://issues.redhat.com/browse/MGDAPI-5090
Refactored the A27/A28 E2E test which deal with RHOAM reconciling the pod priority specified in the RHMI CR spec to the relevant resources. For background information why this was implemented refer to this JIRA: https://issues.redhat.com/browse/MGDAPI-4655
- Provision an OSD cluster
- Install RHOAM from this branch
- Run the A27/A28 E2E test
- Ensure it passes
> MGDAPI-5090 ensure rhoam pod priority is reconciled after installation

- products/additional-images.yaml
https://issues.redhat.com/browse/MGDAPI-5218
Removed unsupported docker.io image
Not required, reach out to me directly for more info
> MGDAPI-5218 comment out docker.io image

- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/bootstrapReconciler_test.go
https://issues.redhat.com/browse/MGDAPI-5222
If any error happen during the initial reconcile loop the status block for the custom domain may not get set.
Changes here allow the custom domain status block to be reconciled will not reconciling the sub domain route. Understand the linked SOP for why the sub domain route is not reconciled. 
* Install this branch with a custom domain enabled
* Guide: https://integreatly-operator.readthedocs.io/en/latest/products/custom_domain/
* Expected: Status block for custom domain is added to the rhmi CR. 
* may take multiply reconcile loops to happen
> MGDAPI-5222 : Fix custom domain status block not being reconciled.

- pkg/products/threescale/reconciler.go
https://issues.redhat.com/browse/MGDAPI-5232
Selection of master route was based on the URL containing `apps`. This may not be the case when using a custom domain.
* Install this branch using a custom domain that **DOES NOT** start with `apps.`
* custom domain guide: https://integreatly-operator.readthedocs.io/en/latest/products/custom_domain/
* Expected: 
* In the rhmi CR the `routingSubdomain` will equal the custom domain
* Install will go to a complete state
* The custom domain status block will be missing from the rhmi CR. This PR does not include the changes from https://github.com/integr8ly/integreatly-operator/pull/3109
**operator:** quay.io/jfitzpat/managed-api-service:rhoam-v1.33.0-5232
**index:** quay.io/jfitzpat/managed-api-service-index:1.33.0-5232
> MGDAPI-5232 : Fix route selection based on route prefix to route labels

- pkg/products/threescale/envoyconfig.go
[MGDAPI-5242](https://issues.redhat.com/browse/MGDAPI-5242)
Updated the [route timeout](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#route-timeouts) to 75s to match the [APIcast](https://github.com/3scale/APIcast/blob/master/doc/parameters.md#http_keepalive_timeout) `HTTP_KEEPALIVE_TIMEOUT`.
- Deploy RHOAM from master with a backend configured with the base URL set to https://reqres.in:443/
- Perform a CURL request to the end point with a delay > 15s and notice that the requests timeout
```
time curl -kv "https://api-3scale-apicast-staging.apps.acatterm.icod.s1.devshift.org/api/users?delay=29&user_key=<REDACTED>"
*   Trying 52.205.155.224:443...
* Connected to api-3scale-apicast-staging.apps.acatterm.icod.s1.devshift.org (52.205.155.224) port 443 (#0)
* ALPN: …
```
> MGDAPI-5242 - extend route timeout to 75s

- pkg/resources/ratelimit/envoy.go
- products/additional-images.yaml
https://issues.redhat.com/browse/MGDAPI-5249
Bump envoy proxy image for better image grading
```
make code/run
```
* Verify install complete successfully
* Verify image in used in annotations 
```
oc get dc apicast-production -n redhat-rhoam-3scale -o json | jq '.spec.template.metadata.annotations."marin3r.3scale.net/envoy-image"'
oc get dc apicast-staging -n redhat-rhoam-3scale -o json | jq '.spec.template.metadata.annotations."marin3r.3scale.net/envoy-image"'
oc get dc backend-listener -n redhat-rhoam-3scale -o json | jq '.spec.template.metadata.annotations."marin3r.3scale.net/envoy-image"'
```
* Run `./test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/test.sh` to ensure …
> MGDAPI-5249 - ratelimit: bump envoy proxy image

- controllers/tenant/apimanagementtenant_controller.go
- pkg/products/observability/prometheusRules.go
[https://issues.redhat.com/browse/MGDAPI-4763](url)
Add verification to the controller to ensure that the user does not have an APIManagementTenant CR already in either the dev or stg namespace. If they do add a warning to the second CR informing them that they can not have more than 1 APIManagementTenant CR
1.  Create cluster
2. Run Operator locally
2.1 `INSTALLATION_TYPE=multitenant-managed-api LOCAL=false make cluster/prepare/local`
2.2 `INSTALLATION_TYPE=multitenant-managed-api LOCAL=false make code/run`
2.3 Command for check RHOAM installation status `oc get rhmi rhoam -n sandbox-rhoam-operator -o yaml`
3. Setup IDP `./scripts/setup-sso-idp.sh`
4. You need to create APIManagementTenant CR with test-user or customer-admin. You need to setup permissions for them with command: `oc adm …
> MGDAPI-4763 Ensure a tenant can only create 1 APIManagementTenant CR

- Makefile
- test/common/alerts_firing.go
- test/common/shared_functions.go
https://issues.redhat.com/browse/MGDAPI-5193
The https://issues.redhat.com/browse/MGDAPI-1404 no longer causes alerts to fire - at least not right after the RHOAM installation so it should be safe to run these tests.
However, the UIBBT alerts are firing in Prow (possibly a limitation of Prow environment). This PR skips the alert tests if running in Prow. Ideal solution would be to ignore the UIBBT alerts if in Prow not skipping the whole tests but this is better than having these tests skipped in non-Prow environment as it is the case now.
For even more context read https://chat.google.com/room/AAAAssKWhTI/h5DeT583XH4
Eye review only, passing rhoam-e2e should suffice.
> MGDAPI-5193 Unskip alert tests

- apis/v1alpha1/rhmi_types.go
- bundles/3scale-operator/bundles.yaml
- manifests/integreatly-3scale/0.11.1-mas/3scale-operator.v0.11.1-mas.clusterserviceversion.yaml
- manifests/integreatly-3scale/0.11.1-mas/apps.3scale.net_apimanagerbackups.yaml
- manifests/integreatly-3scale/0.11.1-mas/apps.3scale.net_apimanagerrestores.yaml
- manifests/integreatly-3scale/0.11.1-mas/apps.3scale.net_apimanagers.yaml
- manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_activedocs.yaml
- manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_applications.yaml
- manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_backends.yaml
- manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_custompolicydefinitions.yaml
- manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_developeraccounts.yaml
- manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_developerusers.yaml
- manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_openapis.yaml
- manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_products.yaml
- manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_proxyconfigpromotes.yaml
- manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_tenants.yaml
- manifests/integreatly-3scale/0.11.1-mas/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- manifests/integreatly-3scale/0.11.1-mas/threescale-operator-controller-manager-metrics-service_v1_service.yaml
- manifests/integreatly-3scale/3scale.package.yaml
- products/installation.yaml
Update 3scale bundle to 0.11.1-mas
This is an automatically generated branch to track the '0.11.1-mas' version of the '3scale' bundles.
This branch will be automatically updated with any changes related to this version until it finally GAs.
Changes required to fix installation issues should be applied to this branch following the usual [PR Workflow](https://github.com/integr8ly/delorean/blob/master/docs/integrealy-ci/prow-pr-workflow.md)
More details about the Early Warning System that generated this can be found [here](https://github.com/integr8ly/delorean/tree/master/docs/ews)
> 3scale update to 0.11.1-mas

- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/grafana/reconciler.go
- pkg/products/marin3r/reconciler.go
- pkg/products/marin3r/reconciler_test.go
- pkg/products/observability/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/resources/marketplace/manager.go
- pkg/resources/marketplace/manager_test.go
https://issues.redhat.com/browse/MGDAPI-5299
* Ensure namespace and operator namespace is correctly written to config 
* Allow operator group to be updatable
```
make code/run
```
* Verify installation completes successfully
* Add `test` as an addition namespace to the targetNamespaces to the `rhmi-registry-og` OperatorGroup in the `edhat-rhoam-customer-monitoring-operator` namespace
* Verify it is reconciled back
* Change the `grafana.Namespace` value to `test` in the `redhat-rhoam-installation-config` config map in the `redhat-rhoam-operate`namespace 
* Verify it is reconciled back
> MGDAPI-5299 - fix: OperatorGroup not being updated on namespace change

- pkg/products/observability/reconciler.go
- pkg/products/observability/reconciler_test.go
https://issues.redhat.com/browse/MGDAPI-5328
Observaility was failing to install on fresh clusters due to the Cluster Logging CRDs did not exist on the cluster as it was never installed. 
The cleanup logic errors due to this and prevents the installation from completing.
```
failed installation of observability: no matches for kind \"ClusterLogging\" in version \"logging.openshift.io/v1\"
```
* On a cluster, ensure none of the cluster logging crds exists
* Delete if they do exist
```
oc get crds | grep logging
```
* Install RHOAM from this branch
```
export LOCAL=false                                                                                                  
make code/run 
```
* Verify installation completes successfully
```
oc get …
```
> MGDAPI-5328 - fix: installation of OO on fresh clusters without cluster logging previously installed

- pkg/products/cloudresources/reconciler.go
[MGDAPI-5446](https://issues.redhat.com/browse/MGDAPI-5446)
Adding the new service update with id elasticache-20230315-001 to the list of updates CRO should push out during RHOAM upgrade.
Review of code change.
> MGDAPI-5446 Apply redis update

- pkg/products/threescale/prometheusRules.go
JIRA: https://issues.redhat.com/browse/MGDAPI-5373
This PR increases the duration that the RHOAMThreescaleCriticalMetricsMissing alert needs to occur before firing from 15 minutes to 30 minutes. This is to reduce toil on CSSRE. 
Passing the PROW checks should be sufficient verification.
> MGDAPI-5373 Increased duration of RHOAMThreescaleCriticalMetricsMissing alert to 30m

- controllers/rhmi/bootstrapReconciler.go
- test/common/rhmicr_metrics.go
https://issues.redhat.com/browse/MGDAPI-5281
Ensure if custom domain is configured via the SOP route on a cluster that never had a custom domain initial installed.
This also should apply to if a custom is configured back to the standard route.
**Current Master:** quay.io/jfitzpat/managed-api-service-index:1.33.0-5281
**Updated Version:** quay.io/jfitzpat/managed-api-service-index:1.34.0-5281 (marked as service affecting for testing)
**SOP:** [Change the Wildcard-domain in an existing RHOAM install](https://gitlab.cee.redhat.com/rhcloudservices/integreatly-help/-/blob/master/sops/rhoam/ChangeWildcardDomainRhoam/ChangeWildcardDomainRhoam.md)
**Dev Guide:** [Configuring custom domain](https://integreatly-operator.readthedocs.io/en/latest/products/custom_domain/)
* Make a note of the …
> MGDAPI-5281 Improvements to Custom Status Block

- products/products.yaml
https://issues.redhat.com/browse/MGDAPI-5315
Fix 3scale version in `products.yaml` to point to correct tag 
* https://github.com/3scale/3scale-operator/tags
Prodsec manifests are also likely missing 3scale dependencies due to this:
```
15:09:13  warning: Could not find remote branch v2.13.0 to clone.
15:09:13  fatal: Remote branch v2.13.0 not found in upstream origin
15:09:13  go: go.mod file not found in current directory or any parent directory; see 'go help modules'
15:09:28  Host key verification failed.
15:09:28  fatal: Could not read from remote repository.
```
* Passing prow checks and eye review is sufficient
> MGDAPI-5315 - fix: 3scale version in products.yaml

- pkg/products/cloudresources/prometheusRules.go
[MGDAPI-5277](https://issues.redhat.com/browse/MGDAPI-5277)
Adding DefaultPostgresAllocatedStorageMetricName to the CRO Missing Metric Alert.
cro_postgres_free_storage_average and cro_redis_memory_usage_percentage_average had already been added.
Once the cluster is ready checkout this PR:
`gh pr checkout 3168`
- Build and push the RHOAM binary
```
ORG=<Your Quay Org> OLM_TYPE=managed-api-service INSTALLATION_TYPE=managed-api make image/build/push 
```
- Edit the managed-api-service.clusterserviceversion.yaml to refer to your image
- Build bundle and index images
```
ORG=<Your Quay Org> OLM_TYPE=managed-api-service UPGRADE=false BUNDLE_VERSIONS=1.34.0 make create/olm/bundle
```
- Create a catalog source
Login to the OSD UI and create a catalog source that points to your index image:
``` …
```
> MGDAPI-5277 Add metrics for critical alerts to CROMissingMetricsalert

- pkg/products/cloudresources/prometheusRules.go
[MGDAPI-5547](https://issues.redhat.com/browse/MGDAPI-5547)
Update to PostgresAllocatedStorageMetricName as defined in CRO V1.0.0
In this case the code review should be sufficient, but if you want you could run the following verification steps:
Once the cluster is ready checkout this PR:
`gh pr checkout 3179`
- Build and push the RHOAM binary
```
ORG=<Your Quay Org> OLM_TYPE=managed-api-service INSTALLATION_TYPE=managed-api make image/build/push 
```
- Edit the managed-api-service.clusterserviceversion.yaml to refer to your image
- Build bundle and index images
```
ORG=<Your Quay Org> OLM_TYPE=managed-api-service UPGRADE=false BUNDLE_VERSIONS=1.34.0 make create/olm/bundle
```
- Create a catalog source
Login to the OSD UI and create a catalog source that points to your index image:
``` …
```
> MGDAPI-5547 Update to PostgresAllocatedStorageMetricName

- pkg/products/marin3r/apiUsagePrometheusRules.go
[MGDAPI-1787](https://issues.redhat.com/browse/MGDAPI-1787)
This PR updates wording in RHOAMApiUsageLevel3ThresholdExceeded alert message
Once the cluster is ready checkout this PR:
`gh pr checkout 3183`
- Build and push the RHOAM binary
```
ORG=<Your Quay Org> OLM_TYPE=managed-api-service INSTALLATION_TYPE=managed-api make image/build/push 
```
- Edit the managed-api-service.clusterserviceversion.yaml to refer to your image
- Build bundle and index images
```
ORG=<Your Quay Org> OLM_TYPE=managed-api-service UPGRADE=false BUNDLE_VERSIONS=1.34.0 make create/olm/bundle
```
- Create a catalog source
Login to the OSD UI and create a catalog source that points to your index image:
```
metadata:
namespace: …
```
> MGDAPI-1787 Update wording in RHOAMApiUsageLevel3ThresholdExceeded

- Makefile
- config/secrets/addon-params-secret.yaml
- pkg/products/cloudresources/reconciler.go
- pkg/products/cloudresources/reconciler_test.go
[MGDAPI-5300](https://issues.redhat.com/browse/MGDAPI-5300)
Consume new addon parameters from RHOAM that specify maintenance date and time. This includes maintenance day and maintenance hour parameters that will be added as part of [MGDAPI-5301](https://issues.redhat.com/browse/MGDAPI-5301). 
Code review for this PR but can be tested properly as part of [MGDAPI-5301](https://issues.redhat.com/browse/MGDAPI-5301).
> MGDAPI-5300 Consume GCP maintenance addon parameter in RHOAM

- pkg/products/threescale/envoyconfig.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/resources/ratelimit/envoy.go
- pkg/resources/ratelimit/envoyconfig.go
- products/additional-images.yaml
https://issues.redhat.com/browse/MGDAPI-5089
Add gRPC support in envoy
Bump envoy image to latest available
Pre-reqs:
- OSD cluster
Install the current version of RHOAM:
- Navigate to marketplace ns and to CatalogSource CRs
- Create new CR:
```
metadata:
spec:
image: quay.io/mstoklus/managed-api-service-index:1.34.0
```
- Prepare the cluster for RHOAM installation
```
INSTALLATION_TYPE=managed-api LOCAL=false make cluster/prepare/local
```
- Navigate to the OperatorHub under redhat-rhoam-operator ns
- Find RHOAM
- Install RHOAM operator under redhat-rhoam-operator ns
- Create RHMI CR:
```
INSTALLATION_TYPE=managed-api USE_CLUSTER_STORAGE=true LOCAL=false …
```
> MGDAPI-5089 add grpc support and bump envoy image

- .golangci.yaml
- pkg/products/marin3r/rateLimitService.go
- test/functional/aws_elasticache_resources_exist.go
[MGDAPI-4601](https://issues.redhat.com/browse/MGDAPI-4601)
This PR addresses all issue shown from the gosimple linter with error code S1008
In this case the code review of the changes should be sufficient, but if you want you could manually verify it by the following verification steps:
- Run `make test/lint`
- Confirm that there are no errors in the output
> MGDAPI-4601 Fix S1008 linter errors

- pkg/client/sigs_clientset.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/cloudresources/reconciler_test.go
[MGDAPI-5301](https://issues.redhat.com/browse/MGDAPI-5301)
Allowing rhoam to use correct cidr-range param from OCM.
- Provision a GCP cluster
- From the master branch of the Delorean repo create a file in the root of the repo called 
gcp_service_account.json. Request GCP credentials and add these to this file.
- Run make -f make/ocm.mk ocm/cluster.json BYOC=true CLOUD_PROVIDER=gcp
- Edit the cluster.json file to update the name (and remove the expiration timestamp if necessary).
- Run make ocm/cluster/create
- Prepare the cluster, patching the `addon-managed-api-service-parameters` secret and install RHOAM 
```
echo -n "10.1.0.0/22" | base64 | xargs -I {} oc patch secret addon-managed-api-service-parameters -n redhat-rhoam-operator --type=json …
```
> MGDAPI-5301 update to use different cidr-range param depending on platform type

- pkg/products/mcg/reconciler.go
https://issues.redhat.com/browse/MGDAPI-5688
MCG had been using default values for memory and cpu requirements. RHOAM does not need these to be so high therefore they were reduced.
- Install as fresh install on cluster and confirm that the resources allocated to nooba-core, nooba db resources and endpoints are as low as they can be.
> MGDAPI-5688 reduce resources required for mcg

- mkdocs.yml
[MGDAPI-5654](https://issues.redhat.com/browse/MGDAPI-5654)
Updating mkdocs.yml file so that link to locust info is included on Integreatly read the docs site.
> MGDAPI-5654 updating mkdocs.yml

- pkg/products/monitoringcommon/dashboards/croResources.go
- pkg/resources/metrics.go
https://issues.redhat.com/browse/MGDAPI-5512
There is a discrepency is metric value for `cro_postgres_max_memory` which causes an alert to be fired for only GCP installs. This is due to the AWS provider uses MiB whereas GCP provider uses bytes for this metric.
https://github.com/integr8ly/cloud-resource-operator/pull/677 handles the conversion to bytes for the `cro_postgres_max_memory` metric for the AWS provider. This will use bytes as the standard for this metric.
With this change, there is no longer a need to handle conversion of this metric in alerts or dashboards
* Code review and passing prow checks should be sufficient
> MGDAPI-5512 - refactor: remove conversion of cro_postgres_max_memory metric to bytes

- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssocommon/reconciler_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/resources/constants/croConstants.go
- pkg/resources/rhsso.go
- pkg/resources/rhsso_test.go
[MGDAPI-5072](https://issues.redhat.com/browse/MGDAPI-5072)
Enable snapshotting for GCP using the SnapshotFrequency and SnapshotRetention on Postgres CR's.
From the master branch of the [Delorean](https://github.com/integr8ly/delorean) repo create a file in the root of the repo called gcp_service_account.json. Request GCP credentials and add these to this file. Adjust this command to suit your needs, it will generate a config at ocm/cluster.json:
```sh
OCM_CLUSTER_NAME=acatterm-ccs OCM_CLUSTER_LIFESPAN=24 COMPUTE_NODES_COUNT=4 BYOC=true CLOUD_PROVIDER=gcp make -f make/ocm.mk ocm/cluster.json
```
Once you have checked the ocm/cluster.json, create the cluster:
```sh
make -f make/ocm.mk ocm/cluster/create
```
Run RHOAM with these changes:
``` …
```
> MGDAPI-5072 - configure snapshotting for GCP

- pkg/config/threescale.go
- pkg/config/threescale_test.go
- pkg/products/threescale/reconciler.go
[MGDAPI-5691](https://issues.redhat.com/browse/MGDAPI-5691)
Configures the default value for the Redis CR `Spec.Size` on GCP for 100M quota
Installing RHOAM on a GCP cluster from this branch with 100M quota results in the threescale backend redis CR to have `Spec.Size` set to 11.
> MGDAPI-5691 - set Redis size for 100M on GCP

- Makefile
- config/hive-config/package.yaml
[MGDAPI-5729](https://issues.redhat.com/browse/MGDAPI-5729)
[MGDAPI-5733](https://issues.redhat.com/browse/MGDAPI-5733)
Updating Makefile and adding config file to create Package CR which in turn creates the following via an MTB repo image:
* ClusterRole `rhoam-prometheus-ext`
* ClusterRoleBinding `rhoam-prometheus-ext`
* MonitoringStack `rhoam`
* ServiceMonitor `openshift-monitoring-federation`
* Provision a cluster
* Prepare the required image:
Checkout this [MR](https://gitlab.cee.redhat.com/service/managed-tenants-bundles/-/merge_requests/974) in the MTB repo and follow steps in the [setup.md file](https://gitlab.cee.redhat.com/service/managed-tenants-bundles/-/merge_requests/974/diffs#d551017d6b0321552069f3dcdc09cd8bae8a5ba7). Alternatively you can use the image I have prepared: …
> MGDAPI-5729 Create MonitoringStack CR in redhat-rhoam-operator

- controllers/subscription/subscription_controller.go
- controllers/subscription/subscription_controller_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
[MGDAPI-5136](https://issues.redhat.com/browse/MGDAPI-5136)
Fixes a bug with maintenanceWindow flag cycling on fresh installs of service affecting RHOAM versions. Further investigation still needed to cover upgrade scenarios. 
One problem I stumbled upon was `threescale-backend-redis-rhoam` not going back to 1 after the change like all the 5 other CR's, but going from ~200 to 55 `generation`s in the same time span, the number wasn't increasing with time as I checked on it so it's likely just 3scale reconciling.
Fresh install:
- Follow [RHOAM OLM Install guide](https://integreatly-operator.readthedocs.io/en/latest/installation_guides/olm_installation) to create a service affecting release based on one of our existing releases (Include the tag in the manifest just like …
> MGDAPI-5136 fixed maintenance window spam bug on fresh install

- Makefile
[MGDAPI-5759](https://issues.redhat.com/browse/MGDAPI-5759)
Remove the 3scale and CRO namespaces using the `make cluster/cleanup` command.
- Provision a cluster
- Log in to the cluster `ocm_cluster_login`
- Prepare the cluster 
```
```
Here you can see that the namespaces were created:
- Clean up the cluster
```
LOCAL=false make cluster/cleanup
```
- Make sure `redhat-rhoam-3scale` and ` redhat-rhoan-cloud-resources-operator` namespaces were deleted:
- Delete the cluster
> MGDAPI-5759 - remove namespaces with make cluster/cleanup

- pkg/resources/marketplace/manager.go
https://issues.redhat.com/browse/MGDAPI-5758
Set resources in the subscription so that the resources values are not taken form the CSV's
* install RHOAM 1.36
* check resources on operators in, resources should be set
* 3scale
* marin3r
* observability
* upgrade to this branch
* recheck the resources on the operators
* EXPECTED: resources set to the namespace default which does not include values for the limits.
> MGDAPI-5758 : set subscription resources to be empty

- Makefile
- test/common/routes_exist.go
- test/common/shared_functions.go
- test/common/tests.go
- test/e2e/integretly_test.go
- test/functional/integreatly_test.go
- test/osde2e/managed_api_test.go
JIRA: [MGDAPI-5783](https://issues.redhat.com/browse/MGDAPI-5783)
The e2e prow checks([example](https://github.com/integr8ly/integreatly-operator/pull/3235)) are failing when run on the OBO [feature branch](https://github.com/integr8ly/integreatly-operator/tree/mgdapi-5727-obo) because the prow checks are run on OCP clusters and OCP clusters don't have the package-operator (or OBO) installed by default. In order to get around this, we need to move any tests that rely on any observability components into a new test suite. We will then only run that test suite when the IN_PROW [environment variable](https://github.com/integr8ly/integreatly-operator/blob/mgdapi-5727-obo/Makefile#L17) is set to false. We also want to update the Makefile to only run …
> MGDAPI-5783 refactored some of the e2e tests for OBO

- Dockerfile.external
https://issues.redhat.com/browse/MGDAPI-5143
ROSA private link pipeline uses the test external image to run tests. It was discovered that `oc` is not there - or to be more precise a rather old `oc` is there.
Here's the update so that a newer version of oc is used.
ORG=yourOrg make image/external/build
podman run --rm -it --entrypoint=/bin/bash quay.io/yourOrg/integreatly-operator-test-external:latest
oc version
Output should be
Client Version: 4.13.0-202304190216.p0.g92b1a3d.assembly.stream-92b1a3d
Kustomize Version: v4.5.7
Optional - you can actually run the tests against the cluster:
```
rm -rf  ./test-run-result
mkdir test-run-result
podman run -it -e OPENSHIFT_HOST='https://api.cluster.s1.devshift.org:6443' -e OPENSHIFT_PASSWORD='kubeadminPassword' -e MULTIAZ=false -e …
```
> MGDAPI-5143 Update oc in test external image

- scripts/alerts-check.sh
https://issues.redhat.com/browse/MGDAPI-5377
It needs to be possible for the script to do its job even if triggered before RHOAM installation starts on the cluster. That way it is possible to use the script to monitor firing/pending alerts during the whole time of RHOAM installation.
I validated this in Playground:
https://master-jenkins-csb-intly.apps.ocp-c1.prod.psi.redhat.com/job/Playground/job/trepel/job/rosa-install-alerts-check/7/artifact/alerts-408/
- as you can see the script waited for RHMI CR and Prometheus route as expected (408-alerts-check.log)
- csv files with firing/pending alerts were created as well
If you want to validate manually, run the script against clean cluster (RHOAM not installed, you need to do oc login first). It should keep running. Trigger the RHOAM …
> MGDAPI-5377 alerts-check.sh can be triggered before RHOAM is installed

- pkg/resources/ratelimit/envoy.go
- products/additional-images.yaml
- test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/test.sh
https://issues.redhat.com/browse/MGDAPI-5867
Bump envoy proxy image for better image grading
```
make code/run
```
* Verify install complete successfully
* Verify image in used in annotations 
```
oc get dc apicast-production -n redhat-rhoam-3scale -o json | jq '.spec.template.metadata.annotations."marin3r.3scale.net/envoy-image"'
oc get dc apicast-staging -n redhat-rhoam-3scale -o json | jq '.spec.template.metadata.annotations."marin3r.3scale.net/envoy-image"'
oc get dc backend-listener -n redhat-rhoam-3scale -o json | jq '.spec.template.metadata.annotations."marin3r.3scale.net/envoy-image"'
```
* Open new go workspace in test folder
* Run `./scripts/products/h22-validate-that-rate-limit-service-is-workin …
> MGDAPI-5867 update envoy image

- pkg/products/cloudresources/reconciler.go
[MGDAPI-5834](https://issues.redhat.com/browse/MGDAPI-5834)
Add the new service update with id `elasticache-redis-6-2-update` to the list of updates.
Eye review of the changes should be sufficient, but you can confirm by following the steps:
1. Once the cluster is ready checkout this PR
2. Install RHOAM
3. Deploy the Workload App on the cluster by running the following commands:
3.1 Login to the RHOAM cluster using `oc login` command
3.2 Set `export GRAFANA_DASHBOARD=true` 
3.3 Run this command to deploy the app: `make local/deploy`
4. Check that there is no downtime
4.1 In the OSD UI navigate to the `redhat-rhoam-observability` project
4.2 On the left hand side choose Networking -> Routes -> `grafana-route` location URL
4.3 Click on dashboards icon and choose Manage
4.4 Go to the …
> MGDAPI-5834 - bump redis engine 6.2

- test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
- test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
- test-cases/tests/products/h21b-verify-all-products-using-the-workloadwebapp.md
- test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
- test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
[MGDAPI-5762](https://issues.redhat.com/browse/MGDAPI-5762)
Update test cases which refers to the workload-web-app as it was moved to another namespace: from `redhat-rhoam-observability` to `redhat-rhoam-customer-monitoring-operator`
Eye review of the code changes
> MGDAPI-5762 - update test cases which refer to workload-web-app

- controllers/rhmi/rhmi_controller.go
[MGDAPI-5857](https://issues.redhat.com/browse/MGDAPI-5857)
- Fix a [bug](https://github.com/integr8ly/integreatly-operator/pull/3297/commits/e6ac2c59057596332bb43232f05a8dd75aad20de) when rhoam install stucks if pagerduty secret does not exist.
- Update a logic by removing extra `ctrl.Result`s in preflightChecks and handleUninstall functions as we already have `ctrl.Result` in Reconcile function.
- Eye review of the code changes should be sufficient, but if you want you can debug and see if rhoam install does not stuck if pagerduty secret does not exist - don't forget to remove `redhat-rhoam-pagerduty` secret before debugging
> MGDAPI-5857 - return non-empty result to requeue rhmi controller

- apis/v1alpha1/rhmi_conditions.go
- controllers/status/status_controller.go
- controllers/status/status_controller_test.go
- go.mod
- go.sum
- test/go.mod
- test/go.sum
- vendor/github.com/openshift/addon-operator/apis/addons/v1alpha1/addoninstances_types.go
- vendor/github.com/openshift/addon-operator/apis/addons/v1alpha1/addons_types.go
- vendor/modules.txt
https://issues.redhat.com/browse/MGDAPI-5901
* Acccount for addon uninstallation flow by addon instance 
*  Implementation is based on the changes provided by https://github.com/openshift/addon-operator/pull/358
* Note: status condition type used to the implementation above was incorrect and will be fixed by https://github.com/openshift/addon-operator/pull/375 which will also provide a client function also that we can later use once released
```
make code/run
```
* Verify installation completes successfully
* Mark addon instance spec for addon deletion
```
oc patch addoninstance addon-instance -p $'spec:\n markedForDeletion: true' --type merge -n redhat-rhoam-operator
```
* Verify RHMI CR is marked for …
> MGDAPI-5901 - feat: addon instance uninstallation flow

- controllers/rhmi/bootstrapReconciler.go
- pkg/products/monitoringcommon/prometheusRules.go
- test/common/alerts_exist.go
- test/go.mod
JIRA: [MGDAPI-5904](https://issues.redhat.com/browse/MGDAPI-5904)
Some PrometheusRules were mistakenly removed when implementing the [OO uninstall logic](https://github.com/integr8ly/integreatly-operator/pull/3278/commits/c6639420c874c4a4a59166b15f12afeb1093d2bd#diff-5a222ffa7e3ccbffdfdbbc30a65069fed706079810a31e1b8074a6f5eacf257f). This PR re-adds them but also slightly refactors them:
- Renames the `ksm-endpoint-alerts` group to be `obo-ksm-endpoint-alerts` since they are all observability related PrometheusRules
- Removes the following alerts as they don't apply with OBO:
- `RHOAMMiddlewareMonitoringOperatorApplicationMonitoringMetricsServiceEndpointDown`
- `RHOAMMiddlewareMonitoringOperatorGrafanaServiceEndpointDown`
- `RHOAMMiddlewareMonitoringOperatorRhmiRegistryCsServiceEndpointDown …
> MGDAPI-5904 Re-added removed OBO PrometheusRules

- controllers/subscription/subscription_controller.go
- pkg/config/threescale.go
- pkg/config/threescale_test.go
https://issues.redhat.com/browse/MGDAPI-5890
Bumped 100mln quota redis size to cache.m5.xlarge
Must be done via OLM on CCS cluster with cluster storage set to false.
- Via OLM, install 1.38.0 (you can use this index: 'quay.io/mstoklus/managed-api-service-index:1.38.0'
- Confirm that 100mln backend redis is now of cache.m5.xlarge size and that installation does not crash at any point
- Via OLM, install rhoam 1.37.0 from this index: 'quay.io/mstoklus/managed-api-service-index:1.37.0' (it's matching prod)
- Quota must be 100mln
- Once installation completes, scale down RHOAM operator
- In backend redis CR add:
```
applyImmediately: true
maintenanceWindow: true
```
And change size to:
```
cache.m5.xlarge
```
- Wait for redis to successfully bump the instance on AWS
- Once redis reports …
> MGDAPI-5890 changes to support 100mln redis bump

- test/common/alerts_mechanism.go
- test/common/verify_prometheus_metrics.go
[MGDAPI-5884](https://issues.redhat.com/browse/MGDAPI-5884)
Fix all e2e tests failing on OBO feature branch:
- C03 - Verify that alerting mechanism works
- Verify prometheus metrics scrapped
- Validate resource requirements are set - [MR](https://gitlab.cee.redhat.com/ckyrillo/managed-tenants-bundles/-/merge_requests/10)
- Provision an OSD cluster
- Install RHOAM
- Run the following commands:
```
INSTALLATION_TYPE=managed-api TEST="C03" make test/e2e/single
```
```
INSTALLATION_TYPE=managed-api TEST="Verify prometheus metrics scrapped" make test/e2e/single
```
```
INSTALLATION_TYPE=managed-api TEST="Validate resource requirements are set" make test/e2e/single
```
For the last one you need to include [MR](https://gitlab.cee.redhat.com/ckyrillo/managed-tenants-bundles/ …
> MGDAPI-5884 - fix e2e tests failing on OBO feature branch

- scripts/alerts-check.sh
- scripts/capture_resource_metrics.sh
- scripts/monitoringupgradetest.sh
https://issues.redhat.com/browse/MGDAPI-5706
- Changed scripts to access prometheus api endpoints without using a route.
- Modified scripts to access `redhat-rhoam-operator-observability` namespace instead of the depreciated `redhat-rhoam-observability` namespace.
- Create a cluster
- Once cluster is created sign into it and run these commands: 
1. `INSTALLATION_TYPE=managed-api LOCAL=false make cluster/prepare/local`
- run the script `scripts/alert-check.sh `
- `INSTALLATION_TYPE=managed-api LOCAL=false  make code/run  ` , wait for install to complete.
- THe script should be waiting and only complete once rhoam install is finished.
- Scale down a resource causing an alert to fire eg. *3scale*
- Make sure it generates all the necessary csv files corresponding to the firing/pending alerts …
> MGDAPI-5706 - updated access to prometheus pod and changed namespace

- test/functional/aws_elasticache_resources_exist.go
[MGDAPI-4729](https://issues.redhat.com/browse/MGDAPI-4729)
It wasn't possible to modify the code to tag the replication groups as stated in the JIRA , so after much consideration an agreement was made to just modify the test so that it passes for nonSTS clusters.
- Spin up a ccs cluster an install rhoam off of master
- Run the test and make sure it passes.
`TEST="F03" INSTALLATION_TYPE=managed-api LOCAL=false DEBUG=true make test/e2e/single`
> MGDAPI-4729 / Modified test to work with nonSts

- pkg/metrics/metrics.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/resources/custom-domain/custom-domain.go
- pkg/resources/custom-domain/custom-domain_test.go
https://issues.redhat.com/browse/MGDAPI-5929
Use the correct ingress router to determine IP for 3scale dns alerts
- Check that ***DNSByPass*** alerts are not firing in Custom Domain Rhoam installation
- Regression - check alerts in regular (Not custom domain) Rhoam  installation
- **References**:  
[Configuring custom domain](https://integreatly-operator.readthedocs.io/en/latest/products/custom_domain/)
> MGDAPI-5929 - Use correct ingress router to determine IP for 3scale dns alerts

- test/functional/suite_test.go
https://issues.redhat.com/browse/MGDAPI-5996
In case that there is something wrong with RHOAM installation (e.g. alerts firing or rhmi CR does not say "stage: complete" the tests might take longer than 90 minutes (rough estimate is 100 - 110 minutes in total).  This increases the timeout to 170 minutes to allow for some contingency space. Also on ci-cd level our pipelines have 180 minute timeout for functional test.
Eye review only. Example of the timeout hit:
https://master-jenkins-csb-intly.apps.ocp-c1.prod.psi.redhat.com/job/Nightly/job/managed-api-install-master/573/artifact/test-logs/test-functional/test-functional_integreatly-operator-test-fgnnf.log
- as you can see it timed out during F08 test execution, after this test only three other tests H29, H30, H31 are executed, see e.g. …
> MGDAPI-5996 Functional test suite timeout increase

- Dockerfile.external
https://issues.redhat.com/browse/MGDAPI-5996
When the image is built via openshift/release it is built from `os` which is ubi8 image so I just updated the Dockerfile.external to use the same FROM image. However, `oc` must be added since this new FROM image does not have it.
See
https://github.com/openshift/release/blob/master/ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml#L44-L50
and
https://github.com/openshift/release/blob/master/ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml#L6-L9 
Have a cluster with RHOAM installed. Build and push the image from this PR and run some tests using the external image:
ORG=yourQuayOrg make image/external/build
ORG=yourQuayOrg make image/external/push
podman run -it …
> MGDAPI-5996 Added oc into external test image

- test/common/alerts_firing.go
https://issues.redhat.com/browse/MGDAPI-5992
Temporary workaround for https://issues.redhat.com/browse/MGDAPI-5992.
Have a cluster with RHOAM installed. In case of no alerts firing the tests should just pass
INSTALLATION_TYPE=managed-api LOCAL=false TEST="Verify Alerts are not firing during or after installation apart from DeadMansSwitch" make test/e2e/single
INSTALLATION_TYPE=managed-api LOCAL=false TEST="C01" make test/e2e/single
I am not sure how to make **ErrorBudgetBurn alerts fire so I recommend to deploy workload-web-app and do some GET requests against the 3scale Product which should make ThreeScaleContainerHighMemory alert to fire. Then run
INSTALLATION_TYPE=managed-api LOCAL=false TEST="Verify Alerts are not firing during or after installation apart from DeadMansSwitch" make …
> MGDAPI-5992 Ignoring firing/pending ErrorBudgetBurn alerts in tests

- bundles/managed-api-service/1.39.0/manifests/managed-api-service.clusterserviceversion.yaml
- pkg/resources/ratelimit/envoy.go
- products/additional-images.yaml
https://issues.redhat.com/browse/MGDAPI-6093
Bump envoy image
- run `make code/run` - RHOAM installation should start
- When installation is completed, navigate to 3scale namespace, click on apicast-production pod, scroll down to find envoy-sidecar container and confirm that the image is registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.8-5
- Cancel `make code/run` to stop rhoam operator
- Navigate to marin3r namespace > configmaps > ratelimig-config cm > change the value of `max_value` to 5
- Navigate to 3scale namespace > secrets > system seed > copy the admin password secret
- Navigate to 3scale namespace > routes > find 3scale-admin route and open it up
- Login with `admin` and password copied from steps above
- Go through the 3scale wizard …
> MGDAPI-6093 bump envoy image

- Makefile
- pkg/products/cloudresources/reconciler.go
- pkg/products/cloudresources/reconciler_test.go
- pkg/resources/utils.go
- pkg/resources/utils_test.go
JIRA: [MGDAPI-6046](https://issues.redhat.com/browse/MGDAPI-6046)
This PR changes the RHOAM uninstallation behavior on CCS clusters using AWS for Postgres and Redis. Previously, when RHOAM was uninstalled, RHOAM (via CRO) would delete the 3 Postgres and 3 Redis DBs without making final snapshots (backups) of them. Therefore if a user accidentally deleted RHOAM on a CCS cluster, there would be no way to recover their DBs.
This PR changes the default behavior to instead make a final snapshot of each of the 3 Postgres and 3 Redis instances before deleting them. This default behavior can be overridden by adding the annotation `skip_final_db_snapshots: 'true'` to the RHMI CR at anytime before deleting it.
This PR also updates the Makefile to set `skip_final_db_snapshots: 'true'` when running …
> MGDAPI-6046 Changed RHOAM uninstall to make final snapshots of Postgres/Redis

- pkg/products/obo/clusterPackage.go
[MGDAPI-6050](https://issues.redhat.com/browse/MGDAPI-6050)
It looks like the package-operator slightly changed the name of the labels it applies to ClusterObjectTemplates from `package-operator.run/package=` to `package-operator.run/instance=`. This was causing the `Verify ClusterObjectTemplates ready state` test to fail. This PR updates the label selector to address that.
N/A - Passing the prow checks should be sufficient verification.
> MGDAPI-6050 Fixed Verify ClusterObjectTemplates e2e test

- pkg/products/grafana/prometheusRules.go
- pkg/products/grafana/reconciler.go
- test/common/alerts_exist.go
Jira: https://issues.redhat.com/browse/MGDAPI-6099
Grafana Operator Alerts remains in from previous release during Upgrade process.
These Alerts are not firing, but impact on Pipeline Functional tests - C04 failed.
Grafana Operator Alerts need to be deleted.
- Rhoam Upgrade process to be used to verify PR, Upgrade from 1.38.0 to 1.39.0 (this branch)
- Pipeline `test-pr-upgrade` can be used, or manual process (the process is not provided here)
- CatalogSource files for testing with Images for 1.38.0 and 1.39.0, that were used for PR testing in development - attached.
[catalogsource-Rhoam_1.39.0.yaml.txt](https://github.com/integr8ly/integreatly-operator/files/13216714/catalogsource-Rhoam_1.39.0.yaml.txt)
[catalogsource-Rhoam_1.38.yaml.txt](https://github.com/integr8ly/integreatly-operator/f …
> MGDAPI-6099 - Delete grafana Operator alerts

- test/common/3Scale_user_promotion.go
- test/common/3scale_crudl.go
- test/common/3scale_smtp.go
- test/common/alerts_invalid_username.go
- test/common/authdelay_first_broker_login.go
- test/common/multitenancy.go
- test/common/multitenancy_performance.go
- test/common/network_policy_access_ns_to_svc.go
- test/common/product_login.go
- test/common/selfmanaged_apicast.go
- test/common/testing_idp.go
- test/common/user_dedicated_admin_permissions.go
- test/common/user_rhmi_developer_permissions.go
- test/common/users_create_realm_sso.go
- test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go
- test/utils/utils.go
https://issues.redhat.com/browse/MGDAPI-4918
Populate Testing IDP password from env var preferably and only use DefaultPassword as a fallback if env var is not defined.
- Install RHOAM and do "oc login" into the cluster
- "export TESTING_IDP_PASSWORD=yourpassword"
- "PASSWORD=$TESTING_IDP_PASSWORD DEDICATED_ADMIN_PASSWORD=$TESTING_IDP_PASSWORD ./scripts/setup-sso-idp.sh"
Execute some of the affected tests:
H07; H03; H11; H34; H35; C19; A16; "Verify Network Policy allows cross NS access to SVC"; B01B; H24; B04; B03; B08B;
Example:
TESTING_IDP_PASSWORD=yourpassword INSTALLATION_TYPE=managed-api LOCAL=false TEST="A16" make test/e2e/single
Note that H03, H07 might fail since they are a bit flaky.
> MGDAPI-4918 Allow for specifying testing-idp password via env var

- apis/v1alpha1/rhmi_types.go
- bundles/rhsso-operator/bundles.yaml
- manifests/integreatly-rhsso/7.6.5-8/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.5-8/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.5-8/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.5-8/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.5-8/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.5-8/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/rhsso.package.yaml
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- products/installation-cpaas.yaml
- products/installation.yaml
https://issues.redhat.com/browse/MGDAPI-6066
KC bump to latest version
- Provision cluster
- create catalog source with 1.38.0:
```
metadata:
spec:
image: quay.io/mstoklus/managed-api-service-index:1.38.0
EOF
```
- create RHMI CR:
```
IN_PROW=false USE_CLUSTER_STORAGE=true make deploy/integreatly-rhmi-cr.yml
```
- Install RHOAM via operator hub
- Once installed, bump the catalog source yaml image to 1.39.0 (same org - just flip version)
- Approve the RHOAM upgrade
- Wait for RHOAM upgrade to fully complete and confirm both sso versions are at 7.6.5-opr-004
- Uninstall RHOAM
Also confirm fresh …
> MGDAPI-6066 bump kc

- bundles/managed-api-service/1.39.0/manifests/managed-api-service.clusterserviceversion.yaml
- pkg/resources/ratelimit/envoy.go
- products/additional-images.yaml
https://issues.redhat.com/browse/MGDAPI-6101
Bump envoy image
- run `make code/run` - RHOAM installation should start
- When installation is completed, navigate to 3scale namespace, click on apicast-production pod, scroll down to find envoy-sidecar container and confirm that the image is registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2
- Cancel `make code/run` to stop rhoam operator
- Navigate to marin3r namespace > configmaps > ratelimig-config cm > change the value of `max_value` to 5
- Navigate to 3scale namespace > secrets > system seed > copy the admin password secret
- Navigate to 3scale namespace > routes > find 3scale-admin route and open it up
- Login with `admin` and password copied from steps above
- Go through the 3scale wizard …
> MGDAPI-6101 bump envoy image

- bundles/managed-api-service/1.39.0/manifests/managed-api-service.clusterserviceversion.yaml
- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
JIRA: [MGDAPI-6160](https://issues.redhat.com/browse/MGDAPI-6160)
This PR bumps the `maxOpenShiftVersion` to 4.14 and updates the `containerImages` in the CSV in preparation for the release of v1.39.0 of RHOAM.
An eye review and passing the PROW checks should be sufficient verification.
> MGDAPI-6160 Bump maxOpenShiftVersion to 4.14

- controllers/rhmi/rhmi_controller.go
https://issues.redhat.com/browse/MGDAPI-6131
If pagerduty secret was missing (e.g. OCM/Hive was slow in creating it for whatever reason) the RHOAM installation got stuck. This fixes is by returing "requeue" result in case of error in getting the secret and in case of non-existence of the secret. This triggers another reconcile(s) later until OCM/Hive creates the secret.
- Get an OSD cluster and `oc login...` into it
-  Checkout this PR
-  Prepare the cluster for rhoam installation: `make cluster/prepare/local`
- Remove the pagerduty secret from redhat-rhoam-operator namespace:
- `oc delete secret redhat-rhoam-pagerduty -n redhat-rhoam-operator`
- Remove `cluster/prepare/pagerduty` make target from `code/run` make target in Makefile:
- …
> MGDAPI-6131 Requeued if pagerduty secret is missing

- controllers/rhmi/rhmi_controller.go
- pkg/products/obo/prometheusRules.go
https://issues.redhat.com/browse/MGDAPI-6217
Increase the time before the RHOAMInstallationControllerReconcileDelayed fires.
- Install RHOAM from this branch, verify that the RHOAMInstallationControllerReconcileDelayed alert mentions 30mins instead of 12.
- When running rhoam locally, stop the operator and add a sleep of 31minutes here https://github.com/integr8ly/integreatly-operator/blob/master/controllers/rhmi/rhmi_controller.go#L252 and run again. 
- the alert should go into pending or firing after that time.
> MGDAPI-6217 update the timer of the alert

- pkg/resources/cluster/cluster.go
- test/common/console_links.go
https://issues.redhat.com/browse/MGDAPI-6243
Change of section class in OSD v4.15 broke the test so the test now has to determine the cluster version first and populate the sectionSelector with proper value based on the cluster version. 
Install RHOAM twice -> on OSD v4.15.0-rc.5 and OSD v4.14.10 (latest 4.14 at the time of writing this)
Run the A33 against both clusters, it should pass for each
```
LOCAL=false INSTALLATION_TYPE=managed-api TESTING_IDP_PASSWORD="HIDDEN" TEST=A33 make test/e2e/single
```
> MGDAPI-6243 Update A33 test to work with OSD v4.15

- test/common/console_links.go
https://issues.redhat.com/browse/MGDAPI-6281
A33 test update so that it pass on OSD v4.16 as well.
LOCAL=false INSTALLATION_TYPE=managed-api TESTING_IDP_PASSWORD="CHANGEME" TEST="A33" make test/e2e/single
> MGDAPI-6281 Update A33 test to pass on OSD v4.16

- pkg/products/cloudresources/reconciler.go
MGDAPI-6376  
Add service update for elasticache
- install this branch on a ccs cluster
```bash
INSTALLATION_TYPE=managed-api USE_CLUSTER_STORAGE=false make deploy/integreatly-rhmi-cr.yml
```
- check the service updates are applied in the aws elasticache ui
- here is eng long lived where they are not applied
- this may not be much of a verification as I believe all new redis will get latest the service updates automatically. This verification may not be worth doing.
> MGDAPI-6376 add service update for elasticache

- test/functional/aws_standalone_vpc.go
https://issues.redhat.com/browse/MGDAPI-6408
Update of A25 test to pass on OSD v4.16.
Given the simplicity of the change I think that eye review is sufficient. I ran the test against ROSA STS OSD v4.15 and it passed. Nightly pipelines will show us quickly if there is smt wrong with this.
> MGDAPI-6408 Update A25 test to pass on OSD v4.16

- test/functional/aws_standalone_vpc.go
https://issues.redhat.com/browse/MGDAPI-6408
Fix bug introduced by me :facepalm:  in https://github.com/integr8ly/integreatly-operator/pull/3475
The condition needs to be converted to its negation.
The test should fail if no. of route tables for multiAZ clusters (having 3 AZs) is *not* in between 4 (incl.)  and 6 (incl.) - exact value depends on the OCP version. The `expectedRouteTableCount` represents the minimum (4) and the `2*len(availableZones)` represents the maximum.
For singleAZ clusters there should be two route tables regardless the OCP version.
Ideal would be to create three clusters:
OSD v4.16 multiAZ cluster (6 route tables)
OSD v41.5 multiAZ cluster (4 route tables)
OSD v4.16 singleAZ cluster (2 route tables)
Install RHOAM on each and validate that A25 test passes on each. …
> MGDAPI-6408 Fix A25 test

- Dockerfile
- Dockerfile.osde2e
- Dockerfile.scorecard
- build/Dockerfile
Jira: https://issues.redhat.com/browse/MGDAPI-5835
Update the ubi8 images to use ubi9 instead.
- validation done - Local RHOAM installation - completed successfully
> MGDAPI-5835 - Update base ubi images to use ubi9

- Dockerfile
https://issues.redhat.com/browse/MGDAPI-6421
The ticket is about CRO but same is true for RHOAM base image build. This is the same fix as was done for CRO:
https://github.com/integr8ly/cloud-resource-operator/pull/827
Have a podman v4 (I validated with v4.9.4 because our ci-cd pipeline uses that version) installed. Then execute:
`ORG=your-quay-org INSTALLATION_TYPE=managed-api TAG=test CONTAINER_ENGINE=podman make image/build/push`
or simply
`podman build --tag quay.io/your-org/managed-api-service:test -f ./Dockerfile .`
I validated this PR via pipeline. It failed due to missing cluster but building base operator image, bundle, index, and test harness image went ok:
https://master-jenkins-csb-intly.apps.ocp-c1.prod.psi.redhat.com/job/ManagedAPI/job/managed-api-rosa-autoscale-upgrade/20/con …
> MGDAPI-6421 Use root to support base image build via podman v4

- bundles/managed-api-service/1.41.0/manifests/managed-api-service.clusterserviceversion.yaml
- pkg/resources/ratelimit/envoy.go
- products/additional-images.yaml
JIRA: [MGDAPI-6432](https://issues.redhat.com/browse/MGDAPI-6432)
Bump envoy image from `2.3.9-2` to `2.5.3-8`.
1. Prepare the cluster:
```bash
```
2. Install RHOAM:
```bash
make code/run
```
3. Wait for the installation to complete:
```bash
```
4. Confirm that the `envoy-sidecar` container in the `apicast-production` Pod is running the image `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.5.3-8`:
```bash
APICAST_POD=$(oc get pods -n redhat-rhoam-3scale | grep apicast-production | grep Running | head -n 1 | awk '{print $1}')
oc get pod -n redhat-rhoam-3scale ${APICAST_POD} -ojson | jq -r '.spec.containers[] | select(.name == "envoy-sidecar") | .image'
```
5. Cancel `make code/run` …
> MGDAPI-6432 Bump Envoy image to 2.5.3-8

- pkg/products/grafana/reconciler.go
- products/additional-images.yaml
JIRA: [MGDAPI-6430](https://issues.redhat.com/browse/MGDAPI-6430)
* Bump `grafana` image to `9-63.1724037159`.
* Bump `grafana-ose-oauth-proxy` image to `v4.13.0-202408131940`.
1. Prepare the cluster:
```bash
```
2. Install RHOAM:
```bash
make code/run
```
3. Wait for the installation to complete:
```bash
```
4. Confirm that the `grafana` container in the `grafana-deployment` Pod is running the image `registry.redhat.io/rhel9/grafana@sha256:31cac5b19c9709d9d7aa00b10858a5f1c0e2badd7b9fdf9b6772e47c87e4cc16`:
```bash
GRAFANA_POD=$(oc get pod -n redhat-rhoam-customer-monitoring --no-headers | awk '{print $1}')
oc get pod -n redhat-rhoam-customer-monitoring ${GRAFANA_POD} -ojson | jq -r …
```
> MGDAPI-6430 Bump grafana and ose-oauth-proxy images

- bundles/managed-api-service/1.41.0/manifests/managed-api-service.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- docs/products/custom_domain.md
- pkg/products/threescale/reconciler.go
- pkg/resources/custom-domain/custom-domain.go
https://issues.redhat.com/browse/MGDAPI-6451
With OSD 4.14 custom domains are deprecated in favor of ingressControllers. This PR goal is to support both, custom domains and ingress controllers in 3scale reconciliation loop.
- Provision ccs cluster 4.14
- Run `make cluster/prepare/local`
- Apply CS with index created from this branch (alternatively create it yourself)
```
metadata:
spec:
image: quay.io/mstoklus/managed-api-service-index:1.41.0
EOF
```
- Create RHMI CR:
```
IN_PROW=false USE_CLUSTER_STORAGE=true make deploy/integreatly-rhmi-cr.yml
```
- Add custom domain to the RHMI CR (in rhmi.spec):
```
routingSubdomain: …
```
> MGDAPI-6451 add ingressController support for custom domain

- bundles/rhsso-operator/bundles.yaml
https://issues.redhat.com/browse/MGDAPI-6446
Bump kc to 7.6.11
https://catalog.redhat.com/software/containers/rh-sso-7/sso7-rhel8-operator-bundle/6160639f5cfcf7adc247ac43
Confirm that the bundles tags match
> MGDAPI-6446 add kc bundles

- bundles/managed-api-service/1.41.0/manifests/managed-api-service.clusterserviceversion.yaml
- config/manifests-multitenant-rhoam/bases/managed-api-service.clusterserviceversion.yaml
- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
Jira: https://issues.redhat.com/browse/MGDAPI-6456
Bump RHOAM's maxOpenShiftVersion for 1.41.0 to 4.17
RHOAM 1.41.0 maxOpenShiftVersion is set to 4.17
```
$ oc describe deploy rhmi-operator |grep -i maxOpen
olm.properties: [{"type": "olm.maxOpenShiftVersion", "value": "4.17"}]
{"properties":[{"type":"olm.maxOpenShiftVersion","value":"4.17"},{"type":"olm.gvk","value":{"group":"integreatly.org","kind":"RHMI","versi...
$ oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq -r '.status.stage'
complete
$ date
Thu Oct 10 15:22:26 EEST 2024
```
Images created and used for testing:
- quay.io/vmogilev_rhmi/managed-api-service-index:1.41.0
- quay.io/vmogilev_rhmi/managed-api-service-bundle:1.41.0
- quay.io/vmogilev_rhmi/managed-api-service:rhoam-v1.41.0
> MGDAPI-6456 Bump RHOAM maxOpenShiftVersion to 4.17

- pkg/products/grafana/reconciler.go
- products/additional-images.yaml
JIRA: [MGDAPI-6489](https://issues.redhat.com/browse/MGDAPI-6489)
* Bump `grafana` image to `9-63.1727117435`.
* Bump `grafana-ose-oauth-proxy` image to `v4.14.0-202409250238`.
1. Prepare the cluster:
```bash
```
2. Install RHOAM:
```bash
make code/run
```
3. Wait for the installation to complete:
```bash
```
4. Confirm that the `grafana` container in the `grafana-deployment` Pod is running the image `registry.redhat.io/rhel9/grafana@sha256:043f656f9c940b66131f8932a9485c66317c1e274d91129d1b9a9a9b594e4547`:
```bash
GRAFANA_POD=$(oc get pod -n redhat-rhoam-customer-monitoring --no-headers | awk '{print $1}')
oc get pod -n redhat-rhoam-customer-monitoring ${GRAFANA_POD} -ojson | jq -r …
```
> MGDAPI-6489 Bump grafana and ose-oauth-proxy images

- bundles/managed-api-service/1.41.0/manifests/managed-api-service.clusterserviceversion.yaml
- pkg/products/marin3r/rateLimitService.go
- pkg/resources/ratelimit/envoy.go
- products/additional-images.yaml
JIRA: [MGDAPI-6489](https://issues.redhat.com/browse/MGDAPI-6489)
Bump envoy image from `2.5.3-8` to `2.5.5-6` and bump limitador image from `v1.3.0` to `v1.6.0`.
1. Prepare the cluster:
```bash
```
2. Install RHOAM:
```bash
make code/run
```
3. Wait for the installation to complete:
```bash
```
4. Confirm that the `ratelimit` Pod in the `redhat-rhoam-marin3r` Namespace is running the image `quay.io/kuadrant/limitador:v1.3.0`:
```bash
RATELIMIT_POD=$(oc get pods -n redhat-rhoam-marin3r | grep ratelimit | grep Running | head -n 1 | awk '{print $1}')
oc get pod -n redhat-rhoam-marin3r ${RATELIMIT_POD} -ojson | jq -r '.spec.containers[] | select(.name == "ratelimit") | .image'
```
5. Confirm that …
> MGDAPI-6489 Bump envoy and limitador images

- scripts/prepare-release.sh
JIRA: MGDAPI-6495
This PR fixes the `prepare-release.sh` script which is required to run the release pipeline.
> MGDAPI-6495 Fix gofmt path for prepare-release.sh script

- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/resources/custom-domain/custom-domain.go
- pkg/resources/custom-domain/custom-domain_test.go
Fix an issue where ingressControllers spec.domain isn't actual domain but part of dns
When coming from osd 4.13 to 4.14, openshift automatically creates ingressController of the same name as the custom domain and deprecates the custom domain. Our goal here is to find custom domain name and find ingressController of the same name -> then check the available condition of ingressController
On fresh installs, the spec.domain in ingressController is expected to be of the same value as routing subdomain in rhmi cr
Already done on cluster with Tomas, please review code.
> MGDAPI-6451 update ingress controller logic

- pkg/products/threescale/reconciler.go
- pkg/resources/reconciler.go
JIRA: [MGDAPI-6498](https://issues.redhat.com/browse/MGDAPI-6498)
This PR patches the `containerImage` in the 3scale CSV so the 3scale-operator is running the correct image.
1. Checkout this PR
2. Prepare the cluster:
```bash
```
3. Install RHOAM:
```bash
make code/run
```
4. Wait for the installation to complete:
```bash
```
5. Confirm that the `threescale-operator-controller-manager-v2-*` Pod in the `redhat-rhoam-3scale-operator` Namespace is running the image `quay.io/integreatly/3scale-operator:v0.12.1-mas`:
```bash
THREESCALE_OPERATOR_POD=$(oc get pods -n redhat-rhoam-3scale-operator | grep threescale-operator-controller-manager-v2 | awk '{print $1}')
oc get pod -n …
```
> MGDAPI-6498 Fixed 3scale CSV container image

- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- pkg/resources/custom-domain/custom-domain.go
IngressController get missing an rbac permission
IngressController get missing an rbac permission
Before adding the rbac:
User \"system:serviceaccount:redhat-rhoam-operator:rhmi-operator\" cannot get resource \"ingresscontrollers\" in API group \"operator.openshift.io\" in the namespace \"openshift-ingress-operator\"\""
After adding the rbac:
> MGDAPI-6451 missing rbac

- bundles/rhsso-operator/bundles.yaml
Jira: https://issues.redhat.com/browse/MGDAPI-6547
This PR is preparation for [PR - RHSSO update for RHOAM 1.42](https://github.com/integr8ly/integreatly-operator/pull/3532) 
prepare to build rhsso-index 7.6.11-3
After PR merge, will use PL similar to previouse rhsso-build: https://jenkins-csb-intly-master.dno.corp.redhat.com/job/ManagedAPI/job/build-product-index/50/
Before creation this PR we checked [PR - RHSSO update for RHOAM 1.42](https://github.com/integr8ly/integreatly-operator/pull/3532)   locally, using private image quay.io/vmogilev_rhmi/rhsso-index:v7.6.11-3  that was created by PL: https://jenkins-csb-intly-master.dno.corp.redhat.com/job/Playground/job/vmogilev/job/build-product-index/29/
> MGDAPI-6547 prepare to build rhsso-index 7.6.11-3

- Makefile
- config/samples/subscription_oo.yaml
Jira: https://issues.redhat.com/browse/MGDAPI-6551
PR allow to add Cluster Observability Operator for local installation
OO required for local install to provide monitoring CRDs
- make install-oo
-  check subscription: Add Cluster Observability Operator to local install
- See Jira description
- For complete RHOAM check run following:
```bash
LOCAL=false USE_CLUSTER_STORAGE=true INSTALLATION_TYPE=managed-api make cluster/prepare/local
LOCAL=false USE_CLUSTER_STORAGE=true INSTALLATION_TYPE=managed-api make code/run
```
where `cluster/prepare/local` contains `install-oo` target
- Expected resullts: 
```bash
~/go/integreatly-operator oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq -r '.status.stage'
complete
```
> MGDAPI-6551 Add Cluster Observability Operator to local install

- config/samples/subscription_oo.yaml
https://issues.redhat.com/browse/MGDAPI-6551
The stable channel needs to be used. The Observability Operator cannot be found otherwise.
Install RHOAM on cluster via `cluster/deploy` make target. However, given the triviality of the change I think that eye review should suffice and full verification can be done via nightly pipelines.
> MGDAPI-6551 Using stable channel for Observability Operator

- test/common/alerts_exist.go
- test/common/alerts_firing.go
- test/common/alerts_mechanism.go
- test/common/dashboards_data.go
- test/common/dashboards_exist.go
- test/common/verify_3scale_UIBBT_alerts.go
- test/common/verify_alert_links_to_SOPs.go
- test/common/verify_prometheus_metrics.go
Jira https://issues.redhat.com/browse/MGDAPI-6602
Replaced wget with curl in the tests to avoid failures in the Jenkins pipeline tests due to the absence of wget.
It will allow to avoid errors like:
```
[FAILED] Failed to query prometheus: failed to exec to prometheus pod: error in Stream: command terminated with exit code 255 (time="2025-03-17T09:57:28Z" level=error msg="exec failed: unable to start container process: exec: \"wget\": executable file not found in $PATH
```
Ensure that the E2E tests pass successfully.
Confirm that Jenkins pipelines are no longer failing due to the missing wget command.
> MGDAPI-6602 Jenkins PLs test suite, avoid using wget

- controllers/rhmi/rhmi_controller.go
- controllers/rhmi/rhmi_controller_test.go
- pkg/products/threescale/reconciler.go
https://issues.redhat.com/browse/MGDAPI-6676
Fix labeling of the deployments to trigger restart
Fix clusterPackage issue
verify in order:
- provision new cluster
- run `make cluster/prepare/local` from this branch
- run `make code/run`
- expectation is successful installation
- scale down RHOAM
- on successful installation from this branch, scale down 3scale operator and zync-db
- both, zync-que and zync will start crashing
- run RHOAM again and confirm that RHOAM is restarting deployments of zync and zync-que by adding: kubectl.kubernetes.io/restartedAt spec.template.metadata.annotations.
> MGDAPI-6676 fix labeling of the deployment and cluster package issue

- pkg/products/threescale/prometheusRules.go
https://issues.redhat.com/browse/MGDAPI-6652
- Update Alert ThreeScaleZyncPodAvailability - change Expression
- Create SOP  - see [MR](https://gitlab.cee.redhat.com/rhcloudservices/integreatly-help/-/merge_requests/929) 
We are checking and updating SOPs for Alerts. See [Jira](https://issues.redhat.com/browse/MGDAPI-6652). We created a new SOP and reviewed/updated the ThreeScaleZyncPodAvailability Alert to make the query expression more precise.
- Checkout this PR/branch.
- Refer to the SOP on how to open Prometheus (using port forwarding).
- Verify that the ThreeScaleZyncPodAvailability alert expression has been updated.
> MGDAPI-6652 update Alert ThreeScaleZyncPodAvailability

- pkg/products/obo/prometheusRules.go
https://issues.redhat.com/browse/MGDAPI-6647
- bumping the alert timeout from 60minutes to 90 minutes
- SOP updated, MR: https://gitlab.cee.redhat.com/rhcloudservices/integreatly-help/-/merge_requests/925
see Jira
> MGDAPI-6647 RHOAMIsInReconcilingErrorState alert - 90m

- pkg/resources/metrics.go
Jira: https://issues.redhat.com/browse/MGDAPI-6664
PostgresFreeableMemoryLow alert -  adjust the threshold (from 20% to 5%)
check PostgresFreeableMemoryLow alert in Prometheus
> MGDAPI-6664 PostgresFreeableMemory adjust the threshold

- apis/v1alpha1/rhmi_types.go
- bundles/managed-api-service/1.43.0/manifests/managed-api-service.clusterserviceversion.yaml
- manifests/integreatly-rhsso/7.6.11-5/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-5/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-5/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-5/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-5/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-5/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/7.6.11-6/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-6/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-6/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-6/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-6/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-6/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/7.6.11-7/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-7/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-7/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-7/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-7/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-7/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/rhsso.package.yaml
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- products/installation-cpaas.yaml
- products/installation.yaml
Jira: https://issues.redhat.com/browse/MGDAPI-6611
Bump RHSSO for Rhoam 1.43.
Other images - PR https://github.com/integr8ly/integreatly-operator/pull/3575
<details>
```
NAME                                       DISPLAY                           VERSION            REPLACES  
oc get csv -n redhat-rhoam-rhsso |grep opr
rhsso-operator.7.6.11-opr-006              Red Hat Single Sign-On Operator   7.6.11-opr-006     rhsso-operator.7.6.11-opr-005           Succeeded
NAME                                       DISPLAY                           VERSION            REPLACES  
oc get csv -n redhat-rhoam-user-sso |grep opr
rhsso-operator.7.6.11-opr-006              Red Hat Single Sign-On Operator   7.6.11-opr-006     rhsso-operator.7.6.11-opr-005           Succeeded
```
```
"rhsso": {
"host": …
```
> MGDAPI-6611 - Bump RHSSO for RHOAM 1.43

- apis/v1alpha1/rhmi_types.go
- pkg/products/grafana/grafanaConfig.go
- pkg/products/marin3r/rateLimitService.go
- pkg/products/marin3r/rateLimitService_test.go
- pkg/products/marin3r/reconciler_test.go
Jira: https://issues.redhat.com/browse/MGDAPI-6611
- Limitador configuration changed.
- Grafana version/config update
```
oc describe cm  ratelimit-config  -n redhat-rhoam-marin3r
Name:         ratelimit-config
Namespace:    redhat-rhoam-marin3r
Labels:       app=ratelimit
part-of=3scale-saas
Annotations:  <none>
Data
====
apicast-ratelimiting.yaml:
----
- namespace: apicast-ratelimit
max_value: 70
seconds: 60
conditions:
- descriptors[0]['generic_key'] == "slowpath"
variables: []
BinaryData
====
Events:  <none>
```
- sanity check, using 3scale for testing (curl "https://myprod1-3scale-apicast-staging.apps.<mycluster>:443/?user_key=xxxxxx"
> MGDAPI-6611 updates: ratelimit-config CM, Grafana config

- pkg/products/obo/prometheusRules.go
- pkg/resources/prometheusRules.go
- test/common/alerts_exist.go
https://issues.redhat.com/browse/MGDAPI-6648
InstallationControllerReconcileDelayed is no longer required and, therefore, has been removed.
- install RHOAM from master via make code/run
- confirm that under "redhat-rhoam-operator-observability" there is prometheusRule monitoring.rhobs/v1 called rhoam-rhmi-controller-alerts present
- inside that rule, confirm there's a rule called: RHOAMInstallationControllerReconcileDelayed present.
- run RHOAM operator from this branch and confirm that the RHOAMInstallationControllerReconcileDelayed rule has been deleted.
> MGDAPI-6648 remove the installation delayed alert

- pkg/products/cloudresources/reconciler.go
https://issues.redhat.com/browse/MGDAPI-6710
ElastiCache service update
- Notes based on [PR](https://github.com/integr8ly/integreatly-operator/pull/3585): Hard to verify as all new elasticache will have the service update already.
merge and test a release time.
- CCS cluster created for verification
> MGDAPI-6710 ElastiCache service update

- pkg/products/cloudresources/reconciler.go
https://issues.redhat.com/browse/MGDAPI-6811
Set S3 deletion to false by default on addon uninstall.
Delete S3 if the `skip_final_db_snapshots=true` is present on RHMI CR
- CCS cluster
- Install RHOAM addon
- Populate S3 data in 3scale CMS
- Double check that S3 for 3scale has data in it
- Uninstall Addon
- The s3 bucket along with final snapshots should remain in place
- Install addon again
- Populate S3 data in 3scale CMS
- Double check that S3 for 3scale has data in it
- Add annotation skip_final_db_snapshots=true to RHMI CR
- Uninstall Addon
- Confirm that S3 and final snapshots are deleted
> MGDAPI-6811 set s3 deletion to false by default when addon is deleted
