integr8ly/integreatly-operator

- deploy/crds/installation.crd.yaml
Small improvement, might become more useful in the future.
> Improve validation of CRD spec

- Gopkg.lock
- Gopkg.toml
- pkg/apis/kafka.strimzi.io/v1alpha1/types.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/products/amqstreams/reconciler.go
- vendor/github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/genutil.go
- vendor/github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go
- vendor/github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/openapi.go
- vendor/github.com/operator-framework/operator-sdk/cmd/operator-sdk/scorecard/scorecard.go
- vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/ansible/gopkgtoml.go
- vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/gopkgtoml.go
- vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/helm/gopkgtoml.go
- vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/olm-catalog/csv.go
- vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/olm-catalog/csv_updaters.go
- vendor/github.com/operator-framework/operator-sdk/pkg/ansible/operator/operator.go
- vendor/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/controllermap/controllermap.go
- vendor/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/proxy.go
- vendor/github.com/operator-framework/operator-sdk/pkg/handler/enqueue_annotation.go
- vendor/github.com/operator-framework/operator-sdk/version/version.go
image for testing:
quay.io/integreatly/integreatly-operator:PR15
verification:
deploy this operator
create installation CR
confirm that AMQ Streams is deployed with persistent storage
> update operator-sdk and add persistent storage

- pkg/apis/integreatly/v1alpha1/installation_types.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/marketplace/manager.go
- pkg/controller/installation/products/amqstreams/reconciler.go
- pkg/controller/installation/products/reconciler.go
- pkg/controller/installation/products/rhsso/reconciler.go
- Creating the keycloak realm
- adding awaiting operator phase which awaits the installplan being ready
- use server client to create components to avoid "no matches for kind" error
> Add Keycloak realm creation

- .travis.yml
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/products/codeready/reconciler_test.go
- pkg/controller/installation/products/config/manager.go
- pkg/controller/installation/products/config/manager_test.go
Using the generated mocks in the config manager tests.
And a `go fmt`
Run the tests, ensure they still work as expected
> Use generated mocks in config manager testing

- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/products/amqstreams/reconciler.go
- pkg/controller/installation/products/codeready/reconciler.go
- pkg/controller/installation/products/codeready/reconciler_test.go
- pkg/controller/installation/products/reconciler.go
- pkg/controller/installation/products/rhsso/reconciler.go
Unit tests for codeready reconciler.
Reconciler needed some small refactoring to make it testable.
> Intly 2764 add unit tests

- Makefile
- deploy/cluster_role_binding.yaml
- deploy/clusterrole.yaml
a helpful command to create your service account, login with that service account and run the operator. So we can test it functions with the restricted permissions we have described.
> adding service account to makefile

- cmd/manager/main.go
- pkg/controller/controller.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/products/fuse/reconciler.go
- pkg/controller/installation/types.go
provides a flag for use in development to choose which products to install ``` --products=rhsso,codeready-workspaces```
> allow optional installation of products

- pkg/controller/installation/products/amqonline/reconciler.go
- pkg/controller/installation/products/amqonline/reconciler_test.go
Currently, the host of the AMQ Online config is never set, meaning
that if other products ever depend on this it will not be available.
This change ensures that the host is set on the config once it
becomes available.
Validation:
- Run the operator, either from fresh or with AMQ Online already setup
- Wait for the config reconciliation to end
- Check the config ConfigMap in the Namespace the operator watches
- Ensure HOST is now set for AMQ Online
> Ensure AMQ Online config is continuously reconciled

- deploy/integreatly.selectorsyncset.yml
SelectorSyncSet tested and deployed through OSD.
Cannot really verify this, but I have personally verified it with the OSD team, and over bluejeans with @maleck13 and @sedroche
> first pass at an integreatly selectorSyncSet

- pkg/resources/oauthResolver.go
JIRA: https://issues.jboss.org/browse/INTLY-2950
**What:**
This PR fixes this error:
```failed installation of solution-explorer: failed to get oauth details : failed to get oauth server config from well known endpoint https://172.30.0.1:443/.well-known/oauth-authorization-server: Get https://172.30.0.1:443/.well-known/oauth-authorization-server: x509: certificate signed by unknown authority```
on the clusters that have valid SSL certificate.
**How:**
Each pod has API servers CA certificate mounted here: 
`/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`
This change will ensure that the certificate authority will be used by http client.
In case of local execution, the CA cert isn't available, the http client has to trust any CA.
**Verification steps:**
Note: test locally AND when …
> INTLY-2950 - fix oauthResolver on clusters with valid certificates

- Makefile
- README.md
Update the readme to use updated `Makefile` commands for less tedious copying and pasting.
> Refactor readme

- OWNERS
> Add pmccarthy as a reviewer

- scripts/setup-htpass-idp.sh
> using custom password for customer-admin if provided

- OWNERS
> Adding Kevin Fan to OWNERS file

- openshift-ci/Dockerfile.tools
- openshift-ci/OWNERS
- scripts/ci/OWNERS
> Add openshift ci dockerfile

- Makefile
> Prep test/e2e make target for openshift CI integration.

- Makefile
- deploy/clusterrole.yaml
- deploy/role.yaml
- pkg/controller/subscription/subscription_controller.go
1) I am addressing my own comments from https://github.com/integr8ly/integreatly-operator/pull/116
2) Roles and ClusterRoles in deploy/ folder were out of date with the roles declared in our CSV
3) Fixing setup/service_account taget in Makefile - ClusterRoleBinding had a hardcoded namespace of the ServiceAccount, and ClusterRoles aren't namespaced.
> A few small fixes and improvements 

- .gitignore
- Makefile
- deploy/crds/examples/integreatly-installation-cr.yaml
- deploy/operator-source-template.yml
- deploy/operator-subscription-template.yml
Add templates to create operator source, catalog source, operator group and subscription.
/cc @philbrookes 
Run the following make target on a fresh openshift 4 cluster and verify integreatly installs as expected:
```
make test/e2e/olm
```
> Add make target to test OLM install of integreatly operator.

- Makefile
- deploy/crds/examples/integreatly-installation-cr.yaml
- test/e2e/integreatly_test.go
updated e2e test to check installation completion and added Makefile changes from this PR: https://github.com/integr8ly/integreatly-operator/pull/144
> updated e2e test to check installation completion

- pkg/controller/installation/products/threescale/reconciler.go
- pkg/controller/installation/products/threescale/reconciler_test.go
- pkg/resources/reconciler.go
https://issues.jboss.org/browse/INTLY-3092
> Use CRO to create s3 bucket for 3scale

- Makefile
- deploy/role.yaml
- pkg/resources/oauthResolver.go
- test/e2e/integreatly_test.go
Run the e2e make target against a clean OpenShift 4 cluster, it should pass:
```
make test/e2e
```
> Add missing cluster role permissions

- pkg/apis/integreatly/v1alpha1/installation_types.go
Related PR: https://github.com/integr8ly/manifests/pull/83
> bump solution explorer version to 0.0.32

- pkg/apis/integreatly/v1alpha1/installation_types.go
This corresponds to the following PR in the manifests repo:
https://github.com/integr8ly/manifests/pull/80
> Update MDC and UPS operator versions

- Makefile
- deploy/operator.yaml
image tag was not being updated when new CSVs were generated.
> fix Makefile gen/csv command

- pkg/controller/installation/products/cloudresources/reconciler.go
Cloud resource operator subscription doesn't get resolved due to the created `CatalogSourceConfig` being unable to find a package called `cloud-resources`. This updates the `defaultSubscriptionName` to be the name as specified in the cloud resources manifest package: https://github.com/integr8ly/integreatly-operator/blob/7169b6542bce8f133b50b395ff34860011b4ba35/manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml#L5
Also changed to use the CRO namespace as the owner of the created CatalogSourceConfig
* Create OperatorSource pointed to my registry
```
metadata:
spec:
endpoint: …
```
> Fix cloud resource subscription name + use CRO namespace as owner of CatalogSourceConfig

- build/Dockerfile
Fix for error
```
time="2019-11-22T09:40:25Z" level=info msg="Error: error loading template: open ./templates/monitoring/jobs/3scale.yaml: no such file or directory"
```
> Add templates to container

- Makefile
- pkg/controller/installation/products/monitoring/reconciler_test.go
https://issues.jboss.org/browse/INTLY-4153
These tests are mostly based on the mobilesecurityservice unit tests, but adapted for monitoring where necessary
> Intly 4153 monitoring unit tests

- deploy/role.yaml
added some comments to clarify what some permissions are required for.
> update comments in role file

- OWNERS
@philbrookes Are you good with me being an owner?
> Add myself to owners & reviewers

- pkg/apis/monitoring/v1alpha1/applicationmonitoring_types.go
- pkg/controller/installation/products/amqonline/reconciler.go
- pkg/controller/installation/products/amqonline/reconciler_test.go
- pkg/controller/installation/products/codeready/reconciler.go
- pkg/controller/installation/products/codeready/reconciler_test.go
- pkg/controller/installation/products/launcher/reconciler.go
- pkg/controller/installation/products/monitoring/reconciler.go
- pkg/controller/installation/products/monitoring/reconciler_test.go
- pkg/controller/installation/products/rhsso/reconciler.go
- pkg/controller/installation/products/rhsso/reconciler_test.go
- pkg/controller/installation/products/solutionexplorer/reconciler.go
- pkg/controller/installation/products/solutionexplorer/reconciler_test.go
- pkg/controller/installation/products/threescale/objects_test.go
- pkg/controller/installation/products/threescale/reconciler.go
- pkg/controller/installation/products/threescale/reconciler_test.go
- pkg/controller/installation/products/ups/reconciler.go
- scripts/ci/unit_test.sh
- templates/monitoring/blackbox/target.yaml
Add blackbox targets for all products (excluding MSS and MDC).
Verification steps:
1. Run a full installation from this branch
2. Check that blackbox targets for each product are created in the monitoring namespaces
3. Check that all blackbox targets are reconciled into the additional scrape config secret
> Intly 4025

- openshift-ci/Dockerfile.tools
Required to merge this into master as the prow E2E tests use this file from master on all other PRs. Until this is merged, E2E tests will always fail on https://github.com/integr8ly/integreatly-operator/pull/203
> feat: Update Dockerfile tools with latest versions

- OWNERS
Adding davidffrench to owners list
> feat: Adding davidffrench to owners

- pkg/controller/installation/products/threescale/reconciler.go
enable 3scale resource requirements
> enable 3scale resource requirements

- pkg/controller/installation/products/monitoring/templateHelper.go
got this value from: https://github.com/integr8ly/integreatly-operator/blob/master/build/Dockerfile#L11
> add template path for docker container

- pkg/controller/installation/products/threescale/reconciler.go
With the current version of 3scale (2.6) when high availability mode is enabled the `system-postgresql` pods are still deployed. This causes the 3scale reconciler to never successfully complete since those pods are using credentials meant for the cloud resource operator postgres deployments. 
This is a workaround which scales down these pods and skips over the requirement for this deployment to be ready in order for the reconciler to continue
- Run the integreatly operator from this branch
- Ensure that 3scale completes in the installation cr
- Ensure that the 3scale `system-postgresql` deployment config spec specifies 0 deployments and that no `system-postgresql` pods are running
> Scale down 3scale postgres pods

- manifests/integreatly-amq-online/amq-online-1.3.1/amq-online.1.3.1.clusterserviceversion.yaml
Fixing https://issues.jboss.org/browse/ENTMQMAAS-1469
/ping @pawelpaszki
> Fix ENTMQMAAS-1469 bug in AMQ Online CSV

- OWNERS
added pawelpaszki to the owners/ reviewres
> added pawelpaszki to the owners/ reviewres

- pkg/controller/installation/products/codeready/reconciler.go
- pkg/controller/installation/products/codeready/reconciler_test.go
JIRA - https://issues.redhat.com/browse/INTLY-4387
> update codeready backup secret

- OWNERS
- openshift-ci/OWNERS
- scripts/ci/OWNERS
- test/OWNERS
> 👥 Add grdryn as reviewer/approver

- pkg/products/cloudresources/reconciler.go
- pkg/products/codeready/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/products/ups/reconciler.go
avoid cloud resource custom resources being recreated and left around by the Integreatly operator.
verification:
- TODO
> INTLY-4780 cloud resource cleanup

- Makefile
- openshift-ci/Dockerfile.tools
- openshift-ci/README.md
- openshift-ci/test/run
https://issues.redhat.com/browse/INTLY-4757
> feat: updated tests

- .gitignore
- Makefile
- make/ocm.mk
- openshift-ci/Dockerfile.tools
- openshift-ci/test/run
- templates/ocm-cluster/cluster-template.json
https://issues.redhat.com/browse/INTLY-4891
cluster creation (after logging in to ocm):
```
make ocm/cluster/create                                                                             20/01/22 2:24pm
Cluster creation started. Cluster id: 1ar0qajm609t1gdnoma1raua91hiujvg
Waiting for cluster creation for 120m...
cluster creation not ready yet, trying again in 300s...
cluster creation not ready yet, trying again in 300s...
cluster creation not ready yet, trying again in 300s...
cluster creation not ready yet, trying again in 300s...
cluster creation not ready yet, trying again in 300s...
cluster creation not ready yet, trying again in 300s...
cluster creation not ready yet, trying again in 300s...
real	35m10.679s
user	0m1.049s
sys	0m0.295s
cluster creation ready!
```
> added ocm make targets

- test/e2e/integreatly_test.go
https://issues.redhat.com/browse/INTLY-4227
> test: e2e - monitoring resources created check

- Makefile
- deploy/crds/integreatly.org_installations_crd.yaml
- go.mod
- go.sum
- pkg/apis/integreatly/v1alpha1/installation_types.go
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/config/amqonline.go
- pkg/config/codeready.go
- pkg/config/fuse.go
- pkg/config/monitoring.go
- pkg/config/rhsso.go
- pkg/config/solutionExplorer.go
- pkg/config/threescale.go
- pkg/products/rhsso/reconciler.go
- pkg/products/solutionexplorer/reconciler.go
- pkg/products/threescale/asserts_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/three_scale_moq.go
- pkg/resources/reconciler.go
https://issues.redhat.com/browse/INTLY-4987
> Fix lint errors associated with vars

- Makefile
- pkg/config/amqonline.go
- pkg/config/codeready.go
- pkg/config/fuse.go
- pkg/config/manager.go
- pkg/config/solutionExplorer.go
- pkg/config/threescale.go
- pkg/controller/installation/bootstrapReconciler.go
- pkg/controller/installation/enqueueIntegreatlyOwner.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/types.go
- pkg/products/amqonline/reconciler.go
- pkg/products/codeready/reconciler.go
- pkg/products/fuseonopenshift/reconciler.go
- pkg/products/fuseonopenshift/reconciler_test.go
- pkg/products/monitoring/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/solutionexplorer/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/products/ups/reconciler.go
- pkg/resources/marketplace/manager.go
- pkg/resources/marketplace/manifestHelper.go
- pkg/resources/owner/integreatlyOwner.go
- pkg/resources/pullSecret.go
- pkg/resources/pullSecret_test.go
- pkg/resources/reconciler.go
https://issues.redhat.com/browse/INTLY-4907
> Further refactoring and syntaxing to INTLY-4907

- pkg/resources/reconciler.go
Reconcile the correct oauthclient redirect uris. The problem was that after the initial `Get`, the values in the passed oauthclient object were all overwritten. We need to preserve and reapply them after the get so that the update actually updates to the new values.
> reconcile oauthclient redirect uris

- Makefile
- deploy/crds/examples/installation.cr.yaml
- deploy/crds/examples/integreatly-installation-cr.yaml
- deploy/crds/integreatly.org_installations_crd.yaml
- deploy/role.yaml
- pkg/apis/integreatly/v1alpha1/installation_types.go
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/controller/installation/bootstrapReconciler.go
- pkg/controller/installation/enqueueAllInstallations.go
- pkg/controller/installation/installation_controller.go
- pkg/products/fuseonopenshift/reconciler.go
- pkg/products/rhsso/reconciler.go
> Intly 5085

- Makefile
- README.md
- deploy/crds/examples/installation.cr.yaml
- deploy/crds/examples/integreatly-installation-cr.yaml
- deploy/crds/integreatly.org_installations_crd.yaml
- go.sum
- pkg/apis/integreatly/v1alpha1/installation_types.go
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/config/cloudresources.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/watch.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/resources/reconciler.go
- test/e2e/integreatly_test.go
JIRA: https://issues.redhat.com/browse/INTLY-4787
> ✨ Add Spec.SMTPSecret & Status.SMTPEnabled to CRD

- README.md
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- test/e2e/integreatly_test.go
> add edge url for user SSO

- pkg/config/amqonline.go
- test/e2e/integreatly_test.go
https://issues.redhat.com/browse/INTLY-5127
> amq online in one namespace

- LICENSE
Not sure if we should also be adding the license header to code files or not,
but this is at least a good first step.
> 📄 Add Apache 2.0 license file

- go.mod
- go.sum
- pkg/apis/enmasse/v1beta1/zz_generated.openapi.go
- pkg/apis/enmasse/v1beta2/zz_generated.openapi.go
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.openapi.go
- pkg/apis/monitoring/v1alpha1/zz_generated.openapi.go
- pkg/products/amqonline/reconciler.go
https://issues.redhat.com/browse/INTLY-2354
> INTLY-2354 | Add AMQ-SLI PrometheusRule

- Makefile
- deploy/crds/integreatly.org_rhmis_crd.yaml
- pkg/apis/enmasse/v1beta1/zz_generated.openapi.go
- pkg/apis/enmasse/v1beta2/zz_generated.openapi.go
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.openapi.go
- pkg/apis/monitoring/v1alpha1/zz_generated.openapi.go
- pkg/products/solutionexplorer/reconciler.go
* adds the integreatly version to the webapp
* Makefile improvements: `make cluster/prepare/project` should not fail when project already exists
* Run code generation to update all auto generated code
> Intly 5191

- README.md
> remove duplicate heading in readme.md

- Makefile
- go.mod
- go.sum
- pkg/products/apicurito/reconciler.go
JIRA: https://issues.redhat.com/browse/INTLY-4824
🚑 Fix `make code/run` for new operator-sdk 0.15.1
🐛 Fix fmt.Errorf call to use %v when not an error
🚨 Fix lint warning: Tls -> TLS in function name
----
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
annotations:
integreatly-name: integreatly
integreatly-namespace: redhat-rhmi-operator
creationTimestamp: "2020-02-17T15:06:25Z"
generation: 2
name: ksm-apicurito-alerts
namespace: redhat-rhmi-apicurito
resourceVersion: "119969"
selfLink: /apis/monitoring.coreos.com/v1/namespaces/redhat-rhmi-apicurito/prometheusrules/ksm-apicurito-alerts
uid: 6497dc0d-7a51-4aa1-8c67-f56cd177e268
spec:
groups:
- name: apicurito.rules
rules:
- alert: ApicuritoPodCount
annotations:
message: Pod count for namespace {{ $labels.namespace …
```
> 🔊 Add Prometheus alert for Apicurito Pod count

- pkg/products/apicurito/reconciler.go
- pkg/products/apicurito/reconciler_test.go
**Test with:**
go test -v -coverprofile cover.out ./pkg/products/apicurito/...
> Tests apicurito

- README.md
change readme operator-sdk version to v0.15.1
> change readme operator-sdk version to v0.15.1

- Makefile
This change only applies when testing olm e2e.
When running the target test/e2e/olm, the operator deployed creates the default rhmi cr before the target deploy/integreatly-rhmi-cr.yaml is called. If an installation prefix is specified when running this target, the installation will fail as the smtp secret would have been created with a different prefix than what is specified in the rhmi cr by default.
This change ensures that the target deploy/integreatly-rhmi-cr.yaml is called before the operator can create the default rhmi cr.
JIRA: https://issues.redhat.com/browse/INTLY-5553
> ensure rhmi cr is created before the operator creates the default cr

- README.md
- make/ocm.mk
> ocm and readme updates

- make/ocm.mk
[Recent change](https://github.com/integr8ly/integreatly-operator/blob/master/pkg/controller/installation/installation_controller.go#L43) that went to `1.19.0` release was not reflected in the makefile we use in pipelines. To prevent potential failures caused by changing the name in the future, the script is now getting the CR name using [this function](https://github.com/integr8ly/integreatly-operator/blob/master/pkg/controller/installation/installation_controller.go#L43) (inspired by https://github.com/integr8ly/integreatly-operator/pull/432)
> fix: reflect changed rhmi name in ocm.mk

- pkg/products/threescale/reconciler.go
Make rhmi-developers 3scale admins when installation type is `workshop`. This is needed because Walkthrough 4 asks the users to create an API.
> make developers 3scale admins in workshop mode

- go.mod
- go.sum
- pkg/controller/installation/bootstrapReconciler.go
- pkg/controller/installation/installation_controller.go
- pkg/resources/finalizers.go
- pkg/resources/reconciler.go
https://issues.redhat.com/browse/INTLY-5595
- Run `make cluster/prepare/local`
- Run `make code/run`
- Verify `useClusterStorage : true` in RHMI CR
- Wait for successful install and ensure a finalizer `foregroundDeletion` has been added to `cloud-resource-config` in the RHMI operator ns
- Delete RHMI CR
- Verify RHMI is deleted successfully
> Add Finalizer to CRO config map

- test/e2e/integreatly_test.go
https://issues.redhat.com/browse/INTLY-5444
There are no verification steps. The tests just have to pass
> Intly 5444 e2e test flake

- test/e2e/integreatly_test.go
JIRA: https://issues.redhat.com/browse/INTLY-5352
The alert `KeycloakAPIRequestDuration90PercThresholdExceeded` fires as part of the Integreatly e2e tests.
Eg: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/integr8ly_integreatly-operator/371/pull-ci-integr8ly-integreatly-operator-master-e2e/1149
> INTLY-5352 e2e test flake: alert tests failed for Keycloak

- scripts/jenkins/nightly-report.sh
fixed not including first build in the report
> fixed not including first build in the report

- scripts/process-image-manifests
Add fuse specific parts to the  manifest processing script.
Successful dryrun of pipeline here https://integreatly-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Delorean%202.0/job/delorean-2-ews/job/fuse-online/job/discovery/12/
> Del 19 fuse online release pipeline

- pkg/controller/installation/installation_controller.go
The `foreground` finalizer gets removed immediately when a resource is marked for deletion. This prevents the operator from removing the created config maps after the product uninstalls. In addition, since this finalizer is used in the "cloud-resource-config", it can be deleted during a namespace deletion before the operator has completed the product uninstalls which may cause problems when used with aws resources 
Jira:
* https://issues.redhat.com/browse/INTLY-5760
* Install integreatly and ensure the `RHMI` CR and `cloud-resources-config` config map now have a `kubernetes` finalizer
* Delete the `RHMI CR`, ensure the `cloud-resource-config` config map is not deleted until the CR has been deleted 
* Ensure the logs contain "uninstall completed"
* Repeat install but instead of deleting …
> INTLY-5760 - Fix config maps are not deleted on uninstall

- test/common/crd_exists.go
- test/common/deployment_types.go
- test/common/tests.go
- test/e2e/integreatly_test.go
https://issues.redhat.com/browse/INTLY-5412
> test: adds automation test for checking expected replicas

- manifests/integreatly-solution-explorer/solution-explorer-0.0.45/solution-explorer-operator.v0.0.45.clusterserviceversion.yaml
- manifests/integreatly-solution-explorer/solution-explorer-0.0.45/webapp.crd.yaml
- manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/products/solutionexplorer/reconciler.go
update solution explorer to LA version
Webapp: https://github.com/integr8ly/tutorial-web-app/releases/tag/2.22.0
Solution patterns: https://github.com/integr8ly/solution-patterns/releases/tag/v1.0.0
Webapp operator: https://github.com/integr8ly/tutorial-web-app-operator/releases/tag/v0.0.45
> update solution explorer to 2.22.0

- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
> [JIRA ticket](https://issues.redhat.com/browse/INTLY-5844)
The operator currently promotes or demotes 3scale users based on their membership to the
admins group in Openshift. However there might be the case that an admin **manually** promotes
a non-admin user. If this happens, the operator will demote that user as they don't belong to the Openshift admin group.
Remove the logic from `reconcileOpenshiftUsers` function that demotes users that have an admin
role in 3scale but are not admins in Openshift
In a cluster:
> INTLY-5844: Remove logic that demotes manually promoted users on 3scale

- templates/monitoring/jobs/openshift_monitoring_federation.yaml
- templates/monitoring/resources-by-namespace.yaml
- templates/monitoring/resources-by-pod.yaml
https://issues.redhat.com/browse/INTLY-5499
1. Install integreatly using my branch
2. Navigate to Grafana dashboards
3. Ensure that resource usage by namespace and resource usuage by pod look like the following:
> Intly 5499 resource dashboards dont work

- make/ocm.mk
- scripts/ocm.sh
https://issues.redhat.com/browse/DEL-172
> feat: refactored ocm make, added ocm.sh

- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/products/amqonline/reconciler.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/codeready/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/products/ups/reconciler.go
- pkg/resources/constants/croConstants.go
- test/common/constants.go
- test/common/cro_cr_success.go
- test/common/tests.go
- test/e2e/integreatly_test.go
Adds tests to check that the CRO CR resources are in a successully provisioned state
Jira:
* https://issues.redhat.com/browse/INTLY-5431
> INTLY-5431 - Test CRO CR successful state

- test/e2e/integreatly_test.go
Jira https://issues.redhat.com/browse/INTLY-5592
To verify this the prow e2e tests need to pass
> Testing does monitoring alert: KubePodCrashLooping still fail

- test/common/deployment_types.go
- test/common/tests.go
Resolves: https://issues.redhat.com/browse/INTLY-6011
**What**
* Verify that the expected numbers of replicas are also available (up and running)
* Add TestStatefulSetsExpectedReplicas to the test list
* Move resources lists to global variables
* Report all errors before failing
> INTLY-6011 Improve expected replicas tests

- test/common/deployment_types.go
- test/common/pdbs_exist.go
- test/common/tests.go
- test/common/types.go
https://issues.redhat.com/browse/INTLY-5735
Adding common test to check for the existence of PodDisruptionBudgets
> Add common test to check PDBs exist

- templates/monitoring/resources-by-pod.yaml
Fixing dashboards not displaying correctly due to a old metric label being used.  https://issues.redhat.com/browse/INTLY-6401
> replacing container_name with container

- pkg/products/solutionexplorer/reconciler.go
Bump solution patterns to v1.0.2 to make the fuse connection name unique per user in WT3
> bump solution patterns to v1.0.2

- Makefile
- README.md
- namespaces.asciidoc
Release process has been updated to create a list of namespaces that are controlled by the RHMI operator. This list of namespaces will be used by the docs teams to create relevant documentation. 
**JIRA** https://issues.redhat.com/browse/INTLY-6374
> INTLY-6374 Genrate RHMI namespaces doc

- deploy/olm-catalog/integreatly-operator/integreatly-operator-2.0.0/integreatly-operator.v2.0.0.clusterserviceversion.yaml
- deploy/operator.yaml
release 2.0.0 rc1
release 2.0.0 rc1
N/A
> v2.0.0-rc1

- test/BEST_PRACTICES.md
This document is an extract of the major points initially discussed in this document: https://docs.google.com/document/d/1gZQ0jFo_onaT643E0eDrzG47VNs2iSAnkI7jzdhxvyA
The goal of this document is to help writing better tests and review new tests.
> Initial Best Practices for e2e and functional tests

- go.mod
- go.sum
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/client.go
- vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
- vendor/modules.txt
This PR is a work in progress. This currently replaces the keycloak-client dependency to point to this [branch](https://github.com/JameelB/keycloak-client/tree/INTLY-6430) so that the following PR can be tested: https://github.com/integr8ly/keycloak-client/pull/6. This will need to be updated to point back to the correct dependency and update it to the correct vendor files.
1. Run the operator using this branch
2. Ensure installation was successful
> INTLY-6430: keycloak client updates from KEYCLOAK-13018

- pkg/products/amqonline/reconciler.go
- pkg/products/amqstreams/reconciler.go
- pkg/products/amqstreams/reconciler_test.go
- pkg/products/codeready/reconciler.go
- pkg/products/codeready/reconciler_test.go
- pkg/products/fuseonopenshift/reconciler.go
- pkg/products/fuseonopenshift/reconciler_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/ups/reconciler.go
**Jira**
https://issues.redhat.com/browse/INTLY-3717
**Description**
Replace the `create` and `update` functions with `controllerutls.CreateOrUpdate()`. This allows the checking of a CR and insures the defaults required are still set.
> RHMI operator maintains only values set by the operator

- test/common/shared_functions.go
- test/e2e/integreatly_test.go
https://issues.redhat.com/browse/DEL-78
- [] Bug fix (non-breaking change which fixes an issue)
> only cleanup resources when there are no test failures

- deploy/operator-subscription-template.yml
* Tiny fix for a subscription template used for OLM installation
> fix: parameter in subscription template

- templates/monitoring/kube_state_metrics_alerts.yaml
JIRA: https://issues.redhat.com/browse/INTLY-6611
> 📝 Add sop_url field to storage alerts

- pkg/config/monitoring.go
- templates/monitoring/critical_slo_alerts.yaml
- test/common/dashboards_exist.go
The following PR is to show the changes made to create a SLO dashboard in grafana.  [Jira](https://issues.redhat.com/browse/INTLY-6594)
Verification
1. Install integreatly from this branch
2. make a few alerts fire
3. verify the dashboard portrays this change.
> Intly 6954 slo dashboards

- guides/ADDING_A_NEW_PRODUCT.md
- guides/TERMINOLOGY.md
- pkg/config/manager.go
- pkg/controller/installation/installation_controller.go
- pkg/products/reconciler.go
- test/common/tests.go
Adding a guide on how to create a new product reconciler
docs
@matskiv @JameelB @pb82 I would appreciate your thoughts on this.
> add docs for creating a new reconciler

- pkg/products/amqstreams/reconciler.go
- pkg/products/apicurito/reconciler.go
- pkg/products/threescale/reconciler.go
- test/common/scale_up_replicas_amqstreams.go
- test/common/scale_up_replicas_apicurito.go
- test/common/scale_up_replicas_threescale.go
- test/common/tests.go
- [ X] I have added tests that prove my fix is effective or that my feature works
> Intly 6588

- pkg/products/monitoring/reconciler.go
- pkg/resources/reconciler.go
https://issues.redhat.com/browse/INTLY-6747
Follow up on #607
> INTLY-6747 Add cluster monitoring label to federate ns

- test/e2e/integreatly_test.go
**issue**: https://issues.redhat.com/browse/INTLY-5780
e2e test flake timing out on deploying solution-explorer.
> Increase test timings on prow

- pkg/products/threescale/reconciler.go
- [ X] Bug fix (non-breaking change which fixes an issue)
> INTLY-7069 - Update 3scale SMTP to be a secret

- pkg/products/solutionexplorer/reconciler.go
update solution patterns to disable SP3 & 4
> update to solution patterns v1.0.4 to disable SP3 and SP4

- deploy/olm-catalog/integreatly-operator/integreatly-operator-2.1.0/integreatly-operator.v2.1.0.clusterserviceversion.yaml
> release v2.1.0-rc1

- deploy/olm-catalog/integreatly-operator/2.1.0/integreatly-operator.v2.1.0.clusterserviceversion.yaml
> release v2.1.0

- README.md
> TEST DO NOT MERGE

- Makefile
- README.md
- RELEASE.md
https://issues.redhat.com/browse/DEL-235
> add release doc

- pkg/products/solutionexplorer/reconciler.go
JIRA: https://issues.redhat.com/browse/INTLY-7044
- Clone this repo
- Run the operator against a PDS/OSD cluster
- Verify the `INSTALLATION_TYPE` parameter is part of the `Spec.Parameters` field of the WebApp CR
> INTLY-7044-added-installation-type-to-solution-explorer-cr

- pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
Feat(Docs): Documentation added for new RHMI config CRD
The documentation that has been added is in the form of comments with in the rhmiconfig_types.go.
**JIRA** https://issues.redhat.com/browse/INTLY-7155
> INTLY-7155 Technical documentation of the fields in the Config CRD

- go.mod
- pkg/products/solutionexplorer/reconciler.go
Update solution patterns to v1.0.5. This brings back the Slack WT (SP3).
> Intly 7031

- pkg/controller/subscription/rhmiConfigs/main.go
broken unit test on thursdays :facepalm:
> fix testUpdateStatus unit test

- test/common/pvc_validate.go
- test/common/tests.go
- test/common/types.go
Add test to check for PVC being available and bound. This test is to replace manual testing.
> INTLY-7427 Add test for PVC check

- pkg/controller/installation/installation_controller.go
Fix issue of un-install not been completed.
**Jira** https://issues.redhat.com/browse/INTLY-7469
> Intly 7469 RHMI uninstallation gets stuck (master branch)

- test/common/operator_versions.go
- test/common/tests.go
- test/e2e/integreatly_test.go
Move check for operator versions as part of functional tests
Associcated test case PR:
* https://gitlab.cee.redhat.com/integreatly-qe/integreatly-test-cases/merge_requests/192
Jira:
* https://issues.redhat.com/browse/INTLY-7426
> INTLY-7426 - e2e test for checking operator versions

- test/common/namespace_created.go
- test/common/tests.go
- test/e2e/integreatly_test.go
Move e2e test for checking namespace are successully created as part of functional tests
Assoicated gitlab test case PR:
* https://gitlab.cee.redhat.com/integreatly-qe/integreatly-test-cases/merge_requests/217
Jira:
* https://issues.redhat.com/browse/INTLY-7425
> INTLY-7425 - move e2e namespace creation test to functional test

- test/common/3scale_crudl.go
- test/common/tests.go
- test/resources/openshift_auth.go
re-add the 3scale e2e test (test code was already merged with the fuse e2e test)
> add 3scale crudl test

- test/common/integreatly_stages.go
- test/common/tests.go
> Link to JIRA: https://issues.redhat.com/browse/INTLY-7424
Extend tests for RHMI stages completion (#703) with verification of the products status within each stage.
> INTLY-7424 Verify RHMI products status

- deploy/olm-catalog/integreatly-operator/2.1.1/integreatly-operator.v2.1.1.clusterserviceversion.yaml
- deploy/olm-catalog/integreatly-operator/2.1.1/integreatly.org_rhmis_crd.yaml
> add csv for 2.1.1 release

- deploy/olm-catalog/integreatly-operator/2.2.0/integreatly-operator.v2.2.0.clusterserviceversion.yaml
update replaces field to match MT PR
> add replaces 2.1.1

- scripts/setup-sso-idp.sh
When completing a PoC as part of https://issues.redhat.com/browse/INTLY-6037 I noted that the same password was being used for both the admin and evals/test users, so this PR is to generate a different password for Admins
> Generate different admin password

- templates/monitoring/kube_state_metrics_3scale_alerts.yaml
- templates/monitoring/kube_state_metrics_amqonline_alerts.yaml
removing dead scaling plan link annotations, these links will be instead found in the SOP itself, they will be added in a separate PR to the `integreatly-help` repo
https://issues.redhat.com/browse/INTLY-7745
Second PR to update the scaling_plan URL in their relative SOPs
https://github.com/RHCloudServices/integreatly-help/pull/510
- [:heavy_check_mark: ] Bug fix (non-breaking change which fixes an issue)
> INTLY-7745 Remove scaling_plan annotation link

- deploy/operator.yaml
https://issues.redhat.com/browse/INTLY-7790
> temporarilly added memory and cpu limits to the operator

- test-cases/tests/backup-restore/j10-verify-amq-backup-and-restore.md
This is an update of the timing it takes to complete a test.
> changed 1h20m to 2h

- test-cases/tests/installation/a02-all-specific-products-specified-under-the-stages-in-the-inte.md
Add "automated" tag that wasn't added after implementing automated test in #707
> Add missing tag to A02 test

- test-cases/tests/walkthroughs/g06-verify-user-role-can-be-determined-in-solutionexplorer.md
- test-cases/tests/walkthroughs/g07-verify-changes-for-customising-solution-explorer-user-roles.md
- test-cases/tests/walkthroughs/g08-verify-addition-of-breadcrumbs-to-solution-explorer.md
- test-cases/tests/walkthroughs/g11-verify-settings-cog-is-inactive.md
Update UXD test-cases for RHMI-2.3.0 release testing (Sprint 18)
Deletion of un-needed test-cases and update to existing test-cases to capture related recent updates.
> RHMI-2.3.0 UXD test-cases

- test-cases/tests/installation/a01-verify-that-all-stages-in-the-integreatlyoperator-cr-report.md
- test-cases/tests/installation/a06-there-are-no-failed-pvcs.md
Added automated tag to test cases for A01 and A06 as there are now automated tests for these.
> Add automated tag to A01 and A06 test cases

- pkg/products/fuse/reconciler.go
- pkg/products/fuse/reconciler_test.go
Jira link: https://issues.redhat.com/browse/INTLY-7188
Reconcile the syndesis-prometheus pvc to 10Gi from 1Gi. Should update
for already existing installations (upgrade) and new installations as well.
> Update the syndesis-prometheus in redhat-rhmi-fuse to 10Gi

- test-cases/tests/backup-restore/j05-verify-3scale-backup-and-restore.md
- test-cases/tests/backup-restore/j06-verify-codeready-backup-and-restore.md
- test-cases/tests/backup-restore/j07-verify-cluster-sso-backup-and-restore.md
- test-cases/tests/backup-restore/j08-verify-user-sso-backup-and-restore.md
- test-cases/tests/backup-restore/j09-verify-fuse-backup-and-restore.md
- test-cases/tests/backup-restore/j11-verify-ups-backup-and-restore.md
Fixed links to backup and restore SOPs in test cases.
> fix: outdated links in backup&restore test cases

- test-cases/tests/installation/a07-all-operand-versions-are-correct.md
Updates A07 as it is not currently included in `functional` tests that are run
> updates A07

- pkg/products/solutionexplorer/reconciler.go
Update solution patterns to v1.0.6
> update solution patterns to v1.0.6

- pkg/products/monitoring/prometheusRules.go
This PR adds new warning and critical alerts for OOMKilled pods
Do not merge before SOP is created and merged
https://github.com/RHCloudServices/integreatly-help/pull/514
https://issues.redhat.com/browse/INTLY-7778
TODO
> INTLY-7778-OOMKill-Alerts

- manifests/integreatly-solution-explorer/0.0.55/solution-explorer-operator.v0.0.55.clusterserviceversion.yaml
- manifests/integreatly-solution-explorer/0.0.55/webapp.crd.yaml
- manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
Update integreatly operator to use tutorial-web-app-operator v0.0.55.
Update version of webapp operator to include latest solution explorer functionality.
> Update for webapp operator to v0.0.55

- manifests/integreatly-amq-online/1.4.2/addresses.crd.yaml
- manifests/integreatly-amq-online/1.4.2/addressplans.crd.yaml
- manifests/integreatly-amq-online/1.4.2/addressspaceplans.crd.yaml
- manifests/integreatly-amq-online/1.4.2/addressspaces.crd.yaml
- manifests/integreatly-amq-online/1.4.2/addressspaceschemas.crd.yaml
- manifests/integreatly-amq-online/1.4.2/amq-online.1.4.2.clusterserviceversion.yaml
- manifests/integreatly-amq-online/1.4.2/authenticationservices.crd.yaml
- manifests/integreatly-amq-online/1.4.2/brokeredinfraconfigs.crd.yaml
- manifests/integreatly-amq-online/1.4.2/consoleservices.crd.yaml
- manifests/integreatly-amq-online/1.4.2/iotconfigs.crd.yaml
- manifests/integreatly-amq-online/1.4.2/iotprojects.crd.yaml
- manifests/integreatly-amq-online/1.4.2/messagingusers.crd.yaml
- manifests/integreatly-amq-online/1.4.2/standardinfraconfigs.crd.yaml
- manifests/integreatly-amq-online/amq-online.package.yaml
Created automatically by jenkins
> amq-online update to 1.4.2

- cmd/manager/main.go
- deploy/crds/integreatly.org_rhmis_crd.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/subscription/rhmiConfigs/main.go
- pkg/controller/subscription/rhmiConfigs/main_test.go
- pkg/controller/subscription/subscription_controller.go
- pkg/metrics/metrics.go
This PR is rebased off https://github.com/integr8ly/integreatly-operator/pull/776
> Expose upgrade metrics

- test-cases/tests/walkthroughs/g13-verify-wt3-solution-pattern-updates.md
Test-case for wt3 solution-pattern update
> Test case for wt3 solution-pattern updates

- deploy/olm-catalog/integreatly-operator/2.2.1/integreatly-operator.v2.2.1.clusterserviceversion.yaml
- deploy/olm-catalog/integreatly-operator/2.2.1/integreatly.org_rhmiconfigs_crd.yaml
- deploy/olm-catalog/integreatly-operator/2.2.1/integreatly.org_rhmis_crd.yaml
Adding 2.2.1 back to master as per our release process:
https://github.com/integr8ly/integreatly-operator/blob/master/RELEASE.md
> Add 2.2.1 manifest back to master

- test-cases/tests/monitoring/m02-verify-rhmi-version-metric-is-exposed.md
Test case for RHMI version metric
https://issues.redhat.com/browse/INTLY-7394
> Add testcase for RHMI version metric

- OWNERS
> chore: add darahayes to reviewers

- make/test-containers.mk
- openshift-ci/Dockerfile.tools
- openshift-ci/test/run
Add Delorean CLI and skopeo to base test image
Add test-containers checks to test the format of the test-containers.yaml file (test-containers/check/format) and that all images exist (test-containers/check/images).
All test-containers checks can be executed with test-containers/check
```
make test-containers/check
```
Jiras:
* https://issues.redhat.com/browse/DEL-289
* https://issues.redhat.com/browse/DEL-287
> Add Delorean CLI and skopeo to test base image

- test-containers.yaml
Add the AMQ Test container to start executing it in our Nightly Pipeline. It's a simple smoke test that is already working on RHMI.
> Add AMQ test container

- test-cases/tests/alerts/c07-verify-rhmi-alerts-metrics-exposed-via-telemtry.md
- test-cases/tests/installation/a21-verify-maintenance-and-backup-windows.md
- test-cases/tests/installation/a22-verify-rhmiconfig-maintenance-and-backup-validation.md
Added note for C07 test case regarding fix that will be made in future.
> added note for test case C07

- test-cases/tests/installation/a21-verify-maintenance-and-backup-windows.md
- test-cases/tests/installation/a22-verify-rhmiconfig-maintenance-and-backup-validation.md
- test-cases/tests/walkthroughs/g06-verify-user-role-can-be-determined-in-solutionexplorer.md
Updates incorrect testcase as per https://issues.redhat.com/browse/INTLY-8136
> updates g06 testcase to remove Manage Users refs

- test-cases/tests/installation/a21-verify-maintenance-and-backup-windows.md
- test-cases/tests/installation/a22-verify-rhmiconfig-maintenance-and-backup-validation.md
- test-cases/tests/products/h05-verify-integration-between-fuse-online-and-openshift.md
Update test case for testing Fuse integration and Fixing some of the lint issues
> Update H05 and fix lint issues

- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- test/common/operand_versions.go
- test/common/tests.go
- test/e2e/integreatly_test.go
Move component version test to common folder so it can be run during functional tests and e2e tests. https://issues.redhat.com/browse/INTLY-7961
> test: move product versions test to common folder

- test-cases/tests/upgrade/n04-verify-customer-config-reconcile-upgrade-logic.md
Removed unnecessary test-cases dependency
> removed unnecessary dependency

- RELEASE.md
The Jenkins pipeline should be used instead of the `make prepare-patch-release`
> Update patch release documentation with the new pipeline

- make/test-cases.mk
- test-cases/tests/installation/a21-verify-maintenance-and-backup-windows.md
- test-cases/tests/installation/a22-verify-rhmiconfig-maintenance-and-backup-validation.md
The `make test-cases/lint` didn't return an error when failing causing the pipeline to always pass
> Fix make test-cases/lint

- Makefile
- test/common/scale_up_replicas_apicurito.go
- test/common/scale_up_replicas_rhsso.go
- test/common/scale_up_replicas_threescale.go
Switched from update to patch and check for readyreplicas before passing test.
Switched from update to patch and check for readyreplicas before passing test.
Tests were reported as failing in these two tickets. 
- https://issues.redhat.com/browse/INTLY-7238 
- https://issues.redhat.com/browse/INTLY-7556
- [X ] Bug fix (non-breaking change which fixes an issue)
> INTLY-7238 Switched from update to patch

- test-cases/README.md
Follow up on https://github.com/integr8ly/integreatly-operator/pull/872
> updated test cases readme - automation jiras

- test-cases/tests/installation/a24-verify-rc-fixes.md
- test-cases/tests/upgrade/n02-measure-downtime-during-rhmi-upgrade.md
Added new test-case for rc fixes and updated N02 test case to make sure that RHMI upgrade and not OS upgrade is being monitored
> added rc fixes test case and updated rhmi upgrade check

- OWNERS
> add wei-lee as owner

- Makefile
> rename delorean tests run to delorean pipeline product-tests

- pkg/controller/subscription/subscription_controller.go
- pkg/controller/subscription/webapp/main.go
- pkg/controller/subscription/webapp/main_test.go
- pkg/products/solutionexplorer/object_test.go
- pkg/products/solutionexplorer/reconciler.go
> Link to JIRA: https://issues.redhat.com/browse/INTLY-7887
* Add a parameter to the spec.Template.Parameters field of the solution explorer CR
with information about an incoming upgrades.
* Add logic to clear this value when the upgrade is approved
* Default the value to `null` in order for the UI to parse the value and check
for nullity.
* Modify logic of WebApp reconciliation to reconcile parameters without removing
custom parameters.
* Add unit tests.
* Include `context.Context` value in subscription controller reconciler and use this
value instead of `context.TODO()` in subsequent calls.
> In order to verify this PR, an OLM installation of RHMI must be used.
1. Install RHMI from this PR through OLM
2. Verify that the `solution-explorer` WebApp has a parameter …
> INTLY-7887 Notify solution explorer of available upgrades

- test-cases/tests/alerts/c08-verify-alert-links-to-sops.md
- test-cases/tests/dashboards/e07-verify-drill-down-links.md
- test-cases/tests/dashboards/e08-verify-values-are-correct-in-resource-usage-dashboard.md
- test-cases/tests/high-availability/f04-verify-aws-s3-resources-exist-and-are-in-expected-state.md
- test-cases/tests/monitoring/m03-verify-number-of-pods-for-amo.md
- test-cases/tests/monitoring/m04-verify-rhmistatus-metric.md
More info: <https://issues.redhat.com/browse/INTLY-8269>
> updated test cases for 2.4.0 monitoring

- test-cases/tests/products/h21-verify-all-products-using-the-workload-web-app.md
- test-cases/tests/products/h21-verify-all-products-using-the-workloadwebapp.md
These test case use the [workload-web-app](https://github.com/integr8ly/workload-web-app) to verify 3scale, AMQ, and SSO
We could use these tests instead of the walkthrough tests "per-build"
> INTLY-8397 Test case: Verify all products using the workload-web-app

- pkg/products/amqonline/prometheusRules.go
- pkg/products/amqonline/reconciler.go
- pkg/products/apicurito/prometheusRules.go
- pkg/products/apicurito/reconciler.go
- pkg/products/cloudresources/prometheusRules.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/codeready/prometheusRules.go
- pkg/products/codeready/reconciler.go
- pkg/products/fuse/prometheusRules.go
- pkg/products/fuse/reconciler.go
- pkg/products/monitoring/prometheusRules.go
- pkg/products/monitoring/reconciler.go
- pkg/products/rhsso/prometheusRules.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/prometheusRules.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/solutionexplorer/prometheusRules.go
- pkg/products/solutionexplorer/reconciler.go
- pkg/products/threescale/prometheusRules.go
- pkg/products/threescale/reconciler.go
- pkg/products/ups/prometheusRules.go
- pkg/products/ups/reconciler.go
- pkg/resources/backup.go
- pkg/resources/sop_url.go
- test/common/alerts_exist.go
https://issues.redhat.com/browse/INTLY-7403
The naming conventions for each alert along with the requirements for the alerts expressions can be found in [INTLY-7402](https://issues.redhat.com/browse/INTLY-7402).
- Install `RHMI` using this branch
- Ensure that none of the alerts are firing during install
- Ensure all of the required alerts are created. [This](https://docs.google.com/spreadsheets/d/1Wt6qrRskOQLd5DndMXvMvocsfsxcIOk7uk8TWsX4MBo/edit#gid=0) Google Sheet contains all of the alerts that were created (please note that there are 3 tabs)
- To test an individual alert, go to the product/operator namespace in which the alerts resides, and search for the `Endpoints` type resource (`home` -> `search` -> `Endpoints`). Within the YAML definitition of the resource, delete everything from …
> Creation of alerts for all RHMI service endpoints

- manifests/integreatly-solution-explorer/0.0.58/solution-explorer-operator.v0.0.58.clusterserviceversion.yaml
- manifests/integreatly-solution-explorer/0.0.58/webapp.crd.yaml
- manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
* Add new manifests to 0.0.58
* Update currentCSV in channel
* Update `OperatorVersionSolutionExplorer` constant  to "0.0.58"
> Bump Solution Explorer operator to v0.0.58

- pkg/products/solutionexplorer/reconciler.go
update solution patterns to include changes from https://github.com/integr8ly/solution-patterns/pull/34
> update solution patterns to v1.0.8

- pkg/products/solutionexplorer/reconciler.go
update solution patterns to v1.0.9 to remove a note that is misleading on workshop type installations
> update solution patterns to v1.0.9

- test-cases/tests/products/h21-verify-all-products-using-the-workloadwebapp.md
> H21 pre upgrade

- deploy/olm-catalog/integreatly-operator/2.2.0/integreatly-operator.v2.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/integreatly-operator/2.2.1/integreatly-operator.v2.2.1.clusterserviceversion.yaml
- deploy/olm-catalog/integreatly-operator/2.3.0/integreatly-operator.v2.3.0.clusterserviceversion.yaml
- deploy/olm-catalog/integreatly-operator/2.4.0/integreatly-operator.v2.4.0.clusterserviceversion.yaml
> add the missing displayName field to CSVs

- deploy/operator.yaml
Follow up on CPU throttling alerts that were [reported by SRE-P](https://app.slack.com/client/T027F3GAJ/CJCAUV38A/thread/CJCAUV38A-1592855711.317200)
cc @philbrookes @david-martin @grdryn 
JIRA: https://issues.redhat.com/browse/INTLY-8790
> Updating CPU requests and limits based on SRE report

- test-cases/tests/products/h11-verify-3scale-smtp-configuration.md
> minor fixes for smtp test

- test-cases/tests/products/h08-verify-amq-online-crs-can-be-modified-and-are-not-reset.md
> updated h08 test case

- test/common/rhmicr_metrics.go
improving the error output to help investigate issues like:
https://issues.redhat.com/browse/INTLY-8165
> Imprrove error messages in rhmicr_metrics.go

- test/common/operand_versions.go
Improve logging to help with investigation of https://issues.redhat.com/browse/INTLY-8390
> Improve logging in operand_versions.go

- test-cases/tests/installation/a07-all-operand-versions-are-correct.md
A07 is [now automated](https://github.com/integr8ly/integreatly-operator/blob/v2.4.0-rc1/test/common/operand_versions.go)
> testcase: mark a07 as automated

- RELEASE.md
Removed patch release preparation step from Release document
> DEL-308: Documentation-Removed patch release preparation step

- test-cases/README.md
- test-cases/tools/cmd/jira.ts
Improve test-cases tooling documentation
> Update --auto-resolve option documentation

- test/common/dashboards_data.go
> added more filters for monitored pods

- test/resources/oauth_proxy_auth.go
https://issues.redhat.com/browse/INTLY-7918 and improved logging (removed excessive error logs on failure)
> added workaround to subsequent fuse crudl failing tests

- test-containers.yaml
Update the 3sclae test container to `quay.io/integreatly/3scale-py-testsuite:2.9`
> Update 3scale test container to 2.9

- test-cases/tests/monitoring/m04-verify-rhmistatus-metric.md
Updates the test case for rhmi_status to automated
> testcase: changes rhmi_status test to automated

- test/functional/aws_legacy_cluster_vpc.go
- test/functional/aws_shared_functions.go
- test/functional/aws_standalone_vpc.go
- test/functional/tests.go
This PR is based on top of the changes in @dimitraz's PR #937. It makes sense that we would get that merged first.
> chore: functional test for legacy cluster vpc

- test-cases/tests/upgrade/n06-verify-rds-and-elasticache-db-instance-types-are-successfull.md
Test case for https://issues.redhat.com/browse/INTLY-8447
> test case: aws instance type migration

- test-cases/tests/installation/a25-verify-standalone-rhmi-vpc-exists-and-is-configured-properly.md
- test-cases/tests/upgrade/n06-verify-legacy-cluster-vpc-is-configured-properly.md
- test-cases/tests/upgrade/n06-verify-vpc-backwards-compatibility-after-upgrade.md
Test cases for Standalone and Legacy VPC https://issues.redhat.com/browse/INTLY-8174
> feat: test cases for standalone & legacy VPCs

- test-cases/tests/high-availability/f04-verify-aws-s3-resources-exist-and-are-in-expected-state.md
Adding some more clarification to pre-requisite steps to get access keys required for AWS CLI configuration
> Add steps to credential retrieval

- test-cases/tests/walkthroughs/g06-verify-user-access-to-settings-menu.md
- test-cases/tests/walkthroughs/g13-verify-wt3-solution-pattern-updates.md
> testcase: update testcases

- test-cases/tests/upgrade/n07-verify-rds-and-elasticache-db-instance-types-are-successfull.md
renamed test case to avoid having duplicate IDs
> renamed test case to avoid having duplicate IDs

- test/common/operand_versions.go
Adding temporary skip for flaky test:
https://issues.redhat.com/browse/INTLY-8390
> INTLY-8390 - skip failing test (tmp)

- test-cases/tests/walkthroughs/g15-verify-soluton-explorer-customer-settings-backup.md
Added test case for Solution Explorer customer back-up time configuration
> Added g15 test-case for RHMI 2.5.0 release testing

- pkg/products/amqonline/prometheusRules.go
- pkg/products/amqonline/reconciler.go
- pkg/products/apicurito/prometheusRules.go
- pkg/products/apicurito/reconciler.go
- pkg/products/cloudresources/prometheusRules.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/codeready/prometheusRules.go
- pkg/products/codeready/reconciler.go
- pkg/products/fuse/prometheusRules.go
- pkg/products/fuse/reconciler.go
- pkg/products/monitoring/prometheusRules.go
- pkg/products/monitoring/reconciler.go
- pkg/products/rhsso/prometheusRules.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/prometheusRules.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/solutionexplorer/prometheusRules.go
- pkg/products/solutionexplorer/reconciler.go
- pkg/products/threescale/prometheusRules.go
- pkg/products/threescale/reconciler.go
- pkg/products/ups/prometheusRules.go
- pkg/products/ups/reconciler.go
- pkg/resources/prometheusRules.go
- pkg/resources/prometheusRules_test.go
- test/common/alerts_exist.go
Refactor the alert reconciliation logic for all the products, and add logic
to delete the alerts if the RHMI instanced is marked for deletion.
In order to verify this PR, follow these steps:
1. Install RHMI on a cluster
2. Once installation is complete, verify that the *alerts have been created
3. Uninstall RHMI (delete the RHMI CR)
4. Verify that the *alerts are deleted
\* The following is a table with the alerts reconciled for each namespace:
| Product | Namespace | Alerts |
| ---------- | ---------------- | -------- |
| AMQ Online | `redhat-rhmi-amq-online` | `rhmi-amq-online-slo`, `ksm-endpoint-alerts`, `ksm-amqonline-alerts` |
| Apicurito | `redhat-rhmi-apicurito` | `ksm-apicurito-alerts`, `ksm-endpoint-alerts` |
| Apicurito | `redhat-rhmi-apicurito-operator` | `ksm-endpoint-alerts` …
> INTLY-8421 Delete alerts during uninstall

- pkg/controller/installation/installation_controller.go
Makes the RHMI operator to be able to add `AlertingEmailAddress` to pre-existing cluster that already have rhmi CR created. 
https://issues.redhat.com/browse/INTLY-9163
- Install the operator locally from master branch
```$  make cluster/prepare/local && operator-sdk run --local --namespace=redhat-rhmi-operator```
- Stop the operator-sdk and checkout this branch
- Verify if the `AlertingEmailAddress` field is not set in the RHMI CR
- Create an `ALERTING_EMAIL_ADDRESS` environment variable
```$  export ALERTING_EMAIL_ADDRESS="noreply-test@rhmi.com"```
- Run the operator and check if the `AlertingEmailAddress` is added to the RHMI CR with the value set in the environment variable
- Modify the value for `AlertingEmailAddress` in the RHMI CR and check if the value remains the unchanged.
> Adds alerting email address to rhmi CR for pre existing clusters

- test-cases/tests/documentation/i08-verify-partial-ag-dedicated-admin-user.md
> Test case for RHMIDOC-141

- pkg/products/solutionexplorer/reconciler.go
Update solution patterns to v1.0.10
> update sp versio to 1.0.10

- test-cases/tests/documentation/i14-verify-partial-ag-backup-window.md
> [RHMIDOC-107] partial_ag - Documenting backup window

- test-cases/tests/documentation/i15-verify-partial-ag-accessing-solution-explorer.md
> [RHMIDOC-122] partial_ag - Accessing Solution Explorer

- test-cases/tests/documentation/i08-verify-partial-ag-dedicated-admin-user.md
The tooling is broken, and we can not export the test cases to Polarion because the title doesn't respect the standard structure
> Fix I08 title otherwise the id is not detected

- test-cases/tests/documentation/i12-verify-partial-ag-associating-apicast.md
> [RHMIDOC-111] partial_ag - Associating APICast

- test-cases/tests/documentation/i13-verify-partial-ag-network-policy.md
> [RHMIDOC-80] partial_ag - Network Policy

- test-cases/tests/documentation/i09-verify-partial-gs-using-solution-patterns.md
> Test Case for RHMIDOC-187

- pkg/products/solutionexplorer/reconciler.go
update solution patterns to 1.0.11 to hide SP3 to avoid an issue where Slack has changed its API in newly created workspaces.
> update sp version to 1.0.11

- test-cases/tests/upgrade/n01-mesure-downtime-during-openshift-upgrade.md
An update to N01 test case. Changes are done to the 
- `Prerequisites` part ( oc must be of version 4.3 + )
- Step 5 and 6 require QE Team support
> Updating N01 test case

- Makefile
- scripts/setup-delorean-pullsecret.sh
> Create and link secrets for 3scale and fuse imagestreams

- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
JIRA Link:  https://issues.redhat.com/browse/INTLY-4885
Check first for the secret created by the pagerduty operator, if
exists then use that, else consider the secret created by CSSRE
and use it.
> Fetch the pager duty secret that the Pager duty operator creates

- OWNERS
He's an okay guy and will be the engineering release coordinator for
the upcoming release.
> Make grdryn an approver for release coordination

- test-cases/tests/upgrade/n03-verify-that-the-minimal-cidr-block-is-configured-correctly.md
Updated test-case to have the correct verification steps.
> N03 update

- test-cases/tests/alerts/c04-verify-alerts-exist.md
- test-cases/tests/backup-restore/j03-verify-that-namespaces-get-recreated-by-the-integreatlyopera.md
Minor test-case updates
add time estimate for C04
better time estimate for J03
remove dependency on J01/J02 from J03 after J01/J01 were removed
> Minor test case updates (C04/J03)

- pkg/products/threescale/prometheusRules.go
* Update alert rules for ThreeScaleZyncPodAvailability, label_threescale_component_element='' -> label_threescale_component_element='zync'
> Update alert rules for ThreeScaleZyncPodAvailability

- scripts/setup-delorean-pullsecret.sh
Use jq to extract the auth token from the delorean pull secret so it works regardless of the file formatting.
> Use jq to extract the auth token from the delorean pull secret

- test-cases/tests/walkthroughs/g15-verify-soluton-explorer-customer-settings-backup.md
- test-cases/tests/walkthroughs/g16-verify-settings-notifications-pop-up.md
New test-case for sol ex settings
> Added test case for Sol Ex Settings banner

- test-cases/package-lock.json
- test-cases/tests/backup-restore/j03-verify-that-namespaces-get-recreated-by-the-integreatlyopera.md
Added a note to comment out unnecessary tests, speeding up the time taken to complete this test, as well as a minor note reminding about the need for manual 3scale namespace restoration.
> J03 - Add note to comment out unnecessary tests

- test-cases/tests/uninstallation/o01-verify-cloud-resources-can-be-properly-cleaned-up-in-case-of.md
New test case for RHMI failed uninstallation alerts + cleanup
https://issues.redhat.com/browse/INTLY-8272
> feat: test case for RHMI cleanup

- test-cases/tests/uninstallation/o01-verify-cloud-resources-can-be-properly-cleaned-up-in-case-of.md
https://issues.redhat.com/browse/INTLY-8272
> fix: o01 test case

- test/common/3scale_crudl.go
Temporary workaround until https://issues.redhat.com/browse/INTLY-8433 is done
> Ignore failure of a flaky 3scale crudl test

- test-cases/tests/backup-restore/j06-verify-codeready-backup-and-restore.md
Minor typo change on PLQSL DB table name
> minor syntax change

- test/functional/main_test.go
Assign a name to the generated JUnit report so that it's not reported in ReportPortal as no_name
> Assign a test-suite name to the JUnit report

- test-cases/tests/products/h11-verify-3scale-smtp-configuration.md
Updated test case with automation tag
> Update automated tag of H11

- test/common/alerts_exist.go
Fixes https://issues.redhat.com/browse/INTLY-9582
> fix: alert test filenames for "ResourceDeletionStatusPhaseFailed"

- test-cases/tests/walkthroughs/g07-verify-changes-for-customising-solution-explorer-user-roles.md
> Update G07 test case steps

- test/common/3scale_smtp.go
Fix for flaky 3scale smtp test.
updated rollout strategy to force recreate so that all pods are recreated rather than created in a rolling strategy.
updated check to check against readyreplicas and to make sure that replicas match expected number of replicas
Added skip if there are issues with testing idp until https://issues.redhat.com/browse/INTLY-8433 is fixed.
Type of change
[ X] Bug fix (non-breaking change which fixes an issue)
> 3scale smtp fix

- pkg/controller/subscription/webapp/main.go
> Link to JIRA:  https://issues.redhat.com/browse/INTLY-9467
1. Begin an RHMI installation through OLM
2. Before the installation finishes (make sure the WebApp CRD does not exist yet) simulate an upcoming upgrade
3. Verify that the upgrade is scheduled successfully in the RHMIConfig status
4. Edit the RHMIConfig upgrade spec to make it approve the upgrade
5. Verify that no error logs are shown in the operator Pod and the upgrade is approved
> INTLY-9467 Skip errors in web app notification due to no kind found

- pkg/resources/marketplace/manifestHelper.go
change to include older CRDs still being referenced only when there aren't newer versions available. 
This can be verified using the new version of 3scale from https://issues.redhat.com/browse/INTLY-9065 
and checking that the old crds are included with the new ones
> INTLY-9099 Update configmap CSV to include CRDs from older manifests

- test/functional/aws_s3_resources_exist.go
- test/functional/aws_shared_functions.go
- test/functional/tests.go
automatest test to check for aws s3 blob resources
> automatest test to check for aws s3 blob resources

- test/common/alerts_mechanism.go
https://issues.redhat.com/browse/INTLY-9697
Based on failed test [here](https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Integreatly/job/rhmi-install-addon-flow/218/console) and [this test case](https://github.com/integr8ly/integreatly-operator/pull/1027/files#diff-231c5ff530657ac84ede9045e779b3a0R33)
> fix: test c03: pagerduty key

- test/functional/integreatly_test.go
> impersonate the system admin user

- pkg/controller/installation/installation_controller.go
An RHMI CR has a Version field and a ToVersion field. The ToVersion field is set during upgrade. Post upgrade, the version field is set to ToVersion. On automatic upgrades (meaning the InstallPlan is auto approved) the logic to set ToVersion is done during Subscription Reconcile. 
This code change caters for the manual (meaning the InstallPlan is manually approved) scenario. 
Install and then upgrade RHMI manually and automatically. Verify that the version field on the CR is set to the correct version before and after the upgrade.
```
oc -n redhat-rhmi-operator get rhmi rhmi -o yaml | grep ersion
```
See [deploying RHMI with bundle format](https://github.com/integr8ly/integreatly-operator/blob/master/README.md#deploying-to-a-cluster-with-olm-and-the-bundle-format) on how to install and …
> 9500 cr version on upgrade

- Dockerfile.functional
- go.mod
- test/common/shared_functions.go
- test/common/types.go
> fix the functional tests to allow them to run inside a cluster

- test-cases/tests/alerts/c08-verify-alert-links-to-sops.md
- test-cases/tests/alerts/c14-verify-3scale-uibbt-alerts.md
- test-cases/tests/alerts/c15-verify-pvc-alerts.md
- test-cases/tests/authorization/b08-verify-user-rhsso-permissions.md
- test-cases/tests/installation/a20-verify-cluster-prometheus-has-rhmi-targets.md
- test-cases/tests/monitoring/m05-verify-secrets.md
Added estimates to some test cases and one target fix (that test case for done against 2.4.0 and was not done against subsequent releases)
Not sure what to do to verify this, probably nothing.
> Added estimates to some test cases

- deploy/olm-catalog/integreatly-operator/2.6.1/integreatly-operator.v2.6.1.clusterserviceversion.yaml
- pkg/controller/installation/installation_controller.go
Cherry picking fix from master: https://github.com/integr8ly/integreatly-operator/pull/1073
> bump version on cr after manually approved upgrade

- go.mod
- pkg/products/fuseonopenshift/reconciler.go
- pkg/products/fuseonopenshift/reconciler_test.go
- pkg/products/fuseonopenshift/testtemplates/fis-image-streams.json
- pkg/products/fuseonopenshift/testtemplates/test_template.json
- pkg/products/reconciler.go
remove network calls in unit tests to overcome Travis issue of network timeouts
> remove network calls in unit tests

- test-cases/tests/documentation/i16-verify-partial-ag-maintenance-and-upgrades.md
> Create doc test case for maintenance windows and upgrades doc

- test/functional/aws_legacy_cluster_vpc.go
- test/functional/aws_standalone_vpc.go
> use the right namespace value to get aws configmap for CRO

- deploy/olm-catalog/integreatly-operator/2.6.1/integreatly-operator.v2.6.1.clusterserviceversion.yaml
Moving skipRange parameter under annotations
> Moving olm skiprange under annotations

- test-cases/README.md
- test-cases/tools/cmd/index.ts
- test-cases/tools/cmd/plan.ts
- test-cases/tools/lib/test-case.ts
- test-cases/tools/tools.ts
Added two new cmds `./tools.sh plan release ...` and `./tools.sh plan for ...` that would help updating the target version on the test cases
> Add the plan cmd to the test-cases tools to bulk update the target version

- test-containers.yaml
Switch the test container config to use the upstream 3scale test container
> switch to upstream 3scale test container

- test-cases/tests/performance/k03-run-performance-test-against-rhsso.md
Updates to the RHSSO performance testing test case template.
To verify:
- read through it
- you can try to create the jks file, if the steps are simple enough
- check the links if all of them are accessible
- not sure what else
> Updates to the RHSSO perf test case

- pkg/products/monitoring/prometheusRules.go
- test/common/alerts_exist.go
https://issues.redhat.com/browse/INTLY-9048
> remove CronJobSuspended alert

- test/common/grafana_routes.go
By using bearer token - https://issues.redhat.com/browse/INTLY-9480.
> fix e2e test flake issue - e05

- test/common/3scale_crudl.go
- test/common/3scale_smtp.go
- test/common/authdelay_first_broker_login.go
Adds a fix to the e2e test for the 3scale authentication
https://issues.redhat.com/browse/INTLY-8433
> fix flake e2e test for 3scale authentication

- test-cases/README.md
Document how to include manual test cases into the next release
> Docs: How to include manual tests into the next release

- test/common/grafana_routes.go
> fix grafana routes e2e test - list secrets

- test-cases/tests/high-availability/f04-verify-aws-s3-resources-exist-and-are-in-expected-state.md
> add 3scale test case

- .gitignore
- test/common/3scale_crudl.go
- test/common/3scale_smtp.go
- test/common/authdelay_first_broker_login.go
- test/common/rhmi_config.go
- test/common/shared_functions.go
added persisting auth related resources on certain test failures
> added persisting auth related resources on certain test failures

- deploy/cro-configmaps.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/controller/installation/bootstrapReconciler.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/types.go
Addition of new managed-3scale installation type. Addresses https://issues.redhat.com/browse/MGDAPI-2
There's a new installation type "managed3scale" added, a new config map for managed-3scale and refactored the bootstrap "checkCloudResources" function logic to set storage to "openshift" in case of `useClusterStorage` being set to true and storage set to "aws" if `useClusterStorage` is set to false.
In my understanding since there's been some work done around the population of CRO configmaps this PR should be verified on both, BYOC and non-BYOC clusters.
1) provision BYOC cluster
2) in https://github.com/integr8ly/integreatly-operator/blob/master/pkg/controller/installation/installation_controller.go#L159 set:
- `type` to : `string(integreatlyv1alpha1.InstallationTypeManaged3scale)`
- …
> MGDAPI-2 - new install type

- test-cases/tests/performance/k03-run-performance-test-against-rhsso.md
Small workaround note for k03 test case.
To verify I think just eye review is sufficient.
> Tag update in k03 SSO performance test case

- test-cases/tests/alerts/c14-verify-3scale-uibbt-alerts.md
- test-cases/tests/alerts/c15-verify-pvc-alerts.md
- test-cases/tests/authorization/b05-verify-codeready-crudl-permissions.md
- test-cases/tests/backup-restore/j08-verify-user-sso-backup-and-restore.md
- test-cases/tests/backup-restore/j10-verify-amq-backup-and-restore.md
- test-cases/tests/backup-restore/j11-verify-ups-backup-and-restore.md
- test-cases/tests/dashboards/e07-verify-drill-down-links.md
- test-cases/tests/monitoring/m03-verify-number-of-pods-for-amo.md
- test-cases/tests/monitoring/m05-verify-secrets.md
- test-cases/tests/performance/k01-run-performance-test-against-amq-online.md
- test-cases/tests/products/h01-ups-verify-that-ups-can-send-push-notification.md
- test-cases/tests/products/h05-verify-integration-between-fuse-online-and-openshift.md
- test-cases/tests/products/h06-verify-integration-between-codeready-and-openshift.md
- test-cases/tests/products/h08-verify-amq-online-crs-can-be-modified-and-are-not-reset.md
- test-cases/tests/uninstallation/o01-verify-cloud-resources-can-be-properly-cleaned-up-in-case-of.md
- test-cases/tests/uninstallation/o02-verify-if-cro-operator-removes-remaining-snapshots-for-rds-e.md
- test-cases/tests/upgrade/n09-verify-that-upgrades-rollout-can-be-paused.md
- test-cases/tests/walkthroughs/g04-verify-api-management-walkthrough.md
- test-cases/tests/walkthroughs/g05-verify-data-sync-walkthrough.md
- test-cases/tests/walkthroughs/g08-verify-addition-of-breadcrumbs-to-solution-explorer.md
According to the Test Plan in the 2.7.0 we will not test the following parts:
* Solution Patterns
* Coderady
* Fuse Online
* SSO
* AMQ
* UPS
therefore I've postponed all relative test cases to the 2.8.0 to reduce the tests required for 2.7.0
> Prepare test cases for 2.7.0

- test-cases/tests/performance/k02-run-performance-test-against-3scale.md
Minor change for something that confused me while executing the test case
> added an extra step to the k02 walthrough

- test-cases/tests/backup-restore/j08-verify-user-sso-backup-and-restore.md
- test/scripts/backup-restore/j08-verify-user-sso-backup-and-restore.sh
- test/scripts/backup-restore/postgres.sh
> Link to JIRA: https://issues.redhat.com/browse/INTLY-8973
Create script that automates the backup and restore test for SSO.
Update the test case to point to the script instead of the SOP
To verify this PR you'll need the following pre-requisites:
1. A BYOC cluster
2. The AWS CLI configured with the credentials for the cluster
Perform the following steps:
1. Install RHMI with `useClusterStorage` set to `false`
2. Wait for the installation to complete
3. Create the testing IdP
```sh
```
4. Perform the [J08](https://github.com/sergioifg94/integreatly-operator/blob/INTLY-8973/test-cases/tests/backup-restore/j08-verify-user-sso-backup-and-restore.md) test and verify that it's completed successfully
> INTLY-8973: Automate backup and restore test for SSO

- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/prometheusRules.go
- pkg/products/monitoring/reconciler.go
- test-cases/tests/alerts/c14-verify-rhmi-upgrade-alerts-are-present.md
- test-cases/tests/alerts/c17-verify-rhmi-upgrade-alerts-are-present.md
> Link to JIRA: https://issues.redhat.com/browse/INTLY-7551
Add alert in the `openshift-monitoring` namespace that will fire if the operator upgrade
takes more than 10 minutes.
Add manual test case to verify that the alert is present and the query is valid.
1. Install RHMI through OLM:
1. Create a bundle for 2.6.0 with no `replaces` field, and pointing to an image built from this PR. Make sure the version in `version/version.go` is 2.6.0
2. Create a bundle for 2.7.0 that replaces 2.6.0, and pointing to and image build from this PR but change the version in `version/version.go` to 2.7.0
3. Create an index 2.6.0 with the 2.6.0 bundle, and an index 2.7.0 with both indices
4. Create the CatalogSource pointing to the 2.6.0 index
2. Wait for the installation to complete
3. Verify that a …
> INTLY-7551: Add alert for operator upgrades

- pkg/products/monitoring/prometheusRules.go
- templates/monitoring/jobs/openshift_monitoring_federation.yaml
- test/common/alerts_exist.go
Had to create a new one because of permissions issue. Original PR: https://github.com/integr8ly/integreatly-operator/pull/1128
https://issues.redhat.com/browse/INTLY-9458
> Intly 9458

- pkg/products/monitoring/prometheusRules.go
- templates/monitoring/jobs/openshift_monitoring_federation.yaml
- test/common/alerts_exist.go
Adds a new warning alert for abnormal operator CSVs
https://issues.redhat.com/browse/INTLY-9458
> INTLY-9458 - Add alert for abnormal CSVs

- test-cases/tests/documentation/i16-verify-partial-ag-rhmi-config.md
The I16 should be tested in the 2.7.0 release
> Add 2.7.0 target to the I16 test case

- test-cases/tests/high-availability/f04-verify-aws-s3-resources-exist-and-are-in-expected-state.md
Update the steps in test case F04 as the AWS command returns json
jira: https://issues.redhat.com/browse/INTLY-10019
update test cast markdown
> update the test case F04 change the output of the command to json

- test-cases/tests/alerts/c16-verify-ocm-sendgrid-service-alerts.md
Updating SendGrid test case (C16)to include steps for checking Production prometheus alerts.
> Updating SendGrid test case with production references

- test-cases/tests/installation/a26-verify-sendgrid-credentials-are-configured-properly.md
- test-cases/tests/uninstallation/o03-verify-sendgrid-credentials-are-removed.md
- test/common/sendgrid_credentials_valid.go
- test/common/tests.go
https://issues.redhat.com/browse/INTLY-9992
> test: smtp credentials are valid

- pkg/controller/subscription/subscription_controller.go
- pkg/controller/subscription/subscription_controller_test.go
The subscription controller decides whether to reconcile a subscription or not based
on the subscription namespace (if it matches the reconciler ns), and the name, if
it's either "integreatly", or "addon-rhmi" (The name of the subscription created by the
addon installation).
Refactor this logic to be based on a list of names to reconcile, and include
"addon-managed-api-service" to the list, in order to reconcile subscriptions created
by the Managed API addon.
Add unit tests for new logic
Coming soon... (when the new addon is available in managed tenants) 😛
> MGDAPI-10: Reconcile Managed API addon subscription

- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/threescale/reconciler.go
Update reconciliation of ConsoleLink CRs to:
1. Add link to SSO as "API Management SSO"
2. Rename link to 3scale as "API Management"
3. Group these links into "OpenShift Managed Services" section
In order to fully verify this PR:
1. Install the operator from master
2. Once the operator is installed, check that there's a 3scale link in the Applications menu
3. Change the operator to this PR
4. Wait for it to start and fully reconcile
5. Verify that the Applications menu contains:
```
OpenShift Managed Services
API Management
API Management SSO
```
6. Uninstall the operator by deleting the RHMI CR
7. Verify that the links have been removed
> MGDAPI-89: Update ConsoleLink reconciliation

- OWNERS
> update codeowners for MGDAPI

- pkg/controller/namespacelabel/namespacelabel_controller.go
Update and refactor logic in namespace controller to check for the label set for the MGDAPI add-on when the add-on is deleted, which triggers the service uninstall.
1. Install MGDAPI from this PR
2. Wait for the installation to complete
3. Patch the `redhat-rhmi-operator` namespace object, adding the following label:
```yaml
api.openshift.com/addon-managed-api-service-delete: 'true'
```
4. Verify that the uninstall process begins
> Support uninstallation by namespace label for MGDAPI addon

- test/common/operand_versions.go
- test/common/operator_versions.go
Unskipping tests that were skipped due to failures. The test hasn't failed for the last 2 months.
> unskipping tests A05 and A07

- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
> Fixes https://issues.redhat.com/browse/MGDAPI-233
Move logic to reconcile "API Management SSO" ConsoleLink from RHSSO
Reconciler to User SSO Reconciler
1. Install the operator from this PR
2. Once the installation is completed, check that the link to "API Management SSO" points to the User SSO route
> MGDAPI-233: Move ConsoleLink from RHSSO to User SSO

- pkg/products/marin3r/reconciler.go
Add Prometheus to the Rate Limiting Solution
- Install managed-api and confirm complete
- Confirm that the RateLimit metrics are being scraped
> add prometheus resources to scrape rate limiting service

- test/scripts/backup-restore/postgres.sh
Seen when working on https://issues.redhat.com/browse/MGDAPI-267
> fix: backup-restore script typo

- Makefile
- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- test-cases/tests/backup-restore/j03-verify-that-namespaces-get-recreated-by-the-integreatlyopera.md
- test/common/cro_cr_success.go
- test/common/deployment_types.go
- test/common/integreatly_stages.go
- test/common/monitoringspec.go
- test/common/namespace_created.go
- test/common/namespace_restoration.go
- test/common/network_policy_access_ns_to_svc.go
- test/common/routes_exist.go
- test/common/subscription_install_plan.go
- test/common/tests.go
- test/common/types.go
- test/common/verify_metrics_scrapped.go
- test/functional/aws_shared_functions.go
Update / Include e2e tests to verify rate limit service components are successfully installed
Jira:
* https://issues.redhat.com/browse/MGDAPI-308
Sample test output log - https://gist.github.com/KevFan/297eb3509074398b320bf1d691526229
* Checkout this branch and install Managed API 
```
make code/run
```
* Run the following functional tests that were updated / added by this PR
```
export DESTRUCTIVE=true; go clean -testcache && go test -v ./test/functional -run="//(^A01)|(^A03)|(^A08)|(^A09)|(^A11)|(^A13)|(^Verify servicemonitors)|(^Verify prometheus metrics)|(^J03)" -timeout=80m
```
* Verify all tests passed
> MGDAPI-308 - Rate limit intallation e2e

- cmd/manager/main.go
- deploy/operator.yaml
Allows log levels to be decided by env var
- [ x ] New feature (non-breaking change which adds functionality)
> support log levels

- scripts/ec2_deploy_teardown/README.md
Added the ec2-remove details to doc
README update for usage of EC2 deploy and remove scripts
> Update to README for the ec2 deployment and remove scripts

- Makefile
> use prow image instead of quay image

- Makefile
- pkg/config/monitoring.go
- pkg/products/monitoring/dashboards/criticalSLOAlerts.go
- pkg/products/monitoring/dashboardsHelper.go
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
[MGDAPI-309](https://issues.redhat.com/browse/MGDAPI-309)
Created a new SLO dashboard specific to RHOAM installs.
We need to verify that both the new and existing dashboard SLO summary dashboards are created as per the install type
- To ensure the correct dashboard get created for managed installs, complete an install of type `managed`
- Ensure that the install completes, and the `critical-slo-summary` Grafana dashboard is created and populated with the `SLO Summary` and `redhat-rhmi*` panels. This install is to test that there are no changes to this dashboard.
- Complete an install of type `managed-api`:
```
export NAMESPACE_PREFIX=redhat-managed-api- && export INSTALLATION_TYPE=managed-api
make code/run
```
- Ensure that the install completes, and the …
> Added RHOAM specific SLO dashboard

- deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
- deploy/crds/integreatly.org_rhmis_crd.yaml
- pkg/products/monitoring/dashboards/criticalSLOAlerts.go
Fix User SSO alert number is incorrect for Crtiical SLO dashboard 
Jira:
* https://issues.redhat.com/browse/MGDAPI-320
* Install managed api
```
make code/run
```
* Once installation completes, go through E04 test case
* https://issues.redhat.com/browse/MGDAPI-291
* Ensure Critical SLO panel for user-sso shows the correct number of firing alerts
* Should be showing `3` alerts firing
* Repeat for managed install type
```
export INSTALLATION_TYPE=managed
make code/run
```
> MGAPI-320 - use correct user sso namespace in critical slo dashboard

- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
Reconcile TopologySpreadConstraints to 3scale
> MGDAPI-231_Reconcile_TopologySpreadConstraints_to_3scale

- .gitignore
- Makefile
- README.md
- deploy/olm-catalog/managed-api-service/0.1.0/integreatly.org_rhmiconfigs_crd.yaml
- deploy/olm-catalog/managed-api-service/0.1.0/integreatly.org_rhmis_crd.yaml
- deploy/olm-catalog/managed-api-service/0.1.0/managed-api-service.v0.1.0.clusterserviceversion.yaml
- deploy/olm-catalog/managed-api-service/managed-api-service.package.yaml
- scripts/README.md
- scripts/bundle-rhmi-operators.sh
- scripts/prepare-release.sh
Cherry picked changes from https://github.com/integr8ly/integreatly-operator/pull/1155 as well as https://github.com/integr8ly/integreatly-operator/commit/6f23f2fd3b241762e6fb70bca3f4ad8e992a8daa#diff-a43cbbe69ab415400a726800c46607654f0c032cfd592ce270cd4180ebbaa4cb to fix failing Jenkins
> pulling in prepare release script changes to fix broken jenkins

- deploy/crds/integreatly.org_rhmis_crd.yaml
- deploy/role.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/controller/installation/bootstrapReconciler.go
- pkg/controller/installation/installation_controller.go
- pkg/products/monitoring/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/resources/podPriority.go
Add priorityClass and configure RHSSO, USERSSO and threescale to use the priorityClass
Verification steps. 
1. Install managed-api type. 
2. Confirm a new priorityclass CR called `managed-service-priority`
3. Confirm managed-api CR has the field `priorityClassName` and it's value is `managed-service-priority`
4. Confirm RHSSO and USERSSO `keycloak` statefulsets have the field `priorityClassName` with the value of `managed-service-priority` 
5. Confirm threescale deployment configs have the field `priorityClassName` with the value of `managed-service-priority` 
Extra verification step if time allows, Install managed type and confirm the above doesn't exist.
> MGDAPI-234 Add priorityClass and configure RHSSO, USERSSO and threescale to use the priorityClass

- scripts/prepare-release.sh
> Fix for installation type been set

- scripts/setup-sso-idp.sh
- test/common/alerts_exist.go
- test/common/authdelay_first_broker_login.go
- test/common/testing_idp.go
- test/functional/aws_s3_resources_exist.go
- test/functional/aws_shared_functions.go
* Fix AWS alerts tests for managed api install
* Fix Blobstoage test for managed api install
* Update IDP from test and script to allow them be used interchangably
Jira:
* https://issues.redhat.com/browse/MGDAPI-244
* Check out this branch
* Provision a **BYOC** cluster
* Install managed-api with **external storage**
```
export USE_CLUSTER_STORAGE=false
make code/run
```
* Run functional tests from this ticket
```
go clean -testcache && go test -v ./test/functional -run="//(^A16)|(^B03)|(^B04)|(^B06)|(^C04)|(^H03)|(^H07)|(^H11)|(^Verify Network Policy)|(^F04)" -timeout=80m
```
* Verify tests passed
* Run idp script **after** tests
```
PASSWORD=Password1 DEDICATED_ADMIN_PASSWORD=Password1 ./scripts/setup-sso-idp.sh
```
* Try sign into cluster with any …
> MGAPI-244 - Fix failing tests for managed api install

- deploy/crds/examples/rhmi.cr.yaml
- pkg/controller/installation/installation_controller.go
add priorityClassName: rhoam-pod-priority to rhmi.cr.yaml
> add priorityClassName: rhoam-pod-priority to rhmi.cr.yaml

- Makefile
Fix typo in how variables have been called
> Fix for Makefile tag versions

- test/common/priority_validate.go
- test/common/tests.go
- test/common/types.go
Added automated test for test cases A27 and A28 which will be added with PR https://github.com/integr8ly/integreatly-operator/pull/1214
> add test for test cases A27 and A28

- scripts/prepare-release.sh
Update prepare-release script to display RHOAM to users rather than RHMI
> [WIP]Update prepare-release script for RHOAM

- test-cases/tools/cmd/polarion.ts
Fix the Polarion test cases description
> fix: Polarion test cases description

- scripts/prepare-release.sh
Update prepare release script for RHOAM
> [WIP] Update prepare release script for RHOAM

- .gitignore
- scripts/capture_resource_metrics.sh
JIRA: https://issues.redhat.com/browse/MGDAPI-368
I created a script that will run through Prometheus queries to gather data that we want to capture in the spreadsheet here:
https://docs.google.com/spreadsheets/d/1v_bZIk8B_thZi93hGBNiOOnbSix0gmpwy3LV_s4WFPw/edit#gid=231944674
The script outputs data that can be copy-pasted into the spreadsheet^
Example output:
```
$ ./scripts/capture_resource_metrics.sh 
60
36
370.3244514465332
278.59929275512695
6145.635817307692
130.53678743131877
1893.8111263736268
1871.7279361263736
12340.445312500004
0.03771175822195376
0.002610469721037184
0.03431138761436085
0.0238761652522742
0.2259820140723326
6603.55859375
122.6171875
3504.53515625
1875.2421875
14512.63671875
1.6822039901579942
0.12463877987516234
6.836452448034511
0.032817338164460405 …
```
> MGDAPI-368 - add a script for capturing metrics after perf test

- scripts/prepare-release.sh
Update prepare release script to remove rhoam-operator command and add RHOAMConfig display name
> Update Prepare Release script to add RHOAMConfig display name

- test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
Improved test case for multi AZ. Based on lessons learned during RHOAM v0.2.0 testing. 
I think there's no need to do the test case - it is quite long. Eye review should be enough, you can try certain scripts/commands etc if you really want.
> Updated Multi AZ test scenario

- manifests/integreatly-3scale/0.6.1/3scale-operator.v0.6.1.clusterserviceversion.yaml
- manifests/integreatly-3scale/0.6.1/apps.3scale.net_apimanagerbackups_crd.yaml
- manifests/integreatly-3scale/0.6.1/apps.3scale.net_apimanagerrestores_crd.yaml
- manifests/integreatly-3scale/0.6.1/apps.3scale.net_apimanagers_crd.yaml
- manifests/integreatly-3scale/0.6.1/capabilities.3scale.net_backends_crd.yaml
- manifests/integreatly-3scale/0.6.1/capabilities.3scale.net_products_crd.yaml
- manifests/integreatly-3scale/0.6.1/capabilities.3scale.net_tenants_crd.yaml
- manifests/integreatly-3scale/3scale.package.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
Update 3scale version 
To validate, install managed-api and confirm successful completion of install and that the 3scale operator reports the correct version of 0.6.1
> MGDAPI-513 3scale version bump

- test-cases/tests/performance/k04-run-performance-test-against-rhoam-3scale-user-sso.md
Added test case for performance testing of 3scale + SSO
Eye review, probably no need to actually run the test case.
> Added RHOAM performace test case

- test-cases/README.md
- test-cases/tools/cmd/polarion.ts
* Added new project ID (for RHOAM)
* updated docs
> fix: update polarion testrun command

- Makefile
- deploy/redhat-rhoam/role_binding.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/controller/installation/installation_controller.go
Removal of RHMI from customer facing parts of RHOAM installation 
To Validate: Do an install of managed-api and confirm no mentions of RHMI in customer accessible areas such as namespace
secrets etc. Also, check for mentions of managed-api as these should be RHOAM
> MGDAPI-419

- pkg/addon/addon.go
- pkg/addon/parameters.go
- pkg/addon/parameters_test.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/installation/installation_controller_test.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/marin3r/reconciler.go
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
> Link to Jira: https://issues.redhat.com/browse/MGDAPI-412
Create `addon` package to include addon related logic, and add logic to retrieve addon parameters.
Add logic to set the CIRD value from the addon parameters.
On a cluster
1. Prepare the cluster and ensure the `cloud-resources-aws-strategies` ConfigMap doesn't exist
```sh
oc delete configmaps cloud-resources-aws-strategies -n redhat-rhmi-operator
```
1. Create the parameters secret
```sh
oc create secret generic addon-managed-api-service-parameters -n redhat-rhmi-operator \
--from-literal=cidr-range=10.1.0.0/23 \
--from-literal=notification-email=test-customer@redhat.com
```
1. Install MGDAPI locally
```sh
```
1. Verify the CIRD parameter is reconciled
1. Wait …
> MGDAPI-412: Ability to read addon parameters

- pkg/apis/integreatly/v1alpha1/rhmi_types.go
follow-up on https://github.com/integr8ly/integreatly-operator/pull/1316
> fix: update 3scale product version

- scripts/prepare-release.sh
Remove service account name change in prepare-release script
> remove service account name change

- pkg/products/threescale/reconciler.go
JIRA Link: https://issues.redhat.com/browse/INTLY-10278
Added  more logging information for rhmi 3scale reconciliation, when it
invokes the 3scale API/End point.
Addition of more logging information
> Add more logging info for RHMI 3Scale reconciler

- README.md
Update readme e2e test command
> Update e2e test instructions

- Makefile
- go.mod
- pkg/webhooks/operator_webhooks.go
Fixing a few more namespace prefix bugs
> webhook selector is always rhmi-operator

- test-cases/tests/alerts/c18-validate-api-usage-alerts.md
Updating C18 API usage test case to validate email notifications for the BU, SRE and Customer respectively.
Also replaced references of `RHMI` with `RHOAM`
Related Jira: https://issues.redhat.com/browse/MGDAPI-537
> Updating C18 API usage test case to validate email notifications

- test-cases/tests/authorization/b09-validate-authentication-with-ldap-idp.md
Test case to validate the integration of RHOAM with LDAP IDP
https://issues.redhat.com/browse/MGDAPI-520
Go through the steps in the test case and make sure it works as expected
> add test case for authenticate RHOAM with LDAP IDP

- test/common/3scale_smtp.go
- test/common/alerts_exist.go
- test/common/dashboards_exist.go
- test/common/deployment_types.go
- test/common/monitoringspec.go
- test/common/namespace_created.go
- test/common/pdbs_exist.go
- test/common/priority_validate.go
- test/common/pvc_validate.go
- test/common/scale_up_replicas_rhsso.go
- test/common/scale_up_replicas_threescale.go
- test/common/subscription_install_plan.go
- test/common/types.go
- test/common/verify_metrics_scrapped.go
- test/osde2e/managed_api_test.go
- test/osde2e/pre-test.go
This is a refactor required in order for our osde2e test runs to pass after changes around namespace prefix.
> osde2e initial refactor

- pkg/products/cloudresources/reconciler.go
add a default CIDR range value
> add default cidr value

- test/common/3Scale_user_promotion.go
- test/common/3scale_crudl.go
- test/common/3scale_smtp.go
- test/common/alerts_firing.go
- test/common/authdelay_first_broker_login.go
- test/common/tests.go
> Skip Failing Flaky tests

- test/common/grafana_routes.go
- test/common/tests.go
> skipping e05

- test-cases/tests/documentation/i06-aws-info-byoc.md
- test-cases/tests/documentation/i06-verify-aws-info-byoc.md
Test published AWS SCP info for BYOC in a KCS article.
> MGDDOC-55: Test case for adding BYOC info for RHOAM

- test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
https://issues.redhat.com/browse/MGDAPI-569
> fix: repurpose ldap idp test case

- test-cases/tests/performance/k04-run-performance-test-against-rhoam-3scale-user-sso.md
Small update to performance testing scenario to make sure alerts are reviewed during the perf test run.
> To watch alerts during performance testing

- test-cases/tests/documentation/i07-overview-of-red-hat-openshift-api-management.md
Please review the new overview of RHOAM.
> MGDDOC-52 New test case for review of RHOAM overview

- test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
- test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
* simple namespace prefix fix: https://github.com/integr8ly/integreatly-operator/pull/1425/commits/1a0fdc3b653258401d7d08fea67fe2d91f313107
* update p01 test case: add steps to verify pod redistribution after AZ recovery: https://github.com/integr8ly/integreatly-operator/pull/1425/commits/fa96c0854443fedffb2627d372a7a8f17ab8a1de
> Test cases updates

- test-cases/tests/alerts/c05a-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
> update to c05 test case

- test-cases/tests/alerts/c05a-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
- test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
Update to h22 test case script
Lint of c05 test case
> fix h22 test case and lint c05 test case

- test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
Updating email expected for c05b
> update to c05b

- test-cases/tests/installation/a31-verify-installation-on-all-osd-versions.md
Added test case about testing different OSD versions for RHOAM fresh install
> Various OSD versions valiation test case added

- test-cases/tests/authorization/b01b-verify-that-the-users-can-login-in-all-products.md
- test-cases/tests/installation/a29-verify-rate-limit-service-pods-are-running.md
Test cases updates for A29 & B01B
Jira:
* https://issues.redhat.com/browse/MGDAPI-694
* https://issues.redhat.com/browse/MGDAPI-685
> Update test cases A29 & B01B

- pkg/products/grafana/reconciler.go
- test-cases/tests/alerts/c18-validate-api-usage-alerts.md
https://issues.redhat.com/browse/MGDAPI-586
Update to Test Case c18 to include checks for the following
adding checks for grafana soft limits
tiered soft limit alerts - RHOAMApiUsageSoftLimitReachedTierX
and spike usage alert - RHOAMApiUsageOverLimit
Follow the steps to ensure the test works as expected
> Update to Test Case c18

- pkg/controller/installation/installation_controller.go
> Link to Jira: https://issues.redhat.com/browse/MGDAPI-702
Add support to reconcile the customer notification email from the add-on parameter Secret
1. Prepare the cluster
```sh
```
1. Create the parameters secret
```sh
oc create secret generic addon-managed-api-service-parameters -n redhat-rhmi-operator \
--from-literal=notification-email=test-customer@redhat.com
```
1. Install MGDAPI locally
```sh
```
1. Verify the email address parameter is reconciled
1. Check that the `.spec.alertingEmailAddress` is `test-customer@redhat.com`
2. Check that the address is included in the `BUAndCustomer` and `SREAndCustomer` receivers in the Alert Manager configuration:
1. Log in the alert manager
>
> …
> MGDAPI-702: Support update of customer notification email

- pkg/products/monitoring/dashboards/criticalSLOAlerts.go
- pkg/products/monitoring/dashboardsHelper.go
- test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
Cherry Pick from https://github.com/integr8ly/integreatly-operator/pull/1448 to release branch
> Release Cherry Pick MGDAPI-695

- pkg/products/grafana/reconciler.go
- test-cases/tests/alerts/c18-validate-api-usage-alerts.md
Cherry-pick of https://github.com/integr8ly/integreatly-operator/pull/1437
> adding checks for grafana soft limits

- Makefile
cleaning up the makefile a little, some errors that shouldn't  stop the pipelines are currently stopping the pipelines.
> ignore errors from makefile

- test-cases/tests/authorization/b03b-verify-rhoam-developer-user-permissions-are-correct.md
- test-cases/tests/authorization/b04a-verify-dedicated-admin-user-permissions-are-correct.md
- test-cases/tests/authorization/b04b-verify-dedicated-admin-user-permissions-are-correct.md
- test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
- test-cases/tests/monitoring/m05a-verify-secrets.md
- test-cases/tests/monitoring/m05b-verify-secrets.md
- test-cases/tests/uninstallation/o01b-verify-cloud-resources-can-be-properly-cleaned-up-in-case-o.md
The following PR includes test case improvements for the following test cases:
* [Jira](https://issues.redhat.com/browse/MGDAPI-687)
* [Jira](https://issues.redhat.com/browse/MGDAPI-690)
* [Jira](https://issues.redhat.com/browse/MGDAPI-691)
* [Jira](https://issues.redhat.com/browse/MGDAPI-707)
* [Jira](https://issues.redhat.com/browse/MGDAPI-709)
Test case update
> Test case improvment

- test-cases/tests/backup-restore/j05a-verify-3scale-backup-and-restore.md
- test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
- test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
- test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
- test/scripts/backup-restore/j05-verify-3scale-postgres-backup-and-restore.sh
- test/scripts/backup-restore/j07-verify-rhsso-backup-and-restore.sh
- test/scripts/backup-restore/j08-verify-user-sso-backup-and-restore.sh
- test/scripts/backup-restore/postgres.sh
* add variable for namespace prefix to backup & restore scripts
* update test cases to mention that variable (`NS_PREFIX`)
* add 3scale postgres b & r script
already verified by running backup & restore scripts for sso, user-sso and 3scale (postgres) against release testing cluster
> Fix backup and restore scripts

- test-cases/tests/products/h23-validate-that-rate-limit-service-with-customer-default-confi.md
https://issues.redhat.com/browse/MGDAPI-413
> feat: test case: h23 - rate limit customer config

- test/resources/util.go
These logs were for development only, and not intended to be merged.
> remove noisy logs

- test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
small updates to h23 test case
> fix: test case: update h23

- scripts/prepare-release.sh
> do not rename rhmi-developers

- pkg/controller/installation/installation_controller.go
Cherry-pick https://github.com/integr8ly/integreatly-operator/pull/1463
> fix: Reconcile webhooks before preflight checks

- Makefile
This change should fix issues we are seeing on some PROW jobs, e.g.:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/integr8ly_integreatly-operator/1196/pull-ci-integr8ly-integreatly-operator-master-e2e/1308673561585520640
> Fix SA login problem on self-signed clusters

- pkg/products/threescale/prometheusRules.go
Cherry pick https://github.com/integr8ly/integreatly-operator/pull/1478 to release branch
> Cherry pick mgdapi 913 to release branch

- test/common/dashboards_data.go
- test/common/dashboards_exist.go
cherry pick https://github.com/integr8ly/integreatly-operator/pull/1483
> fix flaky E02 & E03 - curl from grafana from prometheus pod

- test/common/alerts_exist.go
- test/common/tests.go
Flakey test skipped https://issues.redhat.com/browse/MGDAPI-934
> skipping test commenting out t.fatal for t.skip

- scripts/capture_resource_metrics.sh
- scripts/hyperfoil-request-stats.sh
script to gather hyperfoil stats
independent script for load testing
- Run a load test on hyperfoil and get the run number
```bash
export HYPERFOIL_URL=http://hyperfoil-hyperfoil.apps.mwcollabaz-byoc.2mv4.s1.devshift.org"
./hyperfoil-request-stats.sh <RUN>
```
Should get the following results for a run
```bash
./hyperfoil-request-stats.sh 0007
failed =  839
total =  31075
one percent = 310
===============================================================================================
Percentage failed =  2%
Percentage passed =  98%
===============================================================================================
90% Percentile
Mean =  176125478  Max =  1002438655
```
> script to gather hyperfoil stats

- pkg/addon/parameters.go
- pkg/addon/uninstall.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/namespacelabel/namespacelabel_controller.go
- pkg/controller/subscription/subscription_controller.go
- pkg/resources/rhmi.go
- pkg/webhooks/operator_webhooks.go
- pkg/webhooks/operator_webhooks_test.go
- pkg/webhooks/reconciler.go
- fix automatic non-service-affecting upgrades
- remove webhooks on uninstall
> Mgdapi 953

- pkg/addon/parameters.go
- pkg/addon/uninstall.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/namespacelabel/namespacelabel_controller.go
- pkg/controller/subscription/subscription_controller.go
- pkg/resources/rhmi.go
- pkg/webhooks/operator_webhooks.go
- pkg/webhooks/operator_webhooks_test.go
- pkg/webhooks/reconciler.go
- version/version.go
- uninstall webhooks
- approve upgrades in managed-api
- update version
> Mgdapi 953 1.0.1

- test-cases/tools/cmd/jira.ts
- test-cases/tools/lib/jira.ts
* updates "affects version" field in JIRA test cases with the version that's set in "fix version" field
Verified by generating test cases for this epic https://issues.redhat.com/browse/MGDAPI-951
> feat: test cases tool: update affects version field

- pkg/addon/parameters.go
- pkg/addon/uninstall.go
- pkg/controller/installation/installation_controller.go
- pkg/controller/namespacelabel/namespacelabel_controller.go
- pkg/controller/subscription/subscription_controller.go
- pkg/resources/rhmi.go
- pkg/webhooks/operator_webhooks.go
- pkg/webhooks/operator_webhooks_test.go
- pkg/webhooks/reconciler.go
> Revert mgdapi 953

- pkg/resources/backup.go
JIRA: https://issues.redhat.com/browse/INTLY-10330
> Bump version of backup-container image

- pkg/products/apicurito/reconciler.go
- pkg/products/solutionexplorer/reconciler.go
- pkg/products/ups/reconciler.go
JIRA: https://issues.redhat.com/browse/INTLY-9766
Where the InsecureEdgeTerminationPolicy was not set (defaults to
"Allow"), I've also set it to "Redirect" here instead.
> Set HSTS header for some routes

- test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
Added a new test case, see https://issues.redhat.com/browse/MGDAPI-370. Hopefully we won't need to do this too often.
eye review only I guess. I had a few calls with 3scale QE and the comments in MGDAPI-370 were verified against RHOAM with 3scale 2.9.1.
But you can try yourself for sure.
> Added test case for 3scale custom policy

- Makefile
- deploy/olm-catalog/managed-api-service/1.0.1/integreatly.org_rhmiconfigs_crd.yaml
- deploy/olm-catalog/managed-api-service/1.0.1/integreatly.org_rhmis_crd.yaml
- deploy/olm-catalog/managed-api-service/1.0.1/managed-api-service.v1.0.1.clusterserviceversion.yaml
- deploy/olm-catalog/managed-api-service/managed-api-service.package.yaml
- version/version.go
This PR is bring over the changes that have been create as part of the v1.0.1 release. Which is required for new release to track the correct replaces images.
Jira: https://issues.redhat.com/browse/MGDAPI-1042
> Mgdapi 1042 Cherry Pick v1.0.1 changes over to master

- test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
Updated a30 test case based on the scenario tested in 1.0.0 GA release and 1.0.1 patch release
> fix: test case: a30

- pkg/products/monitoring/dashboards/criticalSLOAlerts.go
Branched from https://github.com/integr8ly/integreatly-operator/pull/1502 with an additional commit to fix dashboard panel were not loaded when Critical SLO Dashboard page is initially visited
Jira:
* https://issues.redhat.com/browse/MGDAPI-498
- Install RHOAM from this branch
- Run though E04B test case https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
- Access Grafana and verify two alerts are firing in the Critical SLO dashboard in the Marin3r Panel
> MGDAPI-498 - Marin3r Critical SLO Panel

- Makefile
- deploy/crds/integreatly.org_rhmis_crd.yaml
- deploy/operator.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
- pkg/controller/installation/installation_controller.go
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoring/reconciler_test.go
- templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
This PR has made changes to allow the work in #1511 pass the e2e test.
As part of this change we will need to add a new parameter to the managed tenants repo see PR 471
Verification
Spin up a cluster and run the operator locally overriding ALERT_SMTP_FROM and setting it to a value of your choice.
Once the install is complete, check the smtp config in alert manager
oc get secret alertmanager-application-monitoring -n redhat-rhoam-middleware-monitoring-operator -o=yaml
it should have the smtp_from set to your chosen email address.
> Mgdapi 995 cherry picked

- deploy/olm-catalog/managed-api-service/1.1.0/managed-api-service.v1.1.0.clusterserviceversion.yaml
Reverts integr8ly/integreatly-operator#1535
> Revert "release PR for version rhoam-v1.1.0"

- test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
Built on top of https://github.com/integr8ly/integreatly-operator/pull/1504 (that is waiting to be merged)
Commit to review: https://github.com/integr8ly/integreatly-operator/commit/bb22482ac811e4396a74f8173d02fd462e6d5a4c
> Add test case for cidr range

- pkg/controller/namespacelabel/namespacelabel_controller.go
Add the ability for hive to remove a cluster using a labeled configmap. 
To Verify:
1. Install RHOAM/RHMI from this branch
2. Once install is complete, add a config map in the integreatly operator namespace called `managed-service-api` / `rhmi` 
3. Label the config map with `api.openshift.com/addon-managed-api-service-delete=true`/ `api.openshift.com/addon-rhmi-operator-delete=true`
4. once the configmap is read the rhmi cr should have a deletion timestamp and the uninstall process should start.
> MGDAPI-1004 Update AddOn Delete Watch

- scripts/prepare-release.sh
https://issues.redhat.com/browse/MGDAPI-1073
* see https://github.com/integr8ly/delorean/pull/174 for more details
> fix: csv: service-affecting

- README.md
Updated description on how to use the olm bundle script in order for it to be used by the rhoam upgrade pipeline.
To verify read through and let me know if it makes sense, alternatively, follow the steps to create an index and bundle in your own quay.io repo and install rhoam on a cluster.
> MGDAPI-1075 update olm build script instructions

- test-cases/tests/alerts/c18-validate-api-usage-alerts.md
- test-cases/tests/installation/a29-verify-rate-limit-service-pods-are-running.md
- test-cases/tests/installation/a32-validate-sso-config.md
- test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
- test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
- test-cases/tests/upgrade/n03-verify-that-the-minimal-cidr-block-is-configured-correctly.md
* update test cases metadata based on test cases related to 1.1.0 release
* [add a32 test case](https://github.com/integr8ly/integreatly-operator/commit/c73cc9ef16df5ef26d32f3ff68e6fd9b4b035583)
> Rhoam 1 1 0 update test cases

- manifests/integreatly-grafana/3.8.1/grafana-operator.v3.8.1.clusterserviceversion.yaml
- manifests/integreatly-grafana/3.8.1/grafanadashboards.integreatly.org.crd.yaml
- manifests/integreatly-grafana/3.8.1/grafanadatasources.integreatly.org.crd.yaml
- manifests/integreatly-grafana/3.8.1/grafanas.integreatly.org.crd.yaml
- manifests/integreatly-grafana/grafana.package.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
Bump of Grafana to take in changes from MGDAPI-1030 
Install from this branch and verify operator version is 3.8.1 and that the grafana CR only updated as status changes happen rather than on every reconciliation
Bump of Grafana to take in changes from MGDAPI-1030
> MGDAPI-1030 Grafana version Bump

- scripts/ec2_deploy_teardown/deployEC2.sh
It seems the PublicIP check is too strict and the script fails even if the publicIP is correct.
eye review, run the script. I will attach the log from Jenkins in a minute
> Relaxing EC2 PublicIP check

- test/common/deployment_types.go
Fix RHMI e2e test
@briangallagher  @CathalOConnorRH
> rhmi expects 2 user-sso replicas

- deploy/olm-catalog/integreatly-operator/2.7.1/integreatly-operator.v2.7.1.clusterserviceversion.yaml
- deploy/olm-catalog/integreatly-operator/2.7.1/integreatly.org_rhmiconfigs_crd.yaml
- deploy/olm-catalog/integreatly-operator/2.7.1/integreatly.org_rhmis_crd.yaml
- deploy/olm-catalog/integreatly-operator/2.7.2/integreatly-operator.v2.7.2.clusterserviceversion.yaml
- deploy/olm-catalog/integreatly-operator/2.7.2/integreatly.org_rhmiconfigs_crd.yaml
- deploy/olm-catalog/integreatly-operator/2.7.2/integreatly.org_rhmis_crd.yaml
- deploy/olm-catalog/integreatly-operator/integreatly-operator.package.yaml
Add 2.7.1 and 2.7.2 manifests to master which were missing due to patch release. 
This is required as 2.8.0 CSV replaces 2.7.2
> add-2.7.1_2.7.2-manifests

- Makefile
- version/version.go
Prepare release script didnt update these files as part of the 2.8.0 release. 
A bug has been created to fix delorean.
> Fix-2.8.0-release

- manifests/integreatly-rhsso/12.0.1/keycloak-operator.v12.0.1.clusterserviceversion.yaml
- manifests/integreatly-rhsso/12.0.1/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/12.0.1/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/12.0.1/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/12.0.1/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/12.0.1/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/rhsso.package.yaml
- pkg/apis/integreatly/v1alpha1/rhmi_types.go
- pkg/products/rhsso/reconciler.go
- test/common/dashboards_exist.go
Bump RHSSO operator version to v12.0.1 and operand to 7.4-16
1. Install RHOAM/RHMI from this branch and verify operand and operator versions match the above version number.
2. Ensure RHSSO has started correctly as there is a change to the authdelay jar in this PR and it must be added to the classpath.
3. Verify version 1.0.2 of the authdelay.jar has been downloaded in the extensions container of the keycloak pod
> MGDAPI-10370 Update RHSSO operator to v12.0.1

- test-cases/tests/alerts/c05a-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
- test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
- test-cases/tests/alerts/c10b-verify-additional-blackboxtargets.md
- test-cases/tests/alerts/c17b-verify-rhoam-upgrade-alerts-are-present.md
- test-cases/tests/alerts/c19-validate-creation-of-invalid-username-triggers-alert.md
- test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
- test-cases/tests/dashboards/e07b-verify-drill-down-links.md
- test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
- test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
- test-cases/tests/installation/a32-validate-sso-config.md
- test-cases/tests/installation/a33-validate-console-links.md
- test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
- test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
- test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
- test-cases/tests/upgrade/n01a-measure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n02a-upgrade-rhmi.md
- test-cases/tests/upgrade/n02b-upgrade-rhoam.md
Update of test cases for RHOAM 1.2.0
> test: test-cases: RHOAM 1.2.0

- Dockerfile.functional
- test/functional/integreatly_test.go
* fix condition for MULTIAZ tests
* add `noColor` flag to remove color format in test output
> test: minor updates to tests

- README.md
- scripts/README.md
https://issues.redhat.com/browse/MGDAPI-1275
I have been pretty ruthless here - think cleaning out you closet and throwing out anything you haven't worn in the last year type update.
Original See https://github.com/sergioifg94/integreatly-operator/pull/10
cc @makslion
**Verifcation Steps**
As well as reviewing the other changes verification should include following the steps in the `Local Dev` section to ensure that it's possible to get a successful intastallation of RHOAM/RHMI with just the information presented there.
> update README with up to date installation commands.

- pkg/config/monitoring.go
- pkg/products/monitoring/dashboards/croResources.go
- pkg/products/monitoring/dashboardsHelper.go
- test/common/dashboards_exist.go
Added new Grafana dashboard that displays CRO resource metrics
- Clone this branch
- Deploy locally on byoc cluster
- Check if CRO resources dashboard exists in middleware monitoring operator grafana
- Verify that the dashboard is displaying data
- Changed is deployed here (mwcollabaz-byoc) to verify visually
> Cro resources dashboard

- scripts/prepare-release.sh
1. Ensure Kustomize is not found in your $PATH
2. Run the script
```sh
SEMVER=1.3.0 OLM_TYPE=managed-api-service ./scripts/prepare-release.sh
```
3. The script runs successfully
> Automatically install Kustomize in prepare-release

- scripts/prepare-release.sh
1. Ensure Kustomize is not found in your $PATH
2. Run the script
```sh
SEMVER=1.3.0 OLM_TYPE=managed-api-service ./scripts/prepare-release.sh
```
3. The script runs successfully
> Install kustomize by downloading binary

- scripts/prepare-release.sh
Temporary fix to prepare release pipeline
> add path to kustomize

- deploy/olm-catalog/integreatly-operator
- deploy/olm-catalog/managed-api-service
Create symlink to packagemanifests folder to allow compatibility with
legacy deploy/olm-catalogs folder
> Create symlink to package manifests

- scripts/bundle-rhmi-operators.sh
Remove unnecessary line in bundle generation script.
> remove unnecessary line

- scripts/hyperfoil-request-stats.sh
Currently the hyperfoil-requests-stats.sh script uses /run/:runId/stats/total, after a controller restart the cli does not return data for runs before the restart. The endpoint /run/:runId/stats/all will persist data after controller restart.
- Clone this branch
- Deploy a cluster 
- Install hyperfoil on cluster
- Run a load test on the cluster
- Run this script pointing to the hyperfoil url 
- Verify that the output matches the script before the changes
> Refactored hyperfoil-requests-stats.sh to use /run/stats/all endpoint

- test/common/dashboards_exist.go
> Mark E03 Verify middleware dashboards exist as flaky

- test/common/shared_functions.go
- test/common/tests.go
- test/e2e/integretly_test.go
- test/functional/integreatly_test.go
- test/osde2e/managed_api_test.go
https://issues.redhat.com/browse/MGDAPI-557
* added a [function for checking whether RHMI is in `complete` stage](https://github.com/integr8ly/integreatly-operator/pull/1637/files#diff-a1556415a07423ac2a86e09105c4ba0d40c6f61c735e82ace37ebde0c280de77R362), that runs before each test
* separated [couple of tests into different categories](https://github.com/integr8ly/integreatly-operator/pull/1637/files#diff-8f8e8391123badb84e94a7a900be5015ccb9f3a10251c1447d83c07ad6c86ac2R91-R100)
> New test categories, JustBeforeEach block

- test/common/3scale_smtp.go
- test/common/alerts_mechanism.go
- test/common/sendgrid_credentials_valid.go
- test/common/tests.go
This PR adds 
- Some extra logging in areas where error where just being ignored.
- Refactor the failing state for the E03 test
- Removes the skip from A26 as this show in reporting as a failure. The test has been changed to test for any changes in the dummy creds if they are detected.
> E2e imporvements

- scripts/capture_resource_metrics.sh
- scripts/hyperfoil-all-means.sh
Adding some improvements and a new script for the perf testing work.
cc @trepel @austincunningham 
Example output of the new script:
https://gist.githubusercontent.com/matskiv/c294b37b41102bf16329c914bac1605e/raw/7127a4df520a4845c53bc1fa70cc2cb987c069b0/output.txt
> Script improvements resiliency

- scripts/hyperfoil-request-stats.sh
- change script output for easier copy and paste to spreadsheet
```bash
./hyperfoil-request-stats.sh 0004
Percentage passed = 99.9744 
Percentage failed = 0.025641
Total =  2761290
Failed =  708
One percent = 27612
post-percentile Mean = 34930687ns Max = 103284735ns
get-percentile Mean = 23049946ns Max = 30932991ns
login-percentile Mean = 115867647ns Max = 115867647ns
```
- improve failed % to handle floats 
- improve success % to handle floats
- and cleanup generated files
> change script output , improve failed % outputted to handle floats , and cleanup generated files

- README.md
Adding step to use IN_PROW for local dev steps for clusters that are smaller than the required
> add options step to use IN_PROW variable for local dev

- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
Jira:
* https://issues.redhat.com/browse/MGDAPI-1044
* Install RHOAM from master
* Manually cause system-app dc to fail
* Rollout new dc 
```
oc rollout latest dc/system-app -n redhat-rhoam-3scale
```
* Delete the rolled out `system-app-4-pre-hook` pod before it completes
```
oc delete pods system-app-4-pre-hook -n redhat-rhoam-3scale
```
* Verify `system-app-deploy` pod is an error state 
```
oc get pods system-app-4-deploy -n redhat-rhoam-3scale
```
* Verify `system-app` deployment config has a 'False' condition due to ReplicationController failed progressing
```
oc get dc system-app -n redhat-rhoam-3scale -o json | jq '.status.conditions'
```
* Checkout this branch and run operator
* Verify a new system-app deployment is rolled out due to failed condition in log
``` …
```
> MGDAPI-1044 - Rescale 3scale DC if failed

- pkg/products/rhssouser/reconciler.go
JIRA: https://issues.redhat.com/browse/MGDAPI-1385
Updating User SSO resources based on our finding from perf tests.
> MGDAPI-1385 - update user SSO resources

- README.md
- pkg/products/threescale/reconciler.go
To stop 3scale user being deleted and recreated the 3scale ID is recorded in the generated keycloakUser CR. When a 3scale updates their user name this ID is used to check if the user should be deleted or updated in the reconciler.
**JIRA** https://issues.redhat.com/browse/MGDAPI-1177
- Install rhoam from v1.3.0 branch 
- Set up the testing IDP 
- Log into 3scale using a normal test user
- Log into 3scale using the customer-admin 
- As the customer admin give more permissions to the normal user.
- Pre-check with the normal user change the user name. 
- Expected: After some time the reconciler will recreate the test user with the old user name and remove the the permissions give by the the customer admin.
- recreate the permission on the test user.
- Switch the rhoam operator to use this …
> MGDAPI-1177: 3Scale user gets deleted and recreated when they change their username via 3Scale UI

- test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
Small fixes of the test case revealed while working on https://issues.redhat.com/browse/MGDAPI-1318
**Verification Steps**
Not sure, eye review only. You can try to follow if you really want but we tried (Joan and me) during the work on that issue.
> Updated SelfManaged APIcast test case

- test-cases/tests/installation/a35-3scale-deploymentconfig-should-rescale-if-it-failed-during-i.md
- test-cases/tests/products/h26-3scale-users-permissions-do-not-change-after-changing-userna.md
Test case for https://github.com/integr8ly/integreatly-operator/pull/1652
> test: RHOAM 1.4.0 test cases

- test/common/tests.go
Details in [this comment](https://issues.redhat.com/browse/MGDAPI-557?focusedCommentId=15967679&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15967679)
> test: move B04 to the end of IDP test suite

- test-cases/tests/documentation/i08-deploying-apicast-on-osd.md
- test-cases/tests/documentation/i09-monitoring-the-service.md
- test-cases/tests/documentation/i10-network-policies.md
Added new Documentation test cases for RHOAM v1.3.0 based on https://github.com/integr8ly/integreatly-operator/pull/1619 by @joaedwar
> Added RHOAM v1.3.0 Documentation test cases

- test-cases/tests/documentation/i11-verify-modifying-custom-parameters-email.md
Adding this docs test case for 1.4 release.
> Add docs test case for 1.4 release

- test-cases/tools/cmd/jira.ts
- test-cases/tools/lib/jira.ts
https://issues.redhat.com/browse/MGDAPI-1455
Verified with both scenarios: sprint and team fields specified/not specified in JIRA epic
> fix: test-cases: add team & sprint id

- test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
- test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
- test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
- test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
- test-cases/tests/installation/a36-rhoam-operator-log-should-not-contain-errors-and-irrelevant.md
- test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
https://issues.redhat.com/browse/MGDAPI-1407
> Rhoam 1 4 0 test case updates

- pkg/resources/marketplace/manifestHelper.go
- pkg/resources/reconciler.go
- test/common/crd_exists.go
Rewire apiextensions v1beta1 imports to v1
Verify that the installation still succeeds
> Rewire apiextensions v1beta1 imports to v1

- Makefile
- test-cases/tests/alerts/c03-verify-that-alerting-mechanism-works.md
- test/common/3scale_smtp.go
- test/common/alerts_mechanism.go
- test/common/tests.go
- test/e2e/integretly_test.go
Jira https://issues.redhat.com/browse/MGDAPI-1346
Updated the alert mechanism works test to reduce the time it takes for the test to complete.
Also, updated the tests output (added some successful messages):
Verify that the e2e tests on this PR passed, or run locally
> mgdapi-1346 - update to C03 test

- test-cases/tests/installation/a34-verify-sku-values.md
- test/common/tests.go
> test: test-case for sku package

- pkg/products/grafana/reconciler.go
- pkg/products/monitoring/reconciler.go
- pkg/products/monitoringspec/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/threescale/reconciler.go
https://issues.redhat.com/browse/MGDAPI-1348
> [MGDAPI-1348] reduced severity of misleading errors

- pkg/products/cloudresources/reconciler.go
- pkg/products/cloudresources/reconciler_test.go
JIRA: https://issues.redhat.com/browse/MGDAPI-1406
Uninstallation fails in CRD is not present (not complete installation process). 
Added checks for that case and if CRD is missing, then return `PhaseCompleeted`. 
Replica of this PR https://github.com/integr8ly/integreatly-operator/pull/1669 
To verify you will need two installations: with and without CRD. If you have the `Postgres` and `PostgresSnapshots` CRSs, consider running the following command: 
```
oc delete -f manifests/integreatly-cloud-resources/0.23.0   
```
This error is hard to catch, so I suggest you modifying [this](https://github.com/integr8ly/integreatly-operator/blob/master/pkg/resources/marketplace/manager.go#L86) line to be as follows: 
```
if !(t.Namespace == "redhat-rhoam-cloud-resources-operator") {
err = …
```
> allow unistall while postgress crd in not present

- Dockerfile
- Dockerfile.functional
- Dockerfile.osde2e
- build/Dockerfile
Updating the ubi8 image to use the latest image.
Verify the container images get built.
`INSTALLATION_TYPE=managed-api ORG=<QUAY ORG> make image/build`
`INSTALLATION_TYPE=managed-api ORG=<QUAY ORG> make image/functional/build`
`INSTALLATION_TYPE=managed-api ORG=<QUAY ORG> make image/osde2e/build`
> Update ubi8 image

- controllers/rhmi/rhmi_controller.go
- pkg/resources/sku/sku.go
> make dynamic sku work rhmi safe

- test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
Update h27 test case based on https://github.com/integr8ly/integreatly-operator/pull/1690
> fix: update test case h27

- test/osde2e/managed_api_test.go
Fixes osde2e test harness being stuck before pre-tests stage
> fix osde2e image

- config/configmap/sku-config.yaml
https://issues.redhat.com/browse/MGDAPI-1390
- Compare values in the .yaml with corresponding from a ticket linked above
> updated sku-config.yaml

- test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
Test case is missing steps to scale 3scale operator down and back up
> Adds missing steps to 3scale uibbt alert test case

- test-cases/tests/installation/a38-external-installation-verify-rhoam-on-nonbyoc-cluster.md
Created a new test case based on https://issues.redhat.com/browse/MGDAPI-1571
> test: test case a38

- test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
After running the destructive test there is no check in the test case to determine if the namespaces have been recreated
Added a check for an expected outcome for namespace recreation
> Add expected outcome for namespace recreation

- test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
change the test case to use Prometheus alerts rather that openshift console
> change the test case to use Prometheus alerts rather that openshift console

- scripts/alerts-during-perf-testing.sh
- test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
https://issues.redhat.com/browse/MGDAPI-1535
Update test case P01 multiAZ to take account of the changes in the perf test suite
Add a fix for `./scripts/alerts-during-perf-testing.sh`
- change default to rhoam
- add an output for the script when alerts are firing
- run the script `./scripts/alerts-during-perf-testing.sh`
- Trigger an alert 
- go to the redhat-rhoam-middleware-monitoring-operator ns
- scale down the application-monitoring-operator deployment
- wait for about 5 min for the alert to trigger
- you should see the script output change to show the alerts
```bash
Fri 16 Apr 2021 13:56:38 IST
Only alert firing is DeadMansSwitch
Fri 16 Apr 2021 13:56:40 IST
Only alert firing is DeadMansSwitch
Fri 16 Apr 2021 13:56:41 IST
Only alert firing is DeadMansSwitch
Fri 16 Apr 2021 13:56:42 …
```
> Update test case P01 multiAZ to take account of the changes in the perf test suite

- OWNERS
Update the reviewers in OWNERS to reflect the current team
> update the reviewers in OWNERS

- go.mod
- test/common/tests.go
- test/common/validate_sso_config.go
Automating test A32 - Validate SSO config
Reopened this PR https://github.com/integr8ly/integreatly-operator/pull/1681 against a feature branch implementing extraction of values from currently active SKU. 
Verification steps remain the same: 
1. Make sure you have access to the cluster with RHOAM installed
2. log in to the cluster
3. Run command:
`INSTALLATION_TYPE=managed-api TEST=A32 make test/e2e/single`
4. Verify the test succeeds
OR
just comment with
`/test rhoam-e2e`
> A32 Automation

- test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
- test-cases/tests/authorization/b01b-verify-that-the-users-can-login-in-all-products.md
- test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
- test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
- test-cases/tests/installation/a37-rhoam-on-rosa.md
- test-cases/tests/performance/k04-run-performance-test-against-rhoam-3scale-user-sso.md
- test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
- test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
- test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n02b-upgrade-rhoam.md
Updates to the test cases based on the review of JIRA ticekts and the RHOAM v1.5.0 testing results.
> Updates to test cases based on RHOAM v1.5.0 testing

- openshift-ci/Dockerfile.tools
> Bump openshift Ci go version

- scripts/prepare-release.sh
Added a check to the prepare-release script to add the `replaces` field back into the generated CSV if it was removed. Previously, the script would remove the `replaces` field when generating a CSV from the same version (e.g. from 1.4.0-rc1 to 1.4.0-rc2)
**Related JIRA ticket:** https://issues.redhat.com/browse/MGDAPI-1456
- Modify the Kustomize path to enable the script to run locally: In scripts/prepare-release.sh, replace line 36 with: `KUSTOMIZE=$KUSTOMIZE_PATH`
- Install yq **v3** on local machine if haven't already. Required to run the script locally. [Link to install](https://mikefarah.gitbook.io/yq/v/v3.x/)
- Run the prepare-release script to generate new CSV:
`SEMVER=1.6.0-rc1 OLM_TYPE=managed-api-service make release/prepare`
- Run the prepare-release …
> change prepare-release script to add the `replaces` field to the CSV if it was removed

- pkg/addon/quota.go
> Link to JIRA: https://issues.redhat.com/browse/MGDAPI-1632
1. Install RHOAM from this PR
2. Verify that the resources match the new values:
| Resource | Replicas | Requests CPU | Requests Memory | Limits CPU | Limits Memory |
| ------------- | ----------- | -------------------- | ------------------------- | --------------- | ------------------- |
| apicasts | 2 | 0.06 vCPU | 250 MiB | 0.18 vCPU | 300 MiB |
| listeners | 2 | 0.06 vCPU | 450 MiB | 0.18 vCPU | 500 MiB |
| workers | 2 | 0.03 vCPU | 60 MiB | 0.09 vCPU | 100 MiB |
| ratelimit | 2 | 0.02 vCPU | 40 MiB | 0.06 vCPU | 80 MiB |
| User SSO | 2 | 0.75 vCPU | 1500 MiB | 1.5 vCPU | 1500 MiB |
> MGDAPI-1632: Update resources for 1M quota

- Makefile
- controllers/rhmi/rhmi_controller.go
- pkg/addon/parameters.go
Copy of https://github.com/integr8ly/integreatly-operator/pull/1748 rebased on master
> feat: Add preflight check for quota param

- scripts/prodsec-manifest-generator.sh
Fix formatting issue around script compare function.
Run 1 - 4 before fix, run 5 + after fix
> fix formating in manifest generation script

- test/functional/aws_rds_resources_exist.go
fix rds version in test. Simple change from 10.13 to 10.15 in hard coded string comparison. 
Run the automated tests
> fix rds version in test

- pkg/config/threescale.go
> update test replicas for 3scale under 1 milion quota

- pkg/addon/quota.go
Add a zero option to the quota configs configmap.
JSON validation: https://jsonformatter.org/json-parser/23933a
> add trial quota option

- go.sum
update go.sum to match cro sha
> udpate cro sum.go

- go.sum
> update CRO sha for 1.5

- pkg/products/grafana/reconciler.go
Created a black box target for grafana
1. Run reconciler from this PR
2. Ensure BlackBox CR was created by 
```
oc get blackboxtarget integreatly-grafana -n redhat-rhoam-middleware-monitoring-operator
```
4. Navigate to Prometheus (Networking -> Routes -> prometheus-route 
5. In Prometheus navigate to Status -> Targets -> blackbox and ensure that there exists one for grafana and it is in `UP` state with no errors present 
6. Navigate to the `prometheus-operator-...` pod in the namespace `redhat-rhoam-middleware-monitoring-operator` and open logs. Ensure there is no errors regarding grafana blackbox target. 
7. Drop an `lgtm` label and enjoy the day for ~3 minutes.
> added blackbox target for grafana

- test/common/3scale_crudl.go
- test/common/alerts_exist.go
See [JIRA](https://issues.redhat.com/browse/MGDAPI-1805)
Running e2e tests sufficient
> fix broken end to end tests

- controllers/subscription/subscription_controller.go
Updated install plan deletion and CSV comparison logic to prevent unwanted install plan deletions.
Closes MGDAPI-1708
1. Create bundles and images for versions 1.6.0, 1.6.1(non-service-affecting, replaces 1.6.0) and 1.7.0 (replaces 1.6.0 also)
2. Create a catalog source and install rhoam 1.6.0 from your image.
3. Point the catalog source to 1.7.0 and verify that an upgrade is pending approval in the subscription.
4. Update 1.7.0 so that it replaces v1.6.1 and verify that the install plan is deleted and the 1.6.1 upgrade takes place.
5. Verify that the installPlan for the upgrade from 1.6.1 to 1.7.0 appears in the subscription
> MGDAPI-1708 Refactor installPlan deletion logic to prevent unwanted deletions in case of patch upgrade

- Makefile
- packagemanifests/managed-api-service/1.6.1/integreatly.org_rhmiconfigs.yaml
- packagemanifests/managed-api-service/1.6.1/integreatly.org_rhmis.yaml
- packagemanifests/managed-api-service/1.6.1/managed-api-service.clusterserviceversion.yaml
- packagemanifests/managed-api-service/1.6.1/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- packagemanifests/managed-api-service/1.6.1/rhoam-operator-metrics-service_v1_service.yaml
- packagemanifests/managed-api-service/managed-api-service.package.yaml
- version/version.go
update rhoam master CSV to 1.6.1
> update version of RHOAM

- packagemanifests/managed-api-service/1.7.0/managed-api-service.clusterserviceversion.yaml
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssouser/reconciler.go
- test/common/dashboards_exist.go
- version/version.go
Remove cleanup code as it's no longer valid
> Remove keycloak dashboard removal

- pkg/products/rhsso/prometheusRules.go
- pkg/products/rhssouser/prometheusRules.go
- pkg/resources/sop_url.go
- templates/monitoring/jobs/openshift_monitoring_federation.yaml
- test/common/alerts_exist.go
This PR is a reference from https://github.com/integr8ly/integreatly-operator/pull/1730 
See approvals and review comments at https://github.com/integr8ly/integreatly-operator/pull/1730 
Update availability alert for SSO to use 5xx error rate
Jira: https://issues.redhat.com/browse/MGDAPI-1516
Below is an image for RHOAMRhssoAvailabilityXxxxErrorBudgetBurn alerts.
Similar exists for RHOAMUserSsoAvailabilityXxxxErrorBudgetBurn alerts.
RHMI - also supported
> RHOME/RHMI SSO Availability alerts for 5xx Errors - MGDAPI-1516

- test/functional/aws_rds_resources_exist.go
Fix rds version in failing test since CRO upgrade was reverted.
> Fix RDS version test

- test-cases/tests/installation/a37-rhoam-on-rosa.md
Link to ROSA pipeline doesn't resolve.
Fix the link to the ROSA pipeline in test case A37
> fix link for ROSA pipeline in test case A37

- test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
- Added some missing steps to the test case h24
> Added some missing steps to the test case h24

- test-cases/tests/installation/a17b-verify-the-go-functional-tests-were-successful.md
> MGDAPI-1831: fix the jenkins url in A17B

- pkg/resources/sop_url.go
JIRA: https://issues.redhat.com/browse/MGDAPI-1516
SSO SLO Alerts SOP files format change from md to asciidoc.
Files were renamed in integreatly-help: SloRhssoAvailabilityAlert.asciidoc, SloUserSsoAvailabilityAlert.asciidoc
> SSO SLO Alerts SOP files format change from md to asciidoc

- pkg/resources/prometheusRules.go
Closes MGDAPI-1797
There were rules to be deleted. This PR cleans up the code after rule deletion. 
- Ensure that rules deletion lines of code were removed
> remove deprecated alerts deletion

- pkg/products/threescale/reconciler.go
Adds rate limit back to the backend listener in 3scale and expose the BACKEND_PUBLIC_URL env var in system app
> Self managed apicast

- test/common/dashboards_exist.go
Follow up on [MGDAPI-1610](https://issues.redhat.com/browse/MGDAPI-1610) and #1845
Adding new dashboard to the list in E03 test case.
> Add new dashboard to tests "SLO SSO..."

- products/products.yaml
- scripts/prepare-release.sh
Revert relatedImages section in prepare/release
> revert relatedImages section

- packagemanifests/managed-api-service/1.8.0/managed-api-service.clusterserviceversion.yaml
Reverts integr8ly/integreatly-operator#1879
> Revert "release PR for version rhoam-v1.8.0-rc1"

- config/prometheus/monitor.yaml
Reverting changes to serviceMonitor
> revert update to service monitor

- test/functional/aws_rds_resources_exist.go
follow-up on https://github.com/integr8ly/cloud-resource-operator/pull/211/files
> test: update postgres version in aws rds test

- controllers/rhmi/bootstrapReconciler.go
The metrics service for rhmi-operator was changed from 2.8 to 2.9. On upgrade the old service is still kept. 
Delete rhmi-operator-metrics service in the redhat-rhmi-operator namespace
Install RHMI 2.8
Verify that rhmi-operator-metrics exists
Install rhmi from this branch
Verify that rhmi-operator-metrics is gone and replaced with rhmi-operator-metrics-service
Verify that RHMI installs ok
> remove obsolete service

- test-cases/tests/alerts/c18-validate-api-usage-alerts.md
- test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
- test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
- test-cases/tests/products/h21b-verify-all-products-using-the-workloadwebapp.md
- test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
- test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
- test-cases/tests/products/h28-validate-self-managed-apicast-rate-limiting.md
- test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n02b-upgrade-rhoam.md
- test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Small fixes to test cases. Mostly just said how to check whether workload webapp has been deployed already. Other changes are:
- fixed link to self managed apicast documentation
- how to check the health status of the cluster before installing RHOAM addon
- how to create request against 3scale and check the response (200 OK code)
- reverting changes made to RHOAM config done as part of the test case after finishing
Verification Steps
Just eye review mostly.
> Small fixes to test cases

- manifests/integreatly-3scale/0.7.0/3scale-operator.v0.7.0.clusterserviceversion.yaml
- pkg/resources/ratelimit/envoy.go
MGDAPI-2070 change images for 3scale and Envoy
Image changes
- install rhoam locally
- confirm 3scale is up and running and check the following containers to see if they have the correct images
- apicast-production-3 pod, apicast-production container has this image  registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:6ea21688678d40ec75e3a309721209eab16978e7d96941df05500e7214b5dd1d
- system-app pod, (system-master, system-provider, system-developer) containers have this image registry.redhat.io/3scale-amp2/system-rhel7@sha256:d02e84ca7835e317bbbc2a702ec84cd67cf37ea86b78485f937a1685ea3563f8
- system-memcache pod memcache container have this image registry.redhat.io/3scale-amp2/memcached-rhel7@sha256:abb74220a349f3d4b5aac8a28bd5c1ca5e1b141434c05f8b8c58a91edfdeaa …
> MGDAPI-2070: change images for 3scale and Envoy

- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/rhmi_controller.go
JIRA: https://issues.redhat.com/browse/MGDAPI-1599
Before we were processing quota in the reconciler but it has now been moved to the bootstrap reconciler.
- [Create a cluster](https://github.com/integr8ly/delorean/blob/master/docs/ocm/README.md#using-ocm-for-installation-of-rhmi-or-managed-api-service-rhoam)
- Install RHOAM based on an image with new changes (ask me for image details)
- Run make cluster/deploy with IMAGE_FORMAT set to the image details I will supply
- Run make cluster/prepare/quota to create the quota secret in the operator namespace (may already be there)
- Change the Quota configuration
- Select a value to change the sku value to. Any value that `name` is set to in the `quota-config-managed-api-service` config map in the operator namespace is a valid entry.
Run make …
> Refactor: moved initial setup of quota to bootstrap stage

- Makefile
- config/secrets/quota-trial-secret.yaml
- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/rhmi_controller.go
- pkg/addon/parameters.go
Read `trial-quota` addon paramter and use that as quota value if normal quota value is not present
Order of prefernce is as follows for quota value:
1. `addon-managed-api-service` addon param
2. `trial-quota` addon param
3. `QUOTA` environment variable
Jira:
* https://issues.redhat.com/browse/MGDAPI-2101
* Provision Cluster
*  (Optional) OSD Trial Cluster
* Checkout this branch 
* Run install using `trial-quota` addon parameter
```
oc delete secret addon-managed-api-service-parameters -n redhat-rhoam-operator
make cluster/prepare/quota/trial
make code/run
```
* Verify installation completes sucessfully and uses the `0` config
```
oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq -r '.status'
```
* Apply normal quota addon parameter to addon secret
```
oc …
```
> MGDAPI-2101 - OSD Trial Quota Support

- test/common/dashboards_exist.go
Added kc metrics dashboard as expected dashboard coming from KC 14
> add keycloak metrics dashboard to expected dashboards test case

- packagemanifests/managed-api-service/1.8.1/integreatly.org_rhmiconfigs.yaml
- packagemanifests/managed-api-service/1.8.1/integreatly.org_rhmis.yaml
- packagemanifests/managed-api-service/1.8.1/managed-api-service.clusterserviceversion.yaml
- packagemanifests/managed-api-service/1.8.1/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- packagemanifests/managed-api-service/1.8.1/rhoam-operator-metrics-service_v1_service.yaml
Add 1.8.1 bundle to master and update 1.9.0 bundle to replace 1.8.1
> add 1.8.1 bundle

- products/installation-cpaas.yaml
> Add products installation file for CPaaS

- README.md
Adding documentation for new command line variable.
> Document the PRODUCT_DECLARATION variable

- products/installation-cpaas.yaml
> Update 3scale bundle in installation-cpaas.yaml

- test-cases/tests/installation/a40-rhoam-on-osd-trial.md
Added a new test case: RHOAM installation on OSD Trial Cluster.
Eye review only.
> Added RHOAM on OSD Trial Cluster test case

- pkg/products/monitoring/prometheusRules.go
- pkg/resources/sop_url.go
Adding SOP URLs for additional alert contexts.
> Adding sop url for Test Alerts

- test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
- test-cases/tests/installation/a17b-verify-the-go-functional-tests-were-successful.md
- test-cases/tests/installation/a31-verify-installation-on-all-osd-versions.md
- test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
- test-cases/tests/products/h21b-verify-all-products-using-the-workloadwebapp.md
- test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
- test-cases/tests/upgrade/n02b-upgrade-rhoam.md
- test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Updated test cases that uses workload-web-app with a few caveats.
One or two other small fixes to test cases.
Eye review only I believe.
> Updated usage of workload-web-app in test cases

- LICENSE
> add redhat to the copyright in licence

- pkg/resources/metrics.go
- pkg/resources/sop_url.go
MGDAPI-2172 add a new alert for redis critical security updates
- deploy this branch locally using a CCS/BYOC cluster
```bash
INSTALLATION_TYPE=managed-api make cluster/prepare/local 
INSTALLATION_TYPE=managed-api USE_CLUSTER_STORAGE=false make deploy/integreatly-rhmi-cr.yml
```
- Go to the Prometheus route in the redhat-rhoam-middleware-monitoring-operator ns
- Check the alert is present
Currently deployed on `mw-collab-byoc`
> setup redis service maintenance critical security update alert

- Makefile
- test-cases/tests/installation/a34-verify-quota-values.md
Test case update caused by https://github.com/integr8ly/integreatly-operator/pull/1974
Install RHOAM using the following catalog source
```
metadata:
spec:
image: quay.io/laurafitzgerald/rhoam-index:1.10.0-install
```
Follow the test case and verify that it passes as expected.
> update for 100k quota config

- test/common/alerts_exist.go
> add alert to alerts_exists

- manifests/integreatly-monitoring/1.6.2/application-monitoring-operator.v1.6.2.clusterserviceversion.yaml
- pkg/products/monitoring/reconciler.go
> fix: Add missing changes to AMO CSV

- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- pkg/products/threescale/clients_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/products/threescale/three_scale_client.go
- pkg/products/threescale/three_scale_moq.go
- pkg/products/threescale/types.go
- pkg/resources/user/userHelper.go
This PR addresses the creation and deletion of tenants in the 3scale reconciler
https://issues.redhat.com/browse/MGDAPI-2323
> MGDAPI-2323 Adds creation of tenants in 3scale

- .github/PULL_REQUEST_TEMPLATE.md
N/A
Rough proposal for the new PR template.
This is done as a follow-up from our retrospective discussion.
N/A
> New PR template draft

- test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
Updating test case as it's expected to see small amount of downtime during the process of disabling/enabling rate limit. This sholdn't go over 5 minutes as per service definition
> update notes about validating graphs

- test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/h22-validate-that-rate-limit-service-is-working-as-expected.go
Refactor test to allow for the changes in redis keys when using
limitador
**Jira:** https://issues.redhat.com/browse/MGDAPI-2532
**Verify**
- Install rhoam 
- run [this script](https://github.com/integr8ly/integreatly-operator/blob/master/test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/test.sh)
- Expected result: script runs successfully
> MGDAPI-2532 - Updating the test case h22

- .gitignore
Remove the .run folder that can be used for store GoLand run configurations
> Update: gitignore

- test/common/grafana_routes.go
The test has failed ocassionally when retrieving the token that's created for a testing ServiceAccount. The reason of this is that the token is attempted to be retrieved immediately after the SA is created, which might result if the token not being created by the time that code is executed.
Fix by introducing polling which waits for the token secret to be set in the service account `secrets` list.
* The E05 test passes
> MGDAPI-2526: Introduce polling for SA token

- Makefile
- README.md
- make/test-containers.mk
- openshift-ci/Dockerfile.tools
- openshift-ci/README.md
- scripts/prepare-release.sh
- scripts/prodsec-manifest-generator.sh
- scripts/setup-delorean-pullsecret.sh
- test-cases/tests/installation/a34-verify-quota-values.md
- test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
[MGDAPI-1147 ](https://issues.redhat.com/browse/MGDAPI-1147l)  Using v4 of yq caused errors when running make cluster/prepare/delorean, this was due to a change of syntax between v3 and v4  of yq and required updating yq commands to comply with new syntax and format.
- Yq updated from version 3 to version 4.9.8(most recent at the time) because v3 of yq is end of life in August.
- Yq commands updated to comply with new syntax and format as v4 introduced new syntax which isn't compatible with v3.
- Yq and jq were added as prerequisites in the readme.
Run the  following make commands localy to ensure they work and match the expected results: 
- `INSTALLATION=managed-api SEMVER=1.10.1 make release/prepare`
Expected Result :`Package manifests generated successfully in …
> update of yq command to v4

- Makefile
- README.md
- make/test-containers.mk
- openshift-ci/Dockerfile.tools
- openshift-ci/README.md
- scripts/prepare-release.sh
- scripts/prodsec-manifest-generator.sh
- scripts/setup-delorean-pullsecret.sh
- test-cases/tests/installation/a34-verify-quota-values.md
- test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Updated yq to v4 to match master branch as well as delorean and ci/cd repos.
> update  yq  to v4

- scripts/prepare-release.sh
Cherry pick(with a conflict fix) of #2077
> Remove extra char in prepare-release.sh

- manifests/integreatly-rhsso/15.0.0/rhsso-operator.15.0.0.clusterserviceversion.yaml
https://issues.redhat.com/browse/MGDAPI-2555
add replaces to the csv
N/A merging to a feature branch
> add replaces to the csv

- test-cases/tests/authorization/b01b-verify-that-the-users-can-login-in-all-products.md
I had no idea where to get the link during release testing so after asking I'm updating it so someone doesn't have to ask in the future
> added instructions on where to find the Cluster SSO link

- scripts/prepare-release.sh
https://issues.redhat.com/browse/MGDAPI-2585
With the bump to `yq v4`, `null` seems to be returned when trying to get a field that does not exist in a yaml file.
This had caused the `-z ` check to always be true in  the `check_csv_replaces_field()` function, which caused the `replaces` field to be missing whenever existing CSVs need to be re-generated such as from RC releases to final releases.
To fix this:
* The above checks for null being returned instead
Additionally:
* Removed some unneeded extra whitespaces
* Generate new release
```
SEMVER=1.13.0 OLM_TYPE=managed-api-service ORG=kevfan scripts/prepare-release.sh
```
* Verify `replaces` field is **present**
* Re-generated release
```
SEMVER=1.13.0 OLM_TYPE=managed-api-service ORG=kevfan scripts/prepare-release.sh …
```
> [MGDAPI-2585] fix: replaces being removed when csv is re-generated

- test-cases/OWNERS
Small update to OWNERS file for test-cases
Eye review only!
> Update of OWNERS for test-cases

- Makefile
- config/developer-sandbox/sandbox-config-template.yml
- config/developer-sandbox/sandbox-operator-template.yml
- config/developer-sandbox/sandbox-rhoam-quickstart.yml
- controllers/rhmi/bootstrapReconciler.go
- main.go
- pkg/metrics/metrics.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/products/threescale/reconciler.go
- pkg/resources/user/userHelper.go
[MGDAPI-2648](https://issues.redhat.com/browse/MGDAPI-2648) 
[MGDAPI-2662](https://issues.redhat.com/browse/MGDAPI-2662) 
Metrics for Multi Tenancy
Scripts for Multi Tenancy
Build an image based on this branch
`ORG=<yourrepo> make image/build/push`
Install multi tenant RHOAM Operator 
`INSTALLATION_TYPE=multitenant-managed-api make install/sandboxrhoam/operator`
After the Operator Installs change the CSV to reference your new image above 
Then create config including, rhmi cr
`INSTALLATION_TYPE=multitenant-managed-api make install/sandboxrhoam/config`
After RHSSO cluster installs, install the IDP
`NUM_REGULAR_USER=10 NUM_ADMIN=5 REALM_DISPLAY_NAME="DevSandbox" REALM="devsandbox" DEDICATED_ADMIN_PASSWORD=Password1 PASSWORD=Password1 ./scripts/setup-sso-idp.sh`
Go to the terminal of the …
> Multitenant metrics

- test-cases/tests/installation/a40-rhoam-on-osd-trial.md
[MGDAPI-2336](https://issues.redhat.com/browse/MGDAPI-2336)
Updated the A40 testcase to automate the deployment of OSD Trial cluster and RHOAM install through an updated install-master pipeline
Not to be merged until [the update to master-install](https://gitlab.cee.redhat.com/integreatly-qe/ci-cd/-/merge_requests/572) pipeline is merged
N/A
> Updated the A40 test case to use a pipeline instead of a manual install

- scripts/setup-private-git-access.sh
> improve message in script

- manifests/integreatly-rhsso/image_mirror_mapping
https://issues.redhat.com/browse/MGDAPI-2555
Remove the manually generated mirror mapping file so the prow manifest check can pass
> removed the image_mirror_mapping

- make/manifest.mk
https://issues.redhat.com/browse/MGDAPI-2555
remove manifest/check/registries
> remove manifest/check/registries

- pkg/products/rhssouser/reconciler_multitenant_test.go
- pkg/products/rhssouser/reconciler_test.go
Unit test update to SSO for multitenancy
Verify code & confirm unit tests on prow check passed
> update unit test for multitenant sso

- apis/v1alpha1/rhmi_types.go
- go.mod
- go.sum
- manifests/integreatly-grafana/3.10.4/grafana-operator.v3.10.4.clusterserviceversion.yaml
- manifests/integreatly-grafana/3.10.4/grafanadashboards.integreatly.org.crd.yaml
- manifests/integreatly-grafana/3.10.4/grafanadatasources.integreatly.org.crd.yaml
- manifests/integreatly-grafana/3.10.4/grafanas.integreatly.org.crd.yaml
- manifests/integreatly-grafana/grafana.package.yaml
- pkg/products/grafana/reconciler.go
- products/products.yaml
- vendor/modules.txt
https://issues.redhat.com/browse/MGDAPI-2671
Bump grafana version to 3.10.4 
Install RHOAM from master
Then run this branch to simulate an upgrade
Verify that Grafana upgrades to 3.10.4
Verify that dashboards still exist and look correct
Automated tests will cover the install scenario
> bump grafana version

- scripts/prepare-release.sh
$ subject
Run `SEMVER=1.13.0 OLM_TYPE=managed-api-service ./scripts/prepare-release.sh`
The script shouldn't face errors on imageScans.
> disable image scan temporarily

- scripts/prepare-release.sh
> fix 3scale and rhsso container images generation

- config/scorecard/bases/config.yaml
- config/scorecard/kustomization.yaml
- config/scorecard/kuttl/kuttl-test.yaml
- config/scorecard/kuttl/rhoam-install/00-assert.yaml
- config/scorecard/kuttl/rhoam-install/01-assert.yaml
- config/scorecard/kuttl/rhoam-install/01-create-secrets.yaml
- config/scorecard/kuttl/rhoam-install/02-assert.yaml
- config/scorecard/kuttl/rhoam-install/02-cluster-storage.yaml
- config/scorecard/kuttl/rhoam-install/03-assert.yaml
- config/scorecard/kuttl/rhoam-install/04-assert.yaml
- config/scorecard/kuttl/rhoam-install/05-assert.yaml
- config/scorecard/kuttl/rhoam-install/06-assert.yaml
- config/scorecard/kuttl/rhoam-install/07-assert.yaml
- config/scorecard/kuttl/rhoam-install/08-assert.yaml
- config/scorecard/kuttl/rhoam-install/resources/secret-dms.yaml
- config/scorecard/kuttl/rhoam-install/resources/secret-pagerduty.yaml
- config/scorecard/kuttl/rhoam-install/resources/secret-smtp.yaml
- config/scorecard/patches/kuttl.config.yaml
Basic test for verifying that product can be installed successfully.
> patch config with kuttl configuration

- test-cases/tests/products/h28-validate-self-managed-apicast-rate-limiting.md
N/A
Small update to H28 test case.
Eye review only
> Small updates of H28 test case

- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
update category annotation to something required by CVP linting job
Verify through the CPaaS process
> update category annotation to something required by CVP linting job

- pkg/products/apicurito/reconciler.go
- pkg/products/fuse/reconciler.go
- pkg/products/grafana/reconciler.go
- pkg/products/marin3r/reconciler.go
- pkg/products/monitoringspec/reconciler.go
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/solutionexplorer/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/products/ups/reconciler.go
- pkg/products/ups/reconciler_test.go
https://issues.redhat.com/browse/MGDAPI-2905
Tidy up code with no error handling on WriteConfig() calls.
Scan the code for any issues
e2e tests passing are sufficient for verification
> error handling on WriteConfig()

- test-cases/tests/documentation/i12-modifying-dynamic-quota.md
- test-cases/tests/documentation/i13- install-rhoam-ocm.md
Docs test cases for 1.6 release.
> Docs Test cases for 1.6 release

- pkg/addon/operator_run.go
- pkg/addon/operator_run_test.go
[JIRA](https://issues.redhat.com/browse/MGDAPI-3089)
Validating the RHOAM install failed because the subscription name generated by CPaaS is random. 
Unit tests sufficient.
Will be validated through CPaaS
> Add exception for CPaaS subscription name

- test/common/quota.go
https://issues.redhat.com/browse/MGDAPI-2896
* rate limit prometheus rule names and namespace
* change the quota to initial value at the end of the test or if the test fails
```
go clean -testcache && BYPASS_STORAGE_TYPE_CHECK=true WATCH_NAMESPACE=redhat-rhoam-operator go test -v ./test/functional -timeout=80m -ginkgo.focus="A34" -ginkgo.v -ginkgo.progress -ginkgo.trace
```
> test: fix automated test a34

- README.md
> test polling

- .gitignore
Testing demo for CPROD-11
dummy change for demo
N/A
> Update for demo for CPROD-11

- .gitignore
Reverts integr8ly/integreatly-operator#2311
> Revert "Update for demo for CPROD-11"

- test/functional/aws_rds_resources_exist.go
https://issues.redhat.com/browse/MGDAPI-3175
Fix to the test F01
> MGDAPI-3175 fix F01 test case

- packagemanifests/managed-api-service/1.15.0/managed-api-service.clusterserviceversion.yaml
Reverts integr8ly/integreatly-operator#2315
> Revert "release PR for version rhoam-v1.15.0-rc3"

- RELEASE.md
> update for CPROD-11

- README.md
> Scoheb patch 2

- README.md
Reverts integr8ly/integreatly-operator#2326
> Revert "Scoheb patch 2"

- README.md
> prepare CPROD-11 demo

- README.md
> demo for CPROD-11

- pkg/config/cloudresources.go
- pkg/products/cloudresources/reconciler.go
Reverts integr8ly/integreatly-operator#2329
> MGDAPI-3208 Revert "MGDAPI-3192"

- controllers/subscription/subscription_controller.go
https://issues.redhat.com/browse/MGDAPI-2580
When version n is installed, and service affecting version n+1 is made available, olm will create an install plan for upgrade to version n+1. Now if version n+2 is made available and the install plan for n+1 is approved, there is a cyclical loop in this scenario preventing n+1 upgrade from completing successfully.
What happens is that when service affecting version n+2 if available, the `toVersion` in RHMI CR is reset by the subscription controller and this causes the CR to be stale when the installation controller updates the RHMI CR status.
* Configure cluster for OLM install for RHOAM 1.14.0
```
oc process -p …
```
> [MGDAPI-2580] fix: upgrade not completing for n+1 when n+2 version available

- test-cases/README.md
- test-cases/tools/cmd/jira.ts
- test-cases/tools/cmd/polarion.ts
- test-cases/tools/lib/jira.ts
https://issues.redhat.com/browse/MGDAPI-3275
See jira description
```bash
export JIRA_TOKEN=<your-personal-jira-token>
./tools.sh jira --epic MGDAPI-2990 --product rhoam --environment osd-fresh-install --dry-run
./tools.sh polarion testrun --epic MGDAPI-3063 --product rhoam --template v1_14_0_rc2 --dump-only true
```
> MGDAPI-3275 update jira auth in test-case tooling

- pkg/addon/uninstall.go
[MGDAPI-3099](https://issues.redhat.com/browse/MGDAPI-3099)
In the light of incoming changes to the reconciliation time of operators from the hive, we might bump into a problem when we delete the subscription during the uninstallation but it gets recreated immediately. To prevent this we want to delegate deletion of the subscription from the rhoam. 
This change makes sure that the subscription stays in place while allowing manual deletion in case of the dev work (in that case the subscription isn't managed by hive hence will never be deleted) by extending `make cluster/cleanup/olm`. 
(if for some weird reason you trust me or want to reuse [bundles](https://quay.io/mvavilov/rhoam-bundle:1.15.0) and [index](https://quay.io/repository/mvavilov/rhoam-index:1.15.0) I've generated you now have …
> MGDAPI-3099 don't delete subscription on uninstall

- Makefile
- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- packagemanifests/managed-api-service/1.15.1/integreatly.org_rhmiconfigs.yaml
- packagemanifests/managed-api-service/1.15.1/integreatly.org_rhmis.yaml
- packagemanifests/managed-api-service/1.15.1/managed-api-service.clusterserviceversion.yaml
- packagemanifests/managed-api-service/1.15.1/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- packagemanifests/managed-api-service/1.15.1/rhoam-operator-metrics-service_v1_service.yaml
- packagemanifests/managed-api-service/1.15.2/integreatly.org_rhmiconfigs.yaml
- packagemanifests/managed-api-service/1.15.2/integreatly.org_rhmis.yaml
- packagemanifests/managed-api-service/1.15.2/managed-api-service.clusterserviceversion.yaml
- packagemanifests/managed-api-service/1.15.2/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- packagemanifests/managed-api-service/1.15.2/rhoam-operator-metrics-service_v1_service.yaml
- packagemanifests/managed-api-service/managed-api-service.package.yaml
- pkg/products/rhsso/reconciler.go
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssocommon/reconciler_test.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- products/installation-cpaas.yaml
- version/version.go
Cherry pick the commits from 1.15.1 and 1.15.2 release
> MGDAPI-3281 1.15 cherrypick

- Makefile
- main.go
- test/common/alerts_exist.go
- test/common/alerts_firing.go
- test/common/alerts_mechanism.go
- test/common/cro_cr_success.go
- test/common/dashboards_data.go
- test/common/deployment_types.go
- test/common/integreatly_stages.go
- test/common/monitoringspec.go
- test/common/namespace_created.go
- test/common/namespace_restoration.go
- test/common/operand_versions.go
- test/common/operator_versions.go
- test/common/pdbs_exist.go
- test/common/priority_validate.go
- test/common/routes_exist.go
- test/common/subscription_install_plan.go
- test/common/tests.go
- test/common/user_dedicated_admin_permissions.go
- test/common/verify_metrics_scrapped.go
- test/e2e/suite_test.go
- test/functional/aws_shared_functions.go
[MGDAPI-3184](https://issues.redhat.com/browse/MGDAPI-3184)
Remove the namespace controller for dev sandbox installs
Running e2e tests sufficient
> Mgdapi 3184

- controllers/rhmi/rhmi_controller.go
https://issues.redhat.com/browse/MGDAPI-3311
Block install if addon flow + missing envar
Review code and confirm e2e passed
> MGDAPI-3311 add addon flow install check

- controllers/rhmi/rhmi_controller.go
- pkg/addon/operator_run.go
- pkg/addon/operator_run_test.go
> add hive managed check

- controllers/subscription/csvlocator/csvlocator.go
- controllers/subscription/csvlocator/csvlocator_test.go
[MGDAPI-3084](https://issues.redhat.com/browse/MGDAPI-3084)
On the 4.9+ cluster, CSV stored in config map under the `openshift-marketplace` namespace resides within `binaryData` field instead of `data`. With the old code it meant that we could find CSV and was defaulting to the default (is service affecting). With this change, we would be able to fetch binary data to make the logic about auto-approval of non-service affecting upgrades work. 
To verify this you would need to simulate an upgrade. I will provide you with indexes for installations. They all are using the same RHOAM image that was built from this PR with addition of the `managed-api-service` subscription [here](https://github.com/integr8ly/integreatly-operator/blob/master/controllers/subscription/subscription_controller.go#L41- …
> MGDAPI-3084 ensure binaryData from CM in openshif-marketplace treated well

- test/common/integreatly_stages.go
https://issues.redhat.com/browse/MGDAPI-3332
Confirm rhoam e2e test pass.
> MGDAPI-3332 Update A01

- config/scorecard/kuttl/02-scalability/00-test-pod-template.yaml
- config/scorecard/kuttl/02-scalability/01-assert.yaml
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>
https://issues.redhat.com/browse/MGDAPI-2370
For demo purposes we add one failing test
> MGDAPI-2370 increase timeout for scalbility tests + add failing test

- test/common/multitenancy.go
https://issues.redhat.com/browse/MGDAPI-3323
Follows up on : https://issues.redhat.com/browse/MGDAPI-3202
fix the multitenant-rhoam-e2e test for Multi Tenant RHOAM.
1 test not passed.
Error: `User login to 3scale failed: User test-user01 login and creation of tenant failed`
It was found that missing Route for testing user. It seems happened after adding `Multitenant on Demand` solution, where 3scale is taking users by tenant annotation.
To have annotation on testing user, and have route to be created in 3scale ns - need create CR with name = name of user. Please see more about solution in MGDAPI-3202
RhoamTenant CR creation for test users` was added to  M01 - TestMultitenancy test
Run multitenant-rhoam-e2e tests and check that All tests passed
> MGDAPI-3323 - fix the e2e test for Multi Tenant RHOAM

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
Bump SSO versions to latest available.
I'm preparing clusters to do an install/upgrade, will make those available when they are ready
@psturc is there any additional tests that should be run here? I'll trigger e2e tests on the pr.
> bump to newer version

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
https://issues.redhat.com/browse/MGDAPI-3416
> MGDAPI-3416 update to registry images

- Makefile
- bundles/managed-api-service/1.18.0/bundle.Dockerfile
- bundles/managed-api-service/1.18.0/manifests/integreatly.org_rhmiconfigs.yaml
- bundles/managed-api-service/1.18.0/manifests/integreatly.org_rhmis.yaml
- bundles/managed-api-service/1.18.0/manifests/managed-api-service.clusterserviceversion.yaml
- bundles/managed-api-service/1.18.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- bundles/managed-api-service/1.18.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
- bundles/managed-api-service/1.18.0/metadata/annotations.yaml
- bundles/managed-api-service/1.18.0/tests/scorecard/config.yaml
- bundles/managed-api-service/managed-api-service.package.yaml
- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
- version/version.go
https://issues.redhat.com/browse/MGDAPI-3209
Manually create next release once previous release is done, so that CPaaS is primed for next release.
Image will be pointed at master for now until the release pipeline is run during release
* Check generated files are as expected
> MGDAPI-3209 - Prepare for next release - 1.18.0

- test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
- test-cases/tests/upgrade/n03-verify-that-the-minimal-cidr-block-is-configured-correctly.md
https://issues.redhat.com/browse/MGDAPI-3436
> MGDAPI-3452 small updates to test cases

- controllers/rhmi/rhmi_controller.go
- pkg/products/rhssocommon/reconciler.go
Jira: [MGDAPI-3457](https://issues.redhat.com/browse/MGDAPI-3457)
One of the nightly pipelines outlined an issue where the uninstall process could move onto later stages without removing all products from current stage. This was due to `pendingUninstalls` being overwritten on each iteration - if the last product in the products list returns true then we move onto the next stage, even if every other product is still pending uninstall.
- Added `productPending` boolean and only update `pendingUninstalls` to true if it hasn't already been set
- Whilst not directly related to this ticket, also spotted controller-runtime was imported twice so removed the extra reference
- In rhssocommon there is the possibility that the CR has been updated by delete before we set the finalizers and so refresh …
> MGDAPI-3457 - uninstall stages performed in order

- README.md
https://issues.redhat.com/browse/MGDAPI-3019
Addition a new piece of documentation explaining different ways of uninstalling RHOAM.
- Make sure it follows the same convention as the rest of the documentation and makes sense when reading.
- Optional can verify that all the different uninstallation methods work.
> MGDAPI-3019 Update Readme with rhoam uninstall documentation

- test-cases/tests/authorization/b09-verify-dedicated-admin-users-are-synced-with-user-sso.md
- test/common/tests.go
- test/common/types.go
- test/common/user_dedicated_admin_synced_sso.go
https://issues.redhat.com/browse/MGDAPI-3454
https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/authorization/b09-verify-dedicated-admin-users-are-synced-with-user-sso.md
```INSTALLATION_TYPE=managed-api TEST=B09 BYPASS_STORAGE_TYPE_CHECK=true make test/e2e/single```
> [MGDAPI-3454] B09 verify dedicated admin users are synced with User SSO

- test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
https://issues.redhat.com/browse/MGDAPI-3408
Updates to A30 test case to point to a newly created LDAP instance.
Eye review only sufficient.
Alternatively you can try the commands around the LDAP instance whether they indeed works. You would need to start that LDAP instance first.
> A30 LDAP test case updates

- test-cases/tests/alerts/c18-validate-api-usage-alerts.md
- test-cases/tests/installation/a17a-verify-the-go-functional-tests-were-successful.md
- test-cases/tests/installation/a17b-verify-the-go-functional-tests-were-successful.md
- test-cases/tests/installation/a31-verify-installation-on-all-osd-versions.md
- test-cases/tests/installation/a37-rhoam-on-rosa.md
- test-cases/tests/installation/a38-installation-verify-rhoam-on-nonbyoc-cluster.md
- test-cases/tests/installation/a39-installation-verify-rhoam-on-private-cluster.md
- test-cases/tests/installation/a40-rhoam-on-osd-trial.md
- test-cases/tests/installation/a42-rhoam-on-byovpc-cluster.md
- test-cases/tests/performance/k01-run-performance-test-against-amq-online.md
- test-cases/tests/upgrade/n02b-upgrade-rhoam.md
https://issues.redhat.com/browse/MGDAPI-3484
updated jenkins URLs
> MGDAPI-3484 update TCs due to jenkins migration

- test-cases/tests/alerts/c10b-verify-additional-blackboxtargets.md
- test/common/tests.go
- test/common/verify_prometheus_metrics.go
https://issues.redhat.com/browse/MGDAPI-3460
https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/alerts/c10b-verify-additional-blackboxtargets.md
`INSTALLATION_TYPE=managed-api TEST=C10B BYPASS_STORAGE_TYPE_CHECK=true make test/e2e/single`
> [MGDAPI-3460] C10B verify prometheus blackbox targets

- bundles/managed-api-service/1.18.0/manifests/managed-api-service.clusterserviceversion.yaml
- bundles/managed-api-service/1.18.2/manifests/managed-api-service.clusterserviceversion.yaml
- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
> support 4.10

- README.md
> MGDAPI-3209 force merge for cpaas

- test-cases/tests/installation/a42-rhoam-on-byovpc-cluster.md
https://issues.redhat.com/browse/MGDAPI-3412
a42 test case was marked as automated
> MGDAPI-3412 a42 test case update

- test/functional/aws_rds_resources_exist.go
https://issues.redhat.com/browse/MGDAPI-3552
Bump version of RDS in e2e test.
> MGDAPI-3552: e2e fix

- controllers/tenant/apimanagementtenant_controller.go
- main.go
- pkg/products/threescale/reconciler.go
- test/common/multitenancy.go
Multiple updates for multi tenant RHOAM 
e2e tests for both single and multi tenant rhoam
> Multitenant rhoam updates

- main.go
https://issues.redhat.com/browse/MGDAPI-3691
> MGDAPI-3691 add v1.DeploymentConfigs to scheme

- products/installation-cpaas.yaml
> MGDAPI-3412 fix cpaas oo issue

- products/installation-cpaas.yaml
> MGDAPI-3412 rollback 3scale to 0.8.0 for cpaas

- products/installation-cpaas.yaml
> MGDAPI-3412 rollback 3scale to 0.8.1

- README.md
update docs - usage of scorecard tests
> MGDAPI-3595 update readme - scorecard

- products/installation-cpaas.yaml
> MGDAPI-3412 sync 3scale back to 0.8.3 for cpaas

- products/installation-cpaas.yaml
> MGDAPI-3412 rollback again to 0.8.2

- products/installation-cpaas.yaml
> MGDAPI-3412 bump back to 0.8.3

- .codecov.yml
[MGDAPI-3745](https://issues.redhat.com/browse/MGDAPI-3745)
> MGDAPI-3745 / Added threshold and ignore to codecov

- OWNERS
- openshift-ci/OWNERS
- scripts/ci/OWNERS
- test-cases/OWNERS
- test/OWNERS
> updating various OWNERS files

- test/common/dashboards_exist.go
https://issues.redhat.com/browse/MGDAPI-1367
The workload app can be deployed with a dashboard added to grafana.
This extra dashboard causes the test E03 to be skipped due to extra dashboards found.
1. Deploy the RHOAM addon
2. Configure the testing IDP
3. Deploy the [workload app](https://github.com/integr8ly/workload-web-app), Ensure the `GRAFANA_DASHBOARD=true` is set.
4. Once deployed check the workload app dashboard is present in the OO grafana.
5. Run the single e2e test. `ACK_GINKGO_DEPRECATIONS=1.16.4 TEST=E03 make test/e2e/single`
Expected result: E2E test passes
> MGDAPI-1367 Allow for workload App

- products/installation-cpaas.yaml
> MGDAPI-3412 move 3scale CPaaS back to 0.8.0

- pkg/products/threescale/reconciler.go
> MGDAPI-3830 update smtp from logic

- pkg/products/marin3r/reconciler.go
> MGDAPI-3422 update to use namespace prefix

- pkg/products/marin3r/reconciler.go
- pkg/products/marin3r/reconciler_test.go
> MGDAPI-3889 fix envoyconfigRevision removal

- pkg/products/marin3r/reconciler.go
> MGDAPI-3892 filter out no matches for kind error

- bundles/managed-api-service/1.21.0/manifests/managed-api-service.clusterserviceversion.yaml
> MGDAPI-3209 fix CSV image containterimage

- pkg/products/threescale/reconciler.go
[MGDAPI-3875](https://issues.redhat.com/browse/MGDAPI-3875)
Added cpu + memory usage limits + requests to threescale reconciler.
1. Install rhoam off this branch.
2. In DeploymentConfigs (apicast-production, apicast-staging, backend-listener) make sure the correct annotations are set.
3. In those 3 DeplymentConfigs make sure the envoy-sidecar container contains the resource limits and requests.
> MGDAPI-3875 / Added resource limits + requests

- pkg/resources/ratelimit/envoy.go
[mgdapi-3875](https://issues.redhat.com/browse/MGDAPI-3875)
> Mgdapi 3875 4

- manifests/integreatly-3scale/0.9.0/3scale-operator.v0.9.0.clusterserviceversion.yaml
- test/common/3scale_tenant_via_CR.go
- test/common/shared_functions.go
- test/common/tests.go
- test/e2e/integretly_test.go
- test/functional/integreatly_test.go
[MGDAPI-3476](https://issues.redhat.com/browse/MGDAPI-3476)
> MGDAPI-3476 / Uncommented test cases + Removed redundant code

- Makefile
- bundles/managed-api-service/1.22.0/bundle.Dockerfile
- bundles/managed-api-service/1.22.0/manifests/integreatly.org_rhmiconfigs.yaml
- bundles/managed-api-service/1.22.0/manifests/integreatly.org_rhmis.yaml
- bundles/managed-api-service/1.22.0/manifests/managed-api-service.clusterserviceversion.yaml
- bundles/managed-api-service/1.22.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- bundles/managed-api-service/1.22.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
- bundles/managed-api-service/1.22.0/metadata/annotations.yaml
- bundles/managed-api-service/1.22.0/tests/scorecard/config.yaml
- bundles/managed-api-service/managed-api-service.package.yaml
- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
- version/version.go
> MGDAPI-3209 - bump manifests to v1.22.0

- pkg/products/marin3r/rateLimitService.go
- products/additional-images.yaml
bump limitador image
- install rhoam
- verify rate limiting works as expected
> MGDAPI-4034 bump limitador image

- products/additional-images.yaml
> MGDAPI-4087 bump grafana init image to correct one

- manifests/integreatly-3scale/0.8.3-0.1649688682/3scale-operator.clusterserviceversion.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/apps.3scale.net_apimanagerbackups.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/apps.3scale.net_apimanagerrestores.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/apps.3scale.net_apimanagers.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_activedocs.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_backends.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_custompolicydefinitions.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_developeraccounts.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_developerusers.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_openapis.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_products.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_tenants.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- manifests/integreatly-3scale/0.8.3-0.1649688682/threescale-operator-controller-manager-metrics-service_v1_service.yaml
- manifests/integreatly-3scale/3scale.package.yaml
[MGDAPI-3979](https://issues.redhat.com/browse/MGDAPI-3979)
Add 3scale manifests to be used to generate related images.
> MGDAPI-3979 - add 3scale manifests to generate related images

- Makefile
- bundles/managed-api-service/1.23.0/bundle.Dockerfile
- bundles/managed-api-service/1.23.0/manifests/integreatly.org_rhmiconfigs.yaml
- bundles/managed-api-service/1.23.0/manifests/integreatly.org_rhmis.yaml
- bundles/managed-api-service/1.23.0/manifests/managed-api-service.clusterserviceversion.yaml
- bundles/managed-api-service/1.23.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- bundles/managed-api-service/1.23.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
- bundles/managed-api-service/1.23.0/metadata/annotations.yaml
- bundles/managed-api-service/1.23.0/tests/scorecard/config.yaml
- bundles/managed-api-service/managed-api-service.package.yaml
- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
- version/version.go
https://issues.redhat.com/browse/MGDAPI-3209
Prime for next 1.23.0 release 
* Passing prow checks should be sufficient
> MGDAPI-3209 - bundles: prime for 1.23.0

- go.mod
- go.sum
- test/common/multitenancy.go
- vendor/github.com/3scale/3scale-porta-go-client/client/accounts.go
- vendor/github.com/3scale/3scale-porta-go-client/client/activedocs.go
- vendor/github.com/3scale/3scale-porta-go-client/client/client.go
- vendor/github.com/3scale/3scale-porta-go-client/client/developer_accounts.go
- vendor/github.com/3scale/3scale-porta-go-client/client/developer_users.go
- vendor/github.com/3scale/3scale-porta-go-client/client/mapping.go
- vendor/github.com/3scale/3scale-porta-go-client/client/oidc.go
- vendor/github.com/3scale/3scale-porta-go-client/client/policies.go
- vendor/github.com/3scale/3scale-porta-go-client/client/policy-registry.go
- vendor/github.com/3scale/3scale-porta-go-client/client/product.go
- vendor/github.com/3scale/3scale-porta-go-client/client/proxy.go
- vendor/github.com/3scale/3scale-porta-go-client/client/types.go
- vendor/github.com/3scale/3scale-porta-go-client/client/user.go
- vendor/modules.txt
JIRA: https://issues.redhat.com/browse/MGDAPI-3636
This PR extends the e2e/multitenant-rhoam test to automate the RHOAM DeveloperSandbox [QuickStart guide](https://github.com/briangallagher/sandbox-sre/blob/master/resources/rhoam-ds-prod.xe9u.p1.openshiftapps.com/configure/member/consolequickstart/rhoam-devsandbox-managed-api-quickstart.yaml).
Passing the PROW tests should be sufficient for verification. However, the test can also be run manually:
1. Provision a cluster
2. Checkout this PR and install RHOAM onto the cluster (either using OLM or locally, it doesn't matter)
3. Once the installation is complete, run the test with `TENANTS_NUMBER=2`:
`TENANTS_NUMBER=2 INSTALLATION_TYPE=multitenant-managed-api BYPASS_STORAGE_TYPE_CHECK=true TEST="M01" make test/e2e/single`
4. Confirm that the …
> MGDAPI-3636 Extended multitenant e2e test to automate RHOAM DevSandbox QuickStart

- test/common/3scale_backend_via_CR.go
- test/common/3scale_product_via_CR.go
- test/common/3scale_tenant_via_CR.go
[MGDAPI-4114](https://issues.redhat.com/browse/MGDAPI-4114)
Changed 3 test namespaces to be different to avoid flakiness of tests.
Make sure Prow rhoam e2e has passed
> Mgdapi 4114

- test-cases/tests/products/h32-verify-that-3scale-invitation-mail-is-set-correctly.md
> MGDAPI-4098 Update h32 test case

- test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
- test/scripts/backup-restore/j05-verify-3scale-postgres-backup-and-restore.sh
Added prerequisite and changed default value to use rhoam as we no longer support rhmi
> MGDAPI-4095 small update to J05

- Makefile
- bundles/managed-api-service/1.24.0/bundle.Dockerfile
- bundles/managed-api-service/1.24.0/manifests/integreatly.org_rhmiconfigs.yaml
- bundles/managed-api-service/1.24.0/manifests/integreatly.org_rhmis.yaml
- bundles/managed-api-service/1.24.0/manifests/managed-api-service.clusterserviceversion.yaml
- bundles/managed-api-service/1.24.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- bundles/managed-api-service/1.24.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
- bundles/managed-api-service/1.24.0/metadata/annotations.yaml
- bundles/managed-api-service/1.24.0/tests/scorecard/config.yaml
- bundles/managed-api-service/managed-api-service.package.yaml
- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
- version/version.go
> MGDAPI-3209 prepare rhoam for 1.24

- pkg/products/marin3r/rateLimitService.go
- pkg/products/marin3r/rateLimitService_test.go
[MGDAPI-4044](https://issues.redhat.com/browse/MGDAPI-4044)
- Change limitador image to one that doesn't exist.
- Install rhoam and check correct error message shows up.
> MGDAPI-4044 / Added check for unsuccessful pod start

- test/common/tests.go
- test/common/verify_alert_links_to_SOPs.go
[https://issues.redhat.com/browse/MGDAPI-3452](url)
https://github.com/integr8ly/integreatly-operator/blob/master/test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
`INSTALLATION_TYPE=managed-api TEST=C08B BYPASS_STORAGE_TYPE_CHECK=true make test/e2e/single`
Test implemented and passing when ran locally and in nightly pipelines
> MGDAPI-3452-C08B-automated-test

- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
> MGDAPI-3290 bump maxOpenshift version

- OWNERS
> MGDAPI-4437 update the owners file

- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- test/common/3Scale_user_promotion.go
- test/common/3scale_crudl.go
- test/common/3scale_smtp.go
- test/common/alerts_invalid_username.go
- test/common/product_login.go
https://issues.redhat.com/browse/MGDAPI-4374
update retrieval of URL from RHMI CR in Test for SSR 
- Install RHOAM Locally
```bash
INSTALLATION_TYPE=managed-api USE_CLUSTER_STORAGE=true make deploy/integreatly-rhmi-cr.yml
INSTALLATION_TYPE=managed-api make code/run 
```
- When RHOAM has finished installing install the testing idp
```bash
export PASSWORD=Password1
export DEDICATED_ADMIN_PASSWORD=Password1
./scripts/setup-sso-idp.sh
```
- confirm the follow test pass
```bash
INSTALLATION_TYPE=managed-api TEST=B01B make test/e2e/single
INSTALLATION_TYPE=managed-api TEST=C19 make test/e2e/single
INSTALLATION_TYPE=managed-api TEST=H07 make test/e2e/single
```
- confirm prow/rhoam-e2e pass as well
> MGDAPI-4374 update retrieval of URL from RHMI CR in Test for SSR

- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/bootstrapReconciler_test.go
https://issues.redhat.com/browse/MGDAPI-4458
> [MGDAPI-4458] skip routing subdomain modification after it's been set

- OWNERS
add kevin and austin as owners
> add kevin and austin as owners

- Makefile
- controllers/rhmi/rhmi_controller.go
- controllers/tenant/apimanagementtenant_controller.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/rhssocommon/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/resources/ratelimit/envoyconfig.go
- pkg/resources/user/userHelper.go
- test/common/grafana_routes.go
- test/common/multitenancy.go
- test/common/namespace_restoration.go
- test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go
https://issues.redhat.com/browse/MGDAPI-3805
Address gosec G601 - https://stackoverflow.com/questions/62446118/implicit-memory-aliasing-in-for-loop
* Passing gosec prow check 
* Passing e2e should be sufficient
> MGDAPI-3805 - gosec: address G601

- test/common/3scale_smtp.go
- test/common/quota.go
- test/common/selfmanaged_apicast.go
- test/common/tests.go
[MGDAPI-4262](https://issues.redhat.com/browse/MGDAPI-4262)
The following tests failed on the MT upgrade pipeline. 
A26 - couldn't reproduce
C04 - couldn't reproduce
M01 - couldn't reproduce
A16 - excluded from MT suite
H03 - excluded from MT suite
H11 - excluded from MT suite
B04 - excluded from MT suite
B09 - excluded from MT suite
B03 - excluded from MT suite
H07 - excluded from MT suite
H24 - fixed 
A34 - fixed 
1. Install MT RHOAM 
2. Run fixed e2e tests from this PR (they are not included in the prow suite):
```
INSTALLATION_TYPE=managed-api TEST=A34 BYPASS_STORAGE_TYPE_CHECK=true make test/e2e/single
INSTALLATION_TYPE=managed-api TEST=H24 BYPASS_STORAGE_TYPE_CHECK=true make test/e2e/single
```
3. Ensure tests are passing
> MGDAPI-4262 fie E2E tests for MT RHOAM

- scripts/create-3scale-index.sh
[MGDAPI-4483](https://issues.redhat.com/browse/MGDAPI-4483)
Search all bundles for the version, not just the last entry
Eye review should be sufficient
> MGDAPI-4483 - search all bundles

- test-cases/tests/products/h33-verify-that-3scale-invitation-mail-works-as-expected.md
MGDAPI-4348 
MGDAPI-4348 update H33 step 3 for correct navigation to ACCOUNTS
> MGDAPI-4348 update H33 step 3 for correct navigation to ACCOUNTS

- test-cases/tests/alerts/c18-validate-api-usage-alerts.md
MGDAPI-4429 
Update the test case with the findings of this comment https://issues.redhat.com/browse/MGDAPI-4429?focusedCommentId=20758467&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20758467
> MGDAPI-4429 update testcase c18

- test/common/3Scale_user_promotion.go
- test/common/product_login.go
[MGDAPI-3768](https://issues.redhat.com/browse/MGDAPI-3768)
[Main Gitlab PR](https://gitlab.cee.redhat.com/integreatly-qe/ci-cd/-/merge_requests/743)
> MGDAPI-3768 - modfiy B01B and H07 test cases to work with multiple users in one run.

- pkg/products/observability/prometheusRules.go
[MGDAPI-4272](https://issues.redhat.com/browse/MGDAPI-4272)
Removed redundant code
Make sure prow checks pass
> MGDAPI-4272 / Removed code

- products/additional-images.yaml
- scripts/prepare-release.sh
[MGDAPI-4449](https://issues.redhat.com/browse/MGDAPI-4449)
Add several missing images that are deployed with RHOAM.
> MGDAPI-4449 - add new images to related images

- pkg/products/threescale/reconciler.go
> MGDAPI-4644 move to next account for any error

- Makefile
- apis/v1alpha1/addtoscheme_integreatly_v1alpha1.go
- bundles/managed-api-service/1.27.0/manifests/integreatly.org_rhmiconfigs.yaml
- bundles/managed-api-service/1.27.0/manifests/integreatly.org_rhmis.yaml
- bundles/managed-api-service/1.27.0/manifests/managed-api-service.clusterserviceversion.yaml
- config/rbac/role.yaml
- config/secrets/addon-params-secret.yaml
- controllers/rhmi/rhmi_controller.go
- controllers/rhmi/rhmi_controller_test.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/cloudresources/reconciler_test.go
- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
- pkg/resources/sts/sts.go
- pkg/resources/sts/sts_test.go
- test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
- test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
- test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
- test/functional/aws_elasticache_resources_exist.go
- test/functional/aws_rds_resources_exist.go
- test/functional/aws_s3_resources_exist.go
- test/functional/aws_shared_functions.go
- test/functional/aws_standalone_vpc.go
- test/functional/aws_strategy_override.go
- test/scripts/backup-restore/j05-verify-3scale-postgres-backup-and-restore.sh
- test/scripts/backup-restore/j07-verify-rhsso-backup-and-restore.sh
- test/scripts/backup-restore/j08-verify-user-sso-backup-and-restore.sh
https://issues.redhat.com/browse/MGDAPI-4638
- Create or borrow an OSD cluster by using the scripts in delorean
```
make -f make/ocm.mk ocm/cluster.json OCM_CLUSTER_REGION=us-west-2 OCM_CLUSTER_NAME=mgdapi-4638
make -f make/ocm.mk ocm/cluster/create
```
- Prepare the cluster and install RHOAM from index image `quay.io/tdimov0/managed-api-service-index:1.26.0`:
```
git checkout tags/rhoam-v1.26.0 -b rhoam-v1.26.0
make cluster/prepare/local LOCAL=false
metadata:
spec:
image: quay.io/tdimov0/managed-api-service-index:1.26.0
EOF
make deploy/integreatly-rhmi-cr.yml LOCAL=false
```
- Install the RHOAM operator from `Operator Hub`
- …
> MGDAPI-4638 merge sts feature branch 

- pkg/products/marin3r/reconciler.go
- pkg/products/rhssouser/reconciler.go
- pkg/products/rhssouser/reconciler_test.go
- pkg/products/threescale/objects_test.go
- pkg/products/threescale/reconciler.go
- pkg/resources/waitForResources.go
- pkg/resources/waitForResources_test.go
[MGDAPI-4388](https://issues.redhat.com/browse/MGDAPI-4388)
- Unrevert MGDAPI-4388
> MGDAPI-4388 - re-implement fix for rhsso waiting

- test/common/verify_alert_links_to_SOPs.go
[https://issues.redhat.com/browse/MGDAPI-4650](url)
Changes done to c08b test. It should reflect recent changes to the SOPs. They were moved from Github to the Gitlab
Run locally or in pipelines
> MGDAPI-4650 edited test to use it with Gitlab, because SOPs were moved there

- controllers/rhmi/prometheusRules.go
> MGDAPI-3209 patch install delayed alert

- test/functional/aws_shared_functions.go
https://issues.redhat.com/browse/MGDAPI-4712
bug fix
> MGDAPI-4712 reverse the credentials request

- pkg/products/threescale/reconciler.go
https://issues.redhat.com/browse/MGDAPI-4718
Nil pointer checks 
Tests passing and eyeballing the code should be sufficient here
> MGDAPI-4718 nil pointer checks on 3scale routes

- bundles/multitenant-managed-api-service/1.27.0/manifests/integreatly.org_apimanagementtenants.yaml
- bundles/multitenant-managed-api-service/1.27.0/manifests/integreatly.org_rhmiconfigs.yaml
- bundles/multitenant-managed-api-service/1.27.0/manifests/integreatly.org_rhmis.yaml
- bundles/multitenant-managed-api-service/1.27.0/manifests/managed-api-service.clusterserviceversion.yaml
- bundles/multitenant-managed-api-service/1.27.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- bundles/multitenant-managed-api-service/1.27.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
- bundles/multitenant-managed-api-service/1.27.0/metadata/annotations.yaml
- bundles/multitenant-managed-api-service/1.27.0/tests/scorecard/config.yaml
- bundles/multitenant-managed-api-service/multitenant-managed-api-service.package.yaml
- config/manifests-multitenant-rhoam/bases/managed-api-service.clusterserviceversion.yaml
JIRA: https://issues.redhat.com/browse/MGDAPI-4533
Bundles files for v1.27.0 multitenant RHOAM.
> MGDAPI-4533 release PR for MT version rhoam-v1.27.0

- scripts/bundle-rhmi-operators.sh
JIRA: https://issues.redhat.com/browse/MGDAPI-4710
Adds support for new command line arg, `OVERWRITE`, which if set to `false` will prevent the script from rebuilding and pushing images that already exist in quay. This parameter is set to false by default.
1. Checkout this PR
2. Run make command to build and push bundle/index images for first time and verify the images are pushed to your quay org: 
`ORG=<your-quay-org> INSTALLATION_TYPE=managed-api UPGRADE=false BUNDLE_VERSIONS=1.27.0 make create/olm/bundle`
3. Run the command again but set `OVERWRITE=false` or don't set it at all and verify that the existing images in your quay org are not overwritten
4. Run the command one last time but this time either set `OVERWRITE=true` and verify that the existing images in your quay org _are_ …
> MGDAPI-4710 Refactored create bundle script to support arg to not overwrite images

- test/common/verify_alert_links_to_SOPs.go
[https://issues.redhat.com/browse/MGDAPI-4650](url)
Edit, that test is skipped if SOPs are not reachable
Test is skipped in the pipelines
> MGDAPI-4650 edit, that test will be skipped if SOPs are not reachable

- test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
https://issues.redhat.com/browse/MGDAPI-4651
Because we run our test suite directly on the OSD cluster (in pod in test-functional ns) and the OSDs are outside of VPN the C08B automated test is always skipped. Hence we had to run it manually so I am updating the C08B test case scenario since it is partially automated now.
Just follow the steps or at least read through them to make sure it is understandable.
> MGDAPI-4651 Update steps in C08B test case

- scripts/create-3scale-index.sh
[MGDAPI-4717](https://issues.redhat.com/browse/MGDAPI-4717)
Build from fresh used string comparison to determine versions to include which stopped working at 0.10.0.
As bundle file is in semver order from delorean, retrieve index of requested version and include all bundles up to and including this version.
Eye review should be sufficient
Add an entry to the bottom of bundles/3scale-operator/bundle.yaml
```
- name: 3scale-operator.v0.10.0-mas
image: quay.io/integreatly/delorean:3scale-bundle-0.10.0mas-22
```
Before change:
```
$ VERSION=0.10.0-mas REG=quay.io ORG=acatterm IMAGE=3scale-index BUILD_FRESH=true make create/3scale/index
./scripts/create-3scale-index.sh
Valid version string: 0.10.0-mas
Building index for v0.10.0-mas
Including bundles: …
```
> MGDAPI-4717 - update 3scale index build from fresh

- apis/v1alpha1/rhmi_types.go
- bundles/3scale-operator/bundles.yaml
- manifests/integreatly-3scale/0.10.0-mas/3scale-operator.clusterserviceversion.yaml
- manifests/integreatly-3scale/0.10.0-mas/apps.3scale.net_apimanagerbackups.yaml
- manifests/integreatly-3scale/0.10.0-mas/apps.3scale.net_apimanagerrestores.yaml
- manifests/integreatly-3scale/0.10.0-mas/apps.3scale.net_apimanagers.yaml
- manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_activedocs.yaml
- manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_backends.yaml
- manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_custompolicydefinitions.yaml
- manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_developeraccounts.yaml
- manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_developerusers.yaml
- manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_openapis.yaml
- manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_products.yaml
- manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_proxyconfigpromotes.yaml
- manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_tenants.yaml
- manifests/integreatly-3scale/0.10.0-mas/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- manifests/integreatly-3scale/0.10.0-mas/threescale-operator-controller-manager-metrics-service_v1_service.yaml
- manifests/integreatly-3scale/3scale.package.yaml
- products/installation.yaml
- products/products.yaml
[MGDAPI-4707](https://issues.redhat.com/browse/MGDAPI-4707)
Upgrade to 3scale-operator version v0.10.0-mas
- Deploy cluster
- Verify upgrading from RHOAM 1.27.0 to changes in this branch result in 3scale-operator upgrade
- Watch workload web app to determine if there is any downtime
> MGDAPI-4707 - update 3scale-operator to v0.10.0-mas

- pkg/products/threescale/reconciler.go
- pkg/resources/ratelimit/envoy.go
- products/additional-images.yaml
[MGDAPI-4812](https://issues.redhat.com/browse/MGDAPI-4812)
revert envoy image to earlier version
e2e pass
> MGDAPI-4812 change envoy image to proxyv2-rhel8:2.1.5-2

- apis/v1alpha1/rhmi_types.go
- bundles/rhsso-operator/bundles.yaml
- manifests/integreatly-rhsso/7.6.0-8/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.0-8/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.0-8/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.0-8/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.0-8/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.0-8/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/rhsso.package.yaml
- pkg/products/rhsso/reconciler_test.go
- pkg/products/rhssouser/reconciler_test.go
- products/additional-images.yaml
- products/installation.yaml
https://issues.redhat.com/browse/MGDAPI-4742
Update RHSSO operator to 7.6-08
new image is available in repo: quay.io/integreatly/rhsso-index:7.6.0-8
> MGDAPI-4742 Update RHSSO operator to 7.6-08

- bundles/multitenant-managed-api-service/1.28.0/manifests/integreatly.org_apimanagementtenants.yaml
- bundles/multitenant-managed-api-service/1.28.0/manifests/integreatly.org_rhmis.yaml
- bundles/multitenant-managed-api-service/1.28.0/manifests/managed-api-service.clusterserviceversion.yaml
- bundles/multitenant-managed-api-service/1.28.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- bundles/multitenant-managed-api-service/1.28.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
- bundles/multitenant-managed-api-service/1.28.0/metadata/annotations.yaml
- bundles/multitenant-managed-api-service/1.28.0/tests/scorecard/config.yaml
- bundles/multitenant-managed-api-service/multitenant-managed-api-service.package.yaml
- config/manifests-multitenant-rhoam/bases/managed-api-service.clusterserviceversion.yaml
JIRA: https://issues.redhat.com/browse/MGDAPI-4533
Bundles files for v1.28.0 multitenant RHOAM.
> MGDAPI-4533 release PR for MT version rhoam-v1.28.0

- controllers/rhmi/bootstrapReconciler.go
- controllers/rhmi/bootstrapReconciler_test.go
- controllers/rhmi/rhmi_controller.go
https://issues.redhat.com/browse/MGDAPI-4741
This code was found during the removal of rhmi in https://github.com/integr8ly/integreatly-operator/pull/2714 
The code being removed is related to the adding of OO and was meant to be removed post 1.14 of RHOAM
- install the current version of rhoam via olm
- upgrade to this version
- expected: upgraded should happen as normal
> Mgdapi 4741 - Removal of temporary code

- bundles/multitenant-managed-api-service/1.29.0/manifests/integreatly.org_apimanagementtenants.yaml
- bundles/multitenant-managed-api-service/1.29.0/manifests/integreatly.org_rhmis.yaml
- bundles/multitenant-managed-api-service/1.29.0/manifests/managed-api-service.clusterserviceversion.yaml
- bundles/multitenant-managed-api-service/1.29.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- bundles/multitenant-managed-api-service/1.29.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
- bundles/multitenant-managed-api-service/1.29.0/metadata/annotations.yaml
- bundles/multitenant-managed-api-service/1.29.0/tests/scorecard/config.yaml
- bundles/multitenant-managed-api-service/multitenant-managed-api-service.package.yaml
- config/manifests-multitenant-rhoam/bases/managed-api-service.clusterserviceversion.yaml
JIRA: https://issues.redhat.com/browse/MGDAPI-4533
Bundles files for v1.29.0 multitenant RHOAM.
> MGDAPI-4533 release PR for MT version rhoam-v1.29.0

- pkg/products/threescale/reconciler.go
[](https://issues.redhat.com/browse/MGDAPI-4932)
tests passing is sufficient
> MGDAPI-4932 wait until 3scale account ready to add dashboard link

- pkg/products/threescale/reconciler.go
https://issues.redhat.com/browse/MGDAPI-4815
Investigate adding APICast metrics to RHOAM prometheus
Use together with 3scale-operator PR https://github.com/3scale/3scale-operator/pull/791
There has been a request to have access to APICast Metrics upstream_response_time_seconds and upstream_status  and to possibly have the ability to build dashboards around these.
To make it working:
1) Current PR - ServiceMonitor `3scale-service-monitor` was added to redhat-rhoam-3scale project ( corresponding ServiceMonitor is created by reconciler in observability project)
2) 3scale PR - metrics port 9421 to be added to Services apicast-staging & apicast-production in redhat-rhoam-3scale ns (discussion with 3scale Team) 
- Install Rhoam, including current PR
- edit apicast-staging Service in …
> MGDAPI-4815 - Investigate adding APICast metrics to RHOAM prometheus

- .golangci.yaml
- controllers/subscription/csvlocator/csvlocator.go
- controllers/subscription/csvlocator/csvlocator_test.go
- controllers/tenant/apimanagementtenant_controller.go
- controllers/user/user_controller.go
- pkg/config/manager.go
- pkg/products/cloudresources/reconciler.go
- pkg/products/marin3r/rateLimitService.go
- pkg/products/marin3r/reconciler.go
- pkg/products/monitoringcommon/alertmanagerConfig_test.go
- pkg/products/threescale/asserts_test.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/three_scale_client.go
- pkg/resources/marketplace/implicit_catalog_source_reconciler_test.go
- pkg/resources/marketplace/manifestHelper.go
- pkg/resources/podHelper.go
- pkg/resources/ratelimit/envoy.go
- test/common/3scale_smtp.go
- test/common/multitenancy.go
- test/common/scale_up_replicas_rhsso.go
- test/common/scale_up_replicas_threescale.go
- test/common/selfmanaged_apicast.go
- test/common/user_dedicated_admin_synced_sso.go
- test/e2e/suite_test.go
- test/resources/3scale_api.go
- test/resources/oauth_proxy_auth.go
- test/resources/openshift_api.go
- test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/h22-validate-that-rate-limit-service-is-working-as-expected.go
- test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go
https://issues.redhat.com/browse/MGDAPI-4598
Enabled insffassign in golangci-lint. This checks for poorly assigned variables.
Pass of prow checks should be enough.
> MGDAPI-4598 : Enable ineffassign

- controllers/rhmi/bootstrapReconciler.go
> MGDAPI-4909 remove check for repeating strings 

- apis/v1alpha1/rhmi_types.go
- bundles/managed-api-service/1.31.0/manifests/managed-api-service.clusterserviceversion.yaml
- products/additional-images.yaml
- products/products.yaml
- scripts/prepare-release.sh
https://issues.redhat.com/browse/MGDAPI-4831
Refactor the related images as a map of products and subcomponents
* Verify that the release prepare script works
```
OLM_TYPE=managed-api-service SEMVER=1.31.0 SERVICE_AFFECTING=true IMAGE_TAG=master make release/prepare
```
> MGDAPI-4831 - refactor: related images as map of product and components

- Makefile
- README.md
- openshift-ci/Dockerfile.tools
https://issues.redhat.com/browse/MGDAPI-5060
Update yq version to the latest version and add a make target to allow of a simple prow check.
Build and test the Dockerfile.tools by following the readme in the openshift-ci folder.
* Ensure the the local verion of yq is 4.30.6 or better.
* Run `make test/scripts`
* Expected to exit with out error
> MGDAPI-5060 : Update yq version

- controllers/rhmi/bootstrapReconciler.go
- controllers/user/user_controller.go
- main.go
- pkg/products/rhsso/reconciler.go
- pkg/products/threescale/reconciler.go
- pkg/resources/user/userHelper.go
- pkg/resources/user/userHelper_test.go
https://issues.redhat.com/browse/MGDAPI-5062
Some code/test refactoring in the user reconciler.
Test should pass.
There should be no logic changes here but have no objection to this being run and a few users created to validate nothing is broken.
> MGDAPI-5062 - refactor of user code and tests

- bundles/managed-api-service/1.31.0/manifests/managed-api-service.clusterserviceversion.yaml
- pkg/addon/quota.go
https://issues.redhat.com/browse/MGDAPI-4927
100M Quota Configuration for 100M suppport
* Provision cluster 
* Install RHOAM using 100M quota configuration
```
make cluster/prepare/local DEV_QUOTA=1000
make code/run DEV_QUOTA=1000
```
* Verify that the appropriate configuration is applied 
* Backend Listener
```
oc get apimanager 3scale -n redhat-rhoam-3scale -o json | jq '.spec.backend.listenerSpec.resources'
oc get apimanager 3scale -n redhat-rhoam-3scale -o json | jq '.spec.backend.listenerSpec.replicas'
```
* Backend Worker
```
oc get apimanager 3scale -n redhat-rhoam-3scale -o json | jq '.spec.backend.workerSpec.resources'
oc get apimanager 3scale -n redhat-rhoam-3scale -o json | jq '.spec.backend.workerSpec.replicas'
```
* APICast Production
```
oc get apimanager 3scale -n …
```
>  MGDAPI-4927 - feat: 100 Million quota configuration

- pkg/products/cloudresources/reconciler.go
https://issues.redhat.com/browse/MGDAPI-5093
On upgrade the added service update should be applied.
> MGDAPI-5093 apply redis service update

- controllers/subscription/subscription_controller.go
- pkg/products/threescale/reconciler.go
- pkg/products/threescale/reconciler_test.go
https://issues.redhat.com/browse/MGDAPI-5144
> MGDAPI-5144 fix mt bug

- config/scorecard/bases/config.yaml
https://issues.redhat.com/browse/CVP-3535
https://issues.redhat.com/browse/MGDAPI-5194
Skipped deployment tests that are executed as part of MSP/CPaaS. It is to be sunset.
No idea tbh.
> MGDAPI-5194 Skipped CPaaS/scorecard deployment tests

- scripts/gce_deploy_teardown/deploy.sh
- scripts/gce_deploy_teardown/teardown.sh
https://issues.redhat.com/browse/MGDAPI-5083
Scripts used by the gce-deploy and gce-remove jenkins pipelines: https://gitlab.cee.redhat.com/integreatly-qe/ci-cd/-/merge_requests/846
> MGDAPI-5083 gce vm instance deployment and teardown scripts

- test/common/grafana_routes.go
https://issues.redhat.com/browse/MGDAPI-5245
This test can be executed and should pass now.
Eye review. Passing rhoam-e2e and multitenant-rhoam-e2e should suffice
> MGDAPI-5245 Grafana route test unskipped in Prow

- test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
https://issues.redhat.com/browse/MGDAPI-5245
C08B needs to be executed manually from a machine behind VPN. The tests are executed outside VPN atm when doing release testing & running nightly pipelines.
Eye review only
> MGDAPI-5245 C08B to be executed manually

- test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
[https://issues.redhat.com/browse/MGDAPI-4509](url)
Small improvements to the description of test case
Eye review only
> MGDAPI-4509 N10 - Verify quota feature upgrade description improvements

- controllers/rhmi/rhmi_controller.go
- controllers/tenant/apimanagementtenant_controller.go
- controllers/tenant/apimanagementtenant_controller_test.go
- pkg/products/rhsso/reconciler.go
- pkg/products/threescale/reconciler.go
> MGDAPI-5307-sandbox-improvements

- .golangci.yaml
- pkg/products/marin3r/apiUsagePrometheusRules.go
- pkg/products/rhssocommon/reconciler_test.go
- pkg/products/threescale/three_scale_client.go
- pkg/resources/quota/quota.go
- test/functional/aws_shared_functions.go
- test/resources/3scale_api.go
JIRA: https://issues.redhat.com/browse/MGDAPI-4602
This PR addresses the S1028 errors that were previously configured to be ignored by our linter. This PR also updates our linter [config file](https://github.com/integr8ly/integreatly-operator/blob/master/.golangci.yaml#L11) to check for S1028 errors going forward.
- An eye review of the changes and passing the PROW checks should be sufficient but if you want to manually verify the changes:
- Run `make test/lint`
- Confirm there are no errors in the output
> MGDAPI-4602 Fixed S1028 linter errors

- pkg/products/threescale/reconciler_test.go
- test/common/alerts_exist.go
- test/functional/aws_shared_functions.go
- test/functional/common_shared_functions.go
- test/functional/gcp_shared_functions.go
- test/functional/integreatly_test.go
[MGDAPI-5082](https://issues.redhat.com/browse/MGDAPI-5082)
Fix lint errors for GCP branch.
> MGDAPI-5082 - fix lint errors

- .golangci.yaml
- pkg/products/threescale/reconciler.go
- pkg/resources/installPlan.go
- test/common/3scale_smtp.go
- test/common/network_policy_access_ns_to_svc.go
- test/common/shared_functions.go
- test/functional/multiaz_pod_distribution.go
- test/resources/3scale_api.go
[MGDAPI-4604](https://issues.redhat.com/browse/MGDAPI-4604)
This PR addresses all issue shown from the gosimple linter with error code S1002
In this case the code review of the changes should be sufficient, but if you want you could manually verify it by the following verification steps:
- Run `make test/lint`
- Confirm that there are no errors in the output
> MGDAPI-4604 Fix S1002 linter errors

- test/functional/gcp_network_state.go
https://issues.redhat.com/browse/MGDAPI-5470
During 1.34.0 rc1 testing it was discovered that GCP03 test fails if the CIDR block is not empty (which is the case for addon flow installation).
Eye review to make sure that I got the logic of the test right. I validated against the cluster myself
```
LOCAL=false INSTALLATION_TYPE=managed-api TEST=GCP03 make test/e2e/single
go clean -testcache && go test ./test/functional -ginkgo.focus="GCP03.*" -test.v -ginkgo.v -ginkgo.progress -timeout=80m
time="2023-04-06T12:29:32+02:00" level=info msg="calling reset on all prometheus gauge vectors" custom_metrics=StartGaugeVector
=== RUN   TestAPIs
I0406 12:29:34.331531   53159 request.go:601] Waited for 1.049691851s due to client-side throttling, not priority and fairness, request: …
```
> MGDAPI-5470 Fix GCP03 test if CIDR block is set

- .golangci.yaml
- pkg/products/marin3r/apiUsagePrometheusRules.go
- pkg/resources/quota/quota.go
[MGDAPI-4608](https://issues.redhat.com/browse/MGDAPI-4608)
This PR addresses all issue shown from the gosimple linter with error code S1023
In this case the code review of the changes should be sufficient, but if you want you could manually verify it by the following verification steps:
- Run `make test/lint`
- Confirm that there are no errors in the output
> MGDAPI-4608 Fix S1023 linter errors

- .github/PULL_REQUEST_TEMPLATE.md
https://issues.redhat.com/browse/MGDAPI-5651
Updating the git pull template to include requirement for upgrade verification OR a reason included 
No verification steps required here as it needs to be merged before it gets seen. An eyeball of the changes to confirm that the are as expected is sufficient.
> MGDAPI-5651  adding upgrade scenario verification required

- apis/v1alpha1/rhmi_types.go
- bundles/rhsso-operator/bundles.yaml
- manifests/integreatly-rhsso/7.6.2-4/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.2-4/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.2-4/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.2-4/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.2-4/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.2-4/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/rhsso.package.yaml
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- products/installation-cpaas.yaml
- products/installation.yaml
https://issues.redhat.com/browse/MGDAPI-5663
* Bump Keycloak Operator to v7.6.2-4
```
export LOCAL=false  
make cluster/prepare/local                                                                               
make code/run 
```
* Allow for installation to complete
* Deploy webload-web app
* https://github.com/integr8ly/workload-web-app#rhoam-clusters
* Stop running the operator
* Checkout this branch 
* Re-run the operator
```
export LOCAL=false                                                                                     
make code/rerun 
```
* Verify keycloak operator upgrades thats places and installation completes
```
watch "echo RHSSO; oc get csv -n redhat-rhoam-rhsso-operator; oc get pods -n redhat-rhoam-rhsso; echo "";echo "USER SSO"; oc …
```
> MGDAPI-5663 - keycloak: v7.6.2-4

- docs/load_testing/locust.md
[MGDAPI-5654](https://issues.redhat.com/browse/MGDAPI-5654)
Updating docs folder and [read the docs site](https://integreatly-operator.readthedocs.io/en/latest/) by adding a link to the load testing documentation in the [Locust](https://github.com/integr8ly/locust-integreatly-operator) repo.
Eye review is sufficient.
> MGDAPI-5654 including link to load testing docs

- docs/load_testing/locust.md
[MGDAPI-5654](https://issues.redhat.com/browse/MGDAPI-5654)
Fixing link
> MGDAPI-5654 updating link

- apis/v1alpha1/rhmi_types.go
- bundles/rhsso-operator/bundles.yaml
- manifests/integreatly-rhsso/7.6.2-5/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.2-5/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.2-5/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.2-5/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.2-5/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.2-5/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/7.6.3-1/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.3-1/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.3-1/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.3-1/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.3-1/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.3-1/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/rhsso.package.yaml
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- products/installation-cpaas.yaml
- products/installation.yaml
[MGDAPI-5754](https://issues.redhat.com/browse/MGDAPI-5754)
Update keycloak to v7.6.3-1
```
LOCAL=false make cluster/prepare/local                                                                               
LOCAL=false make code/run
```
* Allow for installation to complete
* Deploy webload-web app- [integr8ly/workload-web-app#rhoam-clusters](https://github.com/integr8ly/workload-web-app#rhoam-clusters)
* Stop running the operator
* Re-run the operator
```
LOCAL=false make code/rerun
```
* Verify keycloak operator upgrades thats places and installation completes
```
watch "echo RHSSO; oc get csv -n redhat-rhoam-rhsso-operator; oc get pods -n redhat-rhoam-rhsso; echo "";echo "USER SSO"; oc get csv -n redhat-rhoam-user-sso-operator; …
```
> MGDAPI-5754 - keycloak: v7.6.3-1

- test/functional/aws_shared_functions.go
- test/functional/aws_standalone_vpc.go
https://issues.redhat.com/browse/MGDAPI-5580
A25 support for private clusters
Added condition: + 1 route count for Public clusters.
Cluster checked if it's public or private by searching if Internet Gateway exists for VPC. 
No IGW should be for Private cluster. Only NAT.
- Verified on Public CCS cluster. A25 test passed for Public cluster (after implementation condition for private/public cluster).
-  For private cluster - TBD.
> MGDAPI-5580 A25 support for private clusters

- config/hive-config/package.yaml
[MGDAPI-5730](https://issues.redhat.com/browse/MGDAPI-5730)
Updating to use ClusterPackage
> MGDAPI-5730 updating to use ClusterPackage

- Makefile
[MGDAPI-5730](https://issues.redhat.com/browse/MGDAPI-5730)
Refactoring to use ClusterPackage
> MGDAPI-5730 updating to ClusterPackage

- controllers/subscription/csvlocator/csvlocator.go
- controllers/subscription/csvlocator/csvlocator_test.go
https://issues.redhat.com/browse/MGDAPI-5811
The subscription controller had an issue where the CSV locator function was failing to fetch CSV from cm binaryData.
- Provision 2 osd clusters
- On both clusters create catalog source pointing to quay.io/mstoklus/managed-api-service:v1.36.0 - matching current prod
- Install RHOAM
- once installation is completed, confirm that the subscription for RHOAM has approvals set to "Automatic"
```
oc get sub managed-api-service -n redhat-rhoam-operator -o yaml 
```
- update index to point to quay.io/mstoklus/managed-api-service:v1.37.0
- confirm upgrade has been completed successfully and that the subscription approval is updated to "Manual"
```
oc get sub managed-api-service -n redhat-rhoam-operator -o yaml
``` 
- once installation is completed update …
> MGDAPI-5811 fix the csv locator function

- Dockerfile
- Dockerfile.external
- Dockerfile.functional
- Dockerfile.osde2e
- Dockerfile.scorecard
- README.md
- controllers/rhmi/rhmi_controller.go
- docs/getting_started.md
- go.mod
- openshift-ci/Dockerfile.tools
- openshift-ci/README.md
- pkg/client/sigs_client_moq.go
- pkg/config/ConfigReadWriter_moq.go
- pkg/products/monitoringcommon/alertmanagerConfig.go
- pkg/products/monitoringcommon/alertmanagerConfig_test.go
- pkg/products/monitoringcommon/templateHelper.go
- pkg/products/threescale/envoyconfig.go
- pkg/products/threescale/three_scale_client.go
- pkg/resources/marketplace/manifestHelper.go
- pkg/resources/marketplace/products_installation_loader.go
- pkg/resources/ratelimit/envoyconfig.go
- test/go.mod
https://issues.redhat.com/browse/MGDAPI-5854
Update to use go1.19. Passing prow checks is sufficient.
`vendor` prow check will fail until this gets merged. Once merged, the master prow pipelines will get auto updated to use go1.19 as the base image
* Passing prow checks except for vendor
> MGDAPI-5854 - go: v1.19

- controllers/rhmi/bootstrapReconciler.go
- scripts/setup-sso-idp.sh
- test-cases/tests/installation/a33-validate-console-links.md
- test/common/console_links.go
- test/common/tests.go
- utils/console.go
https://issues.redhat.com/browse/MGDAPI-3481
* Automate A33 test case
* Install RHOAM onto cluster 
```
make code/run
```
* Set up IDP onto cluster
```
PASSWORD=Password1 DEDICATED_ADMIN_PASSWORD=Password1 ./scripts/setup-sso-idp.sh
```
* Run and verify test passes successfully 
```
LOCAL=false TEST="A33" make test/e2e/single
```
> MGDAPI-3481 - e2e: automate A33 test case

- docs/observability/obo_setup.md
- mkdocs.yml
https://issues.redhat.com/browse/MGDAPI-5882
Update mkdocs configuration for obo
* check out this branch locally
* run `make mkdocs/serve`
* view the page on localhost:8000
* Confirm obo docs are included
> Obo mkdocs

- test/common/namespace_restoration.go
- test/common/types.go
- test/common/validate_resource_requirements.go
- test/osde2e/suite_test.go
https://issues.redhat.com/browse/MGDAPI-5873
Update the destructive test J03
**Feature:** quay.io/jfitzpat/managed-api-service-index:1.39.0-5873
* Install RHOAM, the obo `Feature` index can be used
* Wait for installation
* Set up a watch on the RHOAM namespaces
```shell
watch "oc get namespaces | grep rhoam"
```
* In a different terminal run the J03 destructive test.
```shell
DESTRUCTIVE=true INSTALLATION_TYPE=managed-api TEST=J03 make test/e2e/single
```
* **Expected:** 
* All namespaces are remove except the `redhat-rhoam-operator`
* Ensure the `redhat-rhoam-operator-observabilty` was removed
* Test should pass
* Operator return to a complete state
> MGDAPI-5873 : Update the destructive test J03

- OWNERS
> MGDAPI-99999 add Carl as owner

- pkg/products/threescale/reconciler.go
https://issues.redhat.com/browse/MGDAPI-5922
Automated tests sufficient
> MGDAPI-5922-logging

- test/functional/aws_elasticache_resources_exist.go
Reverts integr8ly/integreatly-operator#3310
> Revert "MGDAPI-4729 / Modified test to work with nonSts"

- Makefile
- config/hive-config/package.yaml
- controllers/rhmi/rhmi_controller.go
- controllers/rhmi/rhmi_controller_test.go
- pkg/products/obo/clusterPackage.go
- pkg/products/threescale/reconciler.go
- test/common/authdelay_first_broker_login.go
- test/common/cluster_package.go
- test/common/validate_cluster_objects_templates.go
- test/resources/3scale_api.go
JIRA: [MGDAPI-5961](https://issues.redhat.com/browse/MGDAPI-5961)
This PR fixes the following:
1. Preflight check that makes sure the RHOAM ClusterPackage exists and is healthy
2. `Test if cluster package is available` e2e test
3. `Verify ClusterObjectTemplates ready state` e2e test
4. `F05 - Verify Replicas Scale correctly in Threescale` e2e test
5. `A16 - Custom first broker login flow`
6. `H03 - Verify 3scale CRUDL permissions`
7. `H07 - ThreeScale User Promotion`
8. `H11 - Verify 3scale SMTP config`
1. [Provision](https://qaprodauth.console.redhat.com/openshift/create) a cluster
2. Once the cluster is provisioned, login to [Hybrid Cloud Console](https://qaprodauth.console.redhat.com/openshift), select the provisioned cluster, navigate to the `Add-ons` tab and install `Red Hat …
> MGDAPI-5961 refactor ClusterPackage preflight check and tests

- pkg/products/reconciler_test.go
N/A
This PR fixes a the pkg/products/reconciler_test.go unit test so that you don't need to be `oc` logged into a cluster for the unit tests to pass.
An eye review and passing the prow checks should be sufficient verification.
> Refactor products/reconciler unit test to not rely on kube apiserver

- scripts/alerts-check.sh
- test/common/pvc_validate.go
https://issues.redhat.com/browse/MGDAPI-5996
Improvements to A06 test and alerts-check script based on 1.38.0 testing experience
Run alerts-check.sh against the cluster
`./scripts/alerts-check.sh 10`
`./scripts/alerts-check.sh 15 3scale`
`./scripts/alerts-check.sh`
Run A06 test against the cluster
`LOCAL=false INSTALLATION_TYPE=managed-api TEST="A06"  make test/e2e/single`
> MGDAPI-5996 Alerts check fixes & A06 test update

- test/common/alerts_firing.go
https://issues.redhat.com/browse/MGDAPI-5992
Temporary workaround for https://issues.redhat.com/browse/MGDAPI-5992. Rhsso- and UserSso- vailability2hto1dErrorBudgetBurn alerts will be ignored.
Have a cluster with RHOAM installed. In case of no alerts firing the tests should just pass
`INSTALLATION_TYPE=managed-api DESTRUCTIVE=true LOCAL=false TEST="Verify Alerts are not firing during or after installation apart from DeadMansSwitch" make test/e2e/single`
`INSTALLATION_TYPE=managed-api DESTRUCTIVE=true LOCAL=false TEST="C01" make test/e2e/single`
I am not sure how to make **ErrorBudgetBurn alerts fire so I recommend to deploy workload-web-app and do some GET requests against the 3scale Product which should make ThreeScaleContainerHighMemory alert to fire. Then run …
> MGDAPI-5992 temporary workaround in tests

- scripts/alerts-check.sh
https://issues.redhat.com/browse/MGDAPI-5996
We would like to use alerts-check.sh to monitor alerts during rhoam installation. In order to do that the script must not wait for RHOAM install to complete but only wait for prometheus to spin up.
I also slightly updated the output so that Openshift alerts and RHOAM alerts are not mixed together
Have a cluster with RHOAM installed. Do `oc login ...` into the cluster. Run `./alerts-check.sh`. It should start watching alerts every 5 seconds. Then make the RHMI CR think that the installation is not complete, e.g.:
`oc scale deployment/threescale-operator-controller-manager-v2 -n redhat-rhoam-3scale-operator --replicas=0`
`oc scale dc/system-app -n redhat-rhoam-3scale --replicas=0`
Run `./alerts-check.sh` again. The script should behave the same …
> MGDAPI-5996 Alert check not waiting for RHOAM installation to complete

- test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
[MGDAPI-5950](https://issues.redhat.com/browse/MGDAPI-5950)
addition of possible troubleshoot step
> MGDAPI-5950 addition of troubleshooting step

- openshift-ci/Dockerfile.tools
MGDAPI-6067
set openshift-ci to go1.19
> MGDAPI-6067 set openshift-ci to go1.19

- pkg/products/grafana/reconciler.go
Jira: https://issues.redhat.com/browse/MGDAPI-6098
- PR/branch is based on task MGDAPI-6097 (Quota) - PR https://github.com/integr8ly/integreatly-operator/pull/3390
During upgrade/fresh install, Grafana reports completed prematurely.
- Add check deployment status
- Install rhoam and check continuously the status of grafana resources in grafana namespace and compare with status in rhoam instllation
- - Check Quota updates - please see PR https://github.com/integr8ly/integreatly-operator/pull/3390
> MGDAPI-6098 fix - During upgrade/fresh install, Grafana reports completed prematurely

- pkg/products/grafana/prometheusRules.go
- pkg/products/grafana/reconciler.go
Jira: https://issues.redhat.com/browse/MGDAPI-6113
Fix removeGrafanaOperatorAlerts method to work for Internal rhoam (rhoami)
Please see related PR: https://github.com/integr8ly/integreatly-operator/pull/3398
> MGDAPI-6113 Fix removeGrafanaOperatorAlerts() to work for Internal rhoam  (rhmi)

- apis/v1alpha1/rhmi_types.go
- manifests/integreatly-cloud-resources/1.1.2/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- manifests/integreatly-cloud-resources/1.1.2/cloud-resource-operator.clusterserviceversion.yaml
- manifests/integreatly-cloud-resources/1.1.2/integreatly.org_blobstorages.yaml
- manifests/integreatly-cloud-resources/1.1.2/integreatly.org_postgres.yaml
- manifests/integreatly-cloud-resources/1.1.2/integreatly.org_postgressnapshots.yaml
- manifests/integreatly-cloud-resources/1.1.2/integreatly.org_redis.yaml
- manifests/integreatly-cloud-resources/1.1.2/integreatly.org_redissnapshots.yaml
- manifests/integreatly-cloud-resources/1.1.2/operator-metrics-service_v1_service.yaml
- manifests/integreatly-cloud-resources/cloud-resources.package.yaml
- products/installation-cpaas.yaml
- products/installation.yaml
- products/products.yaml
MGDAPI-6105
CRO bump
- e2e pass 
- upgrade testing.
> MGDAPI-6105 Bump cro to v1.1.2

- bundles/managed-api-service/1.39.0/manifests/managed-api-service.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/rhmi/rhmi_controller.go
- pkg/products/grafana/reconciler.go
> MGDAPI-6163 move grafana dep to RHOAM instead of PO temporarily

- test/common/console_links.go
https://issues.redhat.com/browse/MGDAPI-6213
A33 fails (false positive) if other addons are installed because then there are additional console links there. This fixes it by filtering out the non-RHOAM links before assertion. For icons the test validates that there is expected number of RHOAM icons among the found console links. It might not be the cleanest approach but it does not require any modification to the code around browser - it is stable so I think it is not worth doing a massive refactoring of it due to this.
1) Get a cluster and install RHOAM (no matter how).
2) Run the A33 test - it should pass:
`INSTALLATION_TYPE=managed-api TEST=A33 make test/e2e/single`
3) Instal RHODS (RHOAI) addon. Can be done via OCM UI or using the following script (update the cluster ID and email …
> MGDAPI-6213 A33 test not failing if other addons are installed

- bundles/managed-api-service/1.40.0/manifests/managed-api-service.clusterserviceversion.yaml
- config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
https://issues.redhat.com/browse/MGDAPI-6245
This PR bumps the maxOpenShiftVersion to 4.15.
An eye review and passing the PROW checks should be sufficient verification.
> MGDAPI-6245 Bump maxOpenshiftVersion to 4.15

- pkg/products/cloudresources/reconciler.go
> MGDAPI-6265 force CRO version check before completing CRO installation

- openshift-ci/Dockerfile.tools
Fix build issue in PR: https://github.com/integr8ly/integreatly-operator/pull/3460
> MGDAPI-6289-3 - fix - update FROM image in Dockerfile.tools

- scripts/prepare-release.sh
Jira: https://issues.redhat.com/browse/MGDAPI-6289
GOFMT="gofmt"
> MGDAPI-6289-f1 fix - revert GOFMT path

- .github/snyk_pull_request_template.yaml
MGDAPI-6406  override commit message on snyk
> MGDAPI-6406 snyk_pull_request_template.yaml override commit message

- bundles/marin3r-operator/bundles.yaml
> MGDAPI-6221 update marin3r bundle

- bundles/rhsso-operator/bundles.yaml
Jira: https://issues.redhat.com/browse/MGDAPI-6431
preliminary step to update RHSSO
It will be done before: https://github.com/integr8ly/integreatly-operator/pull/3495
> MGDAPI-6431 - preliminary step to update RHSSO

- bundles/3scale-operator/bundles.yaml
https://issues.redhat.com/browse/MGDAPI-6415
Add 0.12.1 3scale bundle
Not required
> MGDAPI-6415 update 3scale bundle ref

- apis/v1alpha1/rhmi_types.go
- bundles/managed-api-service/1.42.0/manifests/managed-api-service.clusterserviceversion.yaml
- bundles/rhsso-operator/bundles.yaml
- manifests/integreatly-rhsso/7.6.11-2/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-2/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-2/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-2/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-2/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-2/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/7.6.11-3/keycloakbackups.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-3/keycloakclients.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-3/keycloakrealms.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-3/keycloaks.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-3/keycloakusers.keycloak.org.crd.yaml
- manifests/integreatly-rhsso/7.6.11-3/rhsso-operator.clusterserviceversion.yaml
- manifests/integreatly-rhsso/rhsso.package.yaml
- pkg/products/rhsso/reconciler.go
- pkg/products/rhssouser/reconciler.go
- products/installation-cpaas.yaml
- products/installation.yaml
Jira: https://issues.redhat.com/browse/MGDAPI-6547
Bump RHSSO image for RHOAM 1.42
[rhsso index image](quay.io/integreatly/rhsso-index:v7.6.11-3) created,  PR https://github.com/integr8ly/integreatly-operator/pull/3534
Rhoam installed successfully with new RHSSO v7.6.11-3
> MGDAPI-6547 Bump RHSSO image for RHOAM 1.42

- pkg/products/grafana/reconciler.go
- pkg/resources/ratelimit/envoy.go
- products/additional-images.yaml
https://issues.redhat.com/browse/MGDAPI-6553
Bump envo, grafana and ose-proxy images
All tests on PR pass
> MGDAPI-6553 bump images

- test/common/authdelay_first_broker_login.go
- test/common/console_links.go
- test/common/product_login.go
- test/common/selfmanaged_apicast.go
- test/common/tests.go
- test/go.mod
- test/go.sum
Jira: https://issues.redhat.com/browse/MGDAPI-6629
Functional tests A33, B01B, H03, H24 were updated/fixed to avoid errors in Jenkins pipelines (PL) tests 
1. Validation in Local environment
- Get this PR
- Install RHOAM
- Create IDP:
```bash
PASSWORD=Password1 DEDICATED_ADMIN_PASSWORD=Password1 scripts/setup-sso-idp.sh
```
- Run e2e/single tests for A33, B01B, H03, H24
```bash
LOCAL=false INSTALLATION_TYPE=managed-api TEST="A33" make test/e2e/single OUTPUT_DIR=./test-run-results
LOCAL=false INSTALLATION_TYPE=managed-api TEST="B01B" make test/e2e/single OUTPUT_DIR=./test-run-results
LOCAL=false INSTALLATION_TYPE=managed-api TEST="H03" make test/e2e/single OUTPUT_DIR=./test-run-results
LOCAL=false INSTALLATION_TYPE=managed-api TEST="H24" make test/e2e/single OUTPUT_DIR=./test-run-results …
```
> MGDAPI-6629 fix functional tests

- pkg/products/threescale/prometheusRules.go
- pkg/resources/sop_url.go
https://issues.redhat.com/browse/MGDAPI-6650
https://issues.redhat.com/browse/MGDAPI-6651
Update URLs to sops
Once MRs are merged, install RHOAM of this branch and confirm that updated URLs work as expected.
> MGDAPI-6651 update SOP URLs

- Makefile
- bundles/cloud-resource-operator/bundles.yaml
- scripts/create-product-index.sh
https://issues.redhat.com/browse/MGDAPI-6693
Add support to build CRO index via jenkins product pipelines.
Passing prow jobs
> MGDAPI-6693 add CRO index builder via jenkins support

- apis/v1alpha1/rhmi_types.go
- bundles/managed-api-service/1.43.0/manifests/managed-api-service.clusterserviceversion.yaml
- bundles/marin3r-operator/bundles.yaml
- manifests/integreatly-marin3r/0.13.3/marin3r-controller-manager-metrics-service_v1_service.yaml
- manifests/integreatly-marin3r/0.13.3/marin3r-manager-config_v1_configmap.yaml
- manifests/integreatly-marin3r/0.13.3/marin3r-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- manifests/integreatly-marin3r/0.13.3/marin3r-webhook-service_v1_service.yaml
- manifests/integreatly-marin3r/0.13.3/marin3r.3scale.net_envoyconfigrevisions.yaml
- manifests/integreatly-marin3r/0.13.3/marin3r.3scale.net_envoyconfigs.yaml
- manifests/integreatly-marin3r/0.13.3/marin3r.clusterserviceversion.yaml
- manifests/integreatly-marin3r/0.13.3/operator.marin3r.3scale.net_discoveryservicecertificates.yaml
- manifests/integreatly-marin3r/0.13.3/operator.marin3r.3scale.net_discoveryservices.yaml
- manifests/integreatly-marin3r/0.13.3/operator.marin3r.3scale.net_envoydeployments.yaml
- manifests/integreatly-marin3r/marin3r.package.yaml
- products/installation-cpaas.yaml
- products/installation.yaml
- products/products.yaml
Jira: https://issues.redhat.com/browse/MGDAPI-6612
Update Mariner to latest : v0.13.3
- both initial instllaton and Upgrade were verified
- upgrade details provided below:
```
"marin3r": {
"host": "",
"name": "marin3r",
"operator": "0.13.2",
"status": "completed",
"version": "0.13.2"
},
~/go/integreatly-operator/manifests/integreatly-marin3r date
Wed Jun  4 15:58:10 IDT 2025
~/go/integreatly-operator/manifests/integreatly-marin3r oc get rhmi rhoam -n redhat-rhoam-operator -o json | jq -r '.status.stage'
complete
```
```
git switch  MGDAPI-6612-3
oc get pod -n redhat-rhoam-marin3r-operator
NAME                                                              READY   STATUS      RESTARTS   AGE
2a9bc88fc34c5c2b34a7519af25298b26e618a3882d6ea05e1a40075d4wchhk   0/1     Completed   0          148m …
```
> MGDAPI-6612 Update Marin3r to 0.13.3

- pkg/products/cloudresources/reconciler.go
MGDAPI-6738 
elasticache service update
Hard to verify as all new elasticache will have the service update already. 
merge and test a release time.
> MGDAPI-6738 elasticache service update

- pkg/products/cloudresources/reconciler.go
MGDAPI-6766
Elasticache service update
Can only be tested on upgrade of eng-long-lived as new elasticache will already have the patch. 
confirm the code changes.
> MGDAPI-6766 elasticache service update

- pkg/products/cloudresources/reconciler.go
MGDAPI-6771
elasticache service update
- Prow test pass
- Install RHOAM with CCS and confirm that the service update is applied
> MGDAPI-6771 add elasticache service update

- Makefile
- go.mod
- pkg/products/marin3r/apiUsagePrometheusRules.go
- pkg/products/marin3r/rateLimitService.go
- pkg/resources/password.go
- pkg/resources/ratelimit/envoy.go
- pkg/resources/ratelimit/envoyconfig.go
- test/common/status_conditions.go
- test/go.mod
MGDAPI-6606
fix failing prow jobs
Prow jobs pass, not concerned with codecover
> MGDAPI-6606 fix failing Prow jobs after go1.24 bump

- pkg/products/cloudresources/reconciler.go
https://issues.redhat.com/browse/MGDAPI-6821
elasticache service update
- Prow test pass
- Install RHOAM with CCS and confirm that the service update is applied
> MGDAPI-6821 add elasticache service update

- bundles/3scale-operator/bundles.yaml
MGDAPI-6838
update the bundle image.
No verification required other that a code review , needs to merge in order for us to generate the 3scale-index
> MGDAPI-6838 update the 3scale bundle image to 2.15.5
